### ISSUE TITLE
Help setting up repository locally

### ISSUE THREAD

**Issue by AlligatorSnappingTurtle19** [HabitRPG/habitica-android#1002]
I have been trying to set up this repository locally to see how it works and potentially try to fix some issues. However, I have tried to follow all the steps listed in the `README.md`, but I end up getting an error whenever I try to build it. I'm using Android Studios to attempt to set up the project on a computer running Windows 10. If someone could take the time to write the steps in more detail or walk me through the process it would be great. This is my first time working on an Android app from GitHub.

**Comment by phillipthelen** [comment]
I'll try to make the setup instructions more detailed soon.
At which point specifically are you having issues? Is there an error in android studio?

**Comment by AlligatorSnappingTurtle19** [comment]
I get several errors when I try to build the code. Most of which I just need to click the error and install something and it will fix itself. However, I get to point when I get this error: `` which so far I can't seem to fix.

A list of all the steps I took to try to set up the app being as detailed as possible:
1. fork the repository
2. clone it using git bash `git clone git@github.com:AlligatorSnappingTurtle19/habitica-android.git`
3. cd into the new directory
4. create a new branch using git `git checkout -b test`
5. run the config commands listed on the `README.md` `cp habitica.properties.example habitica.properties cp habitica.resources.example habitica.resources
cp Habitica/google-services.json.example Habitica/google-services.json` (I ran the commands seperately)
6. open the project in Android Studios
7. Android Studios starts syncing the build automatically
8. the syncing gives me a lot of red text on the event log but the syncing runs succesfully some how
9. However, when the build runs I get an error saying `Unexpected format of Google App ID. Please follow instructions on https://firebase.google.com/ to get a config file that contains a valid Google App Id or update the plugin version if you believe your Google App Id [app-id] is correct.` which causes the build to fail.


Thank you for taking the time to help me.

**Comment by 199sm** [comment]
I suppose #980 can help

**Comment by cvuorinen** [comment]
I went through this process just recently and @199sm is correct, you need to setup the apps in Firebase as instructed in #980 (which is now merged so you can also see the info in the main README https://github.com/HabitRPG/habitica-android#config-files).

Also you might need to pull latest changes for the build to work, @phillipthelen pushed some fixes a few days ago, before those I got some errors about missing view id etc. during the build and it din't work.
