### ISSUE TITLE
Opting out of the class system should not say "changing class" 

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#1003]
If you opt out of the class system upon reaching level 10, you see a screen saying "changing class". It should say "opting out" or similar.

The current text makes you wonder if you tapped in the wrong place or if the app misread your tap. It will be confusing for new users because they'll see they're a Warrior both before and after they were told they were changing class.

Version 1.5 (1980).

**Comment by Alys** [comment]
It's just the standard class change process. Here's four screens in the order you see them:

![screenshot_2018-09-12-12-57-25](https://user-images.githubusercontent.com/1495809/45399979-961e1d00-b68d-11e8-8621-196988dfe0d2.png)
![screenshot_2018-09-12-12-58-21](https://user-images.githubusercontent.com/1495809/45399983-96b6b380-b68d-11e8-8ced-cc8ba386857f.png)
![screenshot_2018-09-12-12-57-37](https://user-images.githubusercontent.com/1495809/45399981-961e1d00-b68d-11e8-80a0-518385a76eec.png)
![screenshot_2018-09-12-13-01-40](https://user-images.githubusercontent.com/1495809/45399985-96b6b380-b68d-11e8-9663-90a6dc986c16.png)

**Comment by saraolson** [comment]
Oooh got it, @Alys thanks!

**Comment by Arbalest007** [comment]
@saraolson @Alys Hello! Is this issue available to be worked on?

**Comment by LulaV14** [comment]
@Arbalest007 if you're not working in this I can take it.

**Comment by Arbalest007** [comment]
@LulaV14 Go for it!
