### ISSUE TITLE
count of tasks for Habits, Dailies, To-Dos, Rewards always shows 1

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#1013]
Android app version 1.5 (1980)

On a new account that has no tasks, the task counts for all task types display 1 when they should be showing zero tasks:
![image](https://user-images.githubusercontent.com/1495809/43748094-f833308a-9a30-11e8-9e36-879ad9bc296e.png)

That screenshot doesn't show Habits because that's the screen I'm on, but when I move to a different task type, Habits also has a 1.

Here's the tasksOrder array for that account showing no tasks at the time the screenshot was added:
```
{
    "_id": "50adeba6-7184-4a1d-97d4-b08e4effdb46",
    "tasksOrder": {
        "habits": [],
        "dailys": [],
        "todos": [],
        "rewards": []
    }
```

When I added two Habits and two To-Dos, the count was still 1 for both those task types.

**Comment by phillipthelen** [comment]
That count is for the tutorial screens. Are they not shown when you open those screens?

--  
Phillip Thelen
Sent with Airmail

**Comment by phillipthelen** [comment]
I understand where they are. Those aren't task count indicators, but instead indicate that there is a tutorial step that should show when you open those views. I'll check why they aren't showing up.
