### ISSUE TITLE
can't see multiple party invitations at once

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#1020]
Android app version 1.5 (1980)

I'm guessing this is probably already on your radar since it's likely related to updating the app to use the `invitations.parties` array instead of the `invitations.party`, but just in case it's not known:

If you have multiple invitations to a party at once (e.g., the data below), you see only one invitation on the main Party screen, and it doesn't give the name of the party. The expected behaviour is that you see all invitations with each one showing the name of the party.

_This might be out of scope:_
_If the invitations could also show you the person who invited you to the party (the `inviter` field), that would be awesome for the users - sometimes they do ask how they can tell which invitation comes from which person._
_Currently, you'd have to do a lookup on the person's User ID to get their profile name, but it would of course be possible to adjust the API's invitation route to store the profile name of the inviter at the time that they send the invitation, if that was felt to be more efficient._

Sample invitation data:
```
{
    "_id": "50adeba6-7184-4a1d-97d4-b08e4effdb46",
    "invitations": {
        "guilds": [],
        "party": {
            "id": "5e917f2a-abfb-445e-ade7-32d1ca640c3a",
            "name": "alys3's Party",
            "inviter": "22bde0db-8e61-4585-aa6f-12fa093ef10a"
        },
        "parties": [
            {
                "_id": "5b69598b6eacb50016eb5007",
                "id": "12345672-8050-4253-85ba-14eab6b19e72",
                "name": "Awesome party.",
                "inviter": "d904bd62-da08-416b-a816-ba797c9ee265"
            },
            {
                "_id": "5b695b0541090a000facf5ba",
                "id": "5e917f2a-abfb-445e-ade7-32d1ca640c3a",
                "name": "alys3's Party",
                "inviter": "22bde0db-8e61-4585-aa6f-12fa093ef10a"
            }
        ]
    },
}
```

**Comment by saraolson** [comment]
i'd like to split out these issues, this one for multiple invites, and another to update what info the invitations show.

**Comment by saraolson** [comment]
#794 might fix this
