### ISSUE TITLE
Experiencing a huge battery drain with habitica installed

### ISSUE THREAD

**Issue by TNychka** [HabitRPG/habitica-android#1029]
I started experiencing this within the past 3 days, the habitica widgets began rendering improperly on the home screen and habitica began draining an enormous amount of my battery. I confirmed that after doing nothing but uninstalling habitica the power drain stopped.
This is using the Microsoft Launcher on a Samsung S6 with android version 7.0

**Comment by Alys** [comment]
Thank you for telling us!

That version of the app has been withdrawn from the market and a fix will be in the next version.
