### ISSUE TITLE
Not receiving any notifications

### ISSUE THREAD

**Issue by JacobFrericks** [HabitRPG/habitica-android#1032]
In the settings I have "Activate Reminder" checked with a time of "17:30", but I never get this reminder. I also have "User Push Notifications" checked, and everything is checked under the "Push Notifications" page, but I never get these reminders either. 

I know awhile ago there was a problem with Android notifications, but I can't find any information on it, and I see commits like this one that make it seem like this problem should be fixed.
https://github.com/HabitRPG/habitica-android/commit/e6876acea06aa5c035b4965a0a266297bcb8280d

**Comment by JacobFrericks** [comment]
@danbruegge what version of Android was your old phone on?

**Comment by danbruegge** [comment]
6.0.0.

**Comment by phillipthelen** [comment]
What version of the app are you using? The newest version should be 1.5 (1992). You can find that info in the apps about page.

**Comment by danbruegge** [comment]
1.4.5 (1989)

**Comment by JacobFrericks** [comment]
I have 1.4.5 as well. No updates available from the play store. It was last updated on August 23rd.

How did you get 1.5? Did you build it manually from the source code, or download it from the store?

**Comment by JacobFrericks** [comment]
Looks like milestone 1.5 was closed an hour ago, so probably built from source. I'll wait until it's on the play store and report back.

**Comment by danbruegge** [comment]
I activated the beta program on google play. Now i have version 1.5 (1992) and notifications still not working.

**Comment by phillipthelen** [comment]
Which notifications have you tested to still not be working?

**Comment by danbruegge** [comment]
For messages and quest invites. I also unchecked and checked again all options to be sure they are activated.

**Comment by phillipthelen** [comment]
Ok! Looked into it further and figured it out. Tested with a few different notifications and everything should work properly with the next update (should be 1.5 (1993)), that I'll push later today

**Comment by JacobFrericks** [comment]
@phillipthelen

I also joined the beta and downloaded the latest version this morning. I did get a quest notification that my party happened to start today, so that's good news!

However, the daily reminder isnt showing. Was that covered in the latest commit?

**Comment by danbruegge** [comment]
I'm still on 1.5 (1992). No updates in the store.

**Comment by phillipthelen** [comment]
@JacobFrericks If the daily reminder still isn't showing for you, the issue with that is probably somewhere else. Do you have multiple daily reminders active of which none are working? Could you maybe try the following: Edit a task to have a reminder that should show 2 or 3 minutes in the future and then see if that one appears?

@danbruegge the 1993 update was not released to all users yet. I just did that and it should be available in the next hour or so.

**Comment by danbruegge** [comment]
I got a new message notification from the app. So looks like it is working again. :)

**Comment by JacobFrericks** [comment]
@phillipthelen sorry, I forgot to report back. I do get reminder notifications from specific tasks and it seems all other notifications as well. I'm not getting the general daily notification though.

**Comment by saraolson** [comment]
@JacobFrericks could you go into settings and try to force the general daily reminder notif by setting it to show ~1 minute from the current time and if nothing goes through, make a new issue specifically for that?
