### ISSUE TITLE
News is misformatted

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#1034]
The News screen has the image cut off and the text squished up:

![image](https://user-images.githubusercontent.com/1495809/44337197-18ffed80-a4bd-11e8-9ae7-652f8c7952d8.png)

_(Thanks to Chandramani Adil (1.d4) (58de0b72-3af8-4f2a-b9a1-f7d196b29757) for reporting it and taking the screenshot.)_

**Comment by phillipthelen** [comment]
This is not something the clients can fix. The news are displayed from the html the website returns. There is no mobile friendly view for this and we don’t have the news posts as p.e. Markdown that the clients could render in a better way

--  
Phillip Thelen
Sent with Airmail

**Comment by Alys** [comment]
Good to know, thanks! I'll direct anyone else I see reporting it to your explanation.

**Comment by TheHollidayInn** [comment]
If we changed the news API to return markdown, would that solve this?

**Comment by phillipthelen** [comment]
There currently is no proper API call for this. There is a url that returns the same html that is also displayed in the modal the website displays. If we had an api call that returns markdown (ideally json array with one object per post and title, date and content for each post) the clients could display news in a much better format that adjusts to the display size. We would sacrifice some of the formatting options (afaik there is no way to define that an image should be rendered to the right of content in markdown?) but imho it would be worth it being able to actually show users a good/usable news view in the apps.

**Comment by TheHollidayInn** [comment]
Yea, I'm saying change the return value of `api/v3/news`. I think sacrificing some formatting for consistency is fine.

**Comment by phillipthelen** [comment]
Does that already exist? Currently the apps use /static/new-stuff. Since we have v4 of the api in progress anyway, we could add/modify the news route there. If we can get that working, it would be great. Been wanting that for a long time!

**Comment by TheHollidayInn** [comment]
Yep! We use it on the web: https://github.com/HabitRPG/habitica/blob/develop/website/server/controllers/api-v3/news.js#L20
