### ISSUE TITLE
Party invite: show sender in the UI

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1045]
When you receive an invite and see it on the party screen, show the name/avatar of the user who sent the invite like this:
<img width="383" alt="screen shot 2018-09-11 at 10 32 08 am" src="https://user-images.githubusercontent.com/12453119/45366894-f9d11900-b5ad-11e8-9d5a-bd03f46e8f45.png">

**Comment by ashleyng** [comment]
for the `accept` and `reject` assets, do i just go find some free ones that match as close as possible? It didn't look like there was anything similar already in the repo

**Comment by saraolson** [comment]
@ashleyng so sorry for the delay, this slipped under our radar for a long time. if you're interested in picking this up again, i've included the icons in this folder.

[Party Invite Icons.zip](https://github.com/HabitRPG/habitica-android/files/2890036/Party.Invite.Icons.zip)

**Comment by HiroinaProtagonist** [comment]
I'm interested in working on this. @ashleyng were you going to pick this back up?

**Comment by ashleyng** [comment]
not at this moment, you can go ahead and take this if you'd like @HiroinaProtagonist

**Comment by saraolson** [comment]
@HiroinaProtagonist i'm taking the help wanted label off and adding the in progress label for ya. please let us know if anything changes and you're not able to work on this, good luck!

**Comment by saraolson** [comment]
@HiroinaProtagonist hi there, just wanted to check in to see how this is going? are you still working on it or do you have any questions you may need help with?

**Comment by HiroinaProtagonist** [comment]
Hi, I'm still working on it. I don't have questions yet.

**Comment by HiroinaProtagonist** [comment]
Just an update, I am working on this actively now and should have an update next week, if not sooner.

**Comment by HiroinaProtagonist** [comment]
I do have a question: I have experience in several languages (it's not a difficult change) and I can partially localize the modified string. Would you like that done or what is the workflow for localization? (I'm happy to read some documentation if that already exists and I just haven't found it.)

**Comment by Alys** [comment]
@HiroinaProtagonist All translations are done through Weblate rather than in GitHub. If you'd like to help with translations for any languages that you're a native speaker of, you'd be very welcome to join those translation teams, but it wouldn't be done through a pull request. The wiki's [Guidance for Linguists](https://habitica.fandom.com/wiki/Guidance_for_Linguists) has some details although Habitica has fairly recently moved from Transifex to Weblate and the new translation process is still being developed so some details on that page will be out of date.

**Comment by saraolson** [comment]
@HiroinaProtagonist Are you still working on this? If not, we'll put the issue back up for claim.

**Comment by HiroinaProtagonist** [comment]
Yes, I am, thanks for asking first. I’ll release it myself if I’m not able
to get it done during this winter break from school, since I think the
semester will be too busy.

**Comment by HiroinaProtagonist** [comment]
Have not abandoned this. I have the front-end part and am dealing with some issues with the reactivex and getting everything to update properly in the back-end.
