### ISSUE TITLE
MOBILE [Oct 12] Implement modal that forces users to change username

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica-android#1049]
Once we release the username feature, users have to set/confirm their username

**Comment by saraolson** [comment]
[Forced modal design](zpl://screen?sid=5baa8079b3727e3fd7089852&pid=585010e7d211174d029f324d)
[Keyboard up](zpl://screen?sid=5baa807aa542332192ab546d&pid=585010e7d211174d029f324d)
[Error typing](zpl://screen?sid=5baa807ac4fcc00466728c73&pid=585010e7d211174d029f324d)
[Errors and Confirmation](zpl://screen?sid=5baa807a82883d4efc8c75fd&pid=585010e7d211174d029f324d)
