### ISSUE TITLE
Add the delete option on Inbox

### ISSUE THREAD

**Issue by matheusvictor** [HabitRPG/habitica-android#1050]
The PMs don't have the trash icon or delete option, but this option exist in the website. It's interesting for a message sent accidentally, for example.

Also, when messages are deleted on website, the log continue existing in the Inbox. The user need clear the data/cache and log in again for log disappear.

**Comment by matheusvictor** [comment]
I need inform my UUID in this issue?

**Comment by saraolson** [comment]
Right now, you're able to delete individual messages from inbox but you can't delete from the convo-level view which could be very helpful in cleaning up the inbox. We have designs for this where you can swipe to delete a whole convo, just need them implemented.

Double checked the issue of messages deleted from web not going away, and indeed a pull to refresh is not enough to make them go away. need to settings > reload content. ideally the pull to refresh would be enough.
