### ISSUE TITLE
Add a quick-add textbox for easily adding new to-dos

### ISSUE THREAD

**Issue by voithos** [HabitRPG/habitica-android#1052]
I try to use Habitica's To-Dos list as my main to-do list, and it'd be nice to be able to quickly enter new items on the mobile app. Ideally, it'd be similar to the quick-add textboxes on the Habitica web site (and perhaps apply to dailies and habits as well, although I'm less interested in that).

Currently, I have to do the following:
1. Tap the "+" FAB
2. Tap "New To-Do"
3. Write the To-Do text
4. Tap "Save"

During this workflow, the UI changes dramatically (going from list view, to the detail view, then back to list view). If there was a quick-add textbox, it would decrease the number of steps needed to add a new To-Do, as well as remove any visual/cognitive strain associated with the rapidly changing UI.

**Comment by saraolson** [comment]
Thanks for your suggestion! We're definitely aware of this pain point and its something we've been interested in exploring in the future.

**Comment by veeeeeee** [comment]
We have thoughts on how we want to handle this interaction in the future but closing this for now. Moving forward, please submit requests through the feedback form: https://forms.gle/Fa6oztkDsbzLqSvE9. This will help us organize all the requests when we’re thinking about next steps. Thanks!
