### ISSUE TITLE
Can't buy cards

### ISSUE THREAD

**Issue by cvuorinen** [HabitRPG/habitica-android#1055]
All of the cards (get well card, congratulation card etc.) are missing in the shop.

If you have pinned any of then, they will show in your Rewards tab, but trying to buy them from there gives the following error.

![screenshot_20181013-151055__01](https://user-images.githubusercontent.com/1764167/46905343-091feb00-cefb-11e8-88f9-3b45a11eb54b.jpg)

![screenshot_20181013-151105__01](https://user-images.githubusercontent.com/1764167/46905344-0f15cc00-cefb-11e8-90b4-11e93ef76558.jpg)

**Comment by RaitheOfDureya** [comment]
I'm experiencing the same issue and I can't buy any of the cards using Android Version 29, AppVersion 3.1.1 (2690).

**Comment by cvuorinen** [comment]
Buying works now, they are just missing from the shop. But if you have pinned one then you can buy it using the app. But yeah, not that useful I guess since not likely that many people have them pinned.

**Comment by RaitheOfDureya** [comment]
I confirm that after pinning a card in the rewards using the desktop version of Habitica I could buy it using the Android App.

**Comment by saraolson** [comment]
ive made a new issue to actually surface cards in the shop, #1453
