### ISSUE TITLE
Collection quest progress not shown

### ISSUE THREAD

**Issue by cvuorinen** [HabitRPG/habitica-android#1058]
Screenshot from Android app:

![screenshot_20181015-070947](https://user-images.githubusercontent.com/1764167/46930814-9e80c380-d050-11e8-889c-6cf1b2205897.jpg)

Screenshot from web app at the same time:

![screenshot from 2018-10-15 07-58-42](https://user-images.githubusercontent.com/1764167/46930820-a9d3ef00-d050-11e8-9c1a-1ac0b59bf7eb.png)

**Comment by phillipthelen** [comment]
Can you try updating through the play store? This should be fixed with the update from a few weeks ago.

--  
Phillip Thelen
Sent with Airmail

**Comment by cvuorinen** [comment]
I do have the latest version (1.5.1)

**Comment by cvuorinen** [comment]
Wasn't able to reproduce with local install, so should be fixed with next version I suppose.
