### ISSUE TITLE
Irritating "How can we help you?" dialog during general use

### ISSUE THREAD

**Issue by KonomiKitten** [HabitRPG/habitica-android#1061]
There's a really irritating dialog that pops up when I am just using the app in general that says "How can we help you?" "Report a problem" "Suggest an improvement" "Powered by Instabug". I never click anything to show this dialog it just shows up while I am trying to use the app. It would be really nice if this did not happen. Screenshot of dialog below.

Habitica Version: 1.5.1 (1997)

![How can we help you?](https://user-images.githubusercontent.com/12713710/47601175-3353cb80-da18-11e8-9b8d-e6a1cefea17d.png)

**Comment by phillipthelen** [comment]
This dialog is triggered when users shake their device. Perhaps the threshold can be changed to have it be invoked less often by accident.

--  
Phillip Thelen
Sent with Airmail

**Comment by KonomiKitten** [comment]
@phillipthelen seems like a very odd behaviour for an app, it'd be nice to have the threshold increased and an option to turn it off entirely.

**Comment by saraolson** [comment]
@phillipthelen is this available for users that aren't a part of beta? and yeah, i often get this when i just pick up my device.
