### ISSUE TITLE
Share hatched pet image still off-center

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1068]
When you hatch a pet and select to share, it provides a screenshot preview of your pet and a url to go to. Two issues are here

1. the url no longer works because there is no static page ( @SabreCat this may be a web thing? should we just get rid of static urls and fix the preview image?)
2. the preview is cut off, so even if we removed the url ppl couldnt see the pet. also it just looks useless on any shared post. see attached example of a gold wolf pet in discord, looks the same in twitter:

<img width="690" alt="screen shot 2018-11-09 at 1 38 53 pm" src="https://user-images.githubusercontent.com/12453119/48281520-d64b1300-e424-11e8-81aa-8c3c0fbe08cf.png">

Other share features may be broken too, not sure.

**Comment by arajago6** [comment]
Setting bounds on the drawable before drawing it out should fix this, I guess. I can work this issue if it's free.

**Comment by saraolson** [comment]
@arajago6 It is indeed free! Thank you for taking it on, I'll mark it as in progress for you.

**Comment by arajago6** [comment]
Just noticed that this was rolled out. Mount images seem alright to me now, but pet images seem within bounds but not centered 😞

**Comment by saraolson** [comment]
@arajago6 im guessing it happened because pet sprites arent centered themselves, they're off to the side where they would appear next to the avatar. do you want to submit a new pr to fix the alignment?

**Comment by arajago6** [comment]
That should be the case @saraolson, but for the next few weeks, I am afraid I cannot spend good time on this. If anybody else wants to take it up in the meantime, please let them. 

I am attaching several pet images I gathered recently, hoping these will give an idea on the offsets.
![image](https://user-images.githubusercontent.com/13992966/58609158-764e7980-825b-11e9-9041-887c22864bd9.png)

**Comment by saraolson** [comment]
@arajago6 alrighty i'll change the title and if its not claimed by the time you're free again, the claim is all yours if you want it!
