### ISSUE TITLE
Guilds: No way to accept a guild invite from the UI

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1072]
Had a report of someone receiving a private guild invite, tapping the notification to view it, and then being unable to accept it because there is no invite in the UI and the notif went away.

**Comment by ajsviado** [comment]
will check

**Comment by ajsviado** [comment]
Can anyone help on how to reproduce this problem on my local environment. I checked the code but there seems to be no problem. Private guilds costs gems to create so I cannot test.

**Comment by saraolson** [comment]
@ajsviado hey there, just tested it by inviting a test account to a private guild. the test account gets a notification in the android notif center, but viewing 'My Guilds' in habitica shows no invite. 

tapping the invite from the notification center crashes the app and makes the invite go away, so there's no way to accept or reject from the app after that point.

tapping the actions on the invite from the notif center work as expected.

**Comment by ajsviado** [comment]
Thank you for the comment. I will check the code again.
