### ISSUE TITLE
Chat: Likes not visible if display name is too long

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1076]
On lower density screens, display names can be so long that they push the like count off the message card. this may be especially bad with staff and mod tags

**Comment by bacowan** [comment]
I think I'm going to take a stab at this issue if that's all right.

**Comment by saraolson** [comment]
@bacowan go for it! i'll mark this as in-progress. You can also shorten the 'Moderator' tag to 'Mod' to help save space as well.

**Comment by bacowan** [comment]
This is what it would look like with the username word-wrapping and with ellipses (obviously I'd fix the star not appearing on the second message from the top).

It looks okay without the Moderator tag, but there's really not a lot of space with it. Shortening to "Mod" would give room for about 3 more characters I imagine, though that might only be a solution for English; I'm not sure what other languages would look like. I included that with the ellipses screenshot for reference though.

Ellipses looks a little cleaner to me. Thoughts?

Wordwrap:
![Screenshot_1556075395](https://user-images.githubusercontent.com/5496948/56629887-843e2880-6625-11e9-8093-17728d990192.png)

Ellipses and shortened "Mod"
![Screenshot_1556077366](https://user-images.githubusercontent.com/5496948/56631035-e6992800-6629-11e9-957f-ba64da586d27.png)
