### ISSUE TITLE
Messages: Show Display Name of the account im talking to when in their convo 

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1078]
Right now it shows my own name, but seems more useful to show the name of the person the convo is with.

**Comment by debashisbiswas** [comment]
I'm interested in getting more involved in this project and this seems like a good first issue. Would it be okay if I took this one?

**Comment by saraolson** [comment]
@debashisbiswas very sorry for the late response, this got lost over the holiday rush! if you're still interested, feel free to take this on.
