### ISSUE TITLE
Todos: Drag and drop still not completely reliable

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1079]
Tasks stay gray for awhile and if you try to reorganize too fast it jumps all around.

**Comment by saraolson** [comment]
Closing for now until we hear its messing up again.

**Comment by Alys** [comment]
We see this reported fairly often, not always for To-Dos.

Here's one that came in my email about an hour ago:
"You probably are already aware of this problem, but I wanted to report a bug with sorting dailies and tasks on mobile app (I’ve encountered this problem on both Android and iPhone). When trying to move a daily further down the list it only moves a couple of steps or not at all - it seems at first like it’ll move but then it jumps back. I’ve also encountered this with to-dos, but to a lesser extent and usually fixable simply by repeating the action (which does not often help with dailies)."
