### ISSUE TITLE
Toolbar showing fragment class names

### ISSUE THREAD

**Issue by debashisbiswas** [HabitRPG/habitica-android#1095]
I was just looking into issue #1078, and noticed that certain fragments show the name of their class in the toolbar. 

A few places this can be reproduced:
- Opening an existing chat with another user will show "InboxMessageListFragment" in the toolbar.

- Opening the stable and clicking on a pet will show "PetDetailRecyclerFragment" in the toolbar.

- Opening the stable, navigating to the mounts and clicking on a mount will show "MountDetailRecyclerFragment" in the toolbar.

I've identified the cause as [navigation.xml](https://github.com/HabitRPG/habitica-android/blob/develop/Habitica/res/navigation/navigation.xml#L186-L218) - it looks like some of the `android:label` attributes contain the names of the fragments rather than string resources with the proper names. 
The Pet and Mount fragments should just require a string resource, but the InboxMessageListFragment may take a bit more time to solve (again referencing #1078) as the text in the toolbar will need to be dynamically set to the name of the other user.

This file is part of @phillipthelen's recent navigation improvements, so I decided to create an issue for it to avoid a potential conflict.

**Comment by saraolson** [comment]
tagging this as important since it has to do with the nav update and should be addressed before release
