### ISSUE TITLE
Tag filters should remain persistent across sessions

### ISSUE THREAD

**Issue by Abdillah** [HabitRPG/habitica-android#1100]
A feature suggestion to "Save filtering preferences as to persist across sessions".
I have two proposals: **first**, filtering always saved by default, **second**, a button/option is added to pin-up the filtering.

I'm going to hack myself (if not too hard) whenever this feature get accepted.

**Comment by veeeeeee** [comment]
When this is complete, we'd like to run it as a small experiment to gauge feedback.

**Comment by saraolson** [comment]
After judging user feedback where often they forget a tag filter is on and report a bug to admin, we'd rather not implement this.
