### ISSUE TITLE
Daily Reminder not working

### ISSUE THREAD

**Issue by bitstacker** [HabitRPG/habitica-android#1105]
Hi, the daily reminder does not work on Android 8.1/Oreo.

Steps to reproduce:
- Set Reminder to 1min into the future
- Wait
- Reminder won't trigger

The following output is generated by adb logcat:
`02-25 14:24:15.266  2835  5720 E NotificationService: No Channel found for pkg=com.habitrpg.android.habitica, channelId=null, id=1, tag=null, opPkg=com.habitrpg.android.habitica, callingUid=10127, userId=0, incomingUserId=0, notificationUid=10127, notification=Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x4 flags=0x11 color=0xff6133b4 vis=PRIVATE)
` 
I think this is due to changes how the notifications work in Android O: https://stackoverflow.com/questions/45668079/notificationchannel-issue-in-android-o

System used:
Android 8.1.0 on ZTE Axon 7
Latest Habitica App from PlayStore

**Comment by saraolson** [comment]
@bitstacker to confirm which reminder you're referencing: are you talking about the reminders you set on each individual daily, or the generic reminder set in the app settings? or perhaps both don't work.

**Comment by bitstacker** [comment]
@saraolson the generic reminder in the app settings (Settings -> Daily Reminder)

**Comment by ajsviado** [comment]
will check
