### ISSUE TITLE
Avatar stats widget shows hourglass icon even if user doesn't have any

### ISSUE THREAD

**Issue by arajago6** [HabitRPG/habitica-android#1120]
First of all: Love to the Habitica team and the contributors for creating such an awesome app.

Now to the issue: Below is a screenshot of the avatar stats widget from my phone. The hourglass count is hidden if the user does not have any of them but the hourglass icon is still shown.

![image](https://user-images.githubusercontent.com/13992966/55374151-76d5c880-54d5-11e9-9275-4bd05a76b584.png)

Also, an OCD like me will greatly appreciate some margin between the footer elements. For instance, some padding between the text '6' and the gold icon in the above example.

Please pardon me if this is a false alarm because I only started using the app couple of days back and haven't explored it fully.

**Comment by saraolson** [comment]
Thanks for picking this up! we'll try to get it reviewed and tested asap
