### ISSUE TITLE
Show confirmation toast when an invite is sent

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1122]
This is for Guild and Party invites. After sending off the invite a green toast should pop up saying 'Invite sent!'

**Comment by camerz** [comment]
Hi @saraolson! If possible, could I be assigned to this issue?

**Comment by phillipthelen** [comment]
Hey,  

Yes, that sounds good!

--  
Phillip Thelen
Sent with Airmail

**Comment by saraolson** [comment]
@camerz it's been marked as in progress for you. good luck!

**Comment by camerz** [comment]
@saraolson By "green toast", do you mean that the background should be green? I've figured one way to get the party invite to display, but the green background color isn't very readable. Are there examples of the green toast elsewhere, so I can be consistent with the formatting?
<img width="178" alt="green_toast" src="https://user-images.githubusercontent.com/16911321/56395535-dc24fb80-61ef-11e9-95bd-336f8680853a.png">

**Comment by saraolson** [comment]
@camerz yeah! you can see the green toast when you check off a task. It pops up to show you what you received for completing the task. This toast would be that same pill-shape and design with the words 'Invite sent!' within.

**Comment by phillipthelen** [comment]
[This class](https://github.com/HabitRPG/habitica-android/blob/d10bedd9901a231d30c27d2f75ac139115ebf089/Habitica/src/main/java/com/habitrpg/android/habitica/ui/views/HabiticaSnackbar.kt) is the one used for the other instances. If you search for the `showSnackbar` method usagees, you can find other examples of how exactly to use it.
