### ISSUE TITLE
Notifications do not display and settings bugs

### ISSUE THREAD

**Issue by vjba** [HabitRPG/habitica-android#1127]
# Initial issue:

I have noticed that app is not pushing notifications with events:
* Party quests have started
* Party messages
* Direct messages received

I've not tested for other notification problems. 

# Secondary (causal?)
 
When I went to check the app notifications I found this issue (animated gif below).

The issue persists after app restarts, device restarts, and app reinstalls. 

As you can see the flickering of check boxes increases in speed until the app grinds to a halt and has to be force closed.

![rec](https://user-images.githubusercontent.com/21375278/55879001-2291af00-5b8d-11e9-8493-6ed93cfd0ebd.gif)

**Comment by saraolson** [comment]
thanks for the report! we don't have notifications set up for party messages just yet, but if the other two aren't going through for you that is indeed a bug.
