### ISSUE TITLE
Hide damage when not participating in a boss quest

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1132]
Currently scoring a task will list damage done even if you arent participating in a boss quest.

Also, if you're in a party that is taking on a boss but you aren't participating, the boss hp bar will still show your 'pending damage' even though you'll never damage it.

**Comment by Alys** [comment]
Version 2.0.2 (2179) so has the problem with the boss HP bar showing pending damage.

**Comment by Alys** [comment]
I'm reopening this because the latest version has the problem with the boss HP bar showing pending damage.

**Comment by saraolson** [comment]
this also happens when you're participating in a collection quest

**Comment by laserzt** [comment]
Hi. I want to try to fix this bug. I already checked out the code, and ran the Habitica project and got the bug shown in my app.
Waiting for approval to try to fix it.

**Comment by shanaqui** [comment]
@laserzt Thank you! I'll mark it as in progress for you.

**Comment by laserzt** [comment]
Hi. This is fixed now since merge #1346

**Comment by laserzt** [comment]
Can you please give me the Contributor achievement?      (User Id: 08576d02-d94b-48aa-9ed3-16de73dd814b)
Thank you :))))

**Comment by laserzt** [comment]
So, do you want for people that are not in quests to not see the damage done at all? and the number of items collected?
Because that is not what the bug title said. But I can do that also.

**Comment by saraolson** [comment]
No, they should be able to see the progress the other party members have made (damage done and items collected) when viewing the quest from the party screen. They should just not see their own 'pending' damage when they are not participating, and should not get notifications on task completion of quest damage being done.

**Comment by phillipthelen** [comment]
Sorry. I forgot to do that and then forgot to comment here that I gave you The contribution in your Habitica account
