### ISSUE TITLE
Rewards: Wrong message in modal when you try to purchase without enough Gold

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1139]
If you try to purchase an armoire without enough Gold, the message that shows says:

'Monthly Gem Cap Reached
You need to complete more tasks before you can afford this item!'

It should say:

'Not Enough Gold
You need to complete more tasks before you can afford this item!'

**Comment by Alys** [comment]
This also happens for other types of Rewards (I tested with Health Potion and Equipment). I'm about to edit the title to replace "Armoire" with "Rewards".

**Comment by rsamborski** [comment]
Fix proposed in following PR #1151
