### ISSUE TITLE
Chat: Show timestamp on system messages after a tap

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1143]
UX would be: tap a system message (mainly in Party) and the timestamp will show below it.

<img width="372" alt="Screen Shot 2020-05-28 at 10 09 45 AM" src="https://user-images.githubusercontent.com/12453119/83152097-687c4000-a0cb-11ea-87c6-735f3ae0a186.png">

**Comment by ilally93** [comment]
Hello,
I would be interested in working on this if it is still available.  Thank you!

**Comment by saraolson** [comment]
@ilally93 it is still available! i'll mark it as in progress for you
