### ISSUE TITLE
Settings: Change Display Name change modal actions to 'Cancel' & 'Save'

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1145]
Right now if you go to change you display name from settings, the modal has the actions 'Cancel' & 'OK'. For consistency, we'd like it to say 'Cancel' & 'Save'

**Comment by meriembounab** [comment]
Hi I'm a new contributor and I'd like to take on this issue! Seems like a good place for me to start

**Comment by saraolson** [comment]
@meriembounab hello there! this is all yours then. i'll remove the 'help wanted' tag and add 'in progress'

**Comment by Nikosmonaut** [comment]
Hello.

Any news on this issue ? I can do it otherwise.

Should this change also apply on Photo URL and About ?

**Comment by phillipthelen** [comment]
Hi @Nikosmonaut,

It doesn't look like this is still being worked on, so you can go ahead with fixing this.
Yes, this should then also apply to the photo url and about.
