### ISSUE TITLE
Can´t create new task

### ISSUE THREAD

**Issue by Sebastian-Schuetz** [HabitRPG/habitica-android#1148]
When trying to add a new task, the following warning appears and the todo isn´t created.
![WhatsApp Image 2019-05-08 at 18 15 18](https://user-images.githubusercontent.com/48769132/57390771-5d532b00-71bd-11e9-9984-24eacf34c95f.jpeg)

**Comment by saraolson** [comment]
this issue has already been fixed in the latest update available on the play store
