### ISSUE TITLE
Filter lists breaking when app resumed

### ISSUE THREAD

**Issue by gnatt123** [HabitRPG/habitica-android#1163]
For over 6 months, whenever the app is opened after being in the background for more than 5 minutes or so (whenever it opens in such a way that it has a brief white screen while it reopens itself), all the filters are broken for to-dos and dailies. Filter options for dailies show all/weak/strong, instead of all/due/grey, and whatever is selected, everything is shown. App has to be closed and restarted to work normally. Happens 10-20 times per day. Exact same issue on this phone and my previous. Happy to get screen capture to demonstrate if necessary.

**Comment by saraolson** [comment]
we already have an issue for this here: #1112 

going to close this issue and copy paste your comment over there
