### ISSUE TITLE
Repository contains a proprietary font file

### ISSUE THREAD

**Issue by RedBug312** [HabitRPG/habitica-android#1210]
I've been browsing the repository, and I found `Habitica/src/main/assets/HelveticaNeue.ttc` the font seems to be proprietary, according to the license contained in the font file:

![圖片](https://user-images.githubusercontent.com/11537681/62691827-0817f700-ba02-11e9-9615-f065947a7ba1.png)

Since this repository uses an open-sourced GPL-3.0 license, I'm concerned if this is against the license of this font?

**Comment by saraolson** [comment]
thanks for finding this! it was not in intentionally. it happened to be put in by a program we use to translate graphic elements into code. we've removed it now.
