### ISSUE TITLE
tag filter hides all tasks

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#122]
When I select a tag that I know has been applied to some tasks, my task lists appear empty.

Reproducible with several different tags.

(Sorry about the late bug report. :(  I haven't been able to install anything on my phone for a while until negue helped me just now.)

**Comment by negue** [comment]
Not able to reproduce this bug, also the rotating is disabled so... can be closed?

**Comment by Alys** [comment]
I just tested with a tag that I know has tasks assigned to it and they didn't show up. Then I chose another tag, some tasks appeared, then the app crashed, and then when I went back in, all the tags I tried were working correctly. So the bug comes and goes. Close this if you like if that's not enough to go on and if you aren't hearing similar reports from others.

**Comment by Alys** [comment]
I'm closing this. I haven't noticed this bug for months.

If anyone else is still experiencing it, comment here and we can reopen.
