### ISSUE TITLE
Action buttons prevent proper viewing

### ISSUE THREAD

**Issue by matheusvictor** [HabitRPG/habitica-android#1220]
**Describe the bug**
Action buttons prevent proper viewing of purchased or purchased Rewards. When you buy an item or mark a task as completed, the item obtained (experience, gold spent, etc.) is hidden by the action buttons.

**To Reproduce**
Steps to reproduce the behavior: To reproduce, simply purchase an item from the Rewards section or mark a To Do as done.

**Expected behavior**
In particular, I didn't really like the current action buttons, especially the add (+) something button.  He preferred it in the lower right corner as a floating button.  I believe that refactoring in terms of button organization is necessary.

**Screenshots**
I will send a screenshot soon

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A2 Lite 
 - OS: Android One 9
 - App Version: 2.1 (2227) - BETA
 - Habitica Username: @Viccthor 

**Additional context**

**Comment by phillipthelen** [comment]
I fixed the underlying issue. Since we just updated the design of the bottom navigation and the feedback has mostly been positive, we are currently not considering updating it again.
