### ISSUE TITLE
All senders are with Tier 7 label

### ISSUE THREAD

**Issue by matheusvictor** [HabitRPG/habitica-android#1223]
**Describe the bug**
All senders are flagged with Tier 7 in Inbox.

**To Reproduce**
Steps to reproduce the behavior: access the Inbox.

**Expected behavior**
The labels need identify if a user have a Tier or no, and which Tier this user is.

**Screenshots**
![Screenshot_20190918-182908](https://user-images.githubusercontent.com/12521391/65187753-fbe07a00-da42-11e9-94b9-18f56e750011.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A2 Lite
 - OS: Android One 9
 - App Version: 2.1.1 (2241) - BETA
 - Habitica Username: @Viccthor

**Comment by phillipthelen** [comment]
There is still an issue here where on the server side the API doesn't always return the right contributor info. But the client side issue is fixed.
@paglias @negue  it looks like the API returns the contributor and userStyles info from the last message, so it might be the users own data shown instead of the one for the other user.

**Comment by negue** [comment]
The conversation query just uses the last messages in the list, which could be also the current user (not the target user).

How about we return the current contributor / userStyles of this user instead of the one in the messages?  @phillipthelen @paglias

**Comment by matheusvictor** [comment]
Adding a detail to this question: I am Tier 6, so I believe there is something wrong with the current tag, as it refers to Tier 7

**Comment by paglias** [comment]
Merged on the web repo, it'll go live for testing soon and on the main website next week but let me know if you need it earlier
