### ISSUE TITLE
Prices not entered in the "Subscription" menu

### ISSUE THREAD

**Issue by matheusvictor** [HabitRPG/habitica-android#1230]
**Describe the bug**
By clicking on the "Subscription" menu, prices are not informed. But when you click on the gift someone option, the prices appear normally.

**To Reproduce**
Steps to reproduce the behavior: Access the "Subscription" menu through the application.

**Expected behavior**
Prices need to appear normally and you need to be able to select the desired option (as the checkbox isn't working either).

**Screenshots**
![photo4965745663723808867](https://user-images.githubusercontent.com/12521391/66446273-3de85480-ea20-11e9-81b2-dec4840a9a76.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A2 Lite
 - OS: Android One 9
 - App Version: 2.2pl 2256
 - Habitica Username: @Viccthor

_Translate with Google Translate._

**Comment by KingOfDireWolves** [comment]
I am having the exact same issue.

- Device: Xiaomi Mi 8 Pro
- OS: Android 9
- App Version: 2.2pl (2256)
- Habitica Username: @KingOfDireWolves
