### ISSUE TITLE
Back button doesn't react in Community Guidelines

### ISSUE THREAD

**Issue by daryaleshcheva** [HabitRPG/habitica-android#1235]
**Describe the bug**
Back button doesn't react in Community Guidelines.

**To Reproduce**
1.	Open app;
2.	Tap the NavDrawer (Hamburger button);
3.	Tap `tavern`;
4.	Tap `View Community Guidelines`;
5.	Tap `back button`.

**Expected behavior**
The previous screen should open.

**Screenshots (video)**
[https://photos.app.goo.gl/rU5YgWsjTJjJYRcg9](url)

**Smartphone**
Device: Xiaomi Mi 9 SE
Android Version: 9
AppVersion: 2.2.1 (2272)
Habitica Username: @hb-en4s6dk4ie7jyfmgl

**Comment by Nikosmonaut** [comment]
Hello.

I'm new to habitica contribution. Is this issue officially reviewed (I see no tag yet) ? I would like to solve this one.

**Comment by matheusvictor** [comment]
@phillipthelen, do you can put a tag on this issue?

**Comment by insomniacmonkey** [comment]
I was able to reproduce this issue:
Device: samsung Galaxy Note8 
Android Version: 28 
AppVersion: Version 2.2.2 (2285) 
User ID: 2e595cc8-a584-4388-be9b-09d761a377b6 
Level: 78 
Class: rogue 
Is in Inn: false 
Uses Costume: true 
Custom Day Start: 2 
Timezone Offset: 300

**Comment by phillipthelen** [comment]
Sorry. I forgot to close this issue. It should be fixed in the most recent beta.
