### ISSUE TITLE
Widget: Show Streaks on Widgets

### ISSUE THREAD

**Issue by crimx** [HabitRPG/habitica-android#1252]
Here is my use case:

I have a "Drink 8 Glasses of Water" in my daily llist and a "Drink a Glass of Water" in my habit list. Every time I drink a glass of water I tap the habit plus. At the end of a day I would check steaks and tick the daily item if I hit the goal.

If the habit widget can show streaks I can see how close I am to my goals without opening the app.

Thanks again for the amazing work!

**Comment by Aayushf** [comment]
I would like to solve this issue, by adding a TextView in the widget layout, and displaying the upCounter of the Task item for that Widget.

**Comment by saraolson** [comment]
We're going to look at widget designs overall soon since android 12 was released. We may include streaks at that point, but in general, for the widget we will prioritize space over content so it may not make it in.
