### ISSUE TITLE
Accepting/rejecting of the invitation to quest in party does not give any feedback.

### ISSUE THREAD

**Issue by sebzieja** [HabitRPG/habitica-android#1253]
**Describe the bug**

**To Reproduce**
1. Get invitation to quest in party
2. In Party view click accept invitation to quest.
3. Nothing happens. When you click again then popup message appears saying that you already joined quest.

**Expected behavior**
You are redirected to party tab / get notification that you successfully joined quest.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xiaomi MI 9 SE
 - OS: Android 9
 - App Version: 2.3
 - Habitica Username: @sebastianzie

**Additional context**
In mobile app there are numerous places where accepting/rejecting things do not give any feedback. Reloading existing view will do a thing, or redirecting to somewhere else.

**Comment by Alys** [comment]
This might also help with people who don't realise that they accepted the quest invitation after the quest had been started. At the moment, there's no feedback to indicate that they aren't in the quest, so if they saw a message something vaguely like "I'm sorry, this quest has already started so you can no longer join it", that might help with their confusion.
