### ISSUE TITLE
 NPCs should have NPC style on Username in chat, Hall, etc #11617 

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#1254]
**Describe the bug**
When [players who are also NPCs](https://habitica.fandom.com/wiki/Kickstarter#Non-Playing_Characters_.28NPCs.29) post to chat, their Display Names don't have the correct formatting for an NPC. You can see what the format should be by looking at Bailey's name in the "Staff and Moderators" list on the right-hand side of the [Tavern](https://habitica.com/groups/tavern) on the website. 

For an NPC who is also a contributor or moderator (e.g., Bailey is a mod), the style should be the NPC style not the contributor/moderator style.

The NPC style should be applied in all the places where a contributor/moderator style is applied.

See also https://github.com/HabitRPG/habitica/issues/11617 for more details about this bug, which currently also occurs on the website.

**To Reproduce**

1. Visit [Bailey Appreciation Guild ](https://habitica.com/groups/guild/401bd3dc-f32b-411b-a5ae-2ee904cc2392)
2. Find a post by Bailey.
3. Observer it does not have the NPC styling.

Or on local install:
1. Set a test user to be an NPC using the info in https://github.com/HabitRPG/habitica/issues/11617
2. Post a message by that user.
3. Check if the user is displayed as an NPC  and if not, that needs to be fixed.
4. Make the same user also a moderator using the info in https://github.com/HabitRPG/habitica/issues/11617
5. Post another message.
6. Observe that the user's Display Name has the mod styling when it should have the NPC styling.

**Expected behavior**
A player who is an NPC should always have the NPC style on their Display Name, in all locations where Display Names appear with styling.
If the player is also a moderator, they should have the NPC style but should also have the "Mod" badge appear after their name.

**Screenshots**
Current behaviour:
![Screenshot_20191214-134619](https://user-images.githubusercontent.com/1495809/70843115-b3393100-1e78-11ea-940d-44336fd3a2e4.png)
Expected behaviour:
The Display Name should be black with the little green flag icon (see the website Tavern's sidebar). The "Mod" badge should remain as it is now.

**Smartphone (please complete the following information):**
 - Device: Moto G6
 - OS: Android 9
 - App Version: 2.4
 - Habitica Username: Alys

**Additional context**
It's possible that the same fix will be needed on the iOS app. I don't have iOS so I can't check.

**Comment by Nikosmonaut** [comment]
Hello.

I may try to implement it.

**Comment by saraolson** [comment]
Are you still interested in working on this @Nikosmonaut ? We'd like to fix this in the next android update.

**Comment by Nikosmonaut** [comment]
Yes you can fix it.
