### ISSUE TITLE
Subscription: Add pull to refresh + Server check

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1256]
Allow people to pull to refresh on the sub page, and request a server check to their subscription status when they perform the action.

Right now if someone cancels their subscription, it will still show as active for up to a few days. Would like to be able to accurately reflect their cancellation faster than that.

**Comment by phillipthelen** [comment]
Pull to refresh is now implemented. However I will need to write a new API call on the server side to cancel the subscription.
