### ISSUE TITLE
Aurora Mounts isn't displayed completely

### ISSUE THREAD

**Issue by matheusvictor** [HabitRPG/habitica-android#1257]
**Describe the bug**
When equipping an Aurora mount or mascot, only a portion of this is displayed when equipped with Avatar.

**To Reproduce**
- Hatching a Aurora pet
- Feed the pet Aurora until it becomes a Mount
- Equip the Aurora Mount 

**Expected behavior**
The mascot should be displayed completely.

**Screenshots**
![Screenshot_20191221-115748](https://user-images.githubusercontent.com/12521391/71309676-82fa1100-23e9-11ea-91ec-861cfc50ecf6.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A2 Lite 
 - OS: Android One 9
 - App Version: 2.4 (2327) BETA
 - Habitica Username: @mathvictor

**Comment by saraolson** [comment]
This should be fixed now. Let us know if you still have the problem.

**Comment by matheusvictor** [comment]
@saraolson, that's ok now =)
