### ISSUE TITLE
Reminders occur at seemingly random times or not at all

### ISSUE THREAD

**Issue by MikeCook9994** [HabitRPG/habitica-android#1258]
**Describe the bug**
My reminders across nearly all of my dailies and tasks don't occur at the expected time.

For example, I just received this push notification reminder:
![Screenshot_20200106-112811](https://user-images.githubusercontent.com/6856899/71843243-49c3d100-3078-11ea-9c22-00d3d7985a3a.png)

However, this notification should come until tonight and as I understand it shouldn't even come on a Monday based on how it's configured. Even so, it certainly shouldn't have come this morning
![Screenshot_20200106-112902](https://user-images.githubusercontent.com/6856899/71843308-6a8c2680-3078-11ea-8407-7cbd3046bc86.png)

I received this alert last night around 11PM:
![Screenshot_20200106-113415](https://user-images.githubusercontent.com/6856899/71843392-a0310f80-3078-11ea-9262-f142183daa03.png)

As a final example, I have this alert that I don't think has ever occurred and I certainly did not receive it this morning:
![Screenshot_20200106-113629](https://user-images.githubusercontent.com/6856899/71843466-d2db0800-3078-11ea-9746-49ce0fbad195.png)

I have many other dailies with reminders that are simply not happening at all or coming at completely random times.

Here are my settings. Frankly, I have no idea what the reminder time in the settings is for, but I've never gotten a reminder for it. Everything in push notifications is enabled:
![Screenshot_20200106-113754](https://user-images.githubusercontent.com/6856899/71843586-1a619400-3079-11ea-8497-6706fe357167.png)

Update: as I was writing this bug I did get the push notification to check off my to-dos. Except it chat at about 11:45 AM and mine is configured come at 10:30 PM as you can see in the above screenshot:
![Screenshot_20200106-114343](https://user-images.githubusercontent.com/6856899/71844034-226e0380-307a-11ea-8673-295799df68df.png)

**To Reproduce**
Create a daily. Set a reminder on said daily.

**Expected behavior**
To receive my reminders at the expected time

**Smartphone (please complete the following information):**
 - Device: Pixel XL
 - OS: ndroid 10
 - App Version: 2.4 (build 2324)
 - Habitica Username: @Draenal

**Comment by MikeCook9994** [comment]
Apologies for the massive screenshots I guess

**Comment by saraolson** [comment]
Thanks for your detailed write up! We've done some work on the reminders in the past, but these bugs always prove surprisingly tricky. We'll look into it as soon as we can.

**Comment by MikeCook9994** [comment]
Let me know if there's any additional information you need that can only be obtained from my device. My bug report here kinda just proves there's an issue but doesn't really do a ton for providing information to solve it.

**Comment by phillipthelen** [comment]
I made some changes to how these notifications are handled, but since I could not verify the fix I'm moving this to 2.6 for now to see if things are fixed or not.

**Comment by saraolson** [comment]
it seems this wasn't fully fixed. we looked at this again in 2.6 and still can't see what may help make the behavior more consistent. bumping again and marking as help wanted in case anyone has any ideas.

**Comment by laserzt** [comment]
Hi, I want to try to tackle this bug.

**Comment by saraolson** [comment]
@laserzt go for it! i'll mark it as in progress

**Comment by shanaqui** [comment]
@laserzt Hi! Are you still working on this issue? If not, I'll set it back to help wanted so someone else can have a try.

**Comment by laserzt** [comment]
I'm not working on it anymore, sorry...
It started working perfectly on my phone, so I thought that there was an
update that fixed it

‫בתאריך יום א׳, 10 בינו׳ 2021 ב-19:11 מאת ‪shanaqui‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by shanaqui** [comment]
@laserzt Thanks for the update, I've set the issue back to help wanted.

**Comment by shanaqui** [comment]
A new report of this:

> Device: samsung SM-G9810
> Android Version: 30
> AppVersion: Version 3.1.2 (2694)
> User ID: bbfc7a12-8de5-4c02-8b9e-daed0d70070e
> Level: 14
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: 0
> Details:
> 
>  
> Notifications launching late, e.g. my 12:00 notification just came thru at 12:10, sometimes for other notifs they come even later

User turned off adaptive notifications, Habitica was open in the background and they were connected. Notifications came through once the user foregrounded the app.

**Comment by shanaqui** [comment]
Another report: 

> Device: Google Pixel 3a XL
> Android Version: 29
> AppVersion: Version 3.1.2 (2694)
> User ID: b1495d0b-f1ef-4f7e-9c55-47a47b75bb00
> Level: 12
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 4
> Timezone Offset: 300 

They *never* receive notifications, though.

**Comment by saraolson** [comment]
> Device: samsung SM-G973F
> Android Version: 31
> AppVersion: Version 3.4.2 (3133)
> User ID: 0a854f6d-b044-4507-b973-8f951a7d1dd5
> Level: 2
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> Timezone Offset: -60
> Details:
> 
>  Hello, I'm new to your app and I can't find a way to have a reminder for my daily task. I would like it to be notifications but nothing happens (no alarm, no notification) at the reminder defined (though I checked alarm and notifications in the parameters)

**Comment by saraolson** [comment]
>  Hi, I'm receiving push notification reminders one hour later... I setup a task in my phone to remind me at 18:00 and I receive the notification way later.

Asked them if they've changed time zones recently, they said no. asked them to try deleting the reminder and recreating it:

> 
> I haven't changed any timezone on any of my devices. In my browser, I use Atlantic/Canary (WET, +0000) and in my Android phone I'm using Canary (GMT +00:00).
> 
> After deleting the reminder on my Android phone, setting it up again and waiting for it to be triggered again, now it's worst. I expected the notification at 18:00 and I received it at 20:40.

**Comment by saraolson** [comment]
this PR should solve this issue (https://github.com/HabitRPG/habitica-android/pull/1720)
