### ISSUE TITLE
App crash on 1/21 Beta release

### ISSUE THREAD

**Issue by Ham5andw1ch** [HabitRPG/habitica-android#1261]
Describe the bug
App crashes after logging in on latest Beta release

To Reproduce
Open the app and login with Google account

Expected behavior
No crash

Smartphone

Device: Google Pixel 2
OS: Android 10
App Version: 2.4.1
Habitica Username: NavReth

**Comment by matheusvictor** [comment]
Oh, thanks for report it @Ham5andw1ch ! I see it now and I justed thinking open a issue :)
