### ISSUE TITLE
show grey dailies on daily widget

### ISSUE THREAD

**Issue by noeuds** [HabitRPG/habitica-android#1265]
Is it possible to show grey dailies in daily widget ? I'm using grey dailies for long term dailies (dailies expected to check 3-4 times in a week) but they don't show on the android widget.

**Comment by saraolson** [comment]
Hi there! This feature request would be best suited to be submitted in our form you can find here: https://forms.gle/Fa6oztkDsbzLqSvE9 This will help us organize all the requests when we’re thinking about next steps. Thanks!
