### ISSUE TITLE
Duplicate screen on the onboarding carousel 

### ISSUE THREAD

**Issue by JRIngram** [HabitRPG/habitica-android#1269]
**Describe the bug**
On the onboarding section of the app (the carousel of screens when the user opens the app for the first time) the screen showing tasks (Floss / Go to the gym) appears two times

**To Reproduce**
* Download the app
* Open the app
* Swipe through the caousel

**Expected behavior**
This screen should only appear once.

**Smartphone (please complete the following information):**
 - Device: Samsung A10
 - OS: Android 9
 - App Version: 2.5 (2384)
 - Habitica Username: flyin-penguin19

**Additional context**
First time installing the app on this device

**Comment by saraolson** [comment]
We found the issue for this and it should be fixed next update
