### ISSUE TITLE
Display daily icons to the right of the daily name in order to save vertical space

### ISSUE THREAD

**Issue by roastchicken** [HabitRPG/habitica-android#1270]
**Is your feature request related to a problem? Please describe.**
My dailies take up too much vertical space. I see that they could be shown more compactly.

**Describe the solution you'd like**
The icons (streak and tags) currently display on a new row under the daily name. I think they could be positioned in the same row, to the right of the name in order to save vertical space.

**Describe alternatives you've considered**
I haven't considered any alternatives.

**Additional context**
Here's a mockup I created:
![mockup of my proposed solution](https://user-images.githubusercontent.com/524709/76599814-05383400-6506-11ea-8d4e-a1cf9768a06e.png)

**Comment by roastchicken** [comment]
I would be interested in implementing this, but I have very little Android experience.

This issue also exists on the website. I'm not sure how the code base is set up, but perhaps a fix on the website could be easily ported to Android? I'm a web developer, so I would be comfortable implementing this in the web app.

**Comment by roastchicken** [comment]
I would say this is more an enhancement than a feature, but I don't seem to be able to assign labels.

**Comment by saraolson** [comment]
While I agree this does work and save space in this specific case, there are a lot of cases where this design will break down. For example, if you have notes, or a longer task title, or a high streak count, or larger text for accessibility reasons, or a challenge icon in the row, this design becomes less efficient. The reasons we put the icons on their own line is to be consistent with all task types in every configuration, and to give the task title and notes room to exist on their own. 

When making design or feature suggestions, the staff will need to sign off on them before any changes are made. There could definitely be improvements to cut down on vertical space used. We have even been experimenting with the idea of allowing users to hide icons all together. However, putting the icons on the same line as the text isn't a solution we'd like to pursue.

**Comment by roastchicken** [comment]
Well, that's disappointing.
