### ISSUE TITLE
Hatching Potions does not appears instantly

### ISSUE THREAD

**Issue by Josh012422** [HabitRPG/habitica-android#1271]
**Describe the bug**
When you complete a task, the app notifies that you earned a hatching potion. Then, when you go to the items tab, the potion does not appears until you restart the app.

**To Reproduce**
Complete a task and get an item.

**Expected behavior**
I expected the potion to appear instantly on the items tab

**Smartphone:**
 - Device: Acer Iconia One b1-780
 - OS: Android 6
 - App Version: 2.5 (2384)
 - Habitica Username: DJBlueSlime

**Comment by Josh012422** [comment]
Same with eggs and food.

**Comment by saraolson** [comment]
I was able to reproduce this but pulling to refresh on the task page was enough to make them show in items, rather than requiring an app restart.
