### ISSUE TITLE
"monthly" Daily is not scheduled correctly when Start Date changes

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#1272]
When a Daily is set to repeat "Monthly" on "Day of the Month", the day that it is supposed to be due on is taken from the Start Date. E.g., if the Start Date is 3 March 2020, then the Daily should be due on the 3rd of every month. I.e., `daysOfMonth` should be set to `[ 3 ]`

If the Daily is edited to change the Start Date, then future due dates should be changed to match. E.g., if you edit the Daily to change the Start Date to 6th March, then `daysOfMonth` should be changed to `[ 6 ]`
This works correctly on the website but does not on the Android app. When a monthly Daily is edited on the Android app to change the Start Date, the `daysOfMonth` value is not changed. The expected behaviour is that `daysOfMonth` is changed to match the new Start Date.

Below is (I think) the website code responsible for changing `daysOfMonth` when Start Date changes.

It's possible that this bug occurs in the iOS app too. I don't have an iOS device for testing it.

Perhaps the best way to fix this is to bring this edit feature into the API, however that's not a call I can make so I'm logging this here since at the moment it's an Android issue.

https://github.com/HabitRPG/habitica/blob/3fe307f6ea4b19b878c521069e6817ebb2a249c9/website/client/src/components/tasks/taskModal.vue#L1307-L1313

https://github.com/HabitRPG/habitica/blob/3fe307f6ea4b19b878c521069e6817ebb2a249c9/website/client/src/components/tasks/taskModal.vue#L1406-L1415

**Comment by saraolson** [comment]
Was decided this would be better handled through changes to the API. Reposted issue in web repo for that: https://github.com/HabitRPG/habitica/issues/12041
