### ISSUE TITLE
Crash in the Guilds menu

### ISSUE THREAD

**Issue by matheusvictor** [HabitRPG/habitica-android#1274]
**Describe the bug**
Upon entering the Guilds menu and selecting any one for viewing, the application is terminated

**To Reproduce**
- Click on the Guilds menu
- And select any Guild you want to visit

**Expected behavior**
The selected guild should be opened without the app being closed

**Screenshots**
![Screenshot_20200321-095901](https://user-images.githubusercontent.com/12521391/77227026-96895500-6b5b-11ea-961a-56d57d9bfc96.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A2 Lite
 - OS: Android One 9 
 - App Version: 2.5 (2387) - BETA
 - Habitica Username: @mathvictor

**Comment by matheusvictor** [comment]
The app crash If the user click on notifications too

**Comment by phillipthelen** [comment]
Can you confirm if these two crashes still happen with the beta version released yesterday?

**Comment by matheusvictor** [comment]
@phillipthelen, this is ok now! ;)
