### ISSUE TITLE
Challenges: When creating, can only add one task

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1278]
When creating a challenge, if you add a second task it will over write the first one you add. It will also show in the wrong place of the screen. For example, I add a Habit. I then add a Daily. The Daily will show in the Habit's place, not in the Daily section.

When I create the Challenge, it's only created with the one task shown.

**Comment by renatojobal** [comment]
I would like to work on it @saraolson .

I could start to review the following things:
- The function that allows to know if the task is already in the view into the recycler view
- The firebase id of the new task added (Maybe here could be the problem)

**Comment by saraolson** [comment]
thank you for looking into this and submitting a fix! we'll review and potentially release it in the next milestone
