### ISSUE TITLE
Tags created by the user are not rendered until the user object is refreshed

### ISSUE THREAD

**Issue by TNychka** [HabitRPG/habitica-android#1281]
**Describe the bug**
Tags created by the user are not rendered until the user object is refreshed. 

**To Reproduce**
1. Click the hamburger drop down menu for tags
2. Create a new tag.
3. After creating the tag, you should be able to see the tag in the menu. 
4. Close the menu, do not refresh the user, open the menu again
5. The tag will not be present

**Expected behavior**
Expect the tag to be present after opening the menu a second time

**Solution**
In TaskFragment.onCreate() of the TagDialog the setTags call should not use the local user object tags, but should instead pull the tags from the localRepository.

**Comment by TNychka** [comment]
https://github.com/HabitRPG/habitica-android/pull/1280/files#r399251692
The fix exists here, however it's part of the offline PR. It can be extracted into it's own PR if desired!

**Comment by saraolson** [comment]
I'm going to assign this to 2.6 since the fix is there, it just needs extracted. @phillipthelen if you'd rather wait tho, feel free to take it out of 2.6.
