### ISSUE TITLE
Google Authentication which loops in case of cancellation / refuse

### ISSUE THREAD

**Issue by Adaok** [HabitRPG/habitica-android#1290]
**Describe the bug**
In case I want to cancel the authentication with my Google account, I have to force the kill of the app to authenticate myself otherwise.

**To Reproduce**
I launch my application for the first time, I go to the "Register" part.
I click on Sign up with google.
I select my google account.
I see Google autorizations ask by Habitica.
I refuse or I cancel using the back button.
We return to the previous screen then the authorization request is restarted and sends us back to the Google Authorizations screen

**Expected behavior**
Return to the registration screen and be able to connect / create an account without having to kill the app.
This bug is also present on Login Screen

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 10
 - App Version: 2.5
 - Habitica Username: not applicable

**Comment by anitawoodruff** [comment]
I'm up for taking a look at this. Haven't worked with the Habitica repo for ages though so may take a while for me to get back up to speed!

**Comment by anitawoodruff** [comment]
I took a look at this and tried to reproduce the issue.

Strangely though, I got different results with the version of the app in the Play store (2.5) than with the debug version of the app I built on my computer. 

In short, I could reproduce the issue as described with the version of the app in the Play store, (got taken back to the screen below whenever I tapped 'Deny') whereas with the version of the app I built myself, I didn't get stuck in the loop, but I was simply unable to register an account via Google auth at all. (I can select the account but then nothing happens - I don't even see the screen below).

![screenshot-habitica-auth-bug](https://user-images.githubusercontent.com/1918555/79085570-0214ab80-7d31-11ea-948b-e788bbc8384b.png)

Is this expected?

**Comment by Adaok** [comment]
I think what is expected is that we can return to the Google Sign-In option despite the first refusal.
For your second problem, just in case, are you thinking about adding your debug certificate fingerprint ?
[Authenticating Your Client](https://developers.google.com/android/guides/client-auth)
It is a frequent oversight.

**Comment by anitawoodruff** [comment]
Thanks, yes, I think that's the issue.

Do I need to follow the steps at https://developers.google.com/identity/sign-in/android/start-integrating#configure_a_project to create a new Cloud Console project with the habitica package name to add my debug certificate to? 

(I have done this for personal projects but I don't know the procedure for shared ones).

**Comment by anitawoodruff** [comment]
Ok I did that, and I no longer get `GoogleAuthException: UNREGISTERED_ON_API_CONSOLE`

However it still doesn't work to login or register via Google account, with the following stack trace:

```
2020-04-13 21:26:00.769 16654-19518/com.habitrpg.android.habitica.debug W/System.err: java.lang.RuntimeException: com.google.android.gms.auth.GoogleAuthException: ServiceDisabled
2020-04-13 21:26:00.769 16654-19518/com.habitrpg.android.habitica.debug W/System.err:     at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
2020-04-13 21:26:00.769 16654-19518/com.habitrpg.android.habitica.debug W/System.err:     at io.reactivex.exceptions.Exceptions.propagate(Exceptions.java:46)
2020-04-13 21:26:00.769 16654-19518/com.habitrpg.android.habitica.debug W/System.err:     at com.habitrpg.android.habitica.ui.activities.LoginActivity$handleGoogleLoginResult$1.call(LoginActivity.kt:412)
2020-04-13 21:26:00.769 16654-19518/com.habitrpg.android.habitica.debug W/System.err:     at com.habitrpg.android.habitica.ui.activities.LoginActivity$handleGoogleLoginResult$1.call(LoginActivity.kt:60)
```

**Comment by anitawoodruff** [comment]
Solved that problem by filling out the OAuth consent screen details in the cloud console. Named it Habitica Debug to avoid confusion and can now reproduce the bug on a local build. Hooray!

Now onto actually *fixing* the bug..(hopefully!)

**Comment by anitawoodruff** [comment]
(For the record, if I *don't* click deny & do click Allow, I still can't actually *log in via Google* on a locally built version of the app - it fails with error code 500 & I see `2020-04-14 00:10:11.810 16654-26381/com.habitrpg.android.habitica.debug D/OkHttp: {"success":false,"error":"InternalServerError","message":"An unexpected error occurred."}` in the logs, and an error dialog in the UI)

**Comment by phillipthelen** [comment]
That error is to be expected, since the habitica servers use different auth data than you have for your debug setup. But for fixing this bug, that should still work? You can also try configuring a local habitica install with the google auth data, but that is a bit more involved then.

**Comment by anitawoodruff** [comment]
Correct  - not being able to log in via Google auth was not a problem for actually fixing this bug - I was still able to reproduce it and fix it - see my PR above!
