### ISSUE TITLE
After canceling the new Task dialog, remain on appropriate tab

### ISSUE THREAD

**Issue by laurel-thomson** [HabitRPG/habitica-android#1292]
**Is your feature request related to a problem? Please describe.**
Whenever you click the "plus" button to add a new Habit, Daily, ToDo, or Reward, you are prompted to create a new task matching the type of the current tab.  However, after either creating the task or canceling, you return to the Tasks screen and the current tab is always "Habits".

**Describe the solution you'd like**
I believe it would be more intuitive if, when you returned to the Tasks screen, your current tab remained the same as it was before adding the new task.

**Describe alternatives you've considered**
N/A

**Additional context**
It appears that a similar functionality was implemented several years ago, but doesn't seem to be in effect currently: https://github.com/HabitRPG/habitica-android/pull/637

I would be interested in working on this issue.

**Comment by saraolson** [comment]
@laurel-thomson Thanks for offering to help us out with this! It's definitely a behavior we'd like to have, and you're welcome to start working on it. I'll mark it as in-progress.

**Comment by laurel-thomson** [comment]
Great! Thank you

**Comment by laurel-thomson** [comment]
Looks like I was wrong, this behavior is implemented when you add a new Task, but not when you cancel the new Task dialog.  I will work on switching to the correct tab after canceling the new Task dialog.

**Comment by laurel-thomson** [comment]
Closed by #1296
