### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by anitawoodruff** [HabitRPG/habitica-android#1298]
`./gradlew build` fails with `SDK location not found` - even though I set the ANDROID_SDK_ROOT environment variable.

**To Reproduce**
1. Follow steps in the README to set up the project (including forking it, renaming the .example files, and downloading google-services.json from a habitica debug project)
2. Execute `./gradlew build` - note it cannot find SDK location
3. Set `ANDROID_SDK_ROOT="/home/anita/Android/Sdk"` in my shell config (.zshrc) and source it
4. Execute `./gradlew build` - note it *still* cannot find SDK location

**Expected behavior**
It should build.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':Habitica:compileBetaReleaseKotlin'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/home/anita/repos/habitica-android/local.properties'.
```
**System details**
Ubuntu 19

**Additional Comments**
Setting `ANDROID_SDK_ROOT="/home/anita/Android/Sdk"` in `/etc/environment` for good measure didn't help either. I'm not sure how to set sdk.dir in local.properties so I haven't tried that yet.

**Comment by anitawoodruff** [comment]
Progress!

After closing the Android Studio config window, and opening the project in Android Studio, something has sorted itself out, because it can now locate the Sdk on command line. The error I now get is:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':Habitica:compileBetaReleaseKotlin'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;29.0.2 Android SDK Build-Tools 29.0.2
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
   
  Using Android SDK: /home/anita/Android/Sdk
```
Perhaps the Sdk wasn't fully installed before somehow, or Studio was holding a lock on it or something (I was at the end of setting up Studio when I encountered the above bug - though I had thought the sdk was fully installed, perhaps it wasn't).

Anyway, I shall now attempt to use Sdk Manager to accept licenses and hopefully that will resolve this new error.

**Comment by anitawoodruff** [comment]
More progress but still can't build!

This time with a compilation error:

`./gradlew build`

```
> Task :Habitica:compileAlphaDebugKotlin FAILED
e: /home/anita/repos/habitica-android/Habitica/src/main/java/com/habitrpg/android/habitica/ui/activities/LoginActivity.kt: (182, 44): Unresolved reference: APPLE_AUTH_CLIENT_ID

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Habitica:compileAlphaDebugKotlin'.
> Compilation error. See log for more details
```

**Comment by anitawoodruff** [comment]
(It also fails to build with `Unresolved reference: APPLE_AUTH_CLIENT_ID` in Android Studio)

**Comment by phillipthelen** [comment]
There was a variable missing in the habitica.properties example file. Can you check that file now and make sure you have all variables defined there in your properties file?

**Comment by anitawoodruff** [comment]
Yup, compiles fine now! :-) Thanks Phillip.
