### ISSUE TITLE
Skins problems

### ISSUE THREAD

**Issue by matheusvictor** [HabitRPG/habitica-android#1299]
**Describe the bug**
Skins already purchased by me appear for purchase again in the Avatar menu (for example: I already have the animal skins. You may have seen "Viccthor, the brazilian fox" a few times). 
In addition, some other skins that I already have (skeleton2 and others in the same set) do not appear among the options of choice for me to modify my Avatar.

**To Reproduce**
- Access the Avatar menu;
- Access the Skin menu from the Body section;
- Look for the sets of skins I already mentioned;
- Note that the Skins that the user already has appear for purchase again. Although it appears costing gems, the user can normally choose the Skins he already has. But, when re-filling the app, prices come up again.

**Expected behavior**
All skins should appear (both to choose and use them and to buy them). Purchased skins should not have their prices apparent every time the content on that page is reloaded.

**Screenshots**
![bugSkins](https://user-images.githubusercontent.com/12521391/79343904-6be5ae80-7f05-11ea-877c-9c9b284d5304.jpg)

**Smartphone (please complete the following information):**
- Device: Xiaomi Mi A2 Lite
- OS: Android One 9
- App Version: 2.5 (2399) - BETA
- Habitica Username: @matheusvictor AKA Viccthor

(_Translation with help with Google Translate_)

**Comment by phillipthelen** [comment]
Are you referring to the "buy all" button always showing? Or do they show as requiring purchase in another way too?

**Comment by matheusvictor** [comment]
@phillipthelen : I mean the "Buy all" button. 
But, also note that the other Skins I own do not appear among the options that I can use.

**Comment by matheusvictor** [comment]
@phillipthelen, I have updated the app, but the problem continues yet
