### ISSUE TITLE
Problems inviting users to Party

### ISSUE THREAD

**Issue by matheusvictor** [HabitRPG/habitica-android#1300]
**Describe the bug**
After entering the username of the player I want to invite to my Party and clicking on the "Send invitations" button, the application returns to the main page of the Party and nothing happens (no warning of error or success with sending). But recently, I found that, although no message appears, the invitation is not sent, as I tried twice to do this to invite a friend and I was unsuccessful.
I tried to perform the same action on the website and it worked normally.

**To Reproduce**
- Access the Party menu;
- Click on the three dots located in the top right menu;
- Enter the name of the user you want to invite. Note that no message will appear. So, ask this friend if received the invitation normally.

**Expected behavior**
A message (of failure or success) should appear to ensure that the submission was made or not.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A2 Lite
 - OS: Android One 9 
 - App Version: 2.5 (2399) - BETA
 - Habitica Username: @matheusvictor AKA Viccthor

**Comment by saraolson** [comment]
Will look into this and at least add some confirmation messaging if we cannot find the reason why invites didn't go through. The invites not working bug has been hard to replicate in the past.

**Comment by SabreCat** [comment]
Still seeing instances of this come in via user support email. Whenever a user reports this, I find they've logged various errors of this style:

```
http:
clientHost:35.224.154.129
contentType:application/json
json:
httpCode:400
isHandledError:true
level:warn
message:BadRequest: Invite must not be empty.
    at Function.getInvitationErr [as validateInvitations] (/usr/src/habitrpg/website/transpiled-babel/models/group.js:612:26)
    at handler (/usr/src/habitrpg/website/transpiled-babel/controllers/api-v3/groups.js:1244:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
method:POST
originalUrl:/api/v4/groups/a0b138d5-8e9b-4ae0-954d-98df2a0c22fc/invite
timestamp:2020-05-02T20:25:00.337Z
body:
inviter:Cashimir
headers:
```

**Comment by laserzt** [comment]
There is a chance that the user typed typed the name of the friend without a @ and then the invite failed. In that case, no fail message appears.

**Comment by SabreCat** [comment]
@laserzt the @ shouldn't be mandatory--the Habitica API will accept either format.

**Comment by saraolson** [comment]
we're trying something that should send out invited more reliably in the next update. will close this issue for now, feel free to reopen if its still a problem in 2.8+
