### ISSUE TITLE
Sync issues for push notifications and emails settings

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica-android#1301]
**Describe the bug**
There seem to be an issue with the settings for enabling emails and push notifications, as shown in the screenshots below while the site shows push notifications and emails enabled they're disabled according to the app.

**Screenshots**
<img width="535" alt="Schermata 2020-04-15 alle 12 09 25" src="https://user-images.githubusercontent.com/589911/79354843-38bf1180-7f3d-11ea-85e2-5f2533b96a7c.png">
![Screenshot_20200415-120915_Habitica](https://user-images.githubusercontent.com/589911/79354846-3957a800-7f3d-11ea-9085-1356b3c812c6.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung s7
 - OS: android 8
 - App Version: 2.5 (2399)
 - Habitica Username: paglias

**Comment by paglias** [comment]
Quick note, from some reports this could affect, but I haven't tested, not just the setting to unsubscribe from all push notifications but also for individual push notifications settings

**Comment by saraolson** [comment]
i just tested with email-- i checked on web to unsubscribe from email notifications then went to app, refreshed, and email notiications were still enabled

**Comment by saraolson** [comment]
this seems to be fixed with some push notif sync updates we made
