### ISSUE TITLE
Messages: swap order of messages so they match other chats

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1303]
Newest message is at the top of the screen at the moment, should be at bottom to match chats. also add a hard refresh button to message screen

**Comment by PatriciaHeimfarth** [comment]
I would like to work on this issue

**Comment by saraolson** [comment]
@PatriciaHeimfarth Marked as in progress for you! We're in a rush to push out the next milestone so we'll be reviewing PRs and offering feedback during the 3.1 milestone
