### ISSUE TITLE
Problems with images (hatching on pets confection)

### ISSUE THREAD

**Issue by matheusvictor** [HabitRPG/habitica-android#1305]
**Describe the bug**
Pets Confection images do not appear in the pop-up window when hatched.

**To Reproduce**
- Click on a Confection potion and then select an Egg to hatch;
- The image of the hatched Pet is not displayed.

**Expected behavior**
The Pet image obtained after using the Hatching Potion should be displayed to the user.

**Screenshots**
![bugConfecction](https://user-images.githubusercontent.com/12521391/79407904-7721f400-7f70-11ea-80f4-01cde84b267d.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A2 Lite
 - OS: Android One 9
 - App Version: 2.5 (2399) - BETA
 - Habitica Username: @matheusvictor AKA Viccthor

(_Translated with Google Translate_)

**Comment by saraolson** [comment]
thanks for pointing this out! the images just need to be uploaded to the server mobile pulls from. We'll get them up asap.

**Comment by matheusvictor** [comment]
@saraolson, nice! But now, I have all this pets. So, I can't test it again :/

**Comment by saraolson** [comment]
thats okay, we had a few staff test the hatching!

**Comment by matheusvictor** [comment]
@saraolson, great! Thanks!
