### ISSUE TITLE
Quests: No indication of finding a collection quest item

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1306]
There is no toast like web has of +1 Quest Item found, and there's no indication of pending items in the party UI

**Comment by Quazyrog** [comment]
Can I try to fix it? I haven't touched Habitica code before, but I study programming and I had some experience with Android application programming (in Kotlin) recently.

**Comment by saraolson** [comment]
@Quazyrog If you're still interested in this, we'd love to have you try to fix it! Thanks for your patience, things have been a little hectic recently! :)

**Comment by Quazyrog** [comment]
I'm still interested! I finished setting up server for testing (maybe it will be useful somehow to have it locally), so I can start playing with the code this week :D

**Comment by saraolson** [comment]
@Quazyrog perfect! ive marked the issue as in progress, let us know if you have any questions :)

**Comment by Quazyrog** [comment]
So it seems to be working now [here](https://github.com/Quazyrog/habitica-android/tree/collection-quest-indication). I'm waiting yet to see if changes in World Boss screen haven't broken anything — I asked about a way to start World Boss with local Habitica installation so I should be able to see it soon.

I guess I should rebase before making PR?

**Comment by phillipthelen** [comment]
When you create the PR in GitHub it should show you the changes that belong to the PR and if there is a merge conflict. As long as there is no conflict, it should be fine without rebasing.

**Comment by Quazyrog** [comment]
There was a merge conflict in translations file xD

Also I tested the world boss screen and it seems to be working after my changes as far as I can tell. This is also the cause of this delay — sorry.

**Comment by saraolson** [comment]
@Quazyrog thanks for the PR! we're in a rush to push out the 3.0 milestone so we'll be reviewing PRs and offering feedback during the 3.1 milestone
