### ISSUE TITLE
Settings: 'Task list display' shouldn't show in non-alpha builds

### ISSUE THREAD

**Issue by matheusvictor** [HabitRPG/habitica-android#1315]
**Describe the bug**
The view of the tasks aren't modify when I selected any of options

**To Reproduce**
Settings > Task list display

**Expected behavior**
The display of tasks should be modified according to the option selected.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A2 Lite
 - OS: Android One 10
 - App Version: 2.6.1 (2423) - BETA
 - Habitica Username: @matheusvictor AKA Viccthor

**Comment by saraolson** [comment]
This is actually an issue where this setting shouldn't even be visible. It's still experimental and should only be in alpha builds right now
