### ISSUE TITLE
To-Dos aren't filtered on startup

### ISSUE THREAD

**Issue by Gansgar** [HabitRPG/habitica-android#1319]
**Describe the bug**
When I open the app, I first see the to-do tab. Which is no problem, but the list contains even all check-off tasks. 

When I try to filter the list it says that the list is filtered with active only. I need to switch the filter to another one and switch back to the "actives only" filter to actually just see my active tasks.

**To Reproduce**
I haven't found a concise way yet to reproduce the issue. When I stop the app completly and open it again it works. I.e. when I try to force the behaviour. 
But this bug occurs to me every single time I opened the app the past few days. 

EDIt: It seems that when the app is in the background and isn't touched for a few hours (probably removed from RAM), reopening it produces the error. Restarting the app by closing it, fixes the error again.

**Expected behavior**
The To-Do list should be filtered with active tasks only.

**Smartphone (please complete the following information):**
 - Device: Samsung S10
 - OS: Android 10
 - App Version: 2.6.1
 - Habitica Username: gansga

**Comment by PatriciaHeimfarth** [comment]
I would like to work on that issue

**Comment by shane-tang** [comment]
👋 If it's okay I'll be picking this up for my first contribution. I took a quick look last night and I think I found the solution

**Comment by saraolson** [comment]
@shane-tang thanks for picking this up! we're working on our iOS release right now but we'll review this for android's next milestone.
