### ISSUE TITLE
Incorrect username shown in notification

### ISSUE THREAD

**Issue by junewerner** [HabitRPG/habitica-android#1327]
**Describe the bug**
I received a push notification addressed to the user hb-8gbu0qveydolwgjhi, who is a user in my party. My username is juniper_junebug, so it must have been mis-addressed. 

**To Reproduce**
I'm unsure. This occurred as a push notification seemingly without being prompted. The user has joined my party within the past 24 hours, so that could be related.  

**Expected behavior**
Push notifications should be addressed with the correct username/display name. 

**Screenshots**
![Screenshot_20200525-203959_2](https://user-images.githubusercontent.com/46098097/82852759-6a76b100-9ec9-11ea-85f4-058f4133a126.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 10 Build Number QQ2A.200501.001.B2
 - App Version: 2.6.2 (2419)
 - Habitica Username: juniper_junebug

**Additional context**
N/A

**Comment by Nakonana** [comment]
Could it be that you enabled push notifications for "Party Activity"...?

**Comment by saraolson** [comment]
the only way we've been able to recreate this is if you've logged into both accounts on the same device, then sometimes if an account you previously logged into gets a notification, it can come through even though you aren't logged into that account anymore.
