### ISSUE TITLE
Add ability to block user from their Profile

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1330]
- [x] The control should be added to the overflow menu on their Profile: 'Block'
- [x] When tapped, it should show a modal
- [x] When a user is blocked, the menu item should change to 'Un-block'. Tapping this will unblock immediately, no modal shown.
<img width="372" alt="Screen Shot 2020-06-01 at 9 38 34 AM" src="https://user-images.githubusercontent.com/12453119/83414549-ba82d580-a3eb-11ea-89f7-d973b3ec0a42.png">

**Comment by jinnyz** [comment]
Hi @saraolson, I'd like to pick up this issue! I know Java but I'd love to work on this to learn Kotlin. 

I'm thinking I can add the "block" option to the menu in red text. Let me know what you think.

**Comment by saraolson** [comment]
@jinnyz Sounds great! I'll change the tags for this to mark it as in progress.

**Comment by shanaqui** [comment]
@jinnyz Hi! Just checking in whether you're still working on this? If not, or if we don't hear from you within a week, I'll mark it as help wanted again for anyone to take it on, just to make sure it doesn't go stale! :) Let me know.

**Comment by jinnyz** [comment]
Hi! Thanks for checking in, I'm currently working on this and need some more time on it if that's ok! @shanaqui
