### ISSUE TITLE
Support for Android 4.4.x in Releases?

### ISSUE THREAD

**Issue by cathalgarvey** [HabitRPG/habitica-android#1332]
**Describe the bug**
Attempted upgrade to the latest version on Github Releases, failed on tablet device because of unsupported Android API.

**To Reproduce**
Attempt to install in Android 4.4.4 - I had to attempt installation through ADB to diagnose the error, it indicated "INSTALL_FAILED_OLDER_SDK".

**Expected behavior**
I doubt, to be honest, that Habitica relies on any newer APIs than 4.4.4 can provide? I'm assuming that it's just a build chain choice that's obsoleted old devices, and that changing this can restore compatibility.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy line tablet
 - OS: Android 4.4.4
 - App Version: 2.4.3 (attempted)
 - Habitica Username: <not relevant, belongs to child account>

**Additional context**
Habitica Android appears to be not available in the Play store from Ireland, and this is for my daughter's account on her personal tablet. The older Habitica version recently stopped connecting to the Habitica servers reliably, cause unknown, so I had hoped to upgrade and only report a bug if the problem affected the newer version of the app.

This has been a useful support for my daughter's ability to get stuff done, and it would be a real pity if she were unable to access Habitica anymore and the only cause was a choice of build chain. If it's more involved then that, then I guess I understand, but it's sad to see good devices being rendered obsolete by the march of API compatibility alone.

Thanks!

**Comment by saraolson** [comment]
‘4.4.4 was rendered obsolete because we do need to use tools and components from newer versions of Android, specifically 5.0 and above. When we depreciate a version, we take a lot of time to look at the impact it will have on our user base and the benefits it will offer both our team and our users. A lot has changed in Android since then that has allowed us to update the app more efficiently. As we’re a one developer team working on both the Android and iOS app, we don’t have the resources to support older versions of Android that have their own bugs and increasingly complex work-arounds to deliver a similar experience. So unfortunately, it is much more involved to restore older compatibility and not within our scope. Hope this explanation helps!

**Comment by shanaqui** [comment]
The cause of the app not connecting to the servers was that the old device required an old SSL intermediate certificate which had expired. The certificate was not needed for newer devices. One of our developers has got the certificates updated, and the app should connect again.

You may find you encounter this issue with other apps and sites as well over time, and you can read more about the causes here: https://www.ssl.com/faqs/i-noticed-that-the-addtrust-external-ca-root-is-expiring-soon-will-i-be-affected/ & https://www.xolphin.com/support/Rootcertificates/Phasing_out_Addtrust_External_CA_Root_certificate

**Comment by cathalgarvey** [comment]
It does help, thank you! I can appreciate the difficulty of maintaining for a moving target like Android. If the SSL issue is resolved and the older version continues to work, I'll stick with that on the kid's device.

Thanks for the information!

On 5 June 2020 16:11:22 GMT+01:00, Sara Olson <notifications@github.com> wrote:
>Android 4.4.4 was rendered obsolete because we do need to use tools and
>components from newer versions of Android, specifically 5.0 and above.
>When we depreciate a version, we take a lot of time to look at the
>impact it will have on our user base and the benefits it will offer
>both our team and our users. A lot has changed in Android since then
>that has allowed us to update the app more efficiently. As we’re a one
>developer team working on both the Android and iOS app, we don’t have
>the resources to support older versions of Android that have their own
>bugs and increasingly complex work-arounds to deliver a similar
>experience. So unfortunately, it is much more involved to restore older
>compatibility and not within our scope. Hope this explanation helps!>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/HabitRPG/habitica-android/issues/1332#issuecomment-639555586

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
