### ISSUE TITLE
Shop: Show newest gala gear at top of seasonal shop

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1334]
right now you have to scroll to the bottom of the seasonal show to see the gold purchasable gala gear that was just released. would be nice if this gear were at the top

**Comment by phillipthelen** [comment]
I think this should be a server side change. The app displays the items in the order they are returned from the API. I can try to write a workaround for handling this, but then I also have to do this on iOS and have to make sure the changes keep working. @SabreCat Would this be an easy change to make?

**Comment by SabreCat** [comment]
hmmm... there are a few ways we could do this, yeah. The incredibly tedious one would be to simply rearrange the items in the content file, hah. Or maybe use a script to rewrite it in reverse?

Maybe we create a ticket in the webserver repo to discuss/prioritize?
