### ISSUE TITLE
Pets: make hatching modal reflect current items

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1342]
We just allowed the ability to hatch from stable if you tap a pet and have the items for it. Along with updating updating the card views, we'd like to add various modals that reflect what you still need/already have to hatch a pet. So, there will be a few modals:

-New Pet: no potion, no egg
-New Pet: potion, no egg
-New Pet: no potion, egg

We may also want to experiment with a slight variation of the modals when the pet has been hatched and is raised into a mount once before, but needs to be hatched again. Will look into possible string edits to see if that makes sense.

**Comment by phillipthelen** [comment]
Do we just want to adjust the detail/description text? Or also have some visual changes to the icons?

What should the different text variants be?
