### ISSUE TITLE
Show transformation items in Items>Special and allow use from there

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1349]
When you buy a transformation item, you expect it to show in the items section (as it does on web). By showing it only in the skills section, it locks people out that may not have skills yet (low level, opted out of classes). 

Flow:
Tap item > bottom menu comes up with option 'Use' > show screen that displays party members
Basically copy the same flow as using the item from Skills, but by tapping the item instead.

I think showing the same item in two places is fine for now, as it is a bit more convenient to use from skills.

**Comment by Mike-Antonacci** [comment]
Is the desired behavior to keep the transformation items under Skills and additionally add them to Items, or to only have them in Items and eliminate finding them in Skills?

Should the item appear under Inventory > Items > Special (from the sidebar), or be pinned in Rewards, or both?

Does this apply to just the initial transformational item (seafoam, etc.) or also the counter-transformational item to undo the transformation?

**Comment by saraolson** [comment]
@Mike-Antonacci 
1. Yes, desired behavior is to still allow use from Skills, just adding the ability to also use from Items.

2. Yes, the location would be Inventory > Items > Special. Pinning to Rewards is for buying the item, and users are always allowed to pin any item they can currently buy to Rewards. If they were to pin Seafoam, then what should be shown in Rewards is the UI to buy the item. If they then bought Seafoam from Rewards, the item would be stocked in their inventory and they could use it whenever they want. Initial transformation items aren't instant use.

3. This only applies to the initial transformation item, as the counter-transformation items are instant-use and are never added to your inventory, similar to a health potion.

hope this helps clear things up.

**Comment by Mike-Antonacci** [comment]
then in that case, I'd love to work on this one.

**Comment by saraolson** [comment]
@Mike-Antonacci awesome, ill mark it as in progress for you!

**Comment by Mike-Antonacci** [comment]
Is there an Android equivalent of setting up a local Habitica install for testing purposes, like Blacksmiths do for the web? I don't want to make changes without being able to see what the changes are

**Comment by Mike-Antonacci** [comment]
As I started work on this one, I realized it's beyond my current knowledge and was more difficult than I expected. I'd like to stop working on it and allow someone else to do it instead.
