### ISSUE TITLE
community guideline is shown if you rotate device to landscape mode in party chat.

### ISSUE THREAD

**Issue by ikassim9** [HabitRPG/habitica-android#1351]
**Describe the bug**
A clear and concise description of what the bug is. If your issue is not related to a specific bug, please submit it as a suggestion through our form: https://forms.gle/Fa6oztkDsbzLqSvE9

**To Reproduce**

Go to party chat and rotate your device to landscape. Community guideline will be appear afterwards. This happens only in party mode chat. I tried the tavern chat and it doesn't happen. 

**Expected behavior**
I expected the chat to still be there but just in landscape mode.

**Screenshots**
![partychatbug](https://user-images.githubusercontent.com/56459089/89841972-f0ee7680-db39-11ea-8538-4e4022021534.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy s20
 - OS: Android 10
 - App Version: 2.8

**Additional context**

**Comment by PatriciaHeimfarth** [comment]
I would like to work on it
