### ISSUE TITLE
English Reward Names in German App

### ISSUE THREAD

**Issue by PatriciaHeimfarth** [HabitRPG/habitica-android#1360]
I use the app with German language setting.
When I get a special reward for doing a task ("you found xy") is the Toast in English.

**Reproducing**:
Having language settings in German. Checking some todos until you get a special item and a message about it. 

**Expected behavior**
The Toast with the message should be in German and not in English. Maybe the other languages are affected, too.

**Smartphone**
 - Device: Sony Xperia
 - OS: Android 9
 - App Version: 2.8

**Comment by Mike-Antonacci** [comment]
I'd like to work on this one.

A brief look in `...res/values-de/strings.xml` compared to `...res/values/strings.xml` shows that English has a string titled "first_drop_title" (`<string name="first_drop_title">You found new items!</string>`) whereas German does not. A brief look at a few other languages shows that they are also missing that string. My plan is to add that string to all other languages.

It also raises a bigger issue, that there are an inconsistent number of strings across languages. English has 1106 lines of code, German has 1023, Spanish has 862, and Korean has 816. I don't think I have the resources/time/knowledge to work on the bigger issue (I'm sure there's a way to do it automatically, but I don't know how to do and would have to do it manually), but hopefully someone else has the time/resources/knowledge to do it. but regardless of the bigger issue, working on the immediate bug you pointed out is something I'm interested in.

**Comment by phillipthelen** [comment]
Our translations are all managed in weblate which is hosted here: https://translate.Habitica.com please add all translations there, since changes to the files directly can cause issues

--  
Phillip Thelen
Sent with Airmail

**Comment by Mike-Antonacci** [comment]
@phillipthelen what's the process for adding strings to Weblate? I'm familiar with the translation side of things (I know what to do once a string has been added) but don't know how blacksmiths/fletchers add strings

**Comment by Mike-Antonacci** [comment]
@PatriciaHeimfarth @phillipthelen if I'm reading Weblate correctly, the string in question is translated but hasn't been approved by a reviewer. So, that's the reason why it appears in English (`...res/values/strings.xml`) but not in German (`...res/values-de/strings.xml`). I don't think there's anything to do from our end to fix this or speed the process up.
