### ISSUE TITLE
Chats aren't update

### ISSUE THREAD

**Issue by matheusvictor** [HabitRPG/habitica-android#1362]
**Describe the bug**
When accessing Party or Guild chats, new messages are not updated and displayed. I couldn't update either by dragging down or through the options

**To Reproduce**
- Access the Party or Guild
- Access chat
- Try to update messages

**Expected behavior**
The new messages should be displayed when accessing the Party or any Guild and updating the chat.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A2 Lite
 - OS: Android 10 One
 - App Version: 3.0 (2543) - BETA
 - Habitica Username: @matheusvictor AKA Viccthor

**Additional context**

**Comment by shanaqui** [comment]
Hi! This is already fixed in the beta build 2546, so you just need to update to that once the version is available! It's been pushed, so it just depends when the Google store allows you to update to it. :)
