### ISSUE TITLE
When you tap an equipped pet/mount, the action should say 'Unequip' rather than 'Equip'

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1372]
Tapping an equipped pet/mount to bring up possible actions will still say 'Equip' even though it is already equipped. Tapping that action will unequip the pet/mount, but the language should match the action.

**Comment by SlothHut** [comment]
Could I work on this?

**Comment by saraolson** [comment]
@SlothHut sure thing, i'll mark it as in progress for you

**Comment by shanaqui** [comment]
@SlothHut Hi! Just checking in whether you're still working on this. If not, or if we don't hear back from you within a week, I'll mark it as help wanted again so others know it's available to work on.

**Comment by alejandro-rios** [comment]
If it's possible I would like to work on this

**Comment by SlothHut** [comment]
Hi @shanaqui, im not working on this anymore

**Comment by saraolson** [comment]
@alejandro-rios if you're still interested, you're welcome to take this on now! i'll keep it it as in progress for you unless you say otherwise!

**Comment by alejandro-rios** [comment]
Fixed in this [PR](https://github.com/HabitRPG/habitica-android/pull/1538) 🎉 🎉 🎉

**Comment by saraolson** [comment]
@alejandro-rios thank you! we'll review it next time we're working on android :)
