### ISSUE TITLE
View should auto-update when you abort a quest

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1374]
Right now if you abort a Quest from the Quest details screen, nothing seems to happen. You're still on the details screen. The app should send you back to the main Party screen with the quest in the grayed out, not-participating state.

**Comment by JofielB** [comment]
Hello, I was wondering if I can take this issue

**Comment by saraolson** [comment]
@JofielB it's all yours! i'll mark it as in progress.

**Comment by JofielB** [comment]
Hello.
I don't know if I am not getting right the purpose of the issue but I think that the app already works like that. 
I create a quest -> Go to quest details -> Abort the quest -> I am redirected to the party screen
![issue flow](https://user-images.githubusercontent.com/32725639/101112107-d7b27f80-3599-11eb-961e-ef0eb7f8c478.png)

Device: LGE LM-X210
Android Version: 25
AppVersion: Version 3.1 (2663)

**Comment by saraolson** [comment]
@JofielB oh you know what, we actually just made a bunch of updates to the quest start flow in 3.1 so that it updates automatically and that may have inadvertently fixed this issue as well.

going to close this issue then! ty for testing it :D
