### ISSUE TITLE
Question completion text is black in dark mode

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1377]
On quest completion, the modal should show readable text with the end of quest story. Instead, the text is black on dark grey, as shown in this screenshot:

![Screenshot_20200929-170158](https://user-images.githubusercontent.com/8144640/94812504-bc3ac500-03ee-11eb-8df4-415228f10a4a.png)

In case this is quest dependent, the quest was Terror in the Taskwoods part II.

Device: Sony F5321
Android Version: 25
AppVersion: Version 3.0 (2561)
User ID: 33bb14bd-814d-40cb-98a4-7b76a752761c

**Comment by saraolson** [comment]
will fix this in 3.0.2

**Comment by saraolson** [comment]
rolling this out today, should be fixed but if its still reported in the update let us know

**Comment by Nakonana** [comment]
@saraolson I just noticed that the same issue occurs when sending a PM, i.e. click on a person's profile, go to the envelope icon to send a PM and you'll write in black on dark grey in the PM pop-up . This doesn't seem to be the case when accessing PMs via the inbox; there it's white text on dark background.

**Comment by saraolson** [comment]
@Nakonana thanks for pointing this out. I need to discuss with our dev whether we want to keep that flow at all, honestly. I would rather the actual messages screen open when you try to send a message so it is a consistent experience.
