### ISSUE TITLE
Users select a class and get the wrong class

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1378]
User report:
"I selected Rogue as my class. Double checked at confirmation and it has me a healer?🤷‍♀️ is this something you can help with."

Device: samsung Galaxy S9+
Android Version: 29
AppVersion: Version 3.0 (2561)
User ID: 9b81f46e-a898-49df-89c0-d3410c601f84
Level: 11
Class: healer
Is in Inn: false
Uses Costume: false
Custom Day Start: 0
Timezone Offset: 420

I resolved it for this user by giving them gems to change class. I've seen this happen to a few people before, though I haven't been able to replicate it, so I don't think it can be dismissed as user error. (Or rather, if it's user error, then it's a consistent problem, perhaps suggesting something is misleading people in the UI.)

**Comment by saraolson** [comment]
I don't think it can be user error, because the screen very obviously changes color and when you try to confirm, it gives you a modal 'Would you like to become a [Class]?' in plain language.. so if theres a problem, it has to be a bug i'm p sure.

**Comment by shanaqui** [comment]
The users are definitely convinced they checked and double-checked! I've
never been able to reproduce it either, and the ones who get back to me
after I give them gems to try again don't have the problem again.

**Comment by shanaqui** [comment]
A new instance of this: healer instead of mage.

Device: samsung Galaxy S8
Android Version: 24
AppVersion: Version 3.1 (2675)
User ID: 071dde8e-61a9-46b0-b133-01a11e29f31c
Level: 11
Class: healer
Is in Inn: false
Uses Costume: false
Custom Day Start: 0
Timezone Offset: -60
