### ISSUE TITLE
Tapping to complete a task will only open edit window

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1379]
User report: "everywhere I click on dailies in the new version I get only the option to alter the settings. I cannot mark them as complete no matter how many times I try."

Device: LGE LG G5
Android Version: 26
AppVersion: Version 3.0.1 (2582)
User ID: 338babdd-f7ce-43c4-a1cb-f5458850badd

One other user so far has mentioned the same problem on the same version.

**Comment by Kirska** [comment]
I have the same problem. I turned on screen touches and recorded a video to demonstrate. Super frustrating.

You can see I am tapping right on the check box and it doesn't work. Seems to only work when the tap registers far on the left side of the box.

https://streamable.com/6n1f1e

Device: Pixel 4XL
App version 3.0.1
![Screenshot_20201003-230124](https://user-images.githubusercontent.com/7443852/95006688-7cc9cf80-05cc-11eb-8e00-fa813730ebb8.png)

**Comment by phillipthelen** [comment]
I looked into this and found the issue. I started rollout of 3.0.1.1 that fixes this issue.
