### ISSUE TITLE
Sometimes cron doesn't immediately record to server

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1380]
Multiple times I've filled out RYA and started my day, then looked at some screen for testing purposes and put the app down, then 15min-1hr later opened the website and RYA will prompt me again. I looked at amplitude and a cron was never registered for the first time i tapped 'start my day' on android.

I feel like this is happening more often recently, but could just be coincidence.

Events that prompted this issue:
I just happened to take a screenshot of RYA today on the first cron for my main account at 10:57 AM (first time opening the app for the day). I then logged out of that account into a test account. 10-15min later, i opened the website on my main account and got another RYA. Instead of completing it, I closed the tab and checked amplitude. I then went back to android, logged out of the test account, force closed the app and logged back into my main account to get the RYA again. I completed it this time and it worked immediately as expected, confirming in amplitude.

**Comment by shanaqui** [comment]
Another user seems to be having this issue too, e.g. on 7th December.

> Device: motorola Moto e5 cruise
> Android Version: 26
> AppVersion: Version 3.1 (2675)
> User ID: 53d1bde8-be9a-430c-90c2-73b53888b4a4
> Level: 89
> Class: healer
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 5
> Timezone Offset: 480

**Comment by shanaqui** [comment]
Seems to still be happening... :(

> Device: samsung SM-G781U1
> Android Version: 30
> AppVersion: Version 3.2 (2832)
> User ID: 1ec92030-f22e-46b0-b6fb-dd899452f6ea
> Level: 4
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 2
> Timezone Offset: 480
> Details:
> 
>  
> Some days my sales updates more than once.  I finished all my tasks yesterday.  Then adding 8pm or did the what did you do yesterday window like I didn't do any of them.  And then this morning at 8am it did the same thing.  But I completed all mine yesterday.  And I dont know why it's trying to update multiple times like it's a new day.

**Comment by saraolson** [comment]
i actually just got this today as well

**Comment by shanaqui** [comment]
Still getting some reports of this, for sure! E.g.

> Device: OPPO CPH1903
> Android Version: 27
> AppVersion: Version 3.2.3 (2934)
> User ID: c211ab05-8ab4-4528-b968-4dc8ba100ae8
> Level: 80
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: -720
> Details:
> 
>  Past 3-4 days (maybe all week) I've had either delayed cron needing repeated attempts (both reload content/kill app) to get it to tick over, at about 7-9am so well past midnight.
> Not only that but i get back on the app and it's as if it's my first login, so not sure whether I get another cron or it reloads as if I never had one? That's been 2-3 of the days as well.
> This is on wifi and mobile data with other apps working fine so not a connection issue.

**Comment by Nakonana** [comment]
Just wondering about the part of the last report where they say they needed several attempts to even trigger cron/RYA... Could this part be a storage issue as described in #1461? Did/would uninstalling and reinstalling have an effect...? Or could they just check how much space their app takes up (and if their phone is low on space in general)?

**Comment by phillipthelen** [comment]
I made some changes that should fix this issue
