### ISSUE TITLE
Sending a message from Profile should open a full conversation screen

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1381]
When you send a message from someone's profile, it currently opens a modal with a textbox to type your message in. This should be changed so that tapping 'Send Message' from profile instead opens up a conversation screen like you would see in Messages.

This should mimic the same flow you'd see after entering a username to start a new conversation from Messages.

**Comment by Nakonana** [comment]
While this is being worked out, can we have an intermediate solution for this issue: https://github.com/HabitRPG/habitica-android/issues/1377#issuecomment-702834452 ? It's appears to be inevitable to use the pop-up when texting someone you've never texted before and it's really hard to type a message without seeing the text 😣

**Comment by saraolson** [comment]
@nakonana you can go to messages and tap 'new message' in the top corner then input the nw person's username to start a message that way and avoid the modal
