### ISSUE TITLE
Notification that you won a challenge is uninformative and dismisses full version on website

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1382]
A user reported in Report a Bug that they had a challenge win, but the notification appeared only via push notification on mobile and was not viewable on web. The notification via push notification was truncated and not expandable.

citrusella did a test and found that it looks like this: 
![image](https://user-images.githubusercontent.com/8144640/95317702-6f8f3800-088d-11eb-95c0-8506df714c54.png)

"Test notif" was the name of the challenge.

The proposed fix, as I understand it, is to ensure that the push notification does not dismiss the modal that can appear on the website, so someone who is unable to read all the information there can still view it on the website. Another potential fix would be to have a popup within the app with the same information the modal on web shows.

**Comment by saraolson** [comment]
@shanaqui im wondering if this user has seen the website version of the modal, bc the web modal doesn't really offer much else that i'm aware of:
<img width="346" alt="Screen Shot 2020-10-27 at 12 15 05 PM" src="https://user-images.githubusercontent.com/12453119/97330006-155f1280-184e-11eb-904b-754030bb3b22.png">

Is there something I'm missing? Any idea what information they wanted to see?

**Comment by saraolson** [comment]
**Proposed change:**
Notification will now say
"You won a Challenge!
[Challenge Name] selected you as the winner"

and there will be a modal visible in the app that will come up whenever you open the app after winning the Challenge. Tapping the notif shows you the modal, otherwise, seeing the modal dismisses the notif.
