### ISSUE TITLE
Save and delete buttons are invisible when editing a task

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1383]
User report: "Good day! I'm in a pickle. Whenever I open my Habits, Dailies, and To Do's the leftward arrow, delete button, and save button isn't seen. I can still press them, and they work but it's troublesome not to see them."

![Screenshot_20201007-123110](https://user-images.githubusercontent.com/8144640/95347803-38348180-08b5-11eb-9fb9-c7c6b53e0d5f.png)

Device: Google Pixel 3a XL
Android Version: 28
AppVersion: Version 3.0.1.1 (2593)

Multiple reports on version 3.0.1.1.

**Comment by matanrom** [comment]
Same here.
Notice it happens only when I'm using dark mode.

Device: OnePlus 5T.
Android version: 29.
Habitica 3.0.1.1.
Thanks.

**Comment by saraolson** [comment]
this was supposed to be fixed in that build.. hm....

**Comment by phillipthelen** [comment]
I just fixed this and am pushing 3.0.2
