### ISSUE TITLE
X icons to delete filters are barely visible against background in dark mode

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1384]
Reported by a user: "I can't seem to delete filters from my To-Do list. I've got a few from past challenges that I'd like to get rid of. Plus, the "X" (that presumably means to delete the adjacent tag when editing your tags) is really hard to see on the dark theme. It was purple before the recent update but is now a dark grey on a black background. Thanks!"

Device: Google Pixel 3a
Android Version: 30
AppVersion: Version 3.0.1.1 (2593)

**Comment by saraolson** [comment]
this was also supposed to be fixed, i made this issue and phillip changed them to be purple.. i think some git stuff went wrong on this update

**Comment by saraolson** [comment]
fixed in 3.0.2
