### ISSUE TITLE
Tags can no longer be deleted (button doesn't work)

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1385]
User report: "I just happened to notice that the X button was really hard to see at the same time I was unable to delete any filters (which was the main issue I was having). It's every tag, ones from challenges and ones I've made myself (including a tag I made just now to test), and all that happens when I tap the X next to a tag I want to delete is that the button briefly lights up."

Device: Google Pixel 3a
Android Version: 30
AppVersion: Version 3.0.1.1 (2593)

Replicated by me on version 3.0.2 (2602).

**Comment by saraolson** [comment]
yup still an issue on 3.0.2
