### ISSUE TITLE
A gem package cannot be selected for purchase

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1387]
User report:

> Device: Google Pixel 2 XL
> Android Version: 30
> AppVersion: Version 3.0.1.1 (2593)
> User ID: ed9c8952-8e90-4076-9387-23b40ac0c6d1
> Level: 146
> Class: healer
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: 240
> Details:
> 
>  I cannot purchase 4 gems with real money in the app. I can select all other options except for 4 gems for $0.99. 
> When I select purchase gems in the menu, it takes me to the purchase gem page. It takes a few seconds for the dollar amounts to appear. When I try to select $0.99, the button flashes, but nothing happens. Clearing my cache, rebooting, and reloading the app have not fixed the issue.

**Comment by saraolson** [comment]
can't reproduce

**Comment by shanaqui** [comment]
Yes, it happens for individual users periodically, rather than being a widespread bug.

**Comment by shanaqui** [comment]
I wonder if this report is related:

> Device: Google Pixel 2 Android Version: 30 AppVersion: Version 3.0.2 (2604) User ID: 21977bf6-22ab-495b-9eee-2f3d4e04464f Level: 40 Class: wizard Is in Inn: false Uses Costume: true Custom Day Start: 0 Timezone Offset: -60 Details:  
> 
> Purchase gems and gift gems is no longer working for me in the Android app (Google pixel 2). The gem amount options are slow to load initially, and then don't do anything when clicked (following load). Tried updating the app and the issue is persisting.

After I asked for some troubleshooting:

> I tried 'reload content', clearing the app's cache, and un/reinstalling, but it's behaving the same (initial screen load has no gem values populated, and then once populated - nothing happens when clicked).

**Comment by shanaqui** [comment]
I'm not sure if adding it to the milestone means we've got it figured out, so just in case, a new report:

> Device: Xiaomi Redmi Note 5
> Android Version: 28
> AppVersion: Version 3.0.2 (2604)
> User ID: de4c38a5-dd35-41e0-b496-57dadcb67d84
> Level: 78
> Class: wizard
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 3
> Timezone Offset: -180
> Details:
> 
> Hi,
> I can't buy 21 or 42 gems through the app. The buttons for 21 and 42 gems doesn't respond, meanwhile buttons to buy 4 and 84 are working fine.
> I cleared cache of the app and it didn't help.

**Comment by saraolson** [comment]
@shanaqui adding to milestone usually just means we're gonna take a shot at fixing it, most the time we aren't sure yet what's wrong. theres an idea that perhaps they had made a purchase in the past and the playstore is kinda 'stalled' on those but hasnt been tested

**Comment by shanaqui** [comment]
And another new report:

> I no longer can purchase 4 gems for 0.99€. all the other options (21 gems, etc) still work and lead to google play purchase window. When I click the 4 gems purchase button nothing happens.
> 
> Tried reinstalling, updating the app and reloading manually. Still there. Problem has been present for 1-2 weeks.
> 
> Device: Xiaomi Mi 9 SE
> Android Version: 29
> AppVersion: Version 3.0.2 (2604)
> User ID: a9b280f7-73d5-429f-a5c8-50cf268b95da
> Level: 69
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 5
> Timezone Offset: -60

**Comment by shanaqui** [comment]
Another new report:

> Device: samsung SM-A520F
> Android Version: 26
> AppVersion: Version 3.0.2 (2604)
> User ID: 02b00e5a-64a0-4af3-8bb7-a909f873c817
> Level: 119
> Class: rogue
> Is in Inn: true
> Uses Costume: true
> Custom Day Start: 1
> Timezone Offset: -60
> Details:
> 
>  Hello. Yesterday, I purchased 21 gems (with real money, not with gold). It worked. I've tried several times since then to purchase 4 more gems but instead of showing gpay button, it always says that I already own the item. If I wanted to purchase 21, 42 or 84 gems, it would work, the button is there. It's only the 4-gems options that doesn't work. Can you tell me what's wrong?

**Comment by shanaqui** [comment]
New report:

> Device: samsung SM-G986U1
> Android Version: 29
> AppVersion: Version 3.0.2 (2604)
> User ID: 540a05ee-2b2e-4d60-a1ba-0593ae990b2c
> Level: 17
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: 300 
> 
> When I try to purchase gems I get a message saying I've "already bought this before". I have previously purchased that amount of gems (21 for $5), and I still get the option to purchase them if i select one of the other tiers. It just won't let me purchase the same amount a second time. I cleared the cache for the app and it still won't work.

**Comment by saraolson** [comment]
@shanaqui i believe we fixed this in 3.1, if we get any more reports like this and its in 3.1 or later, please let us know!
