### ISSUE TITLE
Wrong "tab" (habits, dailies, to-dos, rewards) will be highlighted and unselectable

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1391]
User report: "When I navigated to another page and then back to the Tasks page, it will show me my list of Habits but the icon of the previous tab I have visited will be highlighted instead. If I tap on the highlighted icon I won't be able to visit the selected tab. I'll have to visit another tab then only I'll be able to visit that tab again.  Hope it helps! :)"

Device: vivo Vivo 1920
Android Version: 29
AppVersion: Version 3.0.2 (2605)
BETA
User ID: 4762b2a9-d1b5-4a85-925a-fdc8d18a3b0e
Level: 4
Class: warrior
Is in Inn: false
Uses Costume: false
Custom Day Start: 0
Timezone Offset: -480

This report includes a video if you search for it in the inbox. I haven't been able to replicate it, but I've seen other reports. Will copy those in if/when I find them again.

**Comment by shanaqui** [comment]
Similar report:

"Tasks goes to habits window but label stays where it was last. 
Go to tasks, dailies. Then go to party, and return to tasks. You will be in habits, but the bar in the bottom will show dailies."

> Device: samsung Galaxy S9+
> Android Version: 29
> AppVersion: Version 3.0.2 (2604)
> User ID: 08576d02-d94b-48aa-9ed3-16de73dd814b
> Level: 74
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 5
> Timezone Offset: -180

I can't replicate this.

**Comment by saraolson** [comment]
i can replicate this.
