### ISSUE TITLE
Not clear what is happening when the user you're trying to send a message to has turned off their PMs

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1396]
From SuperSaraA:

> Device: samsung SM-J337P
> Android Version: 28
> AppVersion: Version 3.0.2 (2604)
> User ID: dbf5390d-6a57-42ad-ae14-af8fd8e570ca
> Level: 91
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 4
> Timezone Offset: 420
> Details:
> 
> Hi app team,
> 
> So I got a PM from another user saying that they had gotten a notification that I wanted to PM them so they turned their PMs on and wrote to me. I responded that I do not remember asking to PM them. They then responded thanking me for the responce and saying it might be a bug or something. I tried to write back saying no problem but When I hit send it just keeps blinking and not sending the PM. I think that means they have their PMs off now but think it is odd the app didn't give me a pop up saying "this user has their PMs off" or anything.

**Comment by saraolson** [comment]
@shanaqui i just checked on web, and they don't alert the sender that someone has their PMs turned off either? it just says it for the user who has turned off PMs. also.. i was able to send a message to that person.. hm... lol

**Comment by saraolson** [comment]
i just tried this and it does tell me that i can't send messages bc they other person has them disabled. (lol at first i was testing with my staff account and remembered it has special permissions). did they say what the initial message was? ive never heard of ppl getting notifications to turn on their PMs

**Comment by saraolson** [comment]
i was able to replicate the blink if the account you're trying to message has been deleted. im gonna guess this was a random troll that said they were messaged first, messaged the person, confused them, then deleted their account.
