### ISSUE TITLE
Equipment gained via the Enchanted Armoire does not get auto-equipped

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1397]
If you select to auto-equip new equipment, it works on gear you buy from the market. However, if you purchase the Enchanted Armoire, it doesn't get auto-equipped. I reproduced this with a couple of items. I'm on version 3.0.2 (2606). The user's details:

> Device: vivo Vivo 1920
> Android Version: 29
> AppVersion: Version 3.0.2 (2605)
> BETA
> User ID: 4762b2a9-d1b5-4a85-925a-fdc8d18a3b0e
> Level: 4
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> Timezone Offset: -480

**Comment by phillipthelen** [comment]
This also does not happen on the website. This would be an issue that would need to be fixed on the server side, since the automatic equipping is handled there. But I'm not sure we want to change this behavior.
