### ISSUE TITLE
Chat randomly "jumps", but does not appear to update

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1399]
"why do my chats seem to move/shift randomly but nothing actually updates? Graphics bug?"
"It happens in all chats: tavern, guilds, party, etc. It looks like the messages collapse briefly, then re-expand. Normally, this would mean something updated, but nothing changes. No new messages ever appear unless I manually refresh."

Device: samsung Galaxy S10e
Android Version: 29
AppVersion: Version 3.0.2 (2604)
User ID: 3b0b13bc-059f-4dcb-a18b-0d245776e8a3
Level: 6
Class: warrior
Is in Inn: false
Uses Costume: true
Custom Day Start: 0
Timezone Offset: 240

I've observed this as well and it's been a sporadically reported issue in previous versions as well.

**Comment by saraolson** [comment]
when they say jumps, do they mean like, scrolls you to the newest message? or are they talking about that ui glitch while youre scrolled up that usually happens when loading more messages?

bc he scrolling to the newest message when you initially land on the chat is intended, if its that.

**Comment by shanaqui** [comment]
Sorry, I missed your reply! They were talking about the UI glitch you describe. Someone else reported it today:

> Whenever I am viewing a chat page (The Tavern or any guild, I haven't joined a party or gotten a PM so I can't check those screens) I will encounter an intermittent issue of the chat "jumping." Even on chats that are not receiving any new messages, the chat window will seem to reload and the messages will move up then down. It usually centers back to where I was in my scroll. 
> 
> I haven't figured out what triggers the jumps, it is not a consistent interval of time and there doesn't seem to be much of a pattern of what triggers it. It looks like the jumps do not happen if I have my finger on the screen. The only consistent trigger I've found is the jump occuring when I switch apps back to Habitica, but a reload at that moment would seem normal to me.
> 
> This bug is making it hard to use the chat features in the app as the "jumping" happens frequently (as frequent as every 5 seconds to as long as 30+ seconds betweens jumps).

Device: LGE LM-G820
Android Version: 29
AppVersion: Version 3.0.2 (2604)
User ID: 83cc3868-eafa-4ecb-93e7-2c0cdbe7286d
Level: 5
Class: warrior
Is in Inn: false
Uses Costume: false
Custom Day Start: 0
Timezone Offset: 360

**Comment by saraolson** [comment]
this ui glitch has proven really difficult to clean up in the past as the chat view is actually kinda complex to load. will mark as help wanted if anyone wants to devote the time to tryin to figure it out.

**Comment by beffymaroo** [comment]
Possible related report: 

"Device: OnePlus HD1900
Android Version: 30
AppVersion: Version 3.3.2 (3041)
User ID: 381b7299-d80c-412f-90de-085643165a1d
Level: 6
Class: rogue
Is in Inn: false
Uses Costume: false
Custom Day Start: 6
Timezone Offset: 180
Details:

 Hello there! Thanks for the awesome app! Just two little things I think could help with the experience.
1) While on chat with another user, the keyboard pop-up, you send the message, but after it has been sent and the keyboard is closed, me as user have to scroll down to see my message. It could be cool if the screen goes to the chat botton to keep the focus on it."
