### ISSUE TITLE
Closing the app when trying to create an To Do

### ISSUE THREAD

**Issue by matheusvictor** [HabitRPG/habitica-android#1400]
**Describe the crash**
After I made the last update, whenever I try to create a new To Do, the app fails and closes automatically. The same happens when I try to create a Habit, Daily or Rewards.

**To Reproduce**
Open the application and click on the '+' button to create any To Do, Habit, Daily or Reward.

**Smartphone (please complete the following information):**
 - Device: Xiaomi A2 Lite
 - OS: Android One 10
 - App Version: 3.1 (2612) - BETA
 - Habitica Username: @matheusvictor

**Comment by saraolson** [comment]
unable to reproduce on 2617, but i'm also on android 11. @matheusvictor can you let me know if this continues in later builds?

**Comment by matheusvictor** [comment]
@saraolson, I updated the app for the last version (3.1 - 2615) just now and it seems ok!
