### ISSUE TITLE
FAQ says you can change class under Menu>Choose Class

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1403]
Fairly frequent cause of user confusion! Under "How do I become a Warrior, Mage, Rogue, or Healer?" the FAQ answer states that if you've opted out, you can "choose later under Menu > Choose Class". That route doesn't exist; it's Menu>Settings>Enable Class System if you've opted out, or Menu>Settings>Change Class if you need to change class using gems.

At a minimum, this is an issue on Version 3.0.2 (2604) and Version 3.1 (2619), but it's been being reported for a while.

**Comment by saraolson** [comment]
hm i thought we fixed this but maybe we just did it on ios, ill take a look soon

**Comment by phillipthelen** [comment]
These come from the server. We changed/updated the iOS FAQ answers but not Android yet.

**Comment by saraolson** [comment]
just submitted the string change, will be fixed when its reviewed and deployed
