### ISSUE TITLE
To-do tab sometimes shows mix of completed and active tasks

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1407]
User report: "Hey, so I've noticed that sometimes when I open my to do tab it's cluttered with all my grayed out old to dos instead of just showing those yet to be done like normal and it seems to require jumping around tabs a few times to fix it, is this a fixable issue? Not sure if my settings are wrong or if it's an actual bug :/"

Clearing filters doesn't always help. There is no filter that should show both completed and active tasks at the same time, anyway.

The user's info:

Device: motorola Moto Z (2)
Android Version: 26
AppVersion: Version 3.0.2 (2604)
User ID: 48730559-7a4e-4c67-9d70-fac672352e87
Level: 19
Class: wizard
Is in Inn: false
Uses Costume: false
Custom Day Start: 1
Timezone Offset: 420

**Comment by Mike-Antonacci** [comment]
I think this is related to another open issue, where sometimes opening Habitica does not keep the default filter view for Dailies (for example, if the user wants only non-grey Dailies). I get both behaviors at the same time (both the other issue and this one), and usually when I leave Habitica open and then have a lot of other apps that I actively use (especially usage heavy ones such as Maps or a video call), so it may be a memory issue with my phone.

**Comment by shanaqui** [comment]
@Mike-Antonacci Have you got a link to that issue? I'm searching for it, but apparently not coming up with the right keywords!

**Comment by Mike-Antonacci** [comment]
@shanaqui and now I can't find it either, neither in open issues nor in closed issues. It's possible someone had mentioned it in a comment on another issue, and it's even more likely that I misremembered things. Since it doesn't look like there's an issue like I was describing, I'm not sure we would need to open a new one because it is contained in this issue right here that I'm commenting on. But I'll defer to you on that

**Comment by saraolson** [comment]
@Mike-Antonacci perhaps you were remembering this issue? https://github.com/HabitRPG/habitica-android/issues/1319

**Comment by Mike-Antonacci** [comment]
@saraolson YES. That's the one. @shanaqui

**Comment by shanaqui** [comment]
So do we think this is likely linked with similar behaviour in the dailies tab? 

User report: "Plusieurs fois par jour, je dois remettre mes Quotidiennes sur le filtre "Échéances" au lieu de "Tous" malgré l'option cochée dans les paramètres. Et j'ai la même chose avec mes tâches "À faire" qui les affichent toutes - actives et terminées - au lieu des actives seulement. J'ai déjà vidé mon cache plusieurs fois et synchroniser mais sans succès."

("Multiple times a day, I have to put my dailies back in the "Due" filter instead of "All" despite having the option checked in settings. I have the same thing with my To-Dos which shows them all -- active and completed -- instead of only the active ones. I have already emptied my cache several times and synced up without success.")

Sounds like it probably is, so adding this user's details:

Device: samsung SM-A530F
Android Version: 28
AppVersion: Version 3.0.2 (2604)
User ID: 24b2af06-6b29-4f7d-a59a-b8cd06bbc889
Level: 21
Class: healer
Is in Inn: false
Uses Costume: false
Custom Day Start: 5
Timezone Offset: -60

...just in case it isn't fixed by that previous issue! (But I think it sounds to me like this is a duplicate?)

**Comment by shanaqui** [comment]
Another report, just in case!

> Device: Xiaomi MI 6
> Android Version: 28
> AppVersion: Версия 3.0.2 (2604)
> User ID: 5caf2be2-e05a-4c23-9ef8-a6a7d5f36d56
> Level: 36
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 2
> Timezone Offset: -540
> Details:
> 
> Filters reset regularly, so I always see grey tasks and dailies and have to set filters again and again, every day. It's very inconvenient

**Comment by shanaqui** [comment]
MaybeSteveRogers has reported a problem where dailies are showing both due and not due at once. Still not sure if this is the same issue as the one with completed/uncompleted to-dos, so let me know if it needs breaking out into an issue of its own!

> Device: OnePlus OnePlus 6T
> Android Version: 29
> AppVersion: バージョン： 3.1 (2675)
> User ID: 767e5d92-0e13-4e30-acb1-d8bba62824fc
> Level: 88
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 7
> Timezone Offset: -60
> Details:
> 
> Dear Habitica team,
> 
> Overnight, my app has begun acting weirdly. When I opened it this morning (before CDS), it very briefly displayed no tasks at all before loading them as usual. This has never happened befhttps://assets.grammarly.com/emoji/v1/1f3af.svgore.
> 
> I have enabled the setting to "show only due" for Dailies. However, it now consistently shows "all". The setting is still enabled in Settings. Reloading content does not fix this; neither does closing and reopening the app. It keeps reverting to "all". 
> 
> As I said, this has literally happened overnight, I've not used the app in any way differently from what I normally do.

It seems likely this was caused by updating to 3.1, in this case, because they had just done that when the issue started.

**Comment by shanaqui** [comment]
Actually, I've seen a couple more now, so I'm going to open a new issue for this just in case, since it seems to be different.

**Comment by tveulemans** [comment]
I see that the issue is closed, but on Android I still have that behavior: every time I close and (later) reopen the app, the Due filter is reset. This happens regardless of the setting "Set Dailies default to 'due' tab".

**Comment by saraolson** [comment]
@tveulemans that sounds more like the issue shanaqui made rather than this one with todo's. i just tested and i was able to reproduce so will reopen that issue
