### ISSUE TITLE
deleting a chat message in Tavern/Guild causes app to close

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#1408]
As reported by the moderator Cantras:

"When I delete a post, app closes.  The post does get deleted, at least."

Device: motorola Moto x4
Android Version: 28
AppVersion: Version 3.1 (2622)
ALPHA
User ID: 28771972-ca6d-4c03-8261-e1734aa7d21d

**Comment by saraolson** [comment]
just did this just tried this with staff account and deleting my own post, both crashed app
