### ISSUE TITLE
After leaving Habitica inactive in the background and coming back, you cannot post in the chats

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1409]
Here's SuperSaraA's report:

"Not sure if you all know but on the Android app sometimes when I go to the tavern chat (and a few of the guilds) the page is black (I have dark mode on) and it shows only the agree to the community guidelines button. I try pressing on it but nothing happens. Trying to reload the page does nothing. I usually just close and reopen the app and try again but do not think this is how it is supposed to work. I can go back to the inn page and it is all there but pressing the tavern button gives me the look of the attached screenshot."

"It did not happen for a few days but just did it again. I had been on the tavern chat page and minimized my app to do something else. I turned off my screen and when I can back to Habitica after I opened my phone again a while later it did the black screen thing again. Attached is a new screenshot if that helps. I tried pressing the agree button but it did not work again so I tried typing in the chat box and pressing the post button to see if that would fix it but nothing happened so I hit my phone back button which took me to the last in Habitica place I had been other than the Tavern chat and I navigated back to see that the post I tried to make to get off the black screen page did not post. I think the pattern here is it often happens after I leave the Habitica app open but go to a different app on my phone and power off then go back. Not sure what it could be."

Here's the user's details:

Device: samsung SM-J337P
Android Version: 28
AppVersion: Version 3.0.2 (2604)
User ID: dbf5390d-6a57-42ad-ae14-af8fd8e570ca
Level: 93
Class: warrior
Is in Inn: false
Uses Costume: true
Custom Day Start: 4
Timezone Offset: 420

**Comment by saraolson** [comment]
hm i tried to replicate this doing the steps they listed but couldnt. this makes me think time might be an important factor rather than the steps themselves. ill try it again and leave it longer

**Comment by saraolson** [comment]
havent heard about this again and haven't been able to reproduce, so going to close
