### ISSUE TITLE
Tags appear to be using OR logic when multiple tags are selected

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1410]
User report: "Some of the to-do's are tagged with "Cooking" and "Challenges", but still show up when "Self-Talk" and "Challenges" are selected. Also, the to-do's tagged with "Self-Talk" and "Challenges" still show up when "Cooking" and "Challenges" are active."

Device: Xiaomi Mi A3
Android Version: 29
AppVersion: Version 3.0.2 (2604)
User ID: 6cff2a6f-d8a0-407d-b768-8913c082f5b8
Level: 4
Class: warrior
Is in Inn: false
Uses Costume: false
Custom Day Start: 0
Timezone Offset: -60

Verified in my version of the app (3.1, build no. 2628). The web version [uses AND logic](https://habitica.fandom.com/wiki/Tags#Using_Tags) and it would make sense to be consistent.

**Comment by saraolson** [comment]
my thoughts on this: 
i don't want to change the logic to match web now just for consistency when we may upset the workflows of a bunch of users that are used to the way android works. 

assuming this wasn't a sudden bug, android has used this logic for awhile and we haven't heard many complaints (neither me or phillip remember the last time we worked on filter logic). and/or logic is one of those things that works for some, doesn't work for others. android users have gotten used to the way it works, and we know that while some users are cross platform, the majority are not.

if this were a bug where suddenly the logic got switched, then yea i'm on board for switching it back. it doesnt seem thats the case yet, though correct me if im wrong, so would prefer leaving it the way the majority of our android users are used to.

**Comment by Alys** [comment]
I've documented this Android app behaviour difference in the wiki ([Tags > Multiple Tags](https://habitica.fandom.com/wiki/Tags#Multiple_Tags) and [Features Across Clients](https://habitica.fandom.com/wiki/Features_Across_Clients)).

@saraolson   Does the behaviour on iOS match the website or the Android app?

**Comment by saraolson** [comment]
@Alys iOS uses the and logic, so when filtering to 'morning' and 'health' it will only show tasks that are tagged with both.

**Comment by Alys** [comment]
@saraolson great, thanks! The wiki is correct for that.

**Comment by DavidMichelson2** [comment]
@saraolson With all due appreciation for your contributions, I cannot imagine what benefit an "OR" instead of "AND" would serve--or, at least, that anyone would prefer it given the option of only one or the other.

I would imagine most people use the filter as I do: to describe their current circumstances (e.g., in terms of location, time of day, personal mood) in order to identify the tasks best suited to them.

I am on Android, and if there is any way possible we can get the "AND" logic integrated, I would be so very grateful.

**Comment by saraolson** [comment]
@DavidMichelson2 thank you for taking the time to add your feedback to this issue! we will definitely keep your points in mind when considering whether to change android's filtering logic.

**Comment by paulmand3l** [comment]
@DavidMichelson2 fwiw I’ve never thought to use tags like that and vastly prefer the “or” filtering of the android app the “and” filtering of the web app. I use the tags like categories and like to be able to see multiple categories at once.

**Comment by EDLLT** [comment]
> @DavidMichelson2 thank you for taking the time to add your feedback to this issue! we will definitely keep your points in mind when considering whether to change android's filtering logic.

Why not simply add an option for both behaviors instead?
Then, the user could choose the behavior they want in the settings

**Comment by dcoffm** [comment]
I definitely support the option for choose AND/OR behavior. For my own use case I would prefer OR, but more importantly I need it to be consistent across platforms.
