### ISSUE TITLE
'Sell null' screen shows when you open all Mystery boxes

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1413]
You shouldn't be able to see the 'Sell' action when tapping the placeholder mystery box

<img width="169" alt="Screen Shot 2020-11-10 at 10 04 14 AM" src="https://user-images.githubusercontent.com/12453119/98691526-1dce4780-233c-11eb-99a7-8bbc32b40569.png">

**Comment by JofielB** [comment]
Hello,
How can I get a Mystery Box to try to reproduce this error?

**Comment by saraolson** [comment]
mystery items are delivered to subscribers, and this situation happens only after opening your last mystery box. if you pull to refresh or return to the screen when you dont have any mystery boxes available, then the screen will be blank and you can't tap anything to show the 'sell null' screen.

@phillipthelen will have to get back to you on if theres a way to do this in the code outside of buying a subscription
