### ISSUE TITLE
App allows you to equip a pet that you just raised to a mount if you do it quickly

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1416]
User report: "A pet can be equipped after it raised to a mount. If you do it quickly."

Device: Meizu Meizu M6s
Android Version: 24
AppVersion: Version 3.0.2 (2604)
User ID: e35a4724-0d52-48ad-9f34-75a34066b348
Level: 80
Class: healer
Is in Inn: false
Uses Costume: true
Custom Day Start: 0
Timezone Offset: -120

I haven't replicated this yet, just getting it reported so it's on the radar!

**Comment by saraolson** [comment]
mmm.. this is an issue ill ask phillip to look at to see if theres a quick safeguard but otherwise we'll probably ignore since its pretty niche and not a huge issue
