### ISSUE TITLE
Invite to guild button misaligned (in some languages?)

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1418]
The "Invite to Guild" button becomes misaligned, with the text cut off, in German.

![Screenshot_20201106-092031](https://user-images.githubusercontent.com/8144640/98960075-dc849600-24fb-11eb-8c72-127219f7c476.png)

User info: 

Device: Sony F5321
Android Version: 25
AppVersion: Version 3.0.2 (2604)
User ID: 33bb14bd-814d-40cb-98a4-7b76a752761c
Level: 79
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 16
Timezone Offset: -60

**Comment by Nakonana** [comment]
Here's another misaligned button (it's also misaligned in the German version)

![Quest invitations pending](https://trello-attachments.s3.amazonaws.com/5dfa77963d47893b8474869d/5e261bfa0c5bcf1647c15dbd/b07581c761f968335b8e9aa04b78e9c3/Screenshot_20201118-105945.png)

**Comment by saraolson** [comment]
@Nakonana if you haven't already, you can join the android beta on habitica's playstore page to get the latest version and test to see if this is still happening
