### ISSUE TITLE
Can't create challenges in Android app

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1419]
User report: "I can't add a challenge with the android app. After I hit save it just shows the Habitica logo screen, like a restart, and the challenge isn't created.
I added the challenge with the web app successfully. "

Device: samsung Galaxy S9+
Android Version: 29
AppVersion: Version 3.0.2 (2604)
User ID: 08576d02-d94b-48aa-9ed3-16de73dd814b
Level: 77
Class: warrior
Is in Inn: false
Uses Costume: true
Custom Day Start: 3
Timezone Offset: -120

Can't reproduce in the beta version 3.1 (2631) for other reasons I'll report in the testing Slack!

**Comment by saraolson** [comment]
this along with the visual bugs in dark mode and the 'location' field being unable to be set are all reported and planned to be fixed in 3.1
