### ISSUE TITLE
Hyperlinks are permitted in checklists, but do not work

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1420]
User report: "There are issues with hyperlinks in daily tasks. The hyperlinks work with the coding on the daily tasks themselves, but they don't work on the sub-tasks that have check marks. They show up as links on the sub-tasks, but when I try to click on them, they go to editing the task instead of going to the URL."

Device: motorola Moto Z (2)
Android Version: 26
AppVersion: Version 3.0.2 (2604)
User ID: af2bea91-622a-4f6f-8909-fb7a08b15035
Level: 135
Class: wizard
Is in Inn: false
Uses Costume: true
Custom Day Start: 0
Timezone Offset: 480

Confirmed in 3.1 (2634).

**Comment by shanaqui** [comment]
Will this fix the issues with markdown in checklists in general, @phillipthelen? I can open a new report if not, but I don't want to clutter. 😅

**Comment by saraolson** [comment]
@shanaqui i don't think so. though i believe mobile only offers limited markdown in tasks? if a specific issue has come up again, i'd just make an issue for it and we'll evaluate if its intended or not.
