### ISSUE TITLE
Markdown links don't format correctly in tasks during RYA

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1421]
User report: "There is an issue of  hyperlinks not showing when Habitica starts the next day, and asks if I have completed the tasks. In this case, instead of showing the links, it shows the words in the brackets."

Device: motorola Moto Z (2)
Android Version: 26
AppVersion: Version 3.0.2 (2604)
User ID: af2bea91-622a-4f6f-8909-fb7a08b15035
Level: 135
Class: wizard
Is in Inn: false
Uses Costume: true
Custom Day Start: 0
Timezone Offset: 480

I haven't yet reproduced this as I don't have any suitable tasks.

**Comment by CollinLBauer** [comment]
Hey, I'm a part of a college group studying Habitica for Software Engineering. I tried reproducing this issue out of curiosity, and the hyperlink seems correct. Has this already been fixed?

<img src="https://user-images.githubusercontent.com/34459526/107288139-f79a6f80-6a30-11eb-9051-0156aad4eb0a.png" width="500">

Device: Google Pixel
AppVersion: Version 3.1.2

My phone is running Android 10, which I believe is SDK 29.

**Comment by saraolson** [comment]
@CollinLBauer thanks for checking up on this! we might have fixed something in the normal task view that inadvertently fixed this issue as well. i'm going to close this unless it's reported again.
