### ISSUE TITLE
HTML displayed instead of it being formatted correctly in quest popups, achievement popups, maybe others

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1422]
EDIT by Alys 2020-12-28:

So far we've found this bug in:
- quest description popup
- quest completion popup
- achievements popup

---

From a user report:

![Screenshot_20201116-003520](https://user-images.githubusercontent.com/8144640/99419339-eb03f080-28f3-11eb-8b69-81384891a0f8.png)

Device: Google Pixel 3a
Android Version: 30
AppVersion: Version 3.0.2 (2604)
User ID: 91127bb7-9f1a-4380-8548-250de47f3262
Level: 121
Class: wizard
Is in Inn: true
Uses Costume: true
Custom Day Start: 0
Timezone Offset: 300

**Comment by saraolson** [comment]
i believe this might be fixed in 3.1 but may be wrong. i remember reporting another case of this to phillip and him fixing that one, but hard to remember if it was ios or android

**Comment by Alys** [comment]
Another report of this from @Loz_islove (33d77fee-926f-496d-aec6-0dfaf4c8d516) and Amplitude says they're on version 3.1.

_"The "Vice, Part 1" quest description has some HTMl tags sticking out as raw text."_

![image](https://user-images.githubusercontent.com/1495809/101266080-8d96ed00-3797-11eb-978c-6c4b894f4864.png)

**Comment by Nakonana** [comment]
Btw, this is not only happening for quests, but also other pop-ups for me

Device: Sony F5321
Android Version: 25
AppVersion: Version 3.1.1 (2691)
BETA
User ID: 33bb14bd-814d-40cb-98a4-7b76a752761c

![grafik](https://user-images.githubusercontent.com/68129995/103179761-80998500-488f-11eb-830c-7ad8c8ebacf2.png)

**Comment by Alys** [comment]
We've had another report of this for the quest description popup. I'm about to change the title to this: "HTML displayed instead of it being formatted correctly in quest popups, achievement popups, maybe others"

So far we've found it in:
- quest description popup
- quest completion popup
- achievements popup

I'll add that list to the top post so we can find it easily and update it as needed.
