### ISSUE TITLE
Viewing quest in inventory says "unable to buy that amount"

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1423]
If you go to Menu>Items and tap on a quest you own, you see a screen which has small text saying "You are unable to buy that amount".

![_20201118_102318](https://user-images.githubusercontent.com/8144640/99532870-e5aeb080-299c-11eb-81d7-4dd1cda54cae.JPG)

Device: Sony F5321
Android Version: 25
AppVersion: Version 3.0.2 (2604)
User ID: 33bb14bd-814d-40cb-98a4-7b76a752761c
Level: 80
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 16
Timezone Offset: -60 

Confirmed in 3.1 (2640), in light mode.

**Comment by NiculescuB** [comment]
Hello, I would like to pick up this issue.

I did a little bit of investigation, as it was easily reproducible and I think we could either remove the text from the dialog purchase layout, or make it hidden by default. Which ones would you think is better suited for your needs?

**Comment by saraolson** [comment]
@NiculescuB that line is supposed to show on subscriber gems in the market. if you put in a number that is too high for your monthly amount, its supposed to show that error. so there is a place its supposed to show, but it should never show in the context of a quest scroll. whatever method will work well without breaking the subscriber gem modal is okay!

heres an example of that line from a design mockup:
<img width="317" alt="Screen Shot 2020-12-01 at 3 35 48 PM" src="https://user-images.githubusercontent.com/12453119/100794145-2ec62200-33eb-11eb-9852-6505d0df0da0.png">
