### ISSUE TITLE
Colour states of checklists in Record Yesterday's Activity popup behave inconsistently

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1424]
User report:

> In the mobile app, when using "Record Yesterday's Activity", the internal checkboxes of some dailies have weird color behavior.
> If I check an internal checkbox, and then check the checkbox for the whole daily, the checkbox for the daily header turns black, while the internal checkbox that I just checked stays blue (or whatever color the daily is).
> On the other hand, if I check the main daily checkbox first, and then check an internal checkbox on that daily, the internal checkbox turns from blue to black. If I then uncheck that black internal checkbox, it stays black rather than turning blue again. This remains true even if I uncheck the main daily.
> It is a little confusing and it seems like it would be better if the colors were more consistent.
> I have attached screenshots showing the different odd internal checkbox states.

![Screenshot_20201115-111726](https://user-images.githubusercontent.com/8144640/99920717-37e52e00-2d1d-11eb-911d-94cfc9c2b287.png)
![Screenshot_20201116-174941](https://user-images.githubusercontent.com/8144640/99920718-387dc480-2d1d-11eb-9a90-aeed3fd2846e.png)

Device: motorola Moto z4
Android Version: 29
AppVersion: Version 3.0.2 (2604)
User ID: dea8a9e8-c084-438a-9a14-7fe96a73fd0a
Level: 125
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 9
Timezone Offset: 300

**Comment by saraolson** [comment]
hm we've fixed problems like this in the past, i wonder if it's still a thing on 3.1. i cant remember if we made any improvements there. 

The checklist checkboxes should always follow the color of the main task, so if the main task is checked they should always be dark, and if the main task isnt checked they should always have their color. It shouldn't matter which you act on first.

**Comment by saraolson** [comment]
can confirm happens in 3.1

**Comment by amohnacs15** [comment]
Hello I am new as a Fletcher and would like to take this one.

I've followed the [Guidance for Blacksmiths](https://habitica.fandom.com/wiki/Guidance_for_Blacksmiths#) and have the app running locally with a DEV configuration.  @saraolson I am wondering if there is any additional instruction to get to this specific state without waiting 24 hours.  Thank you 😊

**Comment by saraolson** [comment]
@amohnacs15 hey there! so this issue was actually half fixed in the last update (3.1) but the issue now is checklist checkmarks appear dark purple after you check the main task. ill message our mobile dev to see if he can give you some direction on how to force the RYA modal so you can test and hopefully figurenout whats going on! @phillipthelen

**Comment by phillipthelen** [comment]
The easiest way for testing things in the modal right now would be to when working on it NOT click on the button to dismiss it. That way it will continue to pop up on every app launch.
If you already dismissed it and want to continue work, the logic for displaying it is [here](https://github.com/HabitRPG/habitica-android/blob/develop/Habitica/src/main/java/com/habitrpg/android/habitica/ui/views/yesterdailies/YesterdailyDialog.kt#L173). Removing the filter. that checks for needsCron should do the trick. You then just have to be careful to not commit those changes to git.

**Comment by creaturebytes** [comment]
Had a related bug reported today: 

Device: Xiaomi Mi 9 Lite
Android Version: 29
AppVersion: Version 3.3.2 (3041)
User ID: 3796d76d-74fe-4f0d-be10-77740eec2b4b
Level: 5
Class: warrior
Is in Inn: false
Uses Costume: false
Custom Day Start: 0
Timezone Offset: -120
Details:

Hello. I wanted to report that there is a problem with the black pixels in the game. Noticable on hair colour, equipment and pets. They, instead of showing black, apear white.

**Comment by saraolson** [comment]
the issue with the background color is fixed, but the checkmarks still show inconsistent colors. they seem to be dark purple in some instances when they should be the gray 400
