### ISSUE TITLE
Rewards aren't properly in line with each other

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1425]
User-created rewards and system rewards aren't quite in line:

![image](https://user-images.githubusercontent.com/8144640/99956507-08b2d900-2d7e-11eb-847f-cd0a73ac6be4.png)

Device: OnePlus OnePlus 6
Android Version: 29
AppVersion: Version 3.1 (2651)
BETA
User ID: 874e648a-2df7-4312-a9e6-7217be462204
Level: 70
Class: warrior
Is in Inn: false
Uses Costume: true
Custom Day Start: 0
Timezone Offset: 0

I can't really tell a Google Pixel with 3.1 (2649), but I think I see it too.

**Comment by saraolson** [comment]
will talk with phillip whether its easier to add padding to the grid or extend the reward

**Comment by phillipthelen** [comment]
This one unfortunately isn't as easy to fix, as the spacing between the sides and the item cards depends on the devices width. So we'd need to figure out that spacing somehow, so that we can then use it for the custom rewards.

**Comment by saraolson** [comment]
@phillipthelen is there not a set amount of padding on each side of the screen for item grids that we could increase to match the custom reward?

**Comment by cdmunoz** [comment]
In the meantime, is it ok to work on this or at least take a look?

**Comment by saraolson** [comment]
@cdmunoz you're welcome to take a look! the desired fix would be to add extra padding to the edges of the item grid, and leave the task padding as is.
