### ISSUE TITLE
Achievement text wrapping badly

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1426]
Achievement text wraps oddly on some screens.

![_20201126_090643](https://user-images.githubusercontent.com/8144640/100445627-53e22a00-30a5-11eb-85f2-ba361dd49143.JPG)

Device: Sony F5321
Android Version: 25
AppVersion: Version 3.1 (2660)
BETA
User ID: 33bb14bd-814d-40cb-98a4-7b76a752761c
Level: 81
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 16
Timezone Offset: -60 

(It's fine in the beta on a Google Pixel 3. Screensize or text size issue?)

**Comment by saraolson** [comment]
im guessing we just have to turn on some setting to keep words whole instead of wrap to the exact character?

**Comment by JofielB** [comment]
Hello 
I am new in the world of open-source projects but I want to start making collaborations on this project and I have a doubt; if I want to tackle this issue should I just make a fork of the project make a branch, and work there? or there's some kind of guideline that I should follow to tackle an issue?

**Comment by saraolson** [comment]
hi @JofielB! if you scroll down on the main android repo, there's some basic guidelines on how to get started: https://github.com/HabitRPG/habitica-android

hopefully that helps! if you still have questions let us know
