### ISSUE TITLE
Streak aren't counted

### ISSUE THREAD

**Issue by matheusvictor** [HabitRPG/habitica-android#1428]
**Describe the bug**
When I positively or negatively click on a Habit, or mark a Daily as completed, the sequence counter is not counted. In fact, it is not even displayed in this current version of the app, although it works on the web version normally.

**To Reproduce**
Mark a Habit positively or negatively; or, if you prefer, mark a Daily as completed.

**Expected behavior**
A -1 or +1 marker should be added to the counter, indicating the number of times that Habit or Daily was performed.

**Screenshots**
![streak-arent-counted](https://user-images.githubusercontent.com/12521391/100555005-a2472280-3277-11eb-997b-2eac4078e486.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi A2 Lite
 - OS: Android One 10
 - App Version: 3.1 (2660) - BETA
 - Habitica Username: @matheusvictor AKA Viccthor

**Comment by shanaqui** [comment]
Hi! I haven't been able to replicate this -- is it still happening for you?

**Comment by saraolson** [comment]
also not able to replicate. the only thing i can think of would be awhile ago we were testing a control that would allow you to change your display to compact, and that would get rid of all icons in that notes line (alarm/reminder time, streak, due date, challenge megaphone), but we took that control out a month or 2 ago.. do any of those other controls appear for you in that line? reminder time may be easiest to check.

**Comment by matheusvictor** [comment]
@shanaqui, yeah... still happening. But, @saraolson is right: it was because of display configuration - that I didn't know about it. I fixed in the Settings. So, I'll close this issue, ok?!

Thanks! - and sorry for mistake
