### ISSUE TITLE
Habitica crashed while using using another app

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#143]
Habitica crashed while I was using using another app (the "Unfortunately, Habitica has stopped" dialog popped up over the other app). 

I took this logcat shortly after that happened. I've filtered for "E/" but I have the whole one too if you need it. https://habitica.slack.com/archives/android/p1449607204000424

**Comment by negue** [comment]
still happens?

**Comment by Alys** [comment]
It's happened once to me in the past week, and I've seen one other report of it relatively recently. Given that it's intermittent, I'm not sure there's much you can do. Do you want the exact date and time if it happens again or just close this?
