### ISSUE TITLE
Long username (with a tier?) blocks ability to like posts

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1432]
Device: samsung Galaxy S9+
Android Version: 29
AppVersion: Version 3.0.2 (2604)
User ID: 0a5260ba-a07e-4a09-8e86-462a64b2fcb0
Level: 309
Class: wizard
Is in Inn: false
Uses Costume: true
Custom Day Start: 21
Timezone Offset: 360

>  In line with the "can only see the first two digits of transformation item counts" issue due to an overlarge font size in phone settings, I've got another font related issue on Android mobile. A long username - perhaps only with contribution tier? - blocks me from upvoting messages.
> 
> Not really a bug per say, but since accessibility concerns were brought up with respect to the transformation count issue, I thought I'd send a screenshot yall's way.
> 
> My phone's font size is on tick #5 out of 8 and otherwise carries the standard font settings.
> 
> When I tap in the vicinity of where the +1 should be (aka where the contribution tier marker is), I'm redirected to the user's profile. The blank space between the username and tier marker does the same.

![SmartSelect_20201203-020212_Habitica](https://user-images.githubusercontent.com/8144640/101184351-87dec180-3648-11eb-9e2f-ea326176a81a.jpg)

**Comment by NiculescuB** [comment]
The commit under my name does not reference this issue, it was a bad case of dyslexia. Please ignore it for this issue.

I have updated the title of my commit to reference the correct issue, but I see the old reference still appears here, please ignore.

**Comment by saraolson** [comment]
looks like the icon for the tier isnt being placed correctly either. that should always be at the end of their display name

**Comment by phillipthelen** [comment]
Noticed this is (more or less) the same as #1364. Will close in favour of that.
