### ISSUE TITLE
Progress not always shown in quests

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1436]
A series of reports from a user:

> The quest info on the party screen doesn't update automatically. It doesn't show quest progress and pending "damage". (pulling down to sync fixes the issue, but it returns after a while)

> still investigating on the quest progress not showing. All I know is that it is intermittent, sometimes I see the progress and my pending found drops, but not sure what circumstances cause the difference in display. Also have yet to confirm whether the bug is present in non-collection quests (my party is small and we're still not done with the collection quest xD. Will report back when I have more info).

> I think the bug from the previous email is happening if I Cron via the app and then check the party. It doesn't seem to happen when running Cron on the website and then switching to the app. So some sort of failing sync in the app... 🤔
> 
> Or alternatively, it happens when any other member of the party crons and quest items are found but the quest progress display glitches instead of updating the progress info.
> 
> I'm also still seeing the quest info (without my pending drops) after the quest was completed.
> 
> It doesn't seem to happen with bosses that have HP, except for the first day of the quest starting.

Device: Sony F5321
Android Version: 25
AppVersion: Version 3.1 (2676)
BETA
User ID: 33bb14bd-814d-40cb-98a4-7b76a752761c
Level: 81
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 16
Timezone Offset: -60

**Comment by Nakonana** [comment]
Got to correct myself about bosses with HP. One of my party mates croned today (if relevant: a few hours after my cron) and I got this

![no pending damage](https://user-images.githubusercontent.com/68129995/101677062-57d65a80-3a5c-11eb-817d-fc2cb995db4e.png)

It's not as bad as with the collection quest where the overall quest progress would sometimes "reset"/appear to be zero, but the pending damage is still not showing just like the pending found items.

**Comment by saraolson** [comment]
@Nakonana so you have pending damage that isn't showing for you on bosses with hp?

collection quests we know have a lot of quirks to iron out, but bosses with hp should def be showing your pending damage 🤔

**Comment by Nakonana** [comment]
@saraolson yes, that's what's happening. Even if I don't have pending damage, it woud usually say "0.0 pending damage", if I'm not mistaken, but as you can see in the screenshot, the pending damage line is completely missing after any one of my party mates crons.
