### ISSUE TITLE
Submit feedback button isn't working

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1438]
A few users have reported this -- I can't reproduce it in the beta version I have, though.

Device: Xiaomi Mi A1
Android Version: 28
AppVersion: Version 3.1 (2675)
User ID: c19f3a91-c81d-43ac-9341-0d707efe0802
Level: 60
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 0
Timezone Offset: -330

Device: Sony F5321
Android Version: 25
AppVersion: Version 3.1 (2676)
BETA
User ID: 33bb14bd-814d-40cb-98a4-7b76a752761c
Level: 81
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 16
Timezone Offset: -60

**Comment by saraolson** [comment]
closing bc repeat
