### ISSUE TITLE
PM push notification doesn't open app

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1439]
User report:  "when I get a PM, tapping the push notification doesnt open the app, and if im already in the app, it takes me to the tasks page instead of the message page."

Device: OnePlus KB2007
Android Version: 30
AppVersion: Version 3.1 (2675)
User ID: 48f540c1-336e-4fb8-88e1-9d7204c3a396
Level: 4
Class: warrior
Is in Inn: false
Uses Costume: false
Custom Day Start: 0
Timezone Offset: 480

**Comment by saraolson** [comment]
This may just need an update to the notif since we improved in-app linking?
