### ISSUE TITLE
Leaving party always asks if you want to leave challenges even if none exist

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1442]
Leaving a party will show a modal asking if you want to keep or leave the challenge tasks. This will show even if you aren't in any challenges, and even if the party doesnt have any challenges. Got this on a newly formed party.

**Comment by Mike-Antonacci** [comment]
this also happens on leaving a guild, even if you haven't joined any guild challenges, you still get the same modal

**Comment by chh-2** [comment]
Hello, is this issue still available? If so I would like to work on it.

**Comment by ilally93** [comment]
Hello, 
I am working with @chh-2 and just wanted to clarify (if it was alright for us to take this issue) if the purpose of the leave challenge option is meant to remove the challenge tasks or only remove the overarching challenge.
Thank you!

**Comment by saraolson** [comment]
@chh-2 @ilally93 hey there, thanks for your patience as we catch up on answering questions!

There's a few different problems going on with this.

1. This modal shouldn't show if you aren't a member in any of the party/guild challenges
2. This modal definitely shouldn't show if the party/guild doesn't even have any challenges

This modal is a little out dated, so I'll provide an updated design. The purpose of the modal is to let people choose from a few options:
1. Stay as a participant in the Challenge. This keeps the challenge in your challenge list and all tasks are still active like normal. This button should read 'Keep Challenge' 
2. Leave the Challenge they are participating in. If they choose to leave, we should automatically remove all tasks from their task list. The leave button should thus read 'Leave & Delete Tasks'
3. Cancel, which will leave them as a member in the Party or Guild 

You can see how this should look below, with some changes to the strings:
<img width="664" alt="Screen Shot 2021-02-25 at 12 26 27 PM" src="https://user-images.githubusercontent.com/12453119/109192004-c033fe80-7764-11eb-9725-ec2534911ebf.png">

Hope this helps!

**Comment by bhamrickatmills** [comment]
@ilally93 @chh-2 We've been looking at this issue. Would you like to collaborate?

**Comment by ilally93** [comment]
@bhamrickatmills We'd be happy to collaborate! If you want to get in contact, my email is lallyir@g.cofc.edu.

**Comment by benkelaar** [comment]
@saraolson Just wondering, when a challenge runs out the user is given the option to keep the tasks when leaving the challenge, shouldn't the same option be given here as well? (So leave the challenge, but keep the tasks?)

**Comment by saraolson** [comment]
@benkelaar i originally opted to omit that button from this for the sake of not overwhelming with options (we dont have any modals with 3 buttons + close right now), with the idea that if they keep the challenge, they can then leave from the challenge page and then get that specific option. I wanted to try it with this simpler modal first and see if anyone actually had an issue with that option being missing in this context.

If we wanted to add in another red text button for 'Leave Challenge & Keep Tasks' i wouldn't be completely against it, but that was my thinking for not having it.
