### ISSUE TITLE
Health and experience bars not appearing for Android 5.0 users

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1443]
![Screenshot_2020-12-04-11-59-02-633](https://user-images.githubusercontent.com/8144640/101924723-e8ca4480-3bc8-11eb-82f9-c1954e186757.jpeg)

Device: LENOVO Lenovo K50a40 
Android Version: 21 
AppVersion: Version 3.0.2 (2604) 
User ID: a3d9b5f1-a882-47c2-8c34-d86f0e6c962d 
Level: 1 
Class: warrior 
Is in Inn: false 
Uses Costume: false 
Custom Day Start: 0 
Timezone Offset: -330

Issue was unaffected by reloading content, clearing the app's cache or updating the app to the latest version.

**Comment by phillipthelen** [comment]
This looks to be a bug with android 5.0. Since only a very small number of our users still have that version it's not super high in priority right now.
