### ISSUE TITLE
Can't edit party/guild description text due to scrolling

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1444]
User report: "Hi, I'm having difficulty with editing my party page. When I go to type it scrolls down where I can't see what I'm typing. I can't select certain text to copy/cut. When I try to highlight the certain area, it doesn't go up any further than what's currently highlighted. I've tried clearing cache/data. I've tried restarting my phone. I don't show any updates for the app. Is there something else I can do to fix this issue? Thank you in advance. "

> Device: samsung SM-J327V
> Android Version: 27
> AppVersion: Version 3.1 (2675)
> User ID: faa3008e-0743-4f60-884b-aaa4ed8ce34a
> Level: 135
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 9
> Timezone Offset: 360

Also happened on the beta version I have installed. I replicated it by generating 5000 words of lorem ipsum text, pasting that in, and then it immediately triggered the issue.

**Comment by shanaqui** [comment]
Also reported by:

> Device: samsung Galaxy S10e
> Android Version: 29
> AppVersion: Version 3.1 (2675)
> User ID: 4da4852b-548c-4ce8-a054-83e2c7a03e0e
> Level: 187
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: 480

They created a screen recording of it: https://photos.app.goo.gl/Dr6bUCpT4RPMjVNZ7

**Comment by shanaqui** [comment]
Also affecting this user:

> Device: samsung Galaxy S8
> Android Version: 28
> AppVersion: Versione 3.1 (2675)
> User ID: ca543acf-fc03-480d-a0c4-27a12670f5d0
> Level: 103
> Class: healer
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: -60

**Comment by shanaqui** [comment]
And this user:

> Device: OnePlus OnePlus 6T
> Android Version: 29
> AppVersion: バージョン： 3.1.1 (2690)
> User ID: 767e5d92-0e13-4e30-acb1-d8bba62824fc
> Level: 90
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 7
> Timezone Offset: -60

**Comment by saraolson** [comment]
text box issues strike again.. will give this a look in 3.2 to see if we can improve it a bit
