### ISSUE TITLE
News tab won't load

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1446]
"Details: When I click on the News tab or the "New Bailey Update" in my notifications I get a white Habitica logo in a purple background that just keeps fading in and out instead of showing me the news."

Screenshot:

![Screenshot_2020-11-10-11-06-11](https://user-images.githubusercontent.com/8144640/102100141-0265c900-3e21-11eb-91be-e02bd41de803.png)

No parental controls or anything, persists after clearing cache, persists after updating to 3.1. I haven't been able to replicate.

Device: motorola XT1526
Android Version: 22
AppVersion: Version 3.0.2 (2604)
User ID: 75a3de27-866a-4dbd-a71b-ea80c8e93ef6
Level: 28
Class: wizard
Is in Inn: false
Uses Costume: true
Custom Day Start: 0
Timezone Offset: 300

**Comment by phillipthelen** [comment]
I'm going to close this since it's most likely a obscure bug with the web view and we will make that obsolete soon with the usage of the news API.
