### ISSUE TITLE
Inconsistent styling of challenge tasks

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1448]
![Screenshot_20201209-060750](https://user-images.githubusercontent.com/8144640/102225479-2d165700-3edf-11eb-8b24-7187ddadbe8c.png)

Device: Sony F5321
Android Version: 25
AppVersion: Version 3.1 (2676)
BETA
User ID: 33bb14bd-814d-40cb-98a4-7b76a752761c
Level: 81
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 16
Timezone Offset: -60

**Comment by saraolson** [comment]
These should probably be updated to follow our latest redesign that has tasks in floating 'cards' rather than edge to edge as well.
