### ISSUE TITLE
On avatar death, stats are not refreshed automatically

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1451]
Reported by a user, reproduced by me.

- Tap a negative task until you run out of health
- Tap to refill your health in the modal that pops up when you die
- Expectation: your health goes back to full, level drops, etc
- What happens: nothing; you need to pull down to refresh before your health refills etc

**Comment by Mike-Antonacci** [comment]
I'd like to take this one, and it would be helpful if someone could point me to where in the code that tasks are scored or the user is updated or anything of that sort. I know where it's found on the web version but not for Android. I tested this on the web also and it behaves as expected,health goes back to full and level drops, so it's not a web issue that's spilling over to Android
