### ISSUE TITLE
Double cancel invitation buttons appearing

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1452]
See screenshot:

![Screenshot_20201223-114111_Habitica](https://user-images.githubusercontent.com/8144640/103370345-7ad8b500-4ac4-11eb-98da-9919f5853d4f.jpg)

Device: samsung Galaxy S7
Android Version: 26
AppVersion: Version 3.1.1 (2690)
User ID: 624e48a3-cbea-4bbe-ae44-ca9183f49626
Level: 35
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 5
Timezone Offset: 360

**Comment by varunvjha** [comment]
Can I work on this issue?

**Comment by shanaqui** [comment]
Go ahead! :) I've marked it as in progress for you.
