### ISSUE TITLE
Stats widget is blank with empty bars

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1459]
User report: "The widget for Habitica stats does not display any information on my phone. The other widgets seem to work just fine."

Device: Google Pixel 2
Android Version: 30
AppVersion: Version 3.1.1 (2690)
User ID: 2e8f8755-ceb8-4bdc-ad47-d2cb8fc4b329
Level: 2
Class: warrior
Is in Inn: false
Uses Costume: false
Custom Day Start: 0
Timezone Offset: 360

Replicated by me 3.1.1 (2692) as well.

**Comment by shanaqui** [comment]
User reports: "FYI that it does seem to be working now. I don't know if it updated or if it took a day to sync since I was new? Just wanted you to know."

I didn't leave the widget, so the same does not apply to me. It's still blank if I re-add it.

**Comment by saraolson** [comment]
our android widgets in general seem to have a hard time fetching data, so this doesnt surprise me.

**Comment by shanaqui** [comment]
Nope! If I add it, it stays blank no matter what I do re-opening the app, refreshing, etc. However, I think I have seen the same behaviour as the user I mentioned above, where it did spontaneously start working after a day or two.

**Comment by shanaqui** [comment]
Here's a new user with this issue:

> Device: samsung SM-G998B
> Android Version: 30
> AppVersion: Version 3.3 (2976)
> BETA
> User ID: 817b2e53-8bbd-4be2-806b-970ead2854c1
> Level: 117
> Class: wizard
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 8
> Timezone Offset: -60 

It's also an issue for me at the moment as well, and this time having it active for a few days has not helped at all. It's still just blank, with no functionality.
