### ISSUE TITLE
App suddenly taking up a lot of space

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1461]
User report:

> Device: Sony F5321
> Android Version: 25
> AppVersion: Версия 3.1.1 (2691)
> BETA
> User ID: 33bb14bd-814d-40cb-98a4-7b76a752761c
> Level: 83
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 16
> Timezone Offset: -60
> Details:
> 
> Hello, my app is accumulating lots of data recently. I've checked with someone in the Habitica Help Guild and their app and the saved data on the device take up less than 300mb and that's what used to be the case for me too, but when I asked that question the app had saved more than 1.6GB on my phone (not talking about cache). I uninstalled and got back to the usual <300mb, but it's only been about two weeks since then and it's now back at nearly 500mb. This causes the app to lag quite a bit so I have to force close it every time to even start it and cron doesn't run at all, I have to use the website for that. It doesn't look like a phone issue as Habitica seems to be the only app with that problem.

**Comment by shanaqui** [comment]
The user has provided a screenshot, not showing the bug actually happening, but an amount of storage they consider to be large compared to other apps. I don't know if this is correct or not.

![Screenshot_20210115-174016](https://user-images.githubusercontent.com/8144640/104813823-80900380-5803-11eb-8770-17cf64992fcf.png)

It's a lot compared to my app:

App size: 36.09 MB
User data: 68.44 MB
Cache: 10.70 MB
TOTAL: 115 MB

**Comment by phillipthelen** [comment]
That is quite a lot of data, where i'm not sure where it comes from. It might be from being in a chat where a lot of images are linked, that are then downloaded and cached? But all of that would not affect the way the app runs. So that part of the issue description doesn't fit.

**Comment by Nakonana** [comment]
@phillipthelen but images aren't visible in Android except in guild descriptions? Or are they downloaded anyways? I'm in no art related guilds. There are linked images in the Bakin' Bakin' All Day Long guild.
If you have an idea how I could test where the data comes from, I could uninstall the app and give it a go. If it's linked images, the Pixel Power guild and Pixels in Progress guild could work for testing. They often link to images (but probably not the biggest files) and there's a decent number of images in the description of Pixel Power.

I could imagine that it's the amount of data that slows down my phone because I'm running low on internal storage space (only ~25% storage left) and that's what's leading to the performance issue.

Another question: could notifications be to blame for this? I have a lot of reminders and I let PM notifications and mentions sit in my top menu for quite a while (read: several days and maybe even over a week or two...)

**Comment by Nakonana** [comment]
@phillipthelen

Ok, I went ahead and just tried to go through what I listed above. Here are the details:

1. Freshly installed after uninstall:34.14 MB 

2. Scrolled through tasks (34.17 MB). 

3. Went to settings and changed to Dark Theme. (no changes) 

4. Menu > guilds. Had to refresh for the list to load. Scrolled to bottom (36.14 MB) 

5. Opened The Otaku and Gamers Dōjō (37.18), ADHDers Guild (43.20), Wizard of the Wiki (44.17, after clicking the Trello link 45.16), Report a Bug (48.22), Aspiring Comrades (51.21), Commonwealth of i18n (55.18), Deleted (& after accidentally going back to my tasks 😅: 58.22 - also, I think I just had joined this guild before), and the private guild (62.20), the Tavern (67.23). **I'm seeing a potential source for the data issue...** I visit a lot of different guilds to just invite people to them 😅. 

6. Visited my party (71.22). 

7. Sent 3 @ mentions and one PM from my test account to receive push-notifications (71.18 MB 🤔). 

8. Opened notifications menu in the app to visit the guild from step 7 to see the posts and Liked 2 posts (no changes in MB as there are hardly any posts or anything else in that guild). 

8. Made 8 posts in that guild, including 2 pre-written messages and copied one before posting (back to 71.20 MB). Copied 2 of the test account's messages (no change). 

9.Tried deleting my posts and this time it worked (72.21). 

10. Tried to report a message without going through the whole process 😅 (no changes). 

11. Took one screenshot (still nothing). 

12. Checked 2 profiles that are very similar to the ones before (73.27). 

13. Went to skills menu used the previous skill (74.23). 

14. Created a To Do and checked it off. Also checked a Habit and a checklist item of a Daily. (still same MB) 

15. Changed language to English (77.23 MB) and went to menu > guilds to see if the MB will increase even more if I load other parts of the app, but they didn't. Back to Russian (82.24) .Then German - for the fun of it xD (83.23).Then Russian again (86.23). **This is somewhat surprising...** How come that the app saves data for Russian every time although it should already be on my phone...? Also, why is there more Russian data than German? XD (ok, it is a wordy language, but unlike German, it's not even fully translated... o.o).

16. The **MB magically increased** to 87.22 without me doing anything while I was writing down my observations regarding step 15 o.o. There are no new push-notifications and I didn't even touch the app o.o (Checked the app: There are new messages in guilds, though, that weren't there before. Went back here and now I'm seeing that the data increased again without me doing anything: 89.21 MB. The guild chat notifications count did not change this time! Were there new posts but in the same guilds as before...? Idk... 🤔 ) 

17. Tried to send a bug report (still at 89.21 MB). 

18. **Another magical MB increase** while I was writing here...: 91.21 MB 😅. The notifications count did not increase and it did not turn purple after I checked the list which made it turn grey (i.e. there are no new posts in my guilds). 

Hope this helps. If you want to me to do further testing, let me know. 

I conclude this post with a total of 91.22 MB .\_.

**Comment by phillipthelen** [comment]
First step: Added a check on app launch that compacts the realm database in case it's too big and mostly empty (this is due to how realm is implemented). Will also see how I can prevent the app from caching too much guild/user data.
