### ISSUE TITLE
Coins and items don't update when selling things

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1466]
Based on user report. Sounds a bit like #1404, like it's just not fetching the new data.

Device: samsung SM-G570M 
Android Version: 26 
AppVersion: Versão 3.1.1 (2690) 
User ID: 028c6e54-e1f2-457a-a9b7-54563d778628 
Level: 130 
Class: rogue 
Is in Inn: false 
Uses Costume: true 
Custom Day Start: 0 
Timezone Offset: 180

**Comment by saraolson** [comment]
Seems like we just need to force an auto sync when you sell items
