### ISSUE TITLE
Theme colors sometimes changing app bar color and creating text contrast issues

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1467]
When you use the theme colours, the contrast isn't always good.

User examples: 

![Screenshot_2021-01-17-18-34-17](https://user-images.githubusercontent.com/8144640/104911084-3719f280-5982-11eb-952f-16fba1f1db27.png)
![Screenshot_2021-01-17-18-34-27](https://user-images.githubusercontent.com/8144640/104911085-3719f280-5982-11eb-89db-2375d1a22c6a.png)
![Screenshot_2021-01-17-18-33-49](https://user-images.githubusercontent.com/8144640/104911080-36815c00-5982-11eb-8c10-01be140cc4ba.png)
![Screenshot_2021-01-17-18-33-58](https://user-images.githubusercontent.com/8144640/104911082-3719f280-5982-11eb-90e1-9f5701265b23.png)

Reported by a user on Android version 22, Habitica version 3.1.1 (2690).

**Comment by saraolson** [comment]
i actually have no idea how they achieved this? In dark mode, that top bar should never be colored to your theme and i can't replicate. Similar with light mode, the bar is always white for me. I can never get a purple or red bar

@shanaqui did they give any instruction on how this happens or how often?

**Comment by phillipthelen** [comment]
This looks like an issue with Android version 22. I believe some of the things we use for theming were only supported/working this way with v23. I'll try to find a workaround.
