### ISSUE TITLE
Tasks are difficult to edit if they have a link in them

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1469]
User report:

"In the screenshot with the red spot on the "End Break it Down! Challenge" To Do you see the spot (red) where I click when I want to edit the task, but instead of opening the editor, it opens the link to the Break it Down challenge. This is not only true for this To Do but for To Do's (and other task types?) in general. It's really hard to edit them if there is a link in the title."

Device: Sony F5321
Android Version: 25
AppVersion: Version 3.1.1 (2691)
BETA
User ID: 33bb14bd-814d-40cb-98a4-7b76a752761c
Level: 84
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 16
Timezone Offset: -60 

![_20201212_165158](https://user-images.githubusercontent.com/8144640/105178466-f952d080-5b1f-11eb-9722-dcbde53190dc.JPG)

**Comment by saraolson** [comment]
Solution here seems it would be to make the tap-able area for the link tighter to the actual link-text, rather than the textbox the link is in?

**Comment by phillipthelen** [comment]
More details: This only happens when the link is the last thing in the text. Then the tappable area for the link is extended to the right. If there is any text after it, then the tappable area for the link is only the size of the link.
