### ISSUE TITLE
usability: "Every X Days" and "Start Date" can be changed accidentally while scrolling down the screen

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#147]
Not a but, but a usability problem, although not an urgent one.

If you're in a task edit screen, and you scroll down, if your finger happens to go over the Start Date fields, you can change them without realising you've done so.

**Comment by saraolson** [comment]
Adding this to 1.5 as we're redoing the task creation screen then-- so hopefully we can fix this inherently with those changes.
