### ISSUE TITLE
Issues with weirdly coloured items and no stat bars

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1470]
![IMG_20210118_163200](https://user-images.githubusercontent.com/8144640/105180632-bcd4a400-5b22-11eb-8b02-065c88f41467.jpg)
![IMG_20210118_163149](https://user-images.githubusercontent.com/8144640/105180636-bd6d3a80-5b22-11eb-9edf-9f35def0135f.jpg)

Device: Xiaomi M2003J15SC
Android Version: 29
AppVersion: Version 3.1.1 (2690)
User ID: 21ff148b-48e2-457e-99b2-b4bba39c6557
Level: 7
Class: warrior
Is in Inn: false
Uses Costume: false
Custom Day Start: 0
Timezone Offset: -60

**Comment by saraolson** [comment]
No clue what would cause this, if anyone has ideas on what could be going on that would be helpful

**Comment by phillipthelen** [comment]
I wonder if the user is using some kind of system option or third party app to force dark mode in apps? The bars being darkened like that kinda feel like it.

**Comment by saraolson** [comment]
also, if you look really closely the stat bars are there. theyre just very very very dark. hp is at about 60% full. since there seems to be something going on thats recoloring our sprites, and we never do that, im gonna go along with phillip and guess theres something outside our app doing this
