### ISSUE TITLE
Two spaces instead of one in armoire popup for food items

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1473]
![Screenshot_20210122-154251_Habitica](https://user-images.githubusercontent.com/8144640/105633972-8a44e700-5e53-11eb-9cdc-c8aa84cee212.jpg)

Reproduced in 3.1.2 (2696).

**Comment by Mike-Antonacci** [comment]
I'd like to take this one!

**Comment by saraolson** [comment]
@Mike-Antonacci all yours! ive marked it in progress

**Comment by Mike-Antonacci** [comment]
<img width="212" alt="fixed - extra space before food item in Armoire, without article" src="https://user-images.githubusercontent.com/70340774/105802566-aed6b700-5f58-11eb-8898-08f39048bbcd.png">
<img width="211" alt="fixed - extra space before food item in Armoire, with article" src="https://user-images.githubusercontent.com/70340774/105802567-af6f4d80-5f58-11eb-8511-6253baf494a3.png">
