### ISSUE TITLE
Unclear that you need to be part of a party to start a quest

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1475]
> Device: samsung SM-J327P
> Android Version: 23
> AppVersion: Version 3.1.1 (2690)
> User ID: d4b97542-2c6f-4e27-a25c-083485ef86a1
> Level: 10
> Class: rogue
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> Timezone Offset: 300
> Details:
> 
> Hello,
> I'm trying to activate a quest but it's not working. When I click the quest scroll in my inventory, it gives me the options 'details' and 'invite party'. Selecting 'invite party' doesn't do anything. When I click on 'details', it brings up the information on the quest, but it also has a note at the bottom that says "You can't purchase that amount". It makes no sense. These are quests in my inventory, I shouldn't have to be purchasing anything at all! What's going on?

User was not in a party. I think we have an existing issue for "you can't purchase that amount", but you should also get some kind of error message explaining that you can't start a quest without a party.

**Comment by saraolson** [comment]
we did have plans to give the user and option to start their own party or even just give them a default party they can edit if they tried to start a quest without one. will discuss what the best option would be, whether one of those or just a error telling them why it wont work

**Comment by Alys** [comment]
> we did have plans to give the user and option to start their own party or even just give them a default party they can edit if they tried to start a quest without one... or just a error telling them why it wont work

One thing that may be worth considering is that if they can start their own party from the quest scroll screen and start the quest, then after that they may try to invite other people, not realising that new party members can't join a running quest. We see cases of that already (e.g., questions in the Help guild fairly often), and it may happen more often with that workflow.

If instead they see the error telling them why it wont work (maybe even with a note that you can't add participants to a running quest), it may reduce those cases.

**Comment by saraolson** [comment]
thats a good point. in that case we may be able to tell them why it wont work then link to the party creation screen from that modal, or tell them why it wont work, let them auto generate a party and drop them in the party screen with the usual 'start a quest' ui upfront (so not auto starting the quest but auto generating a party for them)

**Comment by saraolson** [comment]
So our solution to try for now is to implement a modal that appears if you try to start a quest by tapping 'Invite Party' when not in a party. After tapping 'create party' from the modal, we will auto-create a party for them with the name '[Displayname]'s Party', and send them to their party's detail screen. they can then start a quest or invite people from there like usual.

> You have to be in a Party before starting a Quest
> Once in a Party, you can take on Quests by yourself or invite friends to Quest with them too!
<img width="349" alt="Screen Shot 2022-02-14 at 3 38 18 PM" src="https://user-images.githubusercontent.com/12453119/153942722-d5a8ac76-e990-4706-abf1-877a9b7d3176.png">
