### ISSUE TITLE
App may not handle returning from being offline properly

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1476]
User reports that while offline, they couldn't even view their tasks at all without an error about being offline being constantly thrown up. (This is probably intentional, so we don't get people thinking it will work and then surprised once we do sync?) Once they got online, it didn't work properly until the app had been closed and reopened -- should it resume functioning without that?

> Device: motorola Moto z4
> Android Version: 29
> AppVersion: Version 3.1.2 (2694)
> User ID: ac33a26e-dc90-431d-90cf-6b5a059eab27
> Level: 21
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 5
> Timezone Offset: 420
> Details:
> 
>  Minor UI bug:
> Was on Habitica when lost wifi. Attempting to make some change to a task, when a "you are not connected to the internet" warning popped up. Hit ok, intending to go back and just look at stuff offline, but the message repeated immediately after the first closed. I had to restore network connection; error persisted; changed windows, error persisted; closed app, reopened while online - works just fine.
> 
> Not a major thing, just a bit annoying.
> 
> (This could actually be more of a feature request, whether it would be nice to be able to view the app offline as a cached snapshot, as it appears you're already saving a cached version. But, as a simple fix, maybe the underlying issue is that the offline warning makes it seem like you'll have that option by offering the "ok" button. Rephrasing this to "try again" or having it stay open with a ping check until you're connected might make the current functionality more intuitive. And, please confirm it clears correctly once you're reconnected, it didn't seem to for me.)
> 
> Anyways thanks for all you do folks! This probably will come up pretty rarely, and when it does it's hardly a big deal, so I won't be heartbroken if it never changes :)
> 
> Cheers,
> JuniperCrown

**Comment by saraolson** [comment]
marked suggestion discussion to figure out what we'd like the app to do in an offline state, and if its worth the resourcese to clean up this state
