### ISSUE TITLE
Markdown that works in task titles and notes on web does not work in app

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1478]
A user has tried to embed this markdown in a task title:

`![progress](https://progress-bar.dev/10/?title=GENERAL)`
![progress](https://progress-bar.dev/10/?title=GENERAL)

It works on the web version, but not in either of the apps.

I confirmed this on Android, version 3.1.2 (2696). The task actually appears blank for me when I have that markdown in both task title and notes:

![image](https://user-images.githubusercontent.com/8144640/106599896-9d417080-6551-11eb-967f-835e54da4268.png)

It's fine on web:

![image](https://user-images.githubusercontent.com/8144640/106599945-adf1e680-6551-11eb-9851-6fd31e6b5fdf.png)

**Comment by saraolson** [comment]
same as on ios but will just comment here for clarity, this doesnt work bc the image the markdown shows is an svg, which the apps don't support. so just something where mobile will have a more limited markdown experience.
