### ISSUE TITLE
Tavern page is sometimes just blank and won't reload

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1479]
![Screenshot_20210203-001716_Habitica](https://user-images.githubusercontent.com/8144640/106740844-da216c00-6612-11eb-8608-291b1504b4c3.jpg)

This has happened several times for this user. I asked them to keep an eye on it and tell me exactly what they were doing before they saw this:

"With the Tavern issue, it just happened again see the screenshot. Right before this, I had Habitica minimized and then when I reopened it from my open apps it showed the black page.
(Message written January 29th I think but just saw now that it had not sent. Whoops!)

To add more recent info the issue with the black tavern screen just happened again now. I also got another screenshot. Before I had been in the Tavern chat and minimized the screen and then did a few other things on my device and then when I opened the page it just said Tavern at the top with the rest black. "

Device: samsung SM-J337P
Android Version: 28
AppVersion: Version 3.1.1 (2690)
User ID: dbf5390d-6a57-42ad-ae14-af8fd8e570ca
Level: 39
Class: wizard
Is in Inn: false
Uses Costume: false
Custom Day Start: 4
Timezone Offset: 480

**Comment by saraolson** [comment]
@shanaqui if possible, can you ask them if tapping the '...' overflow icon to manually refresh loads it? havent been able to easily reproduce, so it may need some time of being minimized or be tied to something else

**Comment by shanaqui** [comment]
@saraolson Ah, sorry, they stated in the email that they refresh and it doesn't help -- probably they mean pulling down to sync; would tapping the buttons be different? If so, I can email them again!

**Comment by saraolson** [comment]
@shanaqui we actually dont have pull to refresh in tavern view, so only way to actually refresh would be the button. with that in mind im assuming they tried it?
