### ISSUE TITLE
Tapping a notification starts the app but it immediately crashes

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1482]
User report:

> Device: motorola Moto Z3 Play
> Android Version: 28
> AppVersion: Version 3.1.2 (2694)
> User ID: 0e84989d-9538-474b-80d5-84316dddc2c3
> Level: 43
> Class: wizard
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 3
> Timezone Offset: -60
> Details:
> 
>  when i get a notification from habitica and starts the app. it imidietly closes down. but then i can open it normally.
> this started to happen yesterday (5/2 2020 or the day before). so a very recent thing. tried to uninstall and install again. that kind of worked, but i didnt get any notifications for a while instead. when i started to get notifications again the problem came back.

**Comment by shanaqui** [comment]
"whenever clicking notifications, namely ones from my party, the app doesn't open at all. ever since this issue began, my device care app has said that hapitica keeps crashing. i'm not sure if the two are related, but they seem to be.
is there any fix for this? i have tried deleting the cache and updating the app, but nothing seems to be working.
thank you in advance for the assistance!"

> Device: samsung Galaxy S10e
> Android Version: 29
> AppVersion: Version 3.1.2 (2694)
> User ID: 9f1f4e6f-fdf1-48e6-b853-945268d94587
> Level: 93
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: -120

**Comment by saraolson** [comment]
this may be fixed in 3.2, i reported a similar issue but i thought it was just for one notif type. maybe it was for all
