### ISSUE TITLE
App doesn't seem to handle relative links

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1485]
It looks like the Take This challenge is formatted with relative links that are like this "/challenges/b260c6d3-6fd1-4726-ba71-0676e5932960" instead of the full path, which for people on Android is just opening a browser page that says "this site can't be reached".

Consensus is that ideally the apps should be able to handle relative links.

**Comment by bhamrickatmills** [comment]
I would like to investigate this issue, but I'm having trouble replicating it. Could you please give more detail @shanaqui?

**Comment by phillipthelen** [comment]
@bhamrickatmills In case you are still interested in working on this. You can reproduce it by writing a private message or party message containing a markdown link that is not a full url but rather just the part relative to the habitica server. so not `[tavern](https://habitica.com/groups/tavern)` but rather `[tavern](/groups/tavern)`. The url on its own obviously can't be opened by android. so the app should be able to turn those relative urls into full urls and handle them correctly.

**Comment by phillipthelen** [comment]
@bhamrickatmills Are you still interested in working on this? If not, I'd start working on this, so that it can be included in 3.3

**Comment by bhamrickatmills** [comment]
Yeah, go for it. I don't think I'll have time to look into it until Friday.
