### ISSUE TITLE
Errors with beards and moustache purchase/equipping

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1490]
A user on 3.1.2 reported errors with buying beards and moustaches.

In trying to replicate, I found that tapping on the icon to buy the set resulted in the error message "this set of items is invalid and cannot be unlocked".

Buying each item individually doesn't work consistently and the app does not correctly display which items are owned. The web version shows that I don't have one of the items, while the mobile app shows I do own it... but it can't be equipped, with the message "must purchase 2 to set it on preferences.hair.beard". The ones the web shows I own are shown as purchasable on mobile. Amplitude shows some of the purchases have gone through, and those transactions match what I appear to own on web.

I'm on version 3.2 (2834).

**Comment by shanaqui** [comment]
A user is reporting the same problem:

"Hello, I have a problem to buy the Avatar customisation "slim beard". I just bought the "big beard" thinking that was what I wanted but it's too big and now I can't event buy the slim one because the game think, I don't know why, that I already purchased it. But I didn't and I can't even wear this slim beard."

They get the same 'must purchase 2 to set it on preferences.hair.beard' error that I saw.

Device: Xiaomi Redmi Note 9S
Android Version: 29
AppVersion: Version 3.1.2 (2694)
User ID: 3c63c86c-e1a5-460f-a23b-bd655def15c7
Level: 37
Class: wizard
Is in Inn: false
Uses Costume: true
Custom Day Start: 4
Timezone Offset: -60

I'm not honestly sure what to do suggest for them since beards/moustaches are just broken on Android right now, whether you own them or not.

**Comment by shanaqui** [comment]
This appears to be still happening, or a similar issue at least. User has all the facial hair, confirmed by Alys via the database, but sees this:

![Screenshot_2021-04-11-11-31-21](https://user-images.githubusercontent.com/8144640/114569657-14d7fe00-9c6d-11eb-9bb6-f99cc631768a.png)
![Screenshot_2021-04-11-11-26-11](https://user-images.githubusercontent.com/8144640/114569662-15709480-9c6d-11eb-8fbc-adcd6924a627.png)

> 
> Device: HUAWEI PLK-L01
> Android Version: 23
> AppVersion: Version 3.2.2 (2892)
> User ID: 1643f1c4-3199-47b6-b0fc-99a3e567c092
> Level: 54
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 6
> Timezone Offset: -120

**Comment by shanaqui** [comment]
And another:

> Device: samsung Galaxy S10
> Android Version: 30
> AppVersion: Version 3.2.2 (2892)
> User ID: 1ec6cfc6-2c77-430d-bb29-74987ee68a6c
> Level: 33
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: 240
> Details:
> 
> Hi,
> I purchased a mustache from the facial package for 2 gems, equipped and then unequipped it, and then I purchased an item from the facial hair pack for 2 gems (first I tried to purchase the whole facial hair pack and it said "package invalid," so I picked one), and equipped it. I then went to requip the mustache and it asked me to buy it again. I did want to purchase the whole beard facial hair package for five gems, and I spent two gems on a mustache I no longer have. I will say I did not like the way it looked anyway, but still.
> Thanks in advance.

**Comment by shanaqui** [comment]
It looks like the same problem may apply to some of the hairstyles. 

> I already have all the hairstyles, but in the app, under Avatar Customization > Hair > Base, in Hairstyle set 1, the third base from the left in the first row is offered to me for sale for 2 gems (independent of which other hairstyle I select). I can't select it, I really get the sales offer when I tap it.
> 
> Device: samsung SM-T815
> Android Version: 24
> AppVersion: Version 3.2.3 (2934)
> User ID: 1aff9116-34b0-438c-9877-06038bdce161
> Level: 46
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: -120

**Comment by phillipthelen** [comment]
This is the same underlying issues as #1515. Closing this one so that we don't track it twice.
