### ISSUE TITLE
Dailies tab scrolling issue

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1491]
User report:

>  Hi. I just noticed in the app that if you scroll down the Habits or To Do's tab far enough that your avatar and health/xp/mana bars disappears above the screen, then move over to the Dailies tab, there is no way to get the avatar section of the screen back, even if you scroll back up to the top.

We later clarified that your dailies column needs to be empty to trigger this problem.

I've reproduced it on 3.2 (2834)!

**Comment by phillipthelen** [comment]
This is a behaviour of android scrollviews. There's not much I can do here without getting into hacking that scroll behaviour. And even then I might not be able to get a good result. going back to a tab with items allows you to scroll your header visible again, so tbh I don't think this is a "bug" we actually need to fix.
