### ISSUE TITLE
Custom rewards incorrectly show lock icon instead of coin

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1498]
Custom rewards now appear to have a lock symbol, even when you have enough money to buy them.

![Screenshot_20210224-153819](https://user-images.githubusercontent.com/8144640/109025254-77257100-76b6-11eb-9875-64f184544d69.png)

I'm on version 3.2.1 (2840), seems to be being reported by non-beta users, but I'm not sure.

**Comment by saraolson** [comment]
Hmmm this was supposed to only be implemented for challenge views, not show on the rewards view. It's not supposed to be the 'you don't have enough gold to buy this' state but rather 'you can't interact with this here' state.
