### ISSUE TITLE
New task dialogs in Dark Mode are nearly unreadable because contrast is way to low.

### ISSUE THREAD

**Issue by j-m-hoffmann** [HabitRPG/habitica-android#1501]
**Describe the bug**
The contrast of the first screenshot is at 1.41, the second at 1.6. Recommended for small text is 4.5 and for bigger text 3.0 at minimum IIRC. 

**To Reproduce**
Switch your theme to Dark Mode, add a new Task. Add a reminder. If your display brightness is not cranked up high, you will not be able to see the Ok and Cancel Views.

**Expected behavior**
The contrast should be at least 4.5 and the buttons easy to see.

**Screenshots**
![habitica-contrast-problem-1](https://user-images.githubusercontent.com/27806916/109390090-d8944c80-790f-11eb-97a6-ed43c10ff8c2.png)
![habitica-contrast-problem-2](https://user-images.githubusercontent.com/27806916/109390098-e2b64b00-790f-11eb-89dc-583f951aef6b.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S5
 - OS: Android 10
 - App Version: 3.2
 - Habitica User ID: 

**Additional context**
[contrast of the 1st screenshot](https://contrast-ratio.com/#%236133b4-on-%233d3945)
[contrast of the 2nd screenshot](https://contrast-ratio.com/#%23432874-on-%23121212)

[Material Dark Theme Guidelines](https://material.io/design/color/dark-theme.html)

**Comment by j-m-hoffmann** [comment]
i would like to fix this

**Comment by saraolson** [comment]
@j-m-hoffmann for purples in dark mode, we usually use purple 400 (#925CF3) for icons and purple 500 (#BDA8FF) for text

**Comment by j-m-hoffmann** [comment]
Well, to meet the Accesibility Guildelines we have to take the background color into consideration,
we can use the same color for both or do it the other way around. 

The Plus-icon is on a lighter background (#3d3945). Using purple 400 would yield a constrast of 2.69 which is [too low](https://contrast-ratio.com/#%23925CF3-on-%233d3945). Using purple 500 would yield a contrast of 5.46 [which is good](https://contrast-ratio.com/#%23BDA8FF-on-%233d3945)

The text is on a dark background (#121212). purple 500 would give a great contrast of 9.1 here, 400 would still work and meet the 4.5 cutoff.

These elements are on different screens, so using the same color for both should be fine. What do you think @saraolson

**Comment by saraolson** [comment]
@j-m-hoffmann That's true with that background, so lets just do purple 500 for both in this case

**Comment by j-m-hoffmann** [comment]
The second one is fixed in PR #1508. Tried purple 500 but it looked off to me, liked 400 much better and the contrast of 4.5 is still fine.

The first one turned out to be a major headache, to be tackled another time.
