### ISSUE TITLE
allow custom message when you comple a task

### ISSUE THREAD

**Issue by pizzascience** [HabitRPG/habitica-android#1502]
For example if someone has a task "use the stairs" it would be cool if you could add something like "you used stairs, it was super effective" that pops up. Something you can create when making the task

**Comment by bhamrickatmills** [comment]
@saraolson I would like to try to take on this issue. Would that be alright? I think I could add a custom message field to tasks, and then have the custom message populate a toast when the user completes the task.

**Comment by pizzascience** [comment]
Sounds great

**Comment by pizzascience** [comment]
i made a little open scroll pixel art for the message to pop up in. If you want I can send it to you and/or resize it to fit unless you have something else

**Comment by saraolson** [comment]
@pizzascience @bhamrickatmills Hey there, while Habitica is an open source project and we love your enthusiasm, feature requests still need to be approved by staff. At the moment, this feature isn't something we're ready to move forward with. 

For future feature requests, please submit it on the [official feature request form](https://docs.google.com/forms/d/e/1FAIpQLScPhrwq_7P1C6PTrI3lbvTsvqGyTNnGzp1ugi1Ml0PFee_p5g/viewform) that you can access from that link or from the app (Menu > Support > Submit Feedback).

When browsing our repos for issues to work on, ones staff have already approved will be marked Help Wanted and are free to take on :) Thank you!
