### ISSUE TITLE
App not showing any tasks on load after running in the background for extended periods

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1504]
"When I start the Android app, or open its window when I have had other programmes as foreground, it claims I have no tasks.  If I go to party chat, then click tasks, my tasks appear.  This is happening pretty reliably.  I tried to do the clear cache as suggested, but this version of Android does not show that option for Habitica.  

One time I forced Habitica to stop from Android settings, and my tasks appeared when I opened Habitica."

Clearing the cache, pulling down to refresh, etc, don't help; the issue quickly recurs.

> Device: LGE LG-TP450
> Android Version: 24
> AppVersion: Version 3.2 (2832)
> User ID: 1e57e588-c696-478e-84f5-8248e6bd2659
> Level: 20
> Class: wizard
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 4
> Timezone Offset: 480

**Comment by saraolson** [comment]
I've also noticed that when i come back to the app after awhile, the data isn't loaded properly. I haven't noticed it on initial load, though.

**Comment by shanaqui** [comment]
> Device: Xiaomi Mi A1
> Android Version: 28
> AppVersion: Version 3.2 (2832)
> User ID: 011bc428-8be1-4f2c-b4c2-ed82630661f4
> Level: 53
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> Timezone Offset: -60
> 

"When I open the app, it says I don't have any habits, and the habit page is empty. I need to click on skills and then click on habits again for my habits to reappear. When they reappear, they are as normal, same colours and everything. If I close the app and open it again, the same thing happens. This has been going on for a couple of days now."

I suspect there are a bunch more cases of this that I'm still working through troubleshooting for.

**Comment by shanaqui** [comment]
More info from a user:

> Device: Xiaomi MI 9
> Android Version: 29
> AppVersion: Version 3.2 (2832)
> User ID: 0461cdd5-7263-4697-8eaf-422fd331a2ba
> Level: 78
> Class: wizard
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 4
> Timezone Offset: -60

Again it's just "sometimes it doesn't work".

**Comment by shanaqui** [comment]
> My daily tasks, todos and habits disappear and do not reappear unless I quit the app and launch it again. Clearing the cache doesn't help and reloading the data from within the settings menu doesn't either. This has been happening for about two weeks. I installed the beta version because of it, but that doesn't help. I've switched back to production and back to beta since, nothing changed. I really need the app to work.
> 
> 
> Device: Xiaomi Redmi Note 8 Pro
> Android Version: 29
> AppVersion: Version 3.2.1 (2859)
> BETA
> User ID: 5deb1bc7-6aea-4341-a95c-b4bf6b65ddb7
> Level: 1000
> Class: wizard
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 2
> Timezone Offset: -60

**Comment by shanaqui** [comment]
> Device: samsung SM-G981B
> Android Version: 30
> AppVersion: Version 3.2 (2832)
> User ID: 923e79fa-1c8a-40c2-a646-78e1a63cb6b0
> Level: 2
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> Timezone Offset: 0
> Details:
> 
> Hi every time I open the app my habits and dailies disappear and I have to log out and back in for them to reappear.

**Comment by shanaqui** [comment]
> Device: samsung Galaxy S10e
> Android Version: 30
> AppVersion: Version 3.2 (2832)
> User ID: 8f084d77-861a-44a6-b70c-8df31b1a90a8
> Level: 78
> Class: wizard
> Is in Inn: true
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: 360
> Details:
> 
>  My habits, dailies, and to-do's frequently disappear and I have to quit and restart the app to get them back. It seems to happen if I don't open the app for an hour or more, but I've been quitting and restarting it several times a day. This only started happening recently and it's never done this before.

**Comment by shanaqui** [comment]
Several more reports today, but I suspect we have enough details now if the details are going to help. Let me know if I need to continue! So far the background theory is proving true.

**Comment by shanaqui** [comment]
> Device: Google Pixel 3a
> Android Version: 30
> AppVersion: Version 3.2.1 (2865)
> User ID: 9ed97e00-ded7-4f25-8d8b-0425fbd069cb
> Level: 5
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> Timezone Offset: 480
> Details:
> 
>  Frequently I'll open the app and every list will say "you have no [habits/dailies/to dos]. I have to restart the app to get everything back. It's really annoying.

**Comment by shanaqui** [comment]
> Device: OnePlus ONEPLUS A5000
> Android Version: 29
> AppVersion: Version 3.2.1 (2865)
> User ID: 9000cb5e-bdfc-4623-b365-79eeb89b97b4
> Level: 82
> Class: healer
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 9
> Timezone Offset: -120
> Details:
> Hi!
> When I open Habitica on Android, it says I don't have any habits. But when I go to skills or any other place on sidebar and come back to tasks, my habits are back. I also don't receive any notifications. I'm not sure which day this started. Let's say within a week. I have checked app and phone settings, I should receive all notifications. I also deleted habitica and installed it again. I also cleared cache and forced app to close, then opened it again.

**Comment by shanaqui** [comment]
For the last reporter, UUID 9000cb5e-bdfc-4623-b365-79eeb89b97b4, the issue *started* in 3.2.1, and they weren't experiencing it previously.

**Comment by shanaqui** [comment]
> Device: OnePlus ONE A2005
> Android Version: 23
> AppVersion: Version 3.2.1 (2865)
> User ID: d06fde30-1736-4f8b-befe-4d89e1747a78
> Level: 8
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> Timezone Offset: 420
> Details:
> 
>  On opening the app, it incorrectly shows that I have no habits or dailies set up. To dos are unaffected. 
> 
> Refreshing does not help. 
> Quitting the app and reopening doesn't help. 
> 
> Going to a different screen, like Party or equipment and returning to tasks does make the habits and dailies return. 
> 
> I have cleared the cache and that has not helped resolve the issue.

**Comment by shanaqui** [comment]
Closing and reopening doesn't work for this user:

> Device: OnePlus OnePlus 6
> Android Version: 29
> AppVersion: Version 3.2.1 (2865)
> User ID: c1aca4a4-d046-46d0-a455-4222632911c2
> Level: 28
> Class: wizard
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 3
> Timezone Offset: 0

**Comment by saraolson** [comment]
dangit, thanks for the reports. i guess its not unexpected that closing and reopening wouldnt work, as its a problem on launch. navigating to another screen and back should always work at least.

**Comment by ondrejsotek** [comment]
I have same problem, only way to fix this it's to navigate to another screen and then return back.

Device: Xiaomi Mi A1
Android Version: 28
AppVersion: Version 3.2.3 (2913)
BETA
User ID: 6f63bc3a-c719-44c4-9575-1ec97f940f5d
Level: 85
Class: wizard
Is in Inn: false
Uses Costume: true
Custom Day Start: 0
Timezone Offset: -120

**Comment by bplimley** [comment]
I've been having this problem for a couple weeks now. As far as I can tell, whenever the app has been running in the background for a while, when I open it, it shows no habits or dailies (not sure about to do's, but rewards usually still show). Going to another screen and back does not help me. I have to close the app (fully close, not just put in background) and restart it.

Thank you in advance to anyone who is able to look into this!

**Comment by kateriggall** [comment]
Hi, I am wondering if anyone has a workaround for this at all, for example a way to force the app to close instead of going to the background when I move to another app? 

Device: Nokia 2.3
Android Version: 11
AppVersion: Version 3.2.3 (2934)
User ID: c99f87ef-e3d0-4c89-8e77-097fd156ec87
Level: 59
Class: warrior
Is in Inn: false
Uses Costume: false

**Comment by saraolson** [comment]
we don't really have any leads on why this happens to some people or what's causing it yet, so no proper work arounds have been discovered. we're about to switch over to working on android 3.3, as ios 3.3 is about finished, and this issue is on the list for us to look at for that update. hopefully we can figure it out soon so it won't be a bother anymore.

**Comment by saraolson** [comment]
finally got this to happen on my device, including notes from some testing while it was in this state:

1. pull to refresh gives forever loading circle
2. goin to website and checking something off then comin back to pull to refresh doesnt work bc forever loading circle
3. navigate to a different page then press back button, still no habits but loading circle is gone
4. i pulled to refresh again to see if stats up top would change now, but got forever loading circle again
5. going to the menu > items > menu > tasks loaded my habits again
6. i could then pull to refresh and my stats up top updated, and the habit i checked on web showed a +1 streak
