### ISSUE TITLE
Allocating attribute points acting weirdly and assigning wrongly

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1507]
Note: I could not reproduce this, but the user included a video which is very clear: https://photos.app.goo.gl/XubwK5yvzzqHMNZ38

They tapped on "10 points to allocate", and got the modal with the sliders. They typed "3" into the box for the STR stat and confirmed. The app added 5 to STR and 1 to CON.

The video shows they do not have auto-allocation on.

They previously had a problem where they tried to allocate their points and they were all added to STR, so they've had to have it reset twice.

> Device: samsung Galaxy S9
> Android Version: 29
> AppVersion: Version 3.2 (2832)
> User ID: 312a91f9-444a-4213-bff9-04d3668f6542
> Level: 10
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 6
> Timezone Offset: 240

**Comment by shanaqui** [comment]
Actually, Github lets you upload videos now, doesn't it? I've done so here so if they remove their link, we've still got it:

https://user-images.githubusercontent.com/8144640/110326306-665af080-8010-11eb-80c6-2c2af6931a3f.mp4

**Comment by shanaqui** [comment]
> Device: Google Pixel 3a
> Android Version: 30
> AppVersion: Version 3.2 (2832)
> User ID: b597678d-00b8-4c77-829d-38b3da630bfe
> Level: 10
> Class: wizard
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 8
> Timezone Offset: 300
> Details:
> 
>  I tried to allocate my level 10 stat points but regardless of how I set the sliders, it said I didn't have enough points. I restarted the app, and it had allocated some of the points -- and not all where I had attempted to. It put 4 into Strength where I had tried to set just 1.

**Comment by shanaqui** [comment]
The last reporter said something interesting: "Yes, it was all sliders. I actually originally tried to click the little grey arrows but they were unresponsive. Thanks for your help ☺️"

Someone else mentioned the arrows being unresponsive. I wonder if the original reporter also did that -- in which case, the arrows are working but appear unresponsive, and it's causing people to tap them multiple times, ending up with wrong allocations?

**Comment by saraolson** [comment]
wonder if its a slow server thing? im not able to reproduce unresponsive buttons but i would like to get haptic feedback built into the app and that could potentially help 🤔

**Comment by shanaqui** [comment]
Someone else had issues with the buttons seemingly being unresponsive and nothing happening, so I think that's probably the best theory to be going on with here!
