### ISSUE TITLE
Manually syncing never works for user

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1511]
Manually syncing never works for this user. They did a bunch of troubleshooting themselves for a different bug, which I include here for context:

"I'm using android: my tasks and habits have stopped showing up, closing and reopening hasn't fixed, restarting device, clearing cache and reinstalling haven't fixed, the tasks have reappeared a couple of times and then disappear again later.

On a separate note, my manual refresh has never worked, it just gets stuck eternally spinning the refresh icon"

> Device: OnePlus OnePlus 6
> Android Version: 29
> AppVersion: Version 3.2.1 (2865)
> User ID: c1aca4a4-d046-46d0-a455-4222632911c2
> Level: 28
> Class: wizard
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 3
> Timezone Offset: 0

**Comment by saraolson** [comment]
@shanaqui that sounds like some kind of server stall out. not sure what would cause it, but if its just one user then its probably something more on their end? the other issue theyre talking about sounds like the launch issue thats 'fixed' by navigating to another screen and back?

**Comment by shanaqui** [comment]
@saraolson Yes, I only included the other issue because it shows what they've already tried (closing and reopening, restarting their device, clearing the cache and reinstalling the app). If you have any suggestions about what it might be on their end that I can suggest to them, that would be helpful. I can't think of anything they wouldn't have noticed with other apps as well.
