### ISSUE TITLE
Party details not displaying properly

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1512]
Names are missing, details about the quest are missing. User tried clearing cache to no effect.

![Screenshot_2021-03-17-13-23-14-913_com habitrpg android habitica](https://user-images.githubusercontent.com/8144640/111488137-e2e88000-8730-11eb-9466-3968d182b6c7.jpg)
![Screenshot_2021-03-17-13-23-09-959_com habitrpg android habitica](https://user-images.githubusercontent.com/8144640/111488140-e3811680-8730-11eb-98f2-441ced863571.jpg)

> Device: Xiaomi Redmi Note 7
> Android Version: 29
> AppVersion: Version 3.2 (2832)
> User ID: 08efba1f-5f95-475d-ae32-669b085a81aa
> Level: 43
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 1
> Timezone Offset: -180

**Comment by saraolson** [comment]
ive seen something like this happen when the data doesnt load correctly (similar to when your tasks dont load on launch). usually closing and repoening the app fixes it tho.

**Comment by shanaqui** [comment]
I figured it out for the user. It's Xiaomi and their overlays for light/dark mode.
