### ISSUE TITLE
Some seasonal gear wrongly shows gold price as if it is purchaseable

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1518]
> Device: Sony F5321
> Android Version: 25
> AppVersion: Версия 3.2.2 (2889)
> BETA
> User ID: 33bb14bd-814d-40cb-98a4-7b76a752761c
> Level: 86
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 16
> Timezone Offset: -60 

"After purchasing the seasonal Rogue equipment, the Healer equipment appears highlighted for me (I can't purchase it, though, I tried lol)."

![Screenshot_20210323-214513](https://user-images.githubusercontent.com/8144640/112233921-41cb5f00-8c33-11eb-921e-b2814b2a0dba.png)

It does correctly show a lock icon, though.

**Comment by saraolson** [comment]
i wasnt able to reproduce myself, we've had this issue sporadically on other items as well :/ open to anyone investigating to see what may cause the goal highlight to wrong show you're able to buy occassionally

**Comment by phillipthelen** [comment]
Found something that could have caused this (and the other item display issue). We will see if my change actually fixes it.

**Comment by saraolson** [comment]
going to optimistically close this then and we can reopen if it gets reported again in 3.2.3
