### ISSUE TITLE
Adventure Guide 2.0

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1519]
small iteration of the guide that changes some visuals, strings, and how the guide is accessed.

[Task screen(browser link)](https://zpl.io/bo768lW)
zpl://screen?pid=585010e7d211174d029f324d&sid=605b60c27f029c0b9bddea0f

For the details screen, its just changing the bar color to purple 400, the progress text to purple 400, and the top strings seen here:
<img width="357" alt="Screen Shot 2022-01-12 at 11 37 56 AM" src="https://user-images.githubusercontent.com/12453119/149182861-ae7e1ef5-238f-42a5-85c7-804f581244aa.png">

Starting Objectives
Complete these objectives and you’ll earn 5 Achievements and 100 Gold once you’re done!

**Comment by jayesh-srivastava** [comment]
Hi, is this issue still open because I would like to work on it. If open can you please explain it in detail. Thanks.

**Comment by saraolson** [comment]
@jayesh-srivastava hey there! this is an issue that staff is currently working on. you can search for the 'help wanted' label to see issues that are open to contributors

**Comment by jayesh-srivastava** [comment]
@saraolson Thanks for this.
