### ISSUE TITLE
Opening to party page isn't working

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1521]
Starting app on party page isn't working: "I chose "Party" as the new log in page, but Dailies still show up, at least when I first turn the app on within the day. I don't want to see Dailies first hand, because it's likely the day is just beginning and I haven't completed them yet."

> Device: General Mobile GM 8
> Android Version: 28
> AppVersion: Versiyon 3.2.2 (2892)
> User ID: ebd761c5-597a-4421-a128-f115a2497379
> Level: 54
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: -180

Can reproduce in 3.2.2 (2894).

**Comment by shanaqui** [comment]
The user in question says what they were referring to is actually the "record yesterday's activity" popup. But, my launch screen is set to "party" and it never launches to my party screen, so the bug stands!

**Comment by phillipthelen** [comment]
Does this only seem to effect the party screen option? Or do the other options also not work for you?

**Comment by saraolson** [comment]
@phillipthelen just tested em all and only party is messed up
