### ISSUE TITLE
Mount category icons should all be the Base color of the particular Mount

### ISSUE THREAD

**Issue by alejandro-rios** [HabitRPG/habitica-android#1527]
**Describe the bug**
I'm not sure if it is a bug but I find strange that the Lion mount icon doesn't look like a Lion 😅 

**Expected behavior**
That would be a proper image of a Lion 😆 

**Screenshots**
![Screenshot_20210406-210917](https://user-images.githubusercontent.com/10689052/113881753-573b9f80-9782-11eb-9fef-a7ec60af7fea.jpg)

**Smartphone (please complete the following information):**
 - Device: One Plus 5T
 - OS: Android 10
 - App Version: 3.2.2(2892)
 - Habitica Username: @alerios_2021

**Comment by saraolson** [comment]
Not sure what happened here, seems like the app is just pulling a random color of each mount to use as the category icon (ie bear is skeleton bear, but i dont even have that). They should all be locked to the base version

**Comment by alejandro-rios** [comment]
@saraolson If you want i can take a look on this, could you show me the `expected look` on that screen?

**Comment by saraolson** [comment]
@alejandro-rios it should look like this, each mount has a base color and that icon is the one thats supposed to be used 
<img width="391" alt="Screen Shot 2021-04-08 at 3 44 29 PM" src="https://user-images.githubusercontent.com/12453119/114087002-59385800-9881-11eb-833a-272517afbe59.png">
