### ISSUE TITLE
Links not formatted with Markdown are not working in chat

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1534]
> Android Version: 29
> AppVersion: Version 3.2.2 (2892)
> User ID: 6544e17f-237b-4915-ae7e-47744c0dc1bd

(User removed all other information from the standard form.) 

Screenshot: https://snipboard.io/fnRE2J.jpg

![image](https://user-images.githubusercontent.com/8144640/115028227-878ae880-9ebc-11eb-873e-c8d0aba5fe4d.png)

**Comment by ryg-git** [comment]
If it is ok I would like to work on this issue
