### ISSUE TITLE
Locked equipment shows incorrect reason for being locked

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1536]
Locked equipment from sequences says: "This item is only available to a specific class." The user is of the correct class.

![Screenshot_20210420-085048_Habitica](https://user-images.githubusercontent.com/8144640/115400520-49096c80-a1e1-11eb-88b4-6ca812a74b99.jpg)

User hasn't owned any of these items, which is why the royal magus robe is locked:
never owned : armor_wizard_1 : Magician Robe -- base Mage gear
never owned : armor_wizard_2 : Wizard Robe -- base Mage gear
never owned : armor_wizard_3 : Robe of Mysteries -- base Mage gear
never owned : armor_wizard_4 : Archmage Robe -- base Mage gear
never owned : armor_wizard_5 : Royal Magus Robe -- base Mage gear

> Device: samsung Galaxy S9
> Android Version: 29
> AppVersion: Version 3.2.3 (2934)
> User ID: fd1c9c97-54a5-46f8-a300-691f85f20dbe
> Level: 18
> Class: wizard
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 4
> Timezone Offset: 240

**Comment by shanaqui** [comment]
This may be connected: 

> The game mechanics states that when one dies in game, they lose a piece of equipment. However, when I lose a piece of equipment from the Enchanted Armoire, I am unable to repurchase it, since it gives me an error saying that I am not in the class required to buy that equipment and that I'll have to change classes.
> 
> Theoretically, that should not be the case with Enchanted Armoire Equipment.
> 
> I am able to purchase the equipment on the website, which works just fine, it seems as if it is just the app which has an issue.

**Comment by shanaqui** [comment]
For the Enchanted Armoire items lost via avatar death, the item is displaying as unavailable with that error message, even though it *is* available.

![Screenshot_20210504-082302~2](https://user-images.githubusercontent.com/8144640/117155304-9296b180-adb4-11eb-81a5-a5fa81b12a17.png)

> Device: HMD Global TA-1032
> Android Version: 28
> AppVersion: Version 3.2.2 (2892)
> User ID: 4d20af95-9875-4267-be43-928067aca348
> Level: 44
> Class: wizard
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: -330

**Comment by saraolson** [comment]
new string: 'You must purchase the previous items in this sequence to unlock'
