### ISSUE TITLE
Warning for number of Wacky Hatching Potions not triggered

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1537]
It looks like this bug has either recurred or the fix never worked for mobile: https://github.com/HabitRPG/habitica/issues/12103

User seems to have purchased each item separately, though I didn't check for each purchase.

> Device: Google Pixel 2 XL
> Android Version: 30
> AppVersion: Version 3.2.3 (2934)
> User ID: ed9c8952-8e90-4076-9387-23b40ac0c6d1
> Level: 148
> Class: healer
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: 240

**Comment by saraolson** [comment]
hm i think this is something that should be handled server side, but i will ask sabe to make sure
