### ISSUE TITLE
Add indicator to Pets/Mounts to show which you have currently equipped

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1555]
Currently there's no indicator in the pets and mounts section of which pet you actually have equipped. If you tap on the one you do have equipped, the option says "unequip". I reproduced this on my version; user report below:

> On Pets & Mounts. Android does not show an indicator on the currently equipped pet or mount. 
> 
> If you click on the currently equipped mount it shows only "Equip" and not "Unequip". Same with pets (feed is in the menu as it should be) 
> 
> If you click Equip it does Unequip but this isn't obvious.

> Device: LGE LG G6
> Android Version: 28
> AppVersion: Version 3.2.3 (2934)
> User ID: 025f5df6-1a2f-46bc-89cf-c550901b0233
> Level: 89
> Class: healer
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 2
> Timezone Offset: 300

**Comment by saraolson** [comment]
the unequip thing is already an issue. gonna change this to adding an indicator

**Comment by saraolson** [comment]
@Stuie are you still working on this issue? If not, I'll take off the in progress label.

**Comment by Stuie** [comment]
Sorry, I'm no longer looking into this.
