### ISSUE TITLE
User getting persistent connection errors

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1562]
Original report:

> Device: samsung Galaxy S10
> Android Version: 30
> AppVersion: Version 3.2.3 (2934)
> User ID: 8639496b-19c7-4f54-b3aa-fad8219bd9aa
> Level: 1
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> Timezone Offset: -120
> Details:
> 
>  After 1 day app show info: no internet connection. I cant sync anything. Also cant check daily tasks.
> Cache clear: done
> Data clear: done
> Reinstall: done.
> 
> After reinstall app work for 1 day.
> 
> I don't have any anti virus app on phone.
> 
> Also instead od news i see error: net::ERR_NAME_NOT_RESOLVED

I've run through a bunch of other things -- trying it on multiple connections (never works), trying to see whether the web version works on the same device (it does), asking whether they're using a VPN (no), checking their location in case of blocks (Poland)...

I'm otherwise stumped.

**Comment by saraolson** [comment]
this may be an issue with that person's particular phone network/device. haven't heard any more reports so closing.
