### ISSUE TITLE
High GPU overdraw in the task activities affecting rendering speed

### ISSUE THREAD

**Issue by dmartinezg2** [HabitRPG/habitica-android#1563]
**Describe the bug**
The initial view where the habits, dailies and to do tasks are shown is overdrawn in its majority causing the GPU rendering speed to be slower than the proposed benchmark frame speed rate of 60 frames per second

**To Reproduce**
Enable the GPU developer tools to inspect the overdrawing following the android documentation:
https://developer.android.com/topic/performance/rendering/inspect-gpu-rendering

**Expected behavior**
Ideally the GPU overdraw should be less than 4 times, this can be achieved by removing background colors of activities or fragments that are later overdrawn by other fragments or views.

**Screenshots**
![GPU overdraw analysis for the habits view](https://cdn.discordapp.com/attachments/775911066730627076/849450655315525642/WhatsApp_Image_2021-05-21_at_5.05.39_PM2.jpeg)

**Smartphone:**
 - Device: Redmi Note 8
 - OS: Andorid 10
 - App Version: 3.0.1.1
 - Habitica Username:DavidM99

**Comment by saraolson** [comment]
we're making a few improvements to how this view is rendered in 3.3 that may improve this, but we will investigate a bit more in the future to see if theres more we can do
