### ISSUE TITLE
Unviable register functionality after connection recovery

### ISSUE THREAD

**Issue by AlejandroPedrazaL** [HabitRPG/habitica-android#1564]
**Describe the bug**
When you try to register without internet connection the aplication show an error message, but after the conection is restored, if you try to register the application wouldn't work.

**To Reproduce**
1. Open the application in flight mode (or without any kind of connection) when there is no session openend yet.
2. Go to the register view
3. Fill the form
4. Click register button
5. Close the alert pop up
6. Connect to internet
7. Click the register button again

**Expected behavior**
The user would register.

**Screenshots**
Is not clear with an screenshot, because is the register view without working.

**Smartphone (please complete the following information):**
 - Device: Moto G8 plus
 - OS: Android 10
 - App Version: 3.2.3
 - Habitica Username: Alejandro Pedraza

**Comment by Trion129** [comment]
I can try this one.

**Comment by Trion129** [comment]
I tried to reproduce it. First I tried Android 11 Pixel 4 in the emulator. Couldn't reproduce it.
To cross out it was because of the wrong version, I used an Android 10 image. Couldn't reproduce it in that either.

Followed the same steps as advised. I will try my Oneplus phone just in case it is an emulator thing.

**Comment by Trion129** [comment]
Tried on Oneplus 6T. Tried with 4G and Wifi both. Working fine.

**Comment by Trion129** [comment]
@AlejandroPedrazaL Can you tell which registration method did you use?
Also check if the issue is happening with latest app version from Playstore. It'll help a lot in root cause analysis.
