### ISSUE TITLE
Lost content when losing connection

### ISSUE THREAD

**Issue by caguerrero** [HabitRPG/habitica-android#1565]
When the connection is loose, some views appear almost empty. It happens, for example, in the Guild and Market sections.

Lost content is a connectivity antipattern that can be solved by showing an informative message to the user. Here there is, specifically there a lost text case.

**Screenshots**
<img src="https://media.discordapp.net/attachments/775911066730627076/849501257550266388/Loose.png?width=298&height=630" />

**Smartphone**
Device: Moto G8 plus
OS: Android 10
App Version: 3.2.3
Habitica Username: Alejandro Pedraza

**Comment by saraolson** [comment]
@caguerrero what would you prefer to see in this situation? a loading circle? blank boxes where content is supposed to be? we're supposed to have some kind of error banner when connection is lost, but i don't see it in your screenshot.
