### ISSUE TITLE
Markdown in tasks isn't working properly

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1566]
User has this markdown formatting on text:

`*Medium: 50/10 or 25/5 = +*`

That should produce this:

*Medium: 50/10 or 25/5 = +*

But instead, this:

![WhatsApp Image 2021-05-31 at 07 53 05](https://user-images.githubusercontent.com/8144640/120930707-51acf800-c6e6-11eb-845d-988de87730c7.jpeg)

It works correctly on web.

User is on version Version 3.2.4 (2953).

**Comment by phillipthelen** [comment]
This looks like an issue with the markdown library we are using. Needs investigation if it's Markwon or commonmark-java.

**Comment by saraolson** [comment]
> Device: samsung SM-A515F
Android Version: 30
AppVersion: Version 3.4.1.1 (3090)
User ID: d1b0afb2-f0f6-4840-82fa-a3536ab2859d
Level: 56
Class: rogue
Is in Inn: false
Uses Costume: false
Custom Day Start: 0
Timezone Offset: -120
Details:

>Markdown links inside task names or descriptions are not clickable inside the app. They are clickable on the desktop website.

>They are still formatted to look like links but clicking them always takes you to a page to edit the task.
