### ISSUE TITLE
Unable to purchase items with gems

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1567]
I'm unable to test this myself since my app still isn't working, but there are a number of reports of being unable to buy items in the shop with gems:

> Device: samsung SM-A415F
> Android Version: 30
> AppVersion: Version 3.2.4.1 (2957)
> User ID: 0e7f22ac-43c1-4b5e-a8c9-1c20bc108b96
> Level: 46
> Class: wizard
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 5
> Timezone Offset: -120

> Device: samsung Galaxy S8
> Android Version: 28
> AppVersion: Version 3.2.4.1 (2957)
> User ID: d0d10c31-4ad2-4541-8920-919c73df5f20
> Level: 42
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: -180

> Device: motorola Moto e5 plus
> Android Version: 26
> AppVersion: Version 3.2.4.1 (2957)
> User ID: f94a732e-fdf8-4f9f-89d8-c161ee7c771b
> Level: 79
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 6
> Timezone Offset: 300

> Device: samsung SM-G996U1
> Android Version: 30
> AppVersion: Version 3.2.4.1 (2957)
> User ID: 3ad3821f-e71b-4aad-9da5-2143b729a6a6
> Level: 137
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: 240

The first three reports referred specifically to items that you get access to in the shop after completing quests, so that *may* be the problem. However 0e7f22ac-43c1-4b5e-a8c9-1c20bc108b96 mentioned trying lots of different purchases, so it may be everything.

**Comment by saraolson** [comment]
i just tested and its only happenin to quest unlock items for me, ie certain hatching potions, pet eggs

**Comment by saraolson** [comment]
okay i just got this on a white potion as well so its not just quest
