### ISSUE TITLE
If streak is blank, task will not be displayed

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1569]
"Just has a weird situation where one of my dailies disappeared on my mobile. When I logged on via the web, it was there. Figured out what happened was I had reset my streak on thr web and accidently left the streak field empty. That made it disappear on mobile. When I set the streak to zero via the web, it showed back up on mobile.

Since it seems like the mobile app defaults to zero for the streak count if you try to save without entering a number, maybe this isn't really a problem."

> Device: samsung Galaxy S9
> Android Version: 29
> AppVersion: Version 3.2.4.1 (2957)
> User ID: bcfc3512-a076-4689-b9f5-abb906bbd3e5
> Level: 147
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 1
> Timezone Offset: 240

I've confirmed the issue. Would presumably also be fixed by changing the web version not to allow 0 to be saved in that field.

**Comment by saraolson** [comment]
closing in favor of fixing this through the api
