### ISSUE TITLE
Avatars in chat are loading incorrectly, showing other people's avatars

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1577]
I've been able to reproduce this, but Nakonana's email has very thorough screenshots as well: https://mail.google.com/mail/u/0/#label/%40shanaqui/FMfcgzGkXwNccxqVpmqGqbMMVWRdmCJK (link will only work if you're logged into admin email)

> Hello,
> 
> Reporting a display bug and/or a bug with the account of gremlinbearz:
> 
> They posted a (cryptic) message in the Tavern about 2(-3) hours prior to this report (probably an emoji that my old phone doesn't recognize or some fancy font text). Their avatar is wearing something green-ish in the chat icon (like the avatar of the person with the most recent post). But when clicking on their profile it says that they have not logged in since 2014 and their avatar is a snowman.
> 
> After reloading content in settings, the avatar icon showed a snowman - until clicking on their profile (where they are also a snowman and have not logged in since 2014) and closing it again: now the avatar icon is showing them wearing a pi-shield.
> This made me kind of think that their avatar icon is copying the icon of the person who posted the most recent post, but I don't see anyone with a pi-shield. (maybe the latest post was deleted...?)
> 
> Afterwards I opened a different app and then came back to Habitica: the Tavern chat was blank (but that's a known issue), so I went menu > guilds > menu > Tavern to access it. Now gremlinbearz' avatar icon is almost an exact copy of @hoyestoyfeliz' avatar minus the weapon and background. (@hoyestoyfeliz is the latest poster of the Tavern now). (see screenshots - order can be tracked by time of screenshot)
> 
> Cleared cache in phone settings > Habitica app launches from Tavern (is blank) > menu > guilds > menu > Tavern. Gremlinbearz situation is as in the previous step (still a copy of @hoyestoyfeliz when the latest poster is KhalDoggo), but now I got the impression that @boscothekitty 's avatar icon (whom Khal was addressing) was changing to something else while scrolling but couldn't see it when stopping at their message. I thought it was a glitch that happens only temporary after opening the app, so tried to reproduce: cleared cache again, started screen recording and opened Habitica (launched from Tavern, see above) and this is what I got:
> https://drive.google.com/file/d/1D1DST0l1aqms03Cg-4GW9Edw5Vz5IMnH/view?usp=sharing
> 
> (hope I did the sharing right, I usually don't use Google Drive).
> 
> Best,
> Nana
> 
> Edit to add PS: before hitting send on this email I went to the Tavern again and caught boscothekitty and other people's icons changing (after 11a.m. local time). The changes tend to be a fusion of the surrounding posts (e.g. Zephyr's avatar - who posted before Bosco -, and Tired Dog's avatar - posted after Bosco), but it's not limited to it. Some avatars don't seem to change. It kind of feels like those that have a gem-purchased background are not affected by the glitch. But not 100% sure. Gremlinbearz is the only one with the check-in date issue though and seems to be most prone to be affected.

> 
> Device: Sony F5321
> Android Version: 25
> AppVersion: Версия 3.3 (2985)
> BETA
> User ID: 33bb14bd-814d-40cb-98a4-7b76a752761c
> Level: 90
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 16
> Timezone Offset: -120

**Comment by saraolson** [comment]
hmm i tried testing this, and all i could reproduce is the chat icon only loading parts of the avatar, so it looks like a completely different avatar bc it didnt load the whole thing: hair, armor, weapon, ect

could have happened with the snowman too, as in it didnt get to the point where it realized the avatar should actually b a snowman
