### ISSUE TITLE
Scrolling still too sensitive to swiping left/right

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1578]
"scrolling has become more convenient, but still, sometimes, when I swipe up or down, it throws me left or right. Inconvenient."

> Device: Xiaomi MI 8
> Android Version: 29
> AppVersion: Версия 3.3 (2985)
> BETA
> User ID: 681c9230-0fad-4beb-b09c-65e7c7087dfb
> Level: 39
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: -180

**Comment by saraolson** [comment]
@shanaqui for these issues, its helpful if they can share what screen this is happening on. ive asked phillip to fix the task screen, guilds, and challenges screen so far.

i also have the issue in items (especially on the special screen) but he doesnt, so if anyone else has it there it would be helpful to know.

@Nakonana i saw you thumbs up this, are there any particular screens you noticed this on?

**Comment by saraolson** [comment]
ive also noticed this happens on empty task screens as well. when theres a task on the screen, it scrolls as expected

**Comment by Nakonana** [comment]
@saraolson yes, the already mentioned tasks and guild/tavern screens. But it looks like it's fixed now...? Or at least I can't seem to replicate it spontaneously. 

Version 3.3 (2992)
