### ISSUE TITLE
Avatar glitch when removing mount

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1580]
"By the way, I came across another bug. Put the guinea pig on the mount and put it away. What came out of this can be seen in the screenshot :D The pet was removed, of course, but the bug is relevant."

![IMG_20210628_225810](https://user-images.githubusercontent.com/8144640/123965557-78401500-d9ac-11eb-8696-c322faa7e809.jpg)

> Device: Xiaomi MI 8
> Android Version: 29
> AppVersion: Версия 3.3 (2985)
> BETA
> User ID: 681c9230-0fad-4beb-b09c-65e7c7087dfb
> Level: 39
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: -180

**Comment by saraolson** [comment]
fixed in latest build
