### ISSUE TITLE
Inventory Items spacing issues in some languages (e.g., Russian)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#1585]
From Nakonana:

> Discovered some funny tabber spacing/alignment in the inventory/items (in Russian). There's a lot of space to the left of Корм (Pet Food), but only little space to the right (Квесты / Quests).
>
> Device: Sony F5321
> Android Version: 25
> AppVersion: Version 3.3 (2992)
> BETA
> User ID: 33bb14bd-814d-40cb-98a4-7b76a752761c
> Level: 91
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 16
> Timezone Offset: -120 

![image](https://user-images.githubusercontent.com/1495809/124450747-11fe2c80-ddc8-11eb-8196-51afbcce9087.png)

**Comment by saraolson** [comment]
tab spacing is decided by android, as we just use a system tab bar. for some reason, its decided that a two line tab needs that much space in this situation? but, not much we can do about it unless we build our own bar.
