### ISSUE TITLE
App using system language instead of device language, gradually reverting more UI to wrong language

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1587]
> Device: Sony F5321
> Android Version: 26
> AppVersion: Version 3.2.4.2 (2966)
> User ID: fb4c0a1e-b07f-4e4f-946f-2455fb35ab03
> Level: 49
> Class: healer
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 4
> Timezone Offset: -180
> Details:
> 
>  Hello!
> I noticed a bug with the UI language. 
> 
> My language in Habitica Settings: English.
> My System: Android. 
> System language: Ukrainian.
> My location: Ukraine. 
> 
> However, some of the text in Habitica is presented in Russian instead of English.
> For example, instead of the "Notifications" page I see "Уведомления". 
> And the same thing with the message of check-in prize.
> Please, fix this. Thanks in advance. 
> 
> By the way, in the web app everything is OK.

**Comment by saraolson** [comment]
another report:

> when the Habitica app is set to English as default language, somehow it still continues to sometimes translate the texts into Dutch. I did not ask it to do that nor do I want it to. I tried googling but have not yet found the solution. When I go to settings in Habitica it says English as language, after that the texts remain English for a while. However every time the Dutch creeps up again and I don't like it.

**Comment by rilygreat** [comment]
> Device: samsung dm3q
> Android Version: 34
> AppVersion: Version 4.3.4 (7031)
> User ID: e705c7fe-d871-4a13-bd1a-ced7c2c2ba0f
> Level: 17
> Class: rogue
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> Timezone Offset: -540
> Details:
> 
> Background: My device language is set to Japanese, while the language in Habiticas settings is set to English
> Problem: the UI in Habitica gradually shifts from the application language to the system language. Restarting the app temporarily resolves the issue, but the issue always reoccurs gradually over several days of use. 
> 
> I have attached two screenshots of the UI when the issue occurs. As you can see, the UI is in a mix of both English and Japanese. 

![Screenshot_20240225_201728_Habitica](https://github.com/HabitRPG/habitica-android/assets/102926641/4b6f871c-de01-4965-80c3-e3e8962ab2c3)
![Screenshot_20240225_201736_Habitica](https://github.com/HabitRPG/habitica-android/assets/102926641/4f6732a1-1bce-4160-ac5c-7364e53c635a)

**Comment by arjun1194** [comment]
is this available to pick ? seems like an interesting issue to pick up.

**Comment by Hafizzle** [comment]
This has been fixed and rolled out with commit https://github.com/HabitRPG/habitica-android/commit/df4db967209c888385c5598960c6216e4946fb7c
