### ISSUE TITLE
User with CDS has trouble cronning automatically

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1593]
"I have a trouble with the Cron. I set my Cron at 10 PM , but when the time reached 10 PM , the Cron didn't work. Even when i tried to refreshed it. So what i usually do is to force close the app. Almost every single time."

> Device: samsung Galaxy A50
> Android Version: 29
> AppVersion: Version 3.3 (2992)
> BETA
> User ID: a1bcee1e-77a7-45c5-af83-79abc6f212f9
> Level: 180
> Class: healer
> Is in Inn: true
> Uses Costume: true
> Custom Day Start: 22
> Timezone Offset: -420

**Comment by beffymaroo** [comment]
additional report:

Device: samsung Galaxy S9+
Android Version: 29
AppVersion: Version 3.3.1 (3030)
User ID: 4fec0eb8-b208-427e-be81-58ad9507496c
Level: 4
Class: warrior
Is in Inn: false
Uses Costume: true
Custom Day Start: 8
Timezone Offset: 240
Details:
My dailies are still not reseting regularly, I've upgraded to 3.3.2, I've cleared all the caches and checked the website, restarted everything, but it doesn't even say what day it thinks it is, i don't even know if its stuck on yesterday or not there's so little info.

**Comment by creaturebytes** [comment]
This user had a lot more info on what I think is the same issue: 
>Device: samsung Galaxy Note9
>Android Version: 29
>AppVersion: Version 3.3.2 (3041)
>User ID: b7f599ae-3f1c-45e7-a631-63835c5bb195
>Level: 5
>Class: warrior
>Is in Inn: false
>Uses Costume: false
>Custom Day Start: 0
>Timezone Offset: -60
>Details:
>
> Custom day start seems to ignore am/pm when checking if the current time is before or after the custom day start time.
>
>Problems observed: 
>(data above shows its current value of 0, for problems below it was set to 4.00am)
>1. First noticed Dailies appear to reset at the wrong time, no specific details but I often get the popup to check off dailies >completed yesterday, only to then have them marked as done today and I have to uncheck them again.
>2. Screen for setting custom day start displays the date and time of next reset, this shows the next day if custom day start is >3am and current time is 3.30pm, but shows current day if custom day start is 4am and current time is 3.30pm. It seems to be >treating 4am today as a time in the future.
>At 4pm, it then treats 4am as a time in the past and 5am as a time in the future.
>I am assuming that the display is accurate, and the dailies are waiting for a time that has already passed, and this is causing it >to get the days mixed up and display tickboxes for "yesterday" that mark them as complete today instead.
>
>Screenshots:
>Attached screenshots were taken on the 7th, at about 3.40pm and 4.01pm. They show the next daily reset date/time displaying >a time in the past, when the current time with pm ignored would be before the custom reset time. ((Left in email))

>Workaround:
>Setting the custom start time back to 12.00am seems to always correctly pick the next day as the next reset time. (so basically >not using the custom start time feature for now)
