### ISSUE TITLE
Mystery items auto-equipped even with auto-equip turned off

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1597]
Couldn't replicate, don't have mystery items to claim.

> Device: motorola Moto g power
> Android Version: 29
> AppVersion: Version 3.2.4.2 (2966)
> User ID: 8f0f2f48-73b0-4b27-a95a-40603cc919e7
> Level: 23
> Class: healer
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 5
> Timezone Offset: 420
> Details:
> I just noticed my subscriber items, in the Mystery Box. Opened it and got each one. I...don't remember what the button I tapped to dismiss each item said, but I don't think it said Equip, I think I would have noticed.
> 
> All the items ended up equipped. I have Auto-equip New turned off. Now I have to go through and find my previous, carefully-chosen items and equip them again.
> 
> Was this user error or a bug?

**Comment by saraolson** [comment]
this must have been user error. the main button on that modal is indeed equip:

<img width="321" alt="Screen Shot 2021-07-14 at 9 54 32 AM" src="https://user-images.githubusercontent.com/12453119/125634473-84ae4463-9958-473a-87c6-0c5efa1eb3c9.png">
