### ISSUE TITLE
Going into settings causes header to partially disappear

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1599]
"I encountered a small bug in the Habitica App. When I click the three bars on the lower menu (the tab that lets me access my inventory, guilds, etc.), the bar at the top which has my profile, notifications, messages, and settings glitches out partially. The settings still registers when I click on the space where it should be, but the other buttons don’t seem to work. I get the bar to reappear in full when I click into another page (like the About page) on the menu, but when I tab over to my Dailies or Habits and tab back, it’s bugged again. 

It’s more annoying if anything; it doesn’t break or crash the app at all. 

I’ll attach a screen recorded video of what I’m talking about below:

https://user-images.githubusercontent.com/8144640/126175590-962df910-4a45-4212-8f80-8a09c76b3a24.mov"

> iOS Version: 14.6
> Device: iPhone 11
> App Version: 3.3.1 (600)
> User ID: b53978c7-4faf-494e-b3d9-bb35e59a3ff9
> Level: 6
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0

**Comment by saraolson** [comment]
this is an ios issue, so closing here
