### ISSUE TITLE
No error notification that user is already in a party after inviting them

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1600]
"I tried to invite someone to join my party (their user ID is fda81955-987c-4855-b39b-e660c65866bc). The invite didn't go through. I reported it as a bug in the guild, and Alys determined that that person is already in a party. Apparently what should have happened is I should have gotten a notification that they are already in a party. I've told the person this, so that end will be taken care of, it's just the missing notification. Thanks."

> Device: motorola Moto g power
> Android Version: 29
> AppVersion: Version 3.3 (3008)
> User ID: 8f0f2f48-73b0-4b27-a95a-40603cc919e7
> Level: 28
> Class: healer
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 5
> Timezone Offset: 420

**Comment by shanaqui** [comment]
There's also no error notification when the party is already full. Not sure if we want a separate issue for this, or if it's just that errors returned aren't being shown to users in general.

**Comment by pauliancu97** [comment]
Hello, can I be assigned this issue?
