### ISSUE TITLE
Widget: Improve UX when completing task or daily 

### ISSUE THREAD

**Issue by YellowSub17** [HabitRPG/habitica-android#1601]
Tapping anywhere on a todo or daily task item in the widgets completes the task, despite the widget having a "check" area that indicates completing the task. 

Why this is a problem: 
My first instinct is to tap the check box to complete a task, and tap the task title to enter the app to read more/edit the task. Instead, when I tap the title it "completes" the task that might not be done, making the user have to remake the task and awarding undeserved rewards. Also, when scrolling through a list of tasks, accidently tapping a title is a common occurrence for me.

Proposed solution:
Separate tappable areas on the task items. Tapping the check mark box will complete the task, tapping the task title enters the app to edit/view the task details.

**Comment by YellowSub17** [comment]
I don't know anything about making Android apps, but would be happy to learn and try to help if there is interest in solving this.

**Comment by saraolson** [comment]
@YellowSub17 if you'd like to take some time to try to solve this, you're welcome to! we only have one developer for both the android and ios apps, and the android widgets aren't a high priority right now so it would be a while before our team got around to improving this.

**Comment by yarrouye** [comment]
> My first instinct is to tap the check box to complete a task, and tap the task title to enter the app to read more/edit the task. Instead, when I tap the title it "completes" the task that might not be done, making the user have to remake the task and awarding undeserved rewards.

The right way to fix such an action is to filter your taks by Completed, and then uncheck the task you checked off by accident. This will undo the benefits you just received. Then simply change the flter back to active.

**Comment by yarrouye** [comment]
> Tapping anywhere on a todo or daily task item in the widgets completes the task, despite the widget having a "check" area that indicates completing the task.

This doesn't seem to be the case, actually. Right now, and even in June IIRC, Habitica on Android behaves as you want:

> Separate tappable areas on the task items. Tapping the check mark box will complete the task, tapping the task title enters the app to edit/view the task details.

**Comment by YellowSub17** [comment]
@yarrouye Just tried it again on my phone, and tapping the "title" area of the task in the dailies widget marks will complete the task, and not send the user to the app for editing. I will send a video for proof, but if it is working for you, perhaps this is a phone specific issue? (Specs: Samsung A70 (SM-A705YN), One UI version 3.1, Android version 11)

**Comment by saraolson** [comment]
my widgets behave the same as @YellowSub17 , where tapping the text area completes it.

**Comment by yarrouye** [comment]
On my Pixel 5 phone, tapping the text brings up the task editor.

**Comment by DorianK29** [comment]
Changing `R.id.widget_list_row` to `R.id.checkbox_background` in file TaskListFactory.kt, line 97:
`remoteView.setOnClickFillInIntent(R.id.widget_list_row, fillInIntent)` 
Fixed the issue.

my Habitica User-ID:
4b19193f-136e-4fc3-99cc-d3ab760bb02e

**Comment by saraolson** [comment]
had issues interacting with the task in the widget when testing this on a device
