### ISSUE TITLE
In app notifications aren't displaying 

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1611]
"With this latest update, the in-app notifications and the guild chat is also wonky. When I open the app, I see a brief flash of the little number that indicates there are new messages in my guilds, but then it disappears. When I navigate to the notifications tab, there are none to be found, until I pull down on the screen or visit another page in the app."

Device: OnePlus OnePlus 6T
Android Version: 29
AppVersion: バージョン： 3.3 (3008)
User ID: 767e5d92-0e13-4e30-acb1-d8bba62824fc
Level: 113
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 7
Timezone Offset: -120 

I've seen this behaviour as well.

**Comment by saraolson** [comment]
was able to confirm on 3.3.1. force close app > reopen > go to menu (may see a flash of a number in bubble or may look like you have no notifs) > tap notifs > pull to refresh.

able to reproduce every time.
