### ISSUE TITLE
Editing tasks removes filtered view

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1615]
> Device: Xiaomi Mi MIX 2
> Android Version: 28
> AppVersion: Version 3.3.1 (3030)
> User ID: 35c3fb6f-fb98-4bc3-b57a-ac01137d0847
> Level: 58
> Class: wizard
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 1
> Timezone Offset: 420
> Details:
> 
> Dailies filter randomly switches from "All" to "Due" while I'm editing my Dailies.

Reproduced by me -- I switched the filter to all, picked a task to edit (it happened to be one which was due, if that may be relevant), edited the title and then saved the task. I went back to the dailies section, now filtered by due instead of all.

I don't know if this is a change (whether this behaviour has always existed) or not, but I think most people probably expect the filter to "stick" after editing tasks.

**Comment by saraolson** [comment]
i was also able to reproduce using nicky's steps. for the record i don't have 'set default dailies to due tab' checked in the settings.
