### ISSUE TITLE
Cron not triggering when first using app, seems to trigger randomly throughout the day

### ISSUE THREAD

**Issue by creaturebytes** [HabitRPG/habitica-android#1621]
*Device: OnePlus BE2028
Android Version: 30
AppVersion: Version 3.3.2 (3041)
User ID: 1dc853cf-0d4c-42e3-96c5-adbede54afb8
Level: 13
Class: rogue
Is in Inn: false
Uses Costume: false
Custom Day Start: 0
Timezone Offset: -480
Details:

"I have an issue with the app giving me the "select which dailies you did yesterday" and restart in the middle of the day. It happened today at 5pm and the other day at 2pm. I'm not sure if this is something I did or what. Couldn't find anything in the settings to change this. I'll usually check the app a couple of times a day. I'll be in the middle of the day when it resets. I know if you miss it will alert you the next day but it's not waiting until the next day. I don't know if there's a time configuration or something I can change in app. Randomly started doing this a week or 2 ago."

**Comment by saraolson** [comment]
hmm this sounds like they're not triggering cron when they should
