### ISSUE TITLE
Repeating Text for Food 

### ISSUE THREAD

**Issue by creaturebytes** [HabitRPG/habitica-android#1623]
Device: Google Pixel 2 XL
Android Version: 30
AppVersion: Version 3.3.2 (3042)
BETA
User ID: 27d6fcab-e07c-4a90-9458-eb4ed6aa4ac6
Level: 58
Class: healer
Is in Inn: false
Uses Costume: true
Custom Day Start: 21
Timezone Offset: 240
Details:

"I have recently been experiencing a slight visual bug where when I tap on a pet to feed it, if I have let's say 1 rotton meat, 2 pink cotton candy, and 1 chocolate, it shows I have 1 rotton meat, 2 pink cotton candy, 1 chocolate, 1 rotton meat, 2 pink cotton candy, and 1 chocolate."

**Comment by saraolson** [comment]
> Device: Google Pixel 5a
> Android Version: 31
> AppVersion: Version 3.4.2 (3122)
> BETA
> User ID: 29b9c544-3957-4761-af53-376f09a59777
> Level: 108
> Class: wizard
> Is in Inn: true
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: 300

<img width="360" alt="Screen Shot 2022-01-03 at 12 46 19 PM" src="https://user-images.githubusercontent.com/12453119/147962544-93103f7a-bf79-41f2-bef3-f7dd67580570.png">

**Comment by saraolson** [comment]
> Device: samsung SM-N986U1
> Android Version: 30
> AppVersion: Version 3.4.2 (3134)
> BETA
> User ID: a8c9f39f-e070-4481-bf8b-f6634df90fbc
> Level: 48
> Class: healer
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 3
> Timezone Offset: 300
> Details:
> 
> When food is earned, two appear in the app, one isn't real and can't be used and will either go away when I feed the real one or I have to refresh the screen each time beside it does.

**Comment by beffymaroo** [comment]
possibly related report:

"Hey,

Love the app, I'm a happy subscriber.

Bug report: Food drops keep appearing double in my inventory. I can't use the duplicate, and it disappears on refreshing the inventory page. But it's a bit irritating, if it's a wider problem maybe you could fix it.

Jack


Device: samsung SM-G950F
Android Version: 28
AppVersion: Version 3.4.2 (3133)
User ID: d20df2a6-0aed-4b54-a10f-f9e938dfe89c
Level: 42
Class: wizard
Is in Inn: false
Uses Costume: true
Custom Day Start: 0
Timezone Offset: 0
Details: "

**Comment by phillipthelen** [comment]
This is already fixed, but I also added a new test that makes sure it stays that way
