### ISSUE TITLE
"Receipt __ Used" Error When Purchasing Gems

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica-android#1624]
Device: LGE LM-Q730
Android Version: 29
AppVersion: Version 3.3.2 (3041)
User ID: 4e198db8-1006-4654-845e-32d9ad7ff9fe
Level: 51
Class: rogue
Is in Inn: false
Uses Costume: false
Custom Day Start: 0
Timezone Offset: 300
Details:

 Hey! When I go to purchase the .99 Gem Pack of 4 I get a pop up that says, "Receipt___Used" and it tells me I have purachsed the item already. Which...as you can imagine, it's silly, because gems are a recurring purchase

**Comment by creaturebytes** [comment]
A third user report today had a little more information with similar issue: 
> Device: Sony SOG02
> Android Version: 30
> AppVersion: バージョン： 3.3.2 (3041)
> User ID: 8244f569-6afb-48b7-9c5a-67d214457929
> Level: 1
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: -540
> Details: 
> This display appears every time I open the paid plan or gem purchase page. Also, the loading display at the bottom of the gem purchase page doesn't disappear, and the app often quits as soon as I open the page.
This bug has occurred after canceling the subscription once.

![image](https://user-images.githubusercontent.com/89276822/131905330-0461c633-f755-4179-b295-9c7a1083615b.png)
