### ISSUE TITLE
Tag deletion isn't saving in some cases

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1625]
Have a few user reports of trying to delete tags then pressing 'Done' and when they return to the modal, the tag is still there. This seems to happen for tags they created and old Challenge tags. It happens when they tap 'Done' either at the bottom of the modal or the 'Done' that appears in place of the 'Edit' button. 

When I asked them how it appears on the website version, they responded with 'In the website I don't see the tags I've already eliminated and I can eliminate anyone if I want, but once again in the app all tags appear. I mean, in the website I only have 7 tags, while in the app I can see 17.' So the tags are getting deleted but for some reason the app is still displaying them in some cases?

I couldn't reproduce, both Done buttons properly saved the deletion for me.

Attaching recording of the bug:

https://user-images.githubusercontent.com/12453119/131869388-08ed9146-0db3-4756-b619-453715faf7f9.mp4

**Comment by beffymaroo** [comment]
Possible related report:

Device: samsung Galaxy S10
Android Version: 30
AppVersion: Version 3.3.2 (3041)
User ID: 19e33234-be86-42de-893e-30a0e9ba30e1
Level: 8
Class: warrior
Is in Inn: false
Uses Costume: true
Custom Day Start: 0
Timezone Offset: 300
Details:

 At one point, I made a few tags that I named Evening, Morning, and All Day. Everyday, those tags multiply, even though I am not doing anything. Everytime I try deleting them, they all reappear. I tried clearing the cache and force stopping the app, but it didn't help.
