### ISSUE TITLE
NPC Justin keeps showing up after dismissing

### ISSUE THREAD

**Issue by creaturebytes** [HabitRPG/habitica-android#1626]
User cleared all onboarding tasks and cannot dismiss Justin NPC chat boxes. 

>Device: samsung Galaxy S10
>Android Version: 30
>AppVersion: Version 3.3.2 (3041)
>User ID: 83924f9c-b233-4752-8946-329f4b248f5b
>Level: 2
>Class: warrior
>Is in Inn: false
>Uses Costume: false
>Custom Day Start: 0
>Timezone Offset: 360
>Details:
>
>-"I just started with the app, and I get get out of the tutorial?? I'm confused about how to get out of it, it just keeps showing the same messages every time I change screens"
>-"at this point it seems like Justin is just super excited to explain stuff, because I have already completed the onboarding tasks and tried to do other tasks, but he keeps popping up every time I open any window. I don't know if I broke the loop or haven't fulfilled some condition to make him go away, but I have attached some screenshots. you can see the progression of me adding tasks and Justin still popping up. the same thing happens with the other tabs on the navigation bar. "

![Screenshot_20210831-175543_Habitica](https://user-images.githubusercontent.com/89276822/132266094-ac6c81b2-db26-4536-9b06-96ddfedb7ccd.jpg)
![Screenshot_20210831-175525_Habitica](https://user-images.githubusercontent.com/89276822/132266097-e0a93050-7649-4dae-b5cc-cf934de46bda.jpg)
![Screenshot_20210831-175504_Habitica](https://user-images.githubusercontent.com/89276822/132266098-893170bf-20c2-4cb1-a820-3a652bc65b20.jpg)
![Screenshot_20210831-175432_Habitica](https://user-images.githubusercontent.com/89276822/132266100-a93dc3ba-a04f-4dea-946f-3dd2c8d4e829.jpg)

**Comment by saraolson** [comment]
wasn't able to reproduce this myself. probably need to look into this account and see if a flag isnt being set..?

**Comment by saraolson** [comment]
> Device: Sony G8341
> Android Version: 28
> AppVersion: Version 3.3.2 (3041)
> User ID: 19d9a70c-fe1b-49d5-a513-f5967faecba5
> Level: 2
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 6
> Timezone Offset: -120
> Details:
> 
>  Justin "Guide" is always showing the tutorial on every tab every single time I perform any action. It is annoying and O could not find the way to disable it.

**Comment by creaturebytes** [comment]
>Device: motorola Moto g stylus
>Android Version: 30
>AppVersion: Version 3.4.2 (3133)
>User ID: a47f983a-e514-4928-bf9c-6ce81fcfd28e
>Level: 2
>Class: warrior
>Is in Inn: false
>Uses Costume: false
>Custom Day Start: 5
>Timezone Offset: 300
>Details:
>"I love the app but every time I enter any menu, a tutorial event happens which I have to spam click through. Very close to uninstalling because of how very annoying this bug is."

**Comment by CuriousMagpie** [comment]
I set the user's `flags.tutorial.ios` to `true` in the database two days ago, however, they have been reset to `false` and we have another ticket from them. I'm going to try to set everything in `flags.tutorial.common` to `true` and see if that fixes the issue. 

I notice, although this may be nothing, that all the users affected are level 2.
