### ISSUE TITLE
Android app task progress not syncing 

### ISSUE THREAD

**Issue by creatrixtiara** [HabitRPG/habitica-android#1629]
I'm having trouble syncing my Android task progress to my account. I will mark off all these tags on my app but none of it gets registered on the desktop app no matter how many days have passed or how many times I hit Sync. I can tell it's not happening because the Streak doesn't register (it still says 0) and the desktop version is still asking me to mark off dailies that are only meant to repeat every 2 weeks and which I did already do! I'm losing health because of it which seems kind of unfair.

I'm on a Google Pixel 3 if that matters.

**Comment by saraolson** [comment]
@creatrixtiara could you report this issue through the app by going to Menu > Support > Get Help > Report a Bug? Filing a report that way provides our team with some troublshooting information about your account. There may be some bad data in your account that's preventing your days from rolling over.

Providing a specific flow you're going through like 'checked off a daily on the Android app, didn't see the streak go up there, then went to web and the task was still due after a refresh' can help us troubleshoot and figure out if this is a problem with your account, the android app, or the web app.

Going to close this issue for now, but please send us a report through the app and we'll do our best to help.
