### ISSUE TITLE
When you send a message, it appears off-screen and you have to scroll to view it

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1658]
This can make it seem like your message never sent

**Comment by liveHarshit** [comment]
I would like to take it up

**Comment by saraolson** [comment]
@liveHarshit awesome, i'll mark it as in progress for you! just let us know if you have to drop it for any reason and we'll put it back up for grabs.

**Comment by phillipthelen** [comment]
See #1703
