### ISSUE TITLE
Stats widget getting stuck in a blank state

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1661]
It shows the habitica logo and empty bars, even after opening the app.

**Comment by pauliancu97** [comment]
Can you assign this bug to me?

**Comment by saraolson** [comment]
@pauliancu97 thanks for taking this on! sorry for the delay in getting back, had to handle some things last week. we'll review your PR when we're working on the next android update

**Comment by saraolson** [comment]
removing from milestone and putting the pr in milestone instead to avoid any double issue confusion when sorting through it
