### ISSUE TITLE
'You don't have any null' shows when using an item with nothing to use it on

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1663]
to reproduce, go to items and try to use a hatching potion with no eggs. It should say 'You don't have any Eggs' or if the other way around, 'You don't have any Hatching Potions' 
![Screenshot_20211025-150653](https://user-images.githubusercontent.com/12453119/138755219-4e1c585b-fb9d-45ad-890a-74a562084c46.png)
s.

**Comment by dhruvnagarajan** [comment]
I got thi @saraolson assign to me

**Comment by saraolson** [comment]
@dhruvnagarajan Sorry for the delay! If you're still interested in working on this, you're welcome to.

**Comment by dhruvnagarajan** [comment]
@saraolson yeah i'll fix it

**Comment by saraolson** [comment]
@dhruvnagarajan are you still planning to work on this or should I remove the in progress tag?

**Comment by dhruvnagarajan** [comment]
@saraolson yes i'll close this soon

**Comment by dhruvnagarajan** [comment]
@saraolson pl merge

**Comment by saraolson** [comment]
@dhruvnagarajan ive assigned this to be reviewed in our next milestone. right now, our developer is working on the next iOS update, so when he's finished there he'll return to Android 3.5.2.

**Comment by ajmeese7** [comment]
Has this not been pushed to the app yet? I'm still having the same problem, I came to the repo to make an issue and/or push a fix PR and saw that this already existed!

**Comment by saraolson** [comment]
@ajmeese7 it's currently in the version being tested for release, 3.6. we should have a public beta release for that version available this week sometime.
