### ISSUE TITLE
Filters list is not displaying the proper filters for the task list

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica-android#1670]
**Describe the bug**
Per user email: the filters list is not consistently displaying the proper filters for the task list viewed. In particular, the Dailies are often showing the Habits filter options instead of its own and apart from restarting the app or accessing Habitica on the desktop, there often is no way to access them

**To Reproduce**
I have not been about to reproduce this issue.

**Expected behavior**
Filter selections should display those selected.

**Smartphone (please complete the following information):**
 - OS: Android
 - App Version: Unknown
 - Habitica UUID: e85432e5-252f-4f33-a0ee-e02a1dc89129

**Comment by creaturebytes** [comment]
>Device: samsung SM-A326U
>Android Version: 30
>AppVersion: Version 3.4.1.1 (3090)
>User ID: d7d8006d-bf7a-4e4c-8ab1-5f49ef9cd1b4
>Level: 73
>Class: rogue
>Is in Inn: false
>Uses Costume: false
>Custom Day Start: 0
>Timezone Offset: 360
>Details:
>"I am trying to undo completing something on my to-do list, but the filter "completed" does not appear.  It shows the filters for the habits tab instead. "


>Device: samsung SM-G998B
Android Version: 31
>AppVersion: Version 3.4.2 (3133)
>User ID: 47c13536-4aa5-4d52-a3bc-5ddbb0add5d2
>Level: 17
>Class: Disabled
>Is in Inn: false
>Uses Costume: false
>Custom Day Start: 0
>Timezone Offset: -60
>Details: "while viewing dailies, the filter button opens the filter view for habits instead oft filter view for dailies (it used to work, a recent update broke it). because of this it's not possible to filter dailies anymore (e.g. show only the ones that are due today). please also make it possible to show only due dailies permanently without reapplying the filter every time. thank you for your consideration "
