### ISSUE TITLE
Usability Issues on Tablets in Landscape Mode

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica-android#1671]
from user report: 

"Device: samsung SM-T870
Android Version: 30
AppVersion: Version 3.4.1 (3085)
User ID: b47cc54c-b40e-452f-8b3b-f2da2ac877dd
Level: 10
Class: rogue
Is in Inn: false
Uses Costume: false
Custom Day Start: 5
Timezone Offset: 360
Details: Landscape orientation on tablets and probably Chromebooks with the app has issues that aren't the same with portrait mode.  For example, when you tap on a pet, the popup for mount/equip is cut off.  You have to swipe up and hope you don't activate Android's back or home button.  My tablet is heavy and I hate using it in portrait, and Chromebooks probably don't have portrait at all.  So please give all the popups some landscape loving checks."

**Comment by saraolson** [comment]
with our small team, we don't usually spend time checking to make sure everything works well on tablet as phone is our priority especially on android. if any contributors would like to pick this up and make some improvements, we'd welcome the help!
