### ISSUE TITLE
Crash When Trying to Set Custom Day Start

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica-android#1672]
From User Report: 

"Device: samsung SM-S727VL
Android Version: 23
AppVersion: Version 3.4.1 (3085)
User ID: 198ce17a-fdbf-4038-bb1d-a9a9a8ffb5c4
Level: 5
Class: warrior
Is in Inn: false
Uses Costume: false
Custom Day Start: 0
Timezone Offset: 300
Details:

Hi, I'm trying to change my Custom Day Start, but whenever I click on the option in Settings, it freezes for a few seconds, gives me a "Unfortunately, Habitica has stopped" message, and then restarts the app. It's been happening for a few days now since I started the game. Doesnt seem like this was intended to happen, but I can't find any hint of it in the Known Bugs wiki. Hopefully you can fix it! It seems like a great game otherwise and it's been helping with my motivation!"

**Comment by saraolson** [comment]
i couldn't reproduce this

**Comment by saraolson** [comment]
may be an issue with samsung's version of the clock modal? idk
