### ISSUE TITLE
External links not working from Guild pages

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica-android#1674]
User report: (also reproduced by @voidbytes ) 

"Device: LGE LM-V600
Android Version: 30
AppVersion: Version 3.4.1.1 (3090)
User ID: d2656f22-44e5-4239-ad66-e0d40305090f
Level: 5
Class: warrior
Is in Inn: false
Uses Costume: false
Custom Day Start: 0
Timezone Offset: 300
Details:

 Unable to click external links in guild pages including wiki pages. Verified with second user that the issue exists. "

**Comment by creaturebytes** [comment]
Similar issue:
>Device: Google Pixel 2
>Android Version: 30
>AppVersion: Version 3.4.1.1 (3090)
>User ID: 9df18c28-062e-40f9-a5ea-c200ff9f61fe
>Level: 90
>Class: healer
>Is in Inn: false
>Uses Costume: true
>Custom Day Start: 0
>Timezone Offset: 360
>Details:
>I cannot click links on most posts. If I try to click the link, it opens up options to reply, copy, or report, but it won't let me access the link itself. It seems to be related to external links most of the time. Actually, this appears to be a site wide problem where I cannot click any external links in posts, profiles, guild descriptions, etc.

**Comment by saraolson** [comment]
I tried to link to a challenge in my party chat, as well as in party description. neither link was tapable. it was just treated like plain text

**Comment by Nakonana** [comment]
Someone in Commonwealth of i18n also mentioned having issues with the links in the guild description.

**Comment by saraolson** [comment]
@Nakonana nah, no need. this should cover it.

**Comment by ivycheang** [comment]
Floating by and just wants to add on that I see this for my tasks as well. When I click on link it just opens the edit panel instead of directing me to page. Guessing it's the next behaviour bc it's not a link so leaving that here as well.

**Comment by saraolson** [comment]
this wasn't actually fixed in the above pr, that or the pr isnt in the current release so reopening
