### ISSUE TITLE
Phantom Onyx Quest Scroll 

### ISSUE THREAD

**Issue by creaturebytes** [HabitRPG/habitica-android#1677]
>Device: samsung Galaxy S8
>Android Version: 28
>AppVersion: Version 3.4.1.1 (3090)
>User ID: 13f2e230-3ef9-43b5-bfe3-0d00c153fa58
>Level: 129
>Class: healer
>Is in Inn: false
>Uses Costume: true
>Custom Day Start: 4
>Timezone Offset: -60
>Details:
>"I bought The Onyx Odyssey with 4 gems today but the quest cannot be started. The app asks me if I want to sell it for "null Gold" instead of getting the usual options. The quest scroll has no image in the inventory and the text is only "onyx"."

**Comment by saraolson** [comment]
looked into this and it seems to be working as expected now. the app may have just taken some time to load the new content. 

gonna close this for now. unless we continue to hear reports, this has probably cleared up on its own now.
