### ISSUE TITLE
Reminders don't adjust for when you change time zones

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1678]
Had a report from a user where they set a reminder for 10pm Eastern, then they flew to the west coast and the reminder was happening at 7pm Pacific (aka 10 est). They expected the reminder to happen at 10 Pacific.

> Device: OnePlus OnePlus 6T
> Android Version: 30
> AppVersion: Version 3.4.1.1 (3090)
> User ID: d2014dc8-b1b3-4a73-b71c-6573c94461ac
> Level: 1
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 5
> Timezone Offset: 480

> Hello, I noticed that my alarm reminders are sticking to the timezone that I set them in, which is at least undesirable to me. I would suspect most users don't want this, either. Is there a way to change it, or is this a bug?
> To elaborate on my use case, I created a daily task and set a reminder for 10 PM. I did this while I was on the east coast of the United States (Eastern Time). I then moved to the west coast of the United States (Pacific Time), which is behind by three hours. The expected result would be that my reminder continues to alert me at 10 PM, regardless of what timezone I'm currently in or what timezone I created the reminder in. However, the actual result was that the reminder alerted me at 7 PM PST, which is equal to 10 PM EST, the timezone which I originally created the reminder.

**Comment by david-dkp** [comment]
Well, should we add a Time Zone selector ?
