### ISSUE TITLE
Add an undo option

### ISSUE THREAD

**Issue by iswarmondal** [HabitRPG/habitica-android#1681]
The accidental touches make everything into hell. So please add an undo option to prevent them from happening.
For reference, see how Gmail provides an undo option whenever we delete an email.
It would be very helpful.
Thanks.

**Comment by aurelien1986** [comment]
I do agree it would be so helpfull

**Comment by phillipthelen** [comment]
With potential item drops, exp/gold/health changes and other things happening when checking off a task, this is unfortunately quite a complex issue and task. Since we are a very small team and this request has also only very rarely come up, we unfortunately don't have the capacity to tackle this.
