### ISSUE TITLE
Use device settings for 24/12h correctly

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica-android#1682]
**Describe the bug**
User email: "Even though my smartphone is set to use an 24h clock and the correct times are for instance listed in the app settings, the due time select is only usable with am/pm time and the time is also only listed as am/pm. Please allow consistent usage of 24h times throughout the app."

**Expected behavior**
Consistent usage of 24h times throughout the app.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a
 - Android Version: 31
 - AppVersion: Version 3.4.1.1 (3090)

**Comment by yngwi** [comment]
Thank you for creating the issue, it was me that sent the original email. Feel free to ask if you want me to provide additional details.

**Comment by CuriousMagpie** [comment]
@yngwi, If you can share screenshots of exactly what you're seeing, that would be very helpful. Thanks!

**Comment by yngwi** [comment]
Hi,
I have included a screenshot of the Android app settings and the reminder time picker. The first one is in 24h time, the second one in AM/PM time.

I hope this helps.

Best,
Daniel

![Screenshot_20211223-212600.png](https://user-images.githubusercontent.com/963440/147288863-47f8d6bd-1ada-4c10-a95a-f4d0f1bf29ba.png)

![Screenshot_20211223-212632.png](https://user-images.githubusercontent.com/963440/147288876-1c2eec1c-a59f-4614-b785-30d2fa54ce6c.png)
