### ISSUE TITLE
Black screen when switching party view to chat screen

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica-android#1684]
User Report:

Device: samsung SM-G531BT Android Version: 22 AppVersion: Version 3.4.1.1 (3090) User ID: 0e0cd0b4-ace8-48f0-988e-4cfd457eed30 Level: 7 Class: warrior Is in Inn: false Uses Costume: false Custom Day Start: 0 Timezone Offset: 180 

Details: The party menu turns to a black screen after switching from the "Party" to the "Chat". The whole menu turns to black.

**Comment by Hafizzle** [comment]
This was potentially previously fixed - I've attempted to recreate this issue across multiple sdks on physical phones & emulators and have not been able to reproduce the issue. I'll be closing this for now but please feel free to reopen.
