### ISSUE TITLE
Invite a Friend Causes App to Close

### ISSUE THREAD

**Issue by creaturebytes** [HabitRPG/habitica-android#1690]
>Device: motorola Moto g(7) power
>Android Version: 29
>AppVersion: Version 3.5 (3202)
>BETA
>User ID: 38489527-1b3b-4a81-b032-ac6733930357
>Level: 42
>Class: warrior
>Is in Inn: false
>Uses Costume: true
>Custom Day Start: 0
>Timezone Offset: 480
>Details:
 "Good morning! When I try to "invite friends" to the party, my app force closes. Thanks for any help!"

**Comment by phillipthelen** [comment]
This is fixed in the latest beta
