### ISSUE TITLE
Marking messages as liked doesn't work

### ISSUE THREAD

**Issue by matheusvictor** [HabitRPG/habitica-android#1694]
**Describe the bug**

When I click to like a message anywhere (Tavern, Party or Guilds), the like count does not work. Instead, other options like "Reply" and "Report" appear when the message is extended.

**To Reproduce**
- Visit any public space and try to like a message posted by another user

**Expected behavior**
When liking a message, the like count button should be a different color and the counter will increase according to the number of likes.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A2 Lite
 - OS: Android 10
 - App Version: 3.5 (3205) - BETA
 - Habitica Username: @matheusvictor

**Comment by ShivanshGoel221B** [comment]
> **Describe the bug**
> 
> When I click to like a message anywhere (Tavern, Party or Guilds), the like count does not work. Instead, other options like "Reply" and "Report" appear when the message is extended.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> * Visit any public space and try to like a message posted by another user
> 
> **Expected behavior** When liking a message, the like count button should be a different color and the counter will increase according to the number of likes.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: Xiaomi Mi A2 Lite
> * OS: Android 10
> * App Version: 3.5 (3205) - BETA
> * Habitica Username: @matheusvictor

I figured that the like button is on the top-right corner, where the total likes are shown like +0, +1, ...
So, to like the message, you have to click that button. There is no chat expansion for the like button.

**Comment by matheusvictor** [comment]
Exactly, @ShivanshGoel221B. But, if u try follow the steps that I mentioned above, maybe you can see that isn't happening

**Comment by Nakonana** [comment]
Just adding some observations: 

Liking is possible, when opening the app, but only once. For liking another message, one has to (force) close the app, and re-open. This needs to be done after every like. 

It requires a few attempts to like a message. While clicking multiple times, sometimes the message below the to-be-liked message shows some reaction. (Maybe it's not the message below, but the next message by a contributor.) I'll try to add a screen recording of this. 

After having liked a message, the message below it becomes completely unresponsive (reply, copy, delete, report do not appear at the bottom). 


Device: Sony F5321
Android Version: 25
AppVersion: Version 3.5 (3205)
BETA
User ID: 33bb14bd-814d-40cb-98a4-7b76a752761c

**Comment by matheusvictor** [comment]
That's it, @Nakonana. Thank you for your attachment. Maybe it can be helpful

**Comment by ShivanshGoel221B** [comment]
All right, @matheusvictor @Nakonana  I see that, I am working on it right now

**Comment by Nakonana** [comment]
More observations:

It looks like it's working again, but it takes several attempts to Like a message. It doesn't register on the first click. 

Device: Sony F5321
Android Version: 25
AppVersion: Version 3.5.1.3 (3268)
BETA

**Comment by saraolson** [comment]
this should be fixed now. the tap target could still use some work to make it easier but it does like the post if you tap carefully.
