### ISSUE TITLE
Markdown code block displays trailing triple backtick

### ISSUE THREAD

**Issue by akirabaruah** [HabitRPG/habitica-android#1696]
Markdown code blocks include extraneous triple backticks (```) at the end of the block.

**To Reproduce**
1. Create a To Do Task.
2. Add a markdown code block with triple backticks to the Notes section.
3. View the Task in the Habitica Android app.

**Expected behavior**
The [Markdown Cheat Sheet](https://habitica.fandom.com/wiki/Markdown_Cheat_Sheet) on the Habitica wiki explains the expected behavior for this feature. The web UI shows expected behavior, where none of the backticks are rendered.

**Screenshots**

To Do Notes content:
![image](https://user-images.githubusercontent.com/6751517/150664339-1d2ce0c4-9bc4-43c9-90df-35b875480613.png)

Code block rendered in Android app:
![image](https://user-images.githubusercontent.com/6751517/150664329-fcf73fc6-2b87-42b9-8f01-5a3b47ab04df.png)

Code block rendered in web app:
![image](https://user-images.githubusercontent.com/6751517/150664480-7268f381-9109-49da-bb5b-c4d043ce5adf.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 12
 - App Version: 3.4.2 (3133)
 - Habitica Username: 

**Additional context**

**Comment by AKalinins** [comment]
It looks like this functionality works fine if you don't insert a line break after the triple backticks:
![image](https://user-images.githubusercontent.com/29925958/176414234-35743bae-8019-4f40-b91a-64f4d70ac465.png)

If you put a line break, that you can get the behavior described:
![image](https://user-images.githubusercontent.com/29925958/176414357-545a93d8-f7d7-4c24-a91d-172b0f155e4e.png)

So, I'm not sure this is actually a bug, it looks like just how Android works. Maybe I'm wrong though.

Also there is a disclaimer on the Markdown Cheat Sheet page:
Note that in the mobile apps, the formatting produced by Markdown (as shown in the table below) may not display as expected.
