### ISSUE TITLE
Habits, Dailies and To Dos not able to be checked off correctly in Hebrew

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica-android#1705]
**Describe the bug**
User Report

>  In Hebrew form, Habits list, clicking "minus" on a habit without a minus option, affects as a "positive" que.
> Again in Hebrew, To do and Dailies can't be ticked. 

**Smartphone (please complete the following information):**
 - samsung SM-G781B
- Android Version: 31
- AppVersion: Version 3.4.2 (3133)
 - UUID: 006887b0-944c-4173-b21f-2940e38b417c

**Comment by saraolson** [comment]
is this possibly because hebrew is a RTL language and the tap areas don't change appropriately to support that?

**Comment by ByeongsuPark** [comment]
Is this issue still occurs in recent version?

**Comment by saraolson** [comment]
after testing, im unable to reproduce this in the latest version. i'm going to close for now, but if anyone experiences this and can include steps to reproduce then please let us know and we'll reopen!
