### ISSUE TITLE
App not translating into Ukranian

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1724]
You can select Ukranian but the app stays in english

**Comment by saraolson** [comment]
Still seeing the app in english

**Comment by nazarparuna** [comment]
In version 3.6 app could successfully switches language. 
In version 4.0 you can select Ukrainian, but nothing happens. App's text still in English.

**Comment by Hafizzle** [comment]
Fixed:
https://github.com/HabitRPG/habitica-android/commit/266d618eba3ddd019af69e9d0e784725f2f93fa3
