### ISSUE TITLE
Chat expansion, deletion, and crash issues

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1738]
-In chat spaces, sometimes tapping a message won't properly expand options
-After deleting a message, the chat stream won't properly update until close and reopen
-Crashes sometimes when typing in a message with people tagged in it 

I'm assigning minor until we can reproduce or get more reports of this. can split this issue up if we'd like as well, lmk.

> Device: OnePlus ONEPLUS A6013
> Android Version: 30
> AppVersion: Version 3.5.1.3 (3267)
> User ID: 767e5d92-0e13-4e30-acb1-d8bba62824fc
> Level: 125
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 7
> Timezone Offset: -120
> Details:
> 
> Often, when I tap a message, it doesn't expand, meaning I can't see the report/delete/reply buttons at all. There is no rhyme or reason for which message this happens to. 
> 
> Frequently, the 'delete' button doesn't appear to work either - I tap a message to delete it, but it remains until I exit the app and open it again. If I try to delete the same message, I get a "message not found" notifications; if I try to interact with a different message, the app crashes.
> 
> When typing a message with people tagged in it, the app has begun to crash more often, meaning a lot of half finished messages are lost.

> Messages not expanding always happens after I've scrolled up some in a guild chat, but there's no logic to how far back I have to scroll before the bug is triggered. It also happens entirely randomly - if I tap one message and it doesn't expand, other messages still (generally) will.

> The deletion bug happens both with my own and others' messages.

> Crashes when tagging happen, to my recollection, when more than one person is tagged, but it makes no difference whether that's two or six people. I haven't noticed any patterns regarding line length.

**Comment by rilygreat** [comment]
> Device: Xiaomi Redmi 8A Dual
Android Version: 29
AppVersion: Version 3.5.2 (3310)
User ID: 7747905d-9592-441c-8e10-df377041a795
Level: 6
Class: warrior
Is in Inn: false
Uses Costume: false
Custom Day Start: 0
Timezone Offset: -330
Details:

> I don't know whether it is a big issue or not, but the message options and the Like button doesn't work in most of the chats at times. In order to get the message option (ie. Reply, Copy, report and delete) to work properly, we need to go to any other tabs (ie. Party tab, Items tab, Pets and mounts tab etc.) and come back to the chat, in order to make the options and likes working.
