### ISSUE TITLE
Sometimes Task screen is blank

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1766]
They don't have all the onboarding achievements so not only are tasks gone but the onboarding tasks block is as well. I reproduced it a few times on an account i newly made with google sigh in, selecting a few starter task categories. But the issue eventually went away and I can no longer reproduce.

I asked them to change their launch screen to To Do's, and after that To Do's loaded on launch, but if they tapped 'Habits', now that screen was blank instead. 

They also included that single tapping on the blank screen causes everything shows up, and
navigating to somewhere else and then going back to the blank screen causes everything to show up

> Device: samsung SM-G781U
> Android Version: 31
> AppVersion: Version 3.5.2 (3310)
> User ID: bce035d7-c556-4618-9cc0-03f26ab010e7
> Level: 1
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> Timezone Offset: 240
> Details:
> 
>  The to-dos screen appears blank when first opening the app. This only happens when clicking directly on the to-do tab. It doesn't happen when I swipe to the tab. 
> 
> Steps to reproduce:
> 1. Close app
> 2. Reopen app
> 3. Click on To Do's

<img width="366" alt="Screen Shot 2022-05-05 at 8 42 22 AM" src="https://user-images.githubusercontent.com/12453119/166926551-d34f48ab-e97d-43dd-949b-9c3953c5c520.png">

**Comment by saraolson** [comment]
> Device: samsung SM-A127F
> Android Version: 30
> AppVersion: Version 3.5.2 (3310)
> User ID: a8f74939-7163-41cf-80c2-292b3b54d109
> Level: 4
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: 240
> Details: The tasks list does not load when I click the task button. If I click a different tab, and then back in, then it will load.

**Comment by rilygreat** [comment]
> Device: samsung SM-G991U1
Android Version: 31
AppVersion: Version 3.5.2.1 (3318)
User ID: 0027ecbf-ffa2-4bfe-b2eb-d099ebd49bee
Level: 13
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 0
Timezone Offset: 420
Details: My "to do" list doesn't usually display the first time I navigate to that tab. I have to click into habits or dailies and then back to the to do for it to load.

**Comment by beffymaroo** [comment]
another user report:

Device: samsung SM-G975W
Android Version: 31
AppVersion: Version 3.5.2.1 (3318)
User ID: 5c00933e-ec2e-47b1-a8fb-e3c2ff314558
Level: 11
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 5
Timezone Offset: 360
Details:

Dailies and Habits tabs load correctly on first click, but to-do list does not. It is a blank list, that only populates once I drag down on it. This only happens once when setting up the app, so it's a very small bug, but still there.
