### ISSUE TITLE
Duplicate food entry in modal when feeding a pet

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica-android#1779]
> Device: Xiaomi Redmi Note 9 Pro
> Android Version: 30
> AppVersion: Versione 3.5.2.1 (3318)
> User ID: ea27bfc6-62a9-48e1-935c-35bd533d9236
> Level: 53
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> Timezone Offset: -120
> Details:
> 
> Hi, sometimes food discovered and notified immediately after completing a task often does not appear in the food ... it gets lost.
> 
> Now it looks like I had moldy meat, but if I tried to feed an animal it gave me a 'user food don't find' error message.

adding this one but not sure if it's the same thing or not:

> Device: samsung SM-A307FN
> Android Version: 30
> AppVersion: Version 3.5.2.1 (3318)
> User ID: 8ebe9a59-b269-43e4-b344-4e9e2d91556f
> Level: 55
> Class: wizard
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: -300
> Details:
> 
> In the last update, it said the repeating text for food items was fixed. However, I am still having this issue.
>
> It happens whenever there are random item drops of food, but not when i get food from the armoir - in not sure what happens with quests that award you with food, since I've never completed such a quest so far. 
> 
> For example, if I get fish as a part of random drops for completing tasks, when I go to feed a pet or open items > food immediately, then it shows that fish is there twice. After a while, it's not there. 
> 
> If I do tap the phantom fish, it will show a message like the one in the second screenshot.
![Screenshot_20220524-122759_Habitica](https://user-images.githubusercontent.com/102926641/170390196-43368dad-6be7-43f0-92e7-9c078d0d0da2.png)
![Screenshot_20220524-122656_Habitica](https://user-images.githubusercontent.com/102926641/170390207-8782824e-3d47-4c60-a6e4-c488498c5755.png)

**Comment by rilygreat** [comment]
> Device: Xiaomi MI 8 Lite
> Android Version: 28
> AppVersion: Version 3.5.4 (3528)
> User ID: 9df86c42-192e-487b-bb3f-3dcb7173571e
> Level: 7
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> Timezone Offset: 180
>
> Details: When I try to sell 1 Rotten Meat or feed it to one of my pets an error message is displayed.

**Comment by CuriousMagpie** [comment]
It's still happening:

>Just letting y'all know that sometimes food will appear twice even though I've only collected one of the item. It appears as a separate item, and doesn't increase the numerical value that shows quantity of food. Its been an issue for a while, but I noticed it didn't get fixed with the big recent update, so I figured I'd shoot you an email. 

Device: OnePlus OnePlus 9 Pro 5G
Android Version: 30
AppVersion: Version 4.0 (4320)
User ID: 15b71237-7796-4317-91c5-c0eb684a6ecf
Level: 45
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 3
Timezone Offset: 300

**Comment by saraolson** [comment]
should be fixed in 4.1.8
