### ISSUE TITLE
Strings have html entity instead of character

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica-android#1783]
**Describe the bug**
A clear and concise description of what the bug is. If your issue is not related to a specific bug, please submit it as a suggestion through our form: https://forms.gle/Fa6oztkDsbzLqSvE9

**To Reproduce**
Create a quest without sufficient gems.

**Expected behavior**
The error message would be rendered in characters and not as a mix of text and HTML entities.

**Screenshots**
![Screenshot_20220606-075134_Habitica](https://user-images.githubusercontent.com/78037386/172443113-130fb1f1-7dbc-495d-a8d0-de21e8b3caf6.jpg)

**Smartphone (please complete the following information):**
- Device: samsung SM-G950U
- Android Version: 28
- AppVersion: Version 3.5.2.1 (3318)
- User ID: 827f01c0-45dc-4b50-95b7-4f07471cc180

**Additional context**
There may be additional strings with html entities beyond this one.

**Comment by AKalinins** [comment]
I'll pick it up if you don't mind

**Comment by CuriousMagpie** [comment]
@saraolson @phillipthelen Is it okay if @AKalinins picks up this issue?

**Comment by AKalinins** [comment]
@CuriousMagpie I already did and created the PR https://github.com/HabitRPG/habitica-android/pull/1785
I don't know how to add reviewers, so if anyone can take a look at it that would be great (or close it if it's not ok :D)

**Comment by saraolson** [comment]
@AKalinins thanks for your help with this issue :) i've added this contribution to your Habitica profile and granted you a contributor tier! this fix will be out in the next release.

**Comment by AKalinins** [comment]
@saraolson Thanks =) Are fixes tested somehow before release?

**Comment by saraolson** [comment]
@AKalinins yup definitely. we have a staff alpha build, then we release a public beta that anyone can join from our play store page, then finally the update is released. right now we're in closed alpha, but public beta should be coming up soon.
