### ISSUE TITLE
Application doesn't respect selected week start day.

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica-android#1784]
**Describe the bug**
Android application doesn't respect week start day -- i.e., user would like week to start on Monday but app shows Tuesday and they cannot reset it.

**Screenshots**
![Screenshot_20220606_111919_com habitrpg android habitica](https://user-images.githubusercontent.com/78037386/172891019-4fe2d43b-1c5e-4b4a-a18b-0e75762d9cca.jpg)
**Smartphone (please complete the following information):**
- Device: HUAWEI YAL-L21
- Android Version: 29
- AppVersion: Version 3.5.2.1 (3318)
- User ID: 36976c15-5bcd-4197-965c-750d865abcd2

**Additional context**
User mainly uses the website, so doesn't know when this behavior began.

**Comment by saraolson** [comment]
i was also able to reproduce this. just try changing your day around a few times, it won't go well
