### ISSUE TITLE
Reset account message doesn't appear interactive

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica-android#1794]
**Describe the bug**
From user:
>I am trying to reset my account as I have picked up a bunch of tasks that I cannot delete due to no longer being a member of the challenge they came from, this is annoying enough in itself but then the reset button brings up a warning, well and good but there's no button on the warning to either clear it from the screen or proceed. So the reset button is literally just a warning that tells you why you might not want to. 

**Screenshots**
![Screenshot_20220705_131909_com habitrpg android habitica](https://user-images.githubusercontent.com/78037386/177597425-dc511522-34b6-46f3-b91c-27528e7280f3.jpg)

![Screenshot_20220705_131916_com habitrpg android habitica](https://user-images.githubusercontent.com/78037386/177597448-f0d1ab6c-97b1-40f0-90ea-6e85244ebb4b.jpg)

**Smartphone (please complete the following information):**
- Device: HUAWEI MRD-LX1
- Android Version: 28
- AppVersion: Version 3.5.4 (3528)
- User ID: 65438be3-fce0-487a-8f41-a59c5a4e2dc5

**Comment by saraolson** [comment]
this is because the button doesnt appear on screen and the modal doesnt account for scrolling. it will be fixed when we change to not using a modal in the next update.
