### ISSUE TITLE
habit widget not pinning on home screen

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica-android#1799]
> Device: motorola Moto g(50)
> Android Version: 31
> AppVersion: Version 3.5.4 (3528)
> User ID: a1807d79-6374-4cca-9918-e665b9064b1a
> Level: 54
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 3
> Timezone Offset: -60
> Details:
> 
>  Hello,
> 
> I have started using the widgets for my device which I am finding extremely useful. All widgets work except for the habits, when I drag it onto my homescreen it doesn't pin it just opens as if I have tapped it like the others, when I return to my homescreen the widget is gone.

https://user-images.githubusercontent.com/102926641/179274000-273ce5fa-fefb-4967-b75f-a4650aae0537.mp4

**Comment by saraolson** [comment]
for this, they have to select a habit from that list to add it to their home screen. the habit widget is for individual habits
