### ISSUE TITLE
Wrong value for string

### ISSUE THREAD

**Issue by anabeatrizzz** [HabitRPG/habitica-android#1803]
Value "task_container_name" needs to be a phrase in English, thus, Weblate translators can work with it.

https://github.com/HabitRPG/habitica-android/blob/1d1451093f9101c5fb86554c31ec78eb95b3531e/Habitica/res/values/strings.xml#L1218

**Comment by citrusella** [comment]
I wonder if there's a reason the string is this kind of text; as far as I can tell it's not used in any files in the entire repository except the string resource where it's defined. (I tried checking by opening it in Android Studio to double check, too, and I can't find it anywhere else.) Even the commit that added them doesn't make that specific string's purpose clearer: https://github.com/HabitRPG/habitica-android/commit/7a13395773dddc97c3970ead344205972257cb4e

**Comment by phillipthelen** [comment]
I'm not sure why this was created. I probably messed up a shortcut and made it accidentally. Will remove it.
