### ISSUE TITLE
Show confirmation screen after sending gifted gems from balance

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1816]
confirmation shows when you send through a purchase, but not from balance
<img width="264" alt="Screen Shot 2022-08-02 at 9 08 08 AM" src="https://user-images.githubusercontent.com/12453119/182382302-dbbd424d-64d4-42a7-90a7-bfe191fd6b17.png">

**Comment by Hafizzle** [comment]
Tested both purchase and from balance - I got both confirmations successfully.
