### ISSUE TITLE
inviting party members to quest causes crash

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica-android#1821]
> Device: Xiaomi MIX 2
> Android Version: 28
> AppVersion: Version 4.0 (4322)
> BETA
> User ID: 35c3fb6f-fb98-4bc3-b57a-ac01137d0847
> Level: 746
> Class: wizard
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 9
> Timezone Offset: 420
> 
> Details:
> Whenever I invite my party to a quest, it usually takes me 4-5 tries before I can successfully do it without the app crashing.

**Comment by saraolson** [comment]
couldn't reproduce, and haven't heard about it again. going to close unless its reported again. if same user reports, then we can reopen and ask for more details/a video
