### ISSUE TITLE
unable to use challenge filters

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica-android#1826]
> Device: samsung Galaxy S10e
> Android Version: 31
> AppVersion: Version 4.0 (4320)
> User ID: bb3e2512-b1a1-4a8c-9765-6e96d05998de
> Level: 1
> Class: healer
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 12
> Timezone Offset: 300
> Details:
> 
> Can't filter challenges on the app. Any changes i make to the filter immediately revert when i close the list or refresh or anything. I cant choose none or just to see the ones from guilds im in.

**Comment by saraolson** [comment]
do we want to just edit the filters so they match web's now? just have a bunch of check boxes, and if nothing is selected it shows 'all'?


![Image](https://user-images.githubusercontent.com/12453119/184654372-f6f6e2cf-2477-4c62-9347-0ef7a0927626.png)

**Comment by saraolson** [comment]
following up-- adding the new filters would require a lot more work on the challenge list itself to allow it to filter. so we're gonna put off those category filters until a later update
