### ISSUE TITLE
Widget!

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica-android#183]
We're getting lots of request for a widget!

**Comment by jonyeezs** [comment]
+1 be good to have a widget. so i don't have to keep opening up the app just to click on a habit or dailies

**Comment by goldfndr** [comment]
Some (most?) of this functionality is available via [tasker-habitrppg](https://github.com/goldfndr/tasker-habitrpg) (for those with [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm)).
