### ISSUE TITLE
4.0.1 crashes on opening

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica-android#1830]
**Describe the crash**
>I'm a beta tester, and the update just released has made the app unusable to me, as it immediately crashes when opening. Clearing the cache makes no difference and I can clear my data, but the moment I log back in the app crashes instantly. 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21 Ultra 5G
 - OS: Android 12
 - App Version: 4.0.1
 - Habitica Username: framedgeek / 817b2e53-8bbd-4be2-806b-970ead2854c1

**Additional context**
Checked the user in amplitude and there are multiple login events today with the only other event being logged today is cron.

**Comment by CuriousMagpie** [comment]
Another user has the same issue. They were able to roll back to 4.0 and use the app.

**Smartphone (please complete the following information):**
- Device: Samsung Galaxy S10 Lite
- OS: Android 12
- App Version: 4.0.1
- Habitica Username: DaveBlackngreen / 9cd99ef1-7faf-4fd1-a10c-dc1db1d6e0a6

**Comment by dikey0ficial** [comment]
Same error.
Smartphone (please complete the following information):

Device: Honor 8S 
OS: Android 9 (EMUI 9.1.0)
App Version: 4.0.1
Habitica Username: dikey0ficial / 241a33f3-9834-4770-bf86-fe5d3a2cfe00

**Comment by CuriousMagpie** [comment]
We're running a deploy for a fix. Thanks for all y'all's patience! 

In the meantime, here are the steps that framedgeek was able to use to get back up and running:

1. force stop
2. clear cache/data
3. uninstall the app
4. reboot my phone
5. install the non-beta version afresh
