### ISSUE TITLE
App often crashes when party tab is opened (4.0.1)

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica-android#1836]
user report:

Device: HUAWEI HUAWEI Mate 20 Pro
Android Version: 29
AppVersion: Version 4.0.1 (4382)
BETA
User ID: 0771ea46-31ed-4b79-ad21-ee79d1027a2d
Level: 87
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 0
Timezone Offset: -120
Details:

App keeps crashing when opening party tab. Not every time, but far too often.

**Comment by saraolson** [comment]
this crash is hard to find the cause of. phillip changed some stuff that may help, but not 100% cause we can't reproduce to test.
