### ISSUE TITLE
Task names appearing on incorrect task when switching between screens

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica-android#1839]
**Describe the bug**
Sometimes when switching from dailies to to-do etc, the task names will be on the wrong task. The task would have the name of one task and the description of a different task and the streak of that task. It will fix itself if I seitch between tabs again

**Smartphone (please complete the following information):**
- Device: samsung Galaxy M30
- Android Version: 29
- AppVersion: Version 4.0 (4320)
- User ID: f6b3cd97-7e7e-43a4-a131-56e3eecf1100

**Comment by rilygreat** [comment]
> Device: samsung A71
> Android Version: 31
> AppVersion: Version 4.0.1 (4460)
> User ID: 2181c410-ccf1-4aca-b6da-60f20e9c0c6e
> Level: 85
> Class: rogue
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> Timezone Offset: 360
> Details:
> 
> Hi There,
>Some of my daily tasks seem to replace the title with some other task 
> Ex. I have a task called "evening vitamins" and below in the notes have the vitamin yo take. I have a differen task called "floss". When I navigate to the daily tasks, evening vitamins is always "floss" with "iron supplement" in the notes below it, and floss still exists as it should as a different task.
