### ISSUE TITLE
Show current HP in decimals if it's under 1

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1842]
Right now if someone has 0.6 HP, android shows their hp as 0. They get confused wondering why they aren't running out of hp and getting reset to 50. In reality they haven't actually hit 0 HP yet. 

The decimal we show should be limited to the first number that isnt 0. ie if its 0.6, show that. if it's 0.06, show that.

**Comment by booker-lee** [comment]
I'd like to help with this issue, let me know if it is ok for me to take it.

**Comment by saraolson** [comment]
@booker-lee you're welcome to take this issue on! i've marked it as in progress for you. 

if anything comes up and you can't finish this issue, just let us know.

**Comment by booker-lee** [comment]
@saraolson I pushed a change for this one. One thing to note is that if the value is lower than 0.1 (ex: 0.06), this fix would display 0.1 as the minimum hp. I feel like it should be enough for users and we don't have to deal with display of extreme low value (some thing like 0.00000001). Let me know if there are any suggestion for this PR.

**Comment by saraolson** [comment]
@booker-lee that sounds good to me! our developer will reach out after he's had a chance to review if he has any suggestions
