### ISSUE TITLE
Deselecting daily item doesn't decrement count

### ISSUE THREAD

**Issue by ajmeese7** [HabitRPG/habitica-android#1845]
**Describe the bug**
Whenever a daily item is mistakenly selected and the user unchecks the box, the awarded XP  and gold are revoked. However the daily counter is not decremented back to the precious number and awarded items remain in the user's inventory.

The counter is an easy fix, but I'm not sure how the items would best be handled. A user could easily go use the item once it has been assigned and then uncheck the daily, which would be an unfortunate situation. My thoughts are that the desired behavior should be removing the assigned item if it is still in the user's inventory and silently failing if the item has already been consumed, but obviously that's your call.

**To Reproduce**
1. Create a daily task
2. Check the daily task for the day
3. Uncheck the daily task
4. Observe that the counter has not decremented back to the original value of 0, but remains at 1

**Expected behavior**
The count should be decremented to the precious value, and any awarded items should be deleted if possible.

**Smartphone (please complete the following information):**
 - Device: [e.g. Moto G5] Google Pixel 6 Pro
 - OS: [e.g. Android 9] Android 12
 - App Version: [e.g. 2.2] 4.0.1
 - Habitica Username: ajmeese7

**Comment by saraolson** [comment]
the streak not going down is a bug, the items staying is a known behavior we've accepted across platforms.

for many of our features we lean towards the honor system and being more generous than destructive. since there's no real way to consistently guarantee the shade potion in their inventory is the one they just received, we simply leave that to the user to use or sell if they happened to get an item on an accidental tap.

**Comment by ajmeese7** [comment]
It looks like this should be handled in `habitica-android/wearos/src/main/java/com/habitrpg/wearos/habitica/data/repositories/TaskRepository.kt` on line 50:

```kotlin
task.streak = task.streak?.minus(1) ?: 0
```

I was going to try to handle this myself, but I'm not familiar enough with the codebase or with Kotlin to know exactly why this line is not functioning as intended. Hopefully this helps someone else solve the issue.

**Comment by saraolson** [comment]
@kouki4416 made a PR for this, https://github.com/HabitRPG/habitica-android/pull/1857
