### ISSUE TITLE
Reminders for Dailies that were completed the previous day not appearing

### ISSUE THREAD

**Issue by aaaaamir** [HabitRPG/habitica-android#1849]
**Describe the bug**

When assigning a notification / reminder time to a daily task, I don't find it showing up on my notifications. The general "daily reminder" that I enabled through the settings still shows up but none of the one connected to individual tasks that I've made show up, which I prefer so I can individually check them off.

This is on latest 4.x, I know there were changes to reminders in that release. Also I've made sure to allow habitica unrestricted access to battery power in the android settings. Also made sure to enable notifications on web and on android both. Not sure if other changes in settings could be blocking this?

**To Reproduce**

Add a reminder to fire off at some time every day on a daily task, example, 9am

**Expected behavior**

at 9am, reminder should go off for that specific daily task

**Smartphone (please complete the following information):**
 - Device: pixel 4a
 - OS: Android 13 .. Was occurring for me on Android 12 as well. 13 build number is `TP1A.220624.014`
 - App Version: 4.0.1
 - Habitica Username: N/A

**Comment by rilygreat** [comment]
> A new bug report from @Cospita
> 
> Hi! I downloaded the app and everything works fine. Sadly, I am not getting any notifications that remember me to actually do my dailies or anything at all [...]. this is happening on an android 11 phone. I got notifications the first day, then it just stopped for all dailies I entered. If I open the app, they still show up [...].

reminders don't seem to be sending if the task was done the day before and the app hasnt been opened on the new day.

**Comment by aaaaamir** [comment]
Settings for the daily task in question https://imgur.com/a/06NggOD

**Comment by saraolson** [comment]
@aaaaamir every time you open the app it should schedule the reminder for a few days out, i believe 7? so in most cases this shouldnt be an issue. 

we did have an issue for reminders not showing up if the task was done the previous day, but that was supposed to have been fixed. seems like it's come back up with this.

i'll change the title to reflect that use case specifically and our devs will take another look.

**Comment by aaaaamir** [comment]
Awesome! Thanks so much

> we did have an issue for reminders not showing up if the task was done the previous day, but that was supposed to have been fixed. seems like it's come back up with this.

Ah is that in 4.0.2? The google play store doesn't seem to allow me to choose the version to install, do I have to use the portable apk and sideload? Or will that latest release be effective in play store for pixel 4a soon!

**Comment by saraolson** [comment]
@aaaaamir nah the fix was in a previous version, we'll do some investigation on why it's come back up and have to fix in a future release. we've been having some back and forth bug fixing with edge cases around reminders that may have caused it to come back.

you can try 4.02, but it's likely still there. That version's at 30% rollout right now, but should be available for all beta testers

**Comment by aaaaamir** [comment]
Got it, okay will hang tight 

Perhaps need some tweaks to this PR

**Comment by saraolson** [comment]
@aaaaamir for testing purposes, can you let us know your day start time from settings? is it midnight, or adjusted to a later time?

**Comment by aaaaamir** [comment]
Yep it is default (12:00AM)

**Comment by rilygreat** [comment]
> Device: Xiaomi Mi 9T
> Android Version: 30
> AppVersion: Версия 4.0.1 (4460)
> User ID: 1b56c5c1-6872-456e-872e-5ce46219df84
> Level: 132
> Class: warrior
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 8
> Timezone Offset: -420
> Details:
> 
> Hello. Reminders of daily tasks have not been working for a long time. Therefore I forget to perform these tasks. [...] Once after setting the alarm, the reminder is triggered and does not work anymore afterwards.
