### ISSUE TITLE
avatar not displaying in chat in portrait mode on galaxy fold 4 device

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica-android#1852]
> Device: samsung q4q
> Android Version: 32
> AppVersion: Version 4.02 (4510)
> User ID: 60f0b550-62c7-49cc-85d4-30b732badae8
> Level: 82
> Class: wizard
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: -120
> Details:
> 
> Hello,
> 
> On my slim front screen of my Galaxy Fold 4, avatars in chats are not shown in portrait mode. When I switch to landscape mode, they are shown.

**Comment by phillipthelen** [comment]
This is not a big. A stars are intentionally not shown on screens with a small width, to leave enough screen width for the text
