### ISSUE TITLE
Mana dropping by ~25% despite Perfect Day buff

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica-android#1858]
**Describe the bug**
User: 
>My mana keeps decreasing even though I'm hitting all (or nearly all) of my dailies. I have no to-dos. I hit all my dailies, go to sleep, and when I wake up I have lost a quarter of my mana.

**To Reproduce**
We checked the user's profile in the database and they have the Perfect Day buff, so should not be seeing a significant decrease in mana day over day. They are not resting in the Tavern, not in a party (so no buffs from other users to wear off), and have been completing nearly all their dailies. They're a long-time user and have never seen this sort of behavior from the app before. 

When trying to replicate this issue locally on the web, we discovered that despite completing all the test user's tasks, the test user lost their Perfect Day buff. Note that we ensured that the test user was the same class, level, and had all the same gear equipped, as well as matching stat points. We manually set the test user to have a Perfect Day buff, completed tasks, and then added one missing day using the Debug Menu--and lost the Perfect Day buff and have not been able to regain it. 

**Expected behavior**
Perfect Day buff should be consistently applied.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5
 - OS: Android 32
 - App Version: 4.02 (4510)
 - Habitica UUID: 22d78f64-452f-4a4e-a5b1-2d3e4baee13b 

**Additional context**
User reports that she did not lose any mana today.

**Comment by saraolson** [comment]
looking at their amplitude crons, they missed dailies on sept 19, 17, 16, and 14? If we were able to replicate it on web, then wouldn't it be a server issue?
