### ISSUE TITLE
Version 4.0.4 crashed on Android

### ISSUE THREAD

**Issue by leoossa** [HabitRPG/habitica-android#1869]
**Describe the crash**
After update the app crashes (everytime) just after opening the 'Dailies' screen. Reinstall didn't help. 4.0.3 (via apkmirror) works fine.

**To Reproduce**
Update to 4.0.4. Open the app.

**Smartphone (please complete the following information):**
 - Device: Poco F3
 - OS: Android 11 (e_alioth-userdebug 11 RQ3A.211001.001) - /e/ os
 - App Version: 4.0.4
 - Habitica Username: Ns6ifbeV7ML2

**Comment by saraolson** [comment]
was able to find crash logs on firebase for this so we'll look into a fix for an update soon

**Comment by leoossa** [comment]
@saraolson it's not fixed yet. I am forced to use old version. Any updates?

**Comment by saraolson** [comment]
@leoossa have you been able to update to the latest version 4.1.5, through the google play store? this should be fixed in that version. the crash i see you last had on 4.1.1 shouldn't be happening anymore, but if it does after updating please let us know.

**Comment by leoossa** [comment]
@saraolson 
Yes, now it does work with new version 4.15.
Thank you
