### ISSUE TITLE
filters reset upon opening + closing app

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica-android#1878]
report from @iohannes_bononiensis:
> I wanted to report that the filters in the Dailies section always turn off.
> 
> Specifically, I have to manually filter out the dailies that are not active/due in the current day, this happens multiple times a day, even within a few mins since I last used the app.

user's app version: 4.0.4. also tested it on 4.0.5 (4679) and all/due/grey filters revert back to "due" after restarting the app.

**Comment by saraolson** [comment]
this is just how android filters work. can tell them to go into settings and select the 'default to due dailies' setting
