### ISSUE TITLE
App won't open

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica-android#1881]
From user:
>Hello! I've been trying to open the Habitica App for a few weeks and it just doesn't open. I already cleaned data, unistalled and installed it again many times and it's still not working. I'm using the web version instead of the app because the app isn't working. Please help me fix it!

**Smartphone (please complete the following information):**
 - Device: Redmi Note 8
 - OS: Android 10
 - App Version: most recent
 - Habitica Username: @kaduvictorg

![Screenshot_2022-11-23-13-42-37-701_com android settings](https://user-images.githubusercontent.com/78037386/203611991-7c88f215-d0e5-41ed-ac7b-dd6db49cb5c1.jpg)

**Comment by saraolson** [comment]
going to close this. looked up their UUID and found a crash related to alarms that we're already working on.
