### ISSUE TITLE
rearranging tags on web does not sync to app

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica-android#1885]
> UUID | 50a038f1-d7d2-4828-b796-6757f139556f
> User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
> A new bug report from @SorbieTower
> Hello! I'm having issues with re-arranging tags. Issue #1: I can only re-order tags via the website. There appears to be no option to re-arrange them on the mobile (Android) app. Issue #2: When I re-arrange my tags on the website, my changes refuse to sync to the Android app. I've tried refreshing the website and the app, force-stopping the app, uninstalling the app, and re-starting my phone. Currently, none of these actions have resulted in the app showing the changes I made to the tag order on the website. Thanks for your help!

**Comment by michue** [comment]
I would like to tackle this issue, but I'm new to Habitica and might take some time.

Is that okay with you?

**Comment by michue** [comment]
Probably related to #1669

**Comment by michue** [comment]
Hello @saraolson,
can I have a feedback if it is okay for me to work on this issue?

**Comment by saraolson** [comment]
@michue thanks for your patience! i've marked this issue as in progress for you. if you're able to fix this and find the fix also solves #1669, let us know and we'll be sure to test and close both issues accordingly. thanks!! :D
