### ISSUE TITLE
Equipment and Stats not appearing

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica-android#1887]
> Device: Xiaomi Redmi  Note  7
> Android Version: 29
> AppVersion: Версия 4.0.5 (4762)
> BETA
> User ID: bdb06384-80ad-47ce-8449-7d526eaf2192
> Level: 88
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 2
> Timezone Offset: -120
> 
> Equipment symbols and stats not showing

![Screenshot_2022-12-15-22-47-14-459_com habitrpg android habitica](https://user-images.githubusercontent.com/78037386/208157742-358617d5-ea34-4537-9d4f-9a6c20585d63.jpg)

**Comment by saraolson** [comment]
this may actually be related to another issue we had where user data wasnt properly loading in profiles (like hp/exp/level). gonna close this unless its reported again after 4.1 is out.
