### ISSUE TITLE
date format in task view not syncing from web to android app

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica-android#1913]
Device: Xiaomi MI CC 9
Android Version: 30
AppVersion: Version 4.0.5 (4760)
User ID: 40f94655-5282-481e-a693-48852bd3a3cf
Level: 21
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 0
Timezone Offset: -660
Details: 

Regardless of my setting on the Web, the date format is wrong on my device. It is using US date format when it should be dd/mm/yyyy [...] The issue occurs in task view and the task itself.
![Screenshot_2023-01-19-05-53-39-060_com habitrpg android habitica](https://user-images.githubusercontent.com/102926641/213278150-54f8778a-b2cb-4b06-bff3-0620f9f5bc18.jpg)

**Comment by danielgomezrico** [comment]
@rilygreat can you share, what setting do you mean? I didn't know that you can set your preferred date formats
