### ISSUE TITLE
markdown not formatting correctly

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica-android#1923]
> AppVersion: Version 4.1.5
> UUID: 96ff3029-60cb-4e9a-beaf-fcd95d518e81
> 
> A new bug report from @LadySam:
> In the new Android app update, formatting using the backtick symbol (`Example`) in tasks doesn't show up anymore, neither in the task titles nor in task descriptions. Likewise, formatting using the tilde symbol (~~Example~~) doesn't show up in task titles or descriptions.

**Comment by saraolson** [comment]
will be fixed in 4.1.6
