### ISSUE TITLE
rotating device causes various problems, including crashes

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#193]
various reports from different people:
- [ ] "In the tasks view, the currently selected tab (habit, daily, etc) will reset to the default tab when the phone if rotated.
  Expected behavior: rotating the phone horizontal should not affect selected tab."
  -- https://mail.google.com/mail/u/0/#inbox/1518f242f1c30a5f
- [ ] "When I rotate my device from landscape to portrait or vice versa, Habitica crashes. It seems to happen only when I'm in the "Party","Tavern", etc. page. It does not happen in "Tasks" page (the main page Habitica loads in). My device is Samsung Galaxy Note 12.2 SM-P900 with (stock) Android 5.0.2." -- https://mail.google.com/mail/u/0/#inbox/1518fd7337f970c9
- [ ] Rotation while on the party screen causes a crash on a Droid Turbo running Android 5.1, Lollipop ("Unfortunately, Habitica has stopped.") -- https://github.com/HabitRPG/habitrpg/issues/6366
- [ ] Rotation while on the party screen causes a crash on a GT-S5301B with Android 4.0.4 -- https://mail.google.com/mail/u/0/#inbox/15195e2eb4ab64b9

**Comment by AlbRoehm** [comment]
Could be closed too? There is no landscape available at the moment?

**Comment by saraolson** [comment]
The issues still exist, which is why landscape has been disabled for the time being, so keeping this open.

**Comment by phillipthelen** [comment]
The app has been running for a few weeks in production without issues, so this seems to be resolved.
