### ISSUE TITLE
cannot use typing option when adding new task on wearOS device

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica-android#1967]
05/12 Fiz: https://github.com/HabitRPG/habitica-android/pull/1973
_________

to reproduce:
> 1. tap on the "new task" option
> 2. tap "task title..."
> 3. tap on the keyboard icon 
> 4. option for voice command appears

**Comment by saraolson** [comment]
problem here was a change in WearOS UX on a system level. it would remember the last keyboard you used and choose that over the manual option. we took out the option step to follow that behavior. 

you can use the lil tab at the bottom of the watch screen to switch input methods if the one that comes up isnt the one you want now.
