### ISSUE TITLE
Copy as Task from Group Chat

### ISSUE THREAD

**Issue by nonperforming** [HabitRPG/habitica-android#1983]
There is no such button on mobile (Android/iOS), only in Web.
(This is not the Copy Text from chat button)

Related image on Web: ![image](https://github.com/HabitRPG/habitica-android/assets/43197300/80d7d060-1c45-4aa8-be44-54140b25491f)

**Comment by saraolson** [comment]
Hi there! This isn't a feature we plan to support on the mobile devices.
