### ISSUE TITLE
accept party invite button cut off due to screen/text size

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica-android#1991]
> Device: OnePlus OnePlus 8T
> Android Version: 33
> AppVersion: Version 4.2.1 (6111)
> User ID: 940b6c9d-685f-4858-a9ff-6976e6c7561b
> Level: 3
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> Timezone Offset: 240
> Details:
> 
>  I can't join the party, the button won't select the green arrow.
> ![Screenshot_2023-05-27-14-13-15-52_d3b8fcda37c80214ab0c31f986be6207](https://github.com/HabitRPG/habitica-android/assets/102926641/f1ad37de-4f59-4978-8cd0-a30cd3cb8b69)

**Comment by saraolson** [comment]
should be fixed in 4.2.3
