### ISSUE TITLE
markdown: hyperlinks on tasks do not work when using line breaks

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica-android#1995]
Device: motorola motorola edge 30
Android Version: 31
AppVersion: Version 4.2.1 (6111)
User ID: 7b7f06fe-b915-428b-9d27-ebc92543402a
Level: 7
Class: warrior
Is in Inn: false
Uses Costume: true
Custom Day Start: 7
Timezone Offset: 180
Details:

 Hyperlinks on tasks do not work inside bullet points, instead the description and the raw
 link show instead. (Mobile only) , works just fine on pc desktop
![Screenshot_20230613-141719-849](https://github.com/HabitRPG/habitica-android/assets/102926641/dc1163a2-edd6-4f74-9c1d-efaad7dd8ab8)
![Screenshot_20230613-141807-243](https://github.com/HabitRPG/habitica-android/assets/102926641/542e5e19-04e3-48eb-8bd6-e29d31d966f5)

**Comment by lightproof** [comment]
Multi-line markdown in general seems to be broken. If you have only one line, it works. if more than one, it shows as syntax instead.

#### One line example (works properly):
Input:
Click \*\*once\*\* if done.

Displayed as:
Click **once** if done.

#### Multi-line example (broken):
Input:
Click \*\*once\*\* if done.
Click \*\*twice\*\* if done on time!

Displayed as:
Click \*\*once\*\* if done.
Click \*\*twice\*\* if done on time!

Should be:
Click **once** if done.
Click **twice** if done on time!

**Comment by saraolson** [comment]
should be fixed in 4.2.3
