### ISSUE TITLE
Version mismatch between github release and google play store

### ISSUE THREAD

**Issue by sereksim** [HabitRPG/habitica-android#2014]
[In the Google Play Store](https://play.google.com/store/apps/details?id=com.habitrpg.android.habitica)  the current version of habitica is 4.2.2 (updated on June 12, 2023) whereas the last Version released [here on Github](https://github.com/HabitRPG/habitica-android/releases)  is 4.0.2 and was updated on Sep 2, 2022

**Comment by Hafizzle** [comment]
Hey @sereksim -

T hank you for bringing this to our attention! While we do aim to keep our GitHub releases updated, not every update made available on the Google Play Store will have a corresponding release here on GitHub.

However, we ensure that each significant milestone (like version 4.2) is represented on GitHub. For minor version updates (like 4.2.3), these may not be included separately, but rest assured that these changes are folded into the milestone releases.

Your understanding is appreciated, and thank you again for your feedback!
