### ISSUE TITLE
Checklist text should line up with task title text

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#2041]
in the task list view, the checklist text is closer to the colored task tap area than the task title. this text should have the same spacing so it all lines up

<img width="420" alt="Screenshot 2023-10-27 at 11 56 04 AM" src="https://github.com/HabitRPG/habitica-android/assets/12453119/e2bff2d1-56f8-4120-851a-0d5cb769629f">

**Comment by jsoberg** [comment]
Added a PR to fix this: https://github.com/HabitRPG/habitica-android/pull/2050
