### ISSUE TITLE
Delete task confirmation button should always been Maroon100

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#2042]
Right now the delete task button that shows in the confirmation modal is themed to the task color. Since it's confirming a destructive action, we should make it always show as Maroon100. The 'cancel' option can stay themed.

**Comment by arjun1194** [comment]
can i pick this up ??
@saraolson

**Comment by arjun1194** [comment]
Also i saw that destructive buttons are themed to be with a "Red" background. are you sure you want it to be "Maroon_100" ?

**Comment by arjun1194** [comment]
Hey, thanks for your response. I am interested to pick this up


Just to confirm, All the destructive buttons should be maroon100 right ?

**Comment by arjun1194** [comment]
https://github.com/HabitRPG/habitica-android/pull/2063
