### ISSUE TITLE
Rewards filters shouldn't show 'all/weak/strong'

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#2043]
Rewards filters should be 'all/custom/wishlist' where custom only shows rewards you created, and wishlist only shows rewards that are pinned.

if we can't separate the custom from the wishlist, fallback option would be to not show any options at all in that category, and only show tag filters for rewards.

**Comment by jsoberg** [comment]
Hey all! I added a PR [here](https://github.com/HabitRPG/habitica-android/pull/2053) to address this issue. I noticed that we're intentionally trying to hide the filter option in the Rewards tab, so I just fixed the situational bug that caused it to appear the first time you open the tab - if we wanted to actually make a filtering bottom sheet for Rewards it'd be additional work, but this can fix the minor bug in the meantime.
