### ISSUE TITLE
Show item description for Quest bundles and transformation items

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#2044]
right now if you look at a quest bundle, the description that tells you which quests are included isn't visible. just the title, ie 'Sandy Sidekicks Quest Bundle' with nothin below. similarly, transformation items just list their title, ie 'Spooky Sparkles'

on web the description for the example quest bundle is:
> Contains 'The Indulgent Armadillo', 'The Serpent of Distraction', and 'The Icy Arachnid'. Available until October 31, 2023.

and for spooky sparkles:
> Turn your friend into a transparent pal!

**Comment by EanLombardo** [comment]
Is this still a problem. I can't recreate this in the current app.
