### ISSUE TITLE
markdown on tasks do not work when using line breaks

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica-android#2049]
> Device: samsung Galaxy S8
> Android Version: 28
> AppVersion: Version 4.3 (6731)
> User ID: ca543acf-fc03-480d-a0c4-27a12670f5d0
> Level: 113
> Class: healer
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 3
> Timezone Offset: -60
> Details:
> 
> Hello!
> I found a small bug, nothing serious but I use/rely on this function a lot so I thought I'd report it.
> 
> Basically the formatting doesn't work properly on my app. I've attached some screenshots to explain myself better.
> Take picture 1: I'm trying to create a task where the description has text both in italic and in bold. When I save it, the result is as shown in picture 2.
>
> If I try to use only one formatting at a time, however, both work fine, as shown in picture 3 and 4.
>
> ![1](https://github.com/HabitRPG/habitica-android/assets/102926641/4cbdfd44-f290-4cc8-a3de-cf8479e72995)
> ![2](https://github.com/HabitRPG/habitica-android/assets/102926641/60ba14e7-dc37-48e7-9ab0-cb0972c36eed)
> ![3](https://github.com/HabitRPG/habitica-android/assets/102926641/bfb54074-3c69-4f9d-b029-f114de96c3d4)
> ![4](https://github.com/HabitRPG/habitica-android/assets/102926641/469eedbf-ea1e-4bcf-be98-c2ab47793c6a)

**Comment by EanLombardo** [comment]
Can I take this on, I was digging through the markdown code today and I think this is due to a small oversight with regexes that is trivial to fix.
