### ISSUE TITLE
gold balance is hard to find when scrolling through Rewards

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#205]
A user reported that they couldn't see their gold balance while looking at their Rewards, so I explained how to unhide the full header. It's not very obvious that you can do this, so perhaps showing gold more clearly when viewing Rewards would help? Although you'd still want to hide most of the header as now to regain screen space.

**Comment by saraolson** [comment]
With all the rewards changes, I'm gonna close this issue to see if we still get complaints (especially now that we show balance before buying equipment)
