### ISSUE TITLE
Help text says 'Email' in the text box when trying to edit your Display Name

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#2058]
This help text should be 'Display Name', not 'Email'.

To reproduce:
1. Open Settings
2. Tap My Account
3. Tap Display Name

**Comment by rehfeld13** [comment]
Hi Sara, I saw the error and will create a branch to fix it, thanks for reporting!

![image](https://github.com/HabitRPG/habitica-android/assets/88861731/8fc4b8e2-f59b-46cb-801a-a4dbda404493)

**Comment by rehfeld13** [comment]
Here is the pull request for this issue: https://github.com/HabitRPG/habitica-android/pull/2060
