### ISSUE TITLE
Feature request about additional Tasks categories

### ISSUE THREAD

**Issue by Banzaika** [HabitRPG/habitica-android#2073]
Hi, add additional Tasks categories except power, body shape, intellect, perception!

**Comment by rilygreat** [comment]
@Banzaika hi there, we keep the gitub limited to bugs and issues within the app. you can submit any feature requests you may have here: https://docs.google.com/forms/d/e/1FAIpQLScPhrwq_7P1C6PTrI3lbvTsvqGyTNnGzp1ugi1Ml0PFee_p5g/viewform?usp=sf_link

you can create custom tags to categorize your tasks to fit your needs through filters :)
