### ISSUE TITLE
Skills screen is blank, intermittently

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#217]
Sometimes, the Skills screen shows the header but nothing but white where the skills should be listed. You can stay on that screen for a while and it doesn't change. If you go away and come back later, the skills sometimes appear.

Noticed by Alys, redphoenix, and Poline the Wise (phone is a Huawei Y511-U30, Android is 4.2.2, UUID 472d5667-3ebf-4414-af1c-10af2339117c).

**Comment by Alys** [comment]
Skills screen has been blank since I installed version 0.0.23 a couple of hours ago, for two different accounts. I forced-stopped the app, logged out a couple of times, moved back and forth between screens, all without anything appearing in the body of the Skills screen (the header is normal though).

Let me know if there's anything you want me to try.

**Comment by Alys** [comment]
Skills are back so it's still intermittent, not permanent.

**Comment by negue** [comment]
Haven't had this bug for a while now, @Alys does it still happen to you ?

**Comment by Alys** [comment]
Heh, it's just happened now when I went to test it. :) I quit the app and went back in and it was still happening. Logged out and back in and still blank.

It's still intermittent though - I've used skills on the app before.
