### ISSUE TITLE
Health potion appears in the middle of the equipment / gear to buy in Rewards column

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#232]
The Health Potion appears in between equipment, rather than above or below all gear. I've rebirthed recently so I have a lot of gear showing up. This might not occur when fewer items are for sale.

There doesn't seem to be any pattern to it. For example, even though the image below shows only Armoire items below the potion, there are also Armoire items further above.

![screenshot_2015-12-12-07-51-00](https://cloud.githubusercontent.com/assets/1495809/11764946/84ceb988-a191-11e5-8994-84f3f877b7e5.png)

**Comment by AlbRoehm** [comment]
I looked into the rewards fragment a while ago when i was trying to find out why one could not move own created rewards #627. I got a idea of how the page is created but could not fix it at that time. My thoughts on both this issue and #627 are to create multiple sections in the rewards fragment which display the different categories separately like: Own-created rewards first and movable, then buy-able equipment and last potion and enchanted armour. (or whatever categories there are in the backend).
