### ISSUE TITLE
Dailies don't get updated after editing, Refresh of the interface doesn't seem to get updated.

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#237]
_From [email](https://mail.google.com/mail/u/0/#inbox/151965735ec0eb46):_

The Dailies don't get updated after editing!

Refresh of the interface doesn't seem to get updated.

About the Dailies editing issue, whenever I tried to edit existing Dailies I faced this issue on the app, I only edited the Daily texts and extra notes sections, another thing I added were emojis along with the Daily names to add to the RPG feel! :D
Also the updates didn't appear even after the sync!

I use a Motorola MotoG 1st Gen 2014  model, and run the stock Android 5.1 Lollipop OS!

_User ID: 74d084c9-2df3-41ce-8fb9-60dc327e75cc_

**Comment by negue** [comment]
can't reproduce this :/

**Comment by caroldeabreu** [comment]
This is happening to me too ):
