### ISSUE TITLE
Widget does not show avatar or update stats

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#244]
The widget can be installed (was it meant to be disabled for now?) but it shows the Habitica logo instead of your avatar. 

A user has also reported that the stats don't update although I can't replicate that. I can get more information from the user if the widget is meant to be used, otherwise I'll tell them that it's a bug that it's currently available.

**Comment by nishchalchandna** [comment]
I am seeing this issue on Android 9 on my Pixel 3. Stats widget is empty, no avatar, no stats nothing. Any pointers if this is a known issue?

**Comment by safijari** [comment]
I'm seeing the same
