### ISSUE TITLE
Implement MVP architectural pattern

### ISSUE THREAD

**Issue by ianrumac** [HabitRPG/habitica-android#261]
Hey guys,
it would be quite better if this project used a standard architectural pattern a lot of people are familiar with like MVP (Model-View-Presenter). This would enable more people to easily join in, make the project easier to maintain  and separate business logic, data fetching and view manipulation, which in the end would make for easier test writing and would reduce dependency on EventBus. Now, I'm not sure how many people are comfortable and/or familiar with RxJava and Retrolambda, so simple callbacks and listeners could be used and later on it can be easily refactored to use reactive patterns.

Would love to hear your opinions on this, since it's best and easiest to start this way as soon as possible in the project.

**Comment by negue** [comment]
I'm currently not that familiar with RxJava or Retrolamdba (but I really need some lambdas :+1:  xD)

As for EventBus it really helped us to get some commands / events between those many classes `without having a method in Class  A, which calls Class B method, which do the same for Class C until it finally reaches Class D `

**Comment by AlgoRyan** [comment]
I would be interested in doing some refactoring to implement an MVP patttern, if people are still keen for this to happen.

**Comment by vIiRuS** [comment]
We are still interested in implementing a proper architecture in the app and have actually started working on this. I will update this with details as soon as we are at a point, where contributor help is useful!

**Comment by jjbillings** [comment]
Definitely interested in helping out with this!
