### ISSUE TITLE
Memory leaks abound in the app

### ISSUE THREAD

**Issue by dlew** [HabitRPG/habitica-android#287]
I tried installing [LeakCanary](https://github.com/square/leakcanary) to see what sort of memory leaks were occurring and found a whole ton of them. See what I got done before giving up: https://github.com/dlew/habitrpg-android/tree/dlew/memory-leaks

(I could submit this as a PR, but it won't help much since `MainActivity` will still leak all the time.)

There seems to be some fundamental issues with memory retention in the app that may require a more thorough re-examining of architecture. For example, `EventBus.register()` must be matched by a subsequent `EventBus.unregister()`, otherwise the object is leaked forever. I'm not sure I want to tackle this without knowing more of what you have in mind for `EventBus` (or the use of statics).

**Comment by vIiRuS** [comment]
Thanks for bringing this to our attention! As to not lose the work you already did, a PR with the existing commits would be handy. I will then investigate the issue further.

**Comment by christopherfowers** [comment]
What is the status of this? The pasted link is broken now. If like to start looking into this issue to see what I can contribute. Has there been any recent analysis done? Just trying to not duplicate work here.

**Comment by saraolson** [comment]
Since a lot has changed since this issue, we're gonna close it and if any memory leaks are still happening, let a new issue be opened with more specific details.
