### ISSUE TITLE
More filter options for tasks

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitica-android#372]
Same as on the website
1. Habits: All, Positive, Negative
2. Dailies: All, Due, Gray
3. To-Dos: Active, Dated, Done

**Comment by JacobFrericks** [comment]
I'm really interested in the Dailies "Due" filter. I have many repeating tasks for each day of the week, so I need to scroll for the active ones. I would also like to see some way of making the option a default.

**Comment by vIiRuS** [comment]
This is being worked on in #531

**Comment by JacobFrericks** [comment]
Perfect, thank you for the update!

**Comment by Alys** [comment]
Update: This appears to not have anyone currently working on it but there are useful comments in these two closed PRs, which any coder wanting to work on this issue should look through: https://github.com/HabitRPG/habitica-android/pull/438  https://github.com/HabitRPG/habitica-android/pull/53

Josh Miller has expressed interest in working on this in [this Trello card](https://trello.com/c/nytaY3gn/117-sorting-tasks-convert-item-type-by-drag-drop-sort-tasks-sort-columns)

**Comment by joshmiller17** [comment]
Hi Alys. I'm interested in adding this feature, but on second thought I don't think I'm ready yet. I'm going to explore the code a bit on my local repo before taking on a quest of this magnitude. Hopefully I'll return soon. Cheers :)
