### ISSUE TITLE
Use Travis as Pull-Request APK generator?

### ISSUE THREAD

**Issue by negue** [HabitRPG/habitica-android#375]
I kinda have the weird idea of getting the build apk from travis and add it to the pullrequest as comment.

That way we could easily download and test the changed code / ui while not being at the computer and give faster feedbacks

**Comment by Alys** [comment]
Oh! People who don't use Google Play would also love that.

**Comment by Data5tream** [comment]
Would be nice to have Travis change the `applicationIdSuffix` so installing doesn't force you to uninstall your own builds (just an off-topic comment  :sweat_smile: )

**Comment by vIiRuS** [comment]
@Alys this wouldn't be suitable for those people. As it's the non-merged PRs that are being built.
We started providing a downloadable apk with the last update. (Linked on the github releases page)

**Comment by Alys** [comment]
@vIiRuS Oh, I didn't know about that! It's good to know, thanks. I'll pass the information on when I see any questions about it.
