### ISSUE TITLE
Secret Developer Settings

### ISSUE THREAD

**Issue by hartalex** [HabitRPG/habitica-android#384]
How about adding a secret developer settings menu?
The menu would only be available after tapping something several times just like the android system developer options settings.

This would allow power users to change the server and other development specific options,
while keeping regular users from messing with things.

#383

**Comment by Data5tream** [comment]
IMO this only makes sense when we add more dev-related settings into the app. Changing the server address is quite easy for testing proposes, so it only makes sense if this stuff is used by end-users. BTW, I think that a visible labeling and a warning popup should be enough to make clear that any changes in that section could break the app.
