### ISSUE TITLE
Checking items fast causes unintended jumping / scrolling to the top

### ISSUE THREAD

**Issue by 2-4601** [HabitRPG/habitica-android#448]
1. Scroll to the bottom of your dailies list
2. Start checking your dailies from the bottom upwards (do this fast)
3. At some point the whole dailies list jumps at the very top

This will usually result in accidentally checking / unchecking items at the top of the list.

See .gif demonstration:
![mr twitchys dailies](https://cloud.githubusercontent.com/assets/174176/13414110/b26fb0b8-df58-11e5-841b-e5789fbca51a.gif)

Nexus 4, stock 5.1.1, Android Habitica version 0.0.25

**Comment by 2-4601** [comment]
@vIiRuS Thanks, which commit fixes this?
(I'm still experiencing this on the Play Store release 0.0.27.1)

**Comment by vIiRuS** [comment]
Must have misclicked. Sorry.

**Comment by 2-4601** [comment]
This is not an issue anymore.
