### ISSUE TITLE
Make pull to refresh work more reliably

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitica-android#464]
Currently pull to refresh sometimes triggers before the header is scrolled all the way down. It should ideally only happen when the header is already fully visible

**Comment by amohnacs15** [comment]
Is a third party library being used for this or is it all custom/hand written?

**Comment by vIiRuS** [comment]
We're using SwipeRefreshLayout from the android support library. http://developer.android.com/reference/android/support/v4/widget/SwipeRefreshLayout.html

**Comment by amohnacs15** [comment]
Nice, thanks.  I will clone the repo and get to work tonight!



Adrian M. Mohnacs

QA Analyst  BAM Technologies, LLC.
Hanover College  Class of 2014
B.A. Computer Science
Android Developer on the Rise
