### ISSUE TITLE
Missing Empty States

### ISSUE THREAD

**Issue by amohnacs15** [HabitRPG/habitica-android#468]
While not a serious issue the app is missing empty state views for tasks and other screens within the view pager.  This could confuse the user if they are not familiar.  I could fix this for you guys if you would like.

**Comment by vIiRuS** [comment]
That would be awesome!

**Comment by amohnacs15** [comment]
Preferred verbiage?



Adrian M. Mohnacs

QA Analyst  BAM Technologies, LLC.
Hanover College  Class of 2014
B.A. Computer Science
Android Developer on the Rise

**Comment by amohnacs15** [comment]
completed.  pull request has been created.

**Comment by vIiRuS** [comment]
Awesome! Apparentl you created the PR on your fork though. For us to review and accept it, you will have to create the PR on this repository.
To do so, you have to use the "New Pull Request" button in this repo and then select "compare across forks" from the top. The left hand side repo is the branch here and the right hand side repo then is your branch with the changes.
