### ISSUE TITLE
Intent support?

### ISSUE THREAD

**Issue by sanzoghenzo** [HabitRPG/habitica-android#482]
Hi all,
thanks for this great app!
I was wondering if there's a way to start the application with a specific tag filter enabled, and if I could trigger it from Tasker (so in the morning I can view my morning routine tasks). The obvious way would be an intent listener of the habitica app, but I'm not sure where to look for if it's already there.
If not, can you please add it?

**Comment by 2-4601** [comment]
Perhaps not so crucial for this app but good to know: https://www.ibr.cs.tu-bs.de/news/ibr/surreptitious-sharing-2016-04-04.xml

**Comment by saraolson** [comment]
with the size of our team, and the fact no one has volunteered to work on this yet, it's not feasible that we'll ever have time to implement. we have made improvements with opening the app to specific screens at least, but we're going to close this for now.
