### ISSUE TITLE
Links with underscore character are formatted into italics

### ISSUE THREAD

**Issue by agentx999** [HabitRPG/habitica-android#509]
If a (non-Markdown) link added to a post happens to contain underscores, part of the link becomes italicized (and therefore you can't click on the link to view it).

Screenshot from a guild post showing Markdown formatting being applied to a link:
![screenshot_2016-04-11-16-25-12](https://cloud.githubusercontent.com/assets/10248632/14446067/d99d1206-0006-11e6-9f7c-3df8b8f140c4.png)

**Comment by mandyzhou** [comment]
Note that this happens anytime there's an even number of underscores in a post, not just in links. In the example below, a user with the display name Moody_goals is mentioned twice and that triggered the italicizing.

![2016_04_15_23 48 45](https://cloud.githubusercontent.com/assets/279805/14612905/9e0d613a-0567-11e6-9092-91a51bc84d4d.png)

**Comment by vIiRuS** [comment]
The issue is more specifically that we will want to prevent underscores from being detected as markdown formatting codes if they are in 1. a username (this will not be completely possible, but we can at least do it for single-word names that have an @ in front) and for urls.
