### ISSUE TITLE
messages when changing class

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#524]
When changing class, there's a popup saying: "Are you sure you want to be a [Class Name]?" It should also say something like "This will cost 3 gems" because the gem cost on the Settings screen is easy to miss if you're not reading carefully.

It would also be good if it could warn players "You will no longer be able to buy equipment from the [previous class name] class." This is a common source of confusion for new players and is demotivating if they've been saving up for gear.

After the class change is applied, there could be a Justin popup that says, "You are now a [CLASS], and you have new default Battle Gear that you can change under Equipment!"

**Comment by lakshmanaram** [comment]
Hey @Alys, I am a newbie to Habitica. I wish to take up this issue. Is this still open? And Is there anything that I have to do before forking it and starting to work on it?

**Comment by Alys** [comment]
@lakshmanaram  Thank you!  The message has already been changed to say "This will cost 3 gems" but the rest of the issue can still be done.

Have a look at the README.md at https://github.com/HabitRPG/habitica-android . If you have questions, I guess post here again, although I'm not an Android coder so I won't be the one who can help you. :)

**Comment by Pandhariix** [comment]
Hey @Alys, I also am a newbie to Habitica, do you know if the issue has been resolved by @lakshmanaram ?

**Comment by Alys** [comment]
@lakshmanaram How are you going with this? Are you still interested in doing it? If you are, that's great, but if you've found that real life commitments have got in the way, that's totally okay too - we know how that goes! :)

**Comment by Alys** [comment]
@Pandhariix I guess if you'd like to do this, go ahead!

**Comment by Pandhariix** [comment]
Okay, thanks @Alys !

**Comment by ralphie9224** [comment]
@Alys Slightly confused on the status of this issue. Anyone working on it? Since it was last mentioned?

**Comment by Alys** [comment]
It was fixed by @Pandhariix but we didn't close the issue. However since then the dialog size has changed so another fix is needed to make the whole message be visible:

![Uploading Screenshot_20170505-143421.png…]()

**Comment by Alys** [comment]
![screenshot_20170505-143421](https://cloud.githubusercontent.com/assets/1495809/25733957/9a09f7da-31a1-11e7-8395-1171a249a43c.png)

**Comment by vIiRuS** [comment]
The message being cut off affects some devices, depending on the configured text size. Apparently android allows the dialog titles to only be 2 lines. This will be fixes in the next update.
