### ISSUE TITLE
Completing checklist items pops up Connection Error, even when connected to internet.

### ISSUE THREAD

**Issue by BeanieB** [HabitRPG/habitica-android#532]

**Comment by JacobFrericks** [comment]
I cannot reproduce this issue on the latest version, can you give more details? I verified everything went through on the web version as well.

**Comment by BeanieB** [comment]
Maybe it was an actual connectivity issue. It could have been that my 
phone was connecting unsuccessfully to the internet. Seems to be working 
fine now. Than you for looking at it!

On 5/18/2016 5:21 PM, Jacob Frericks wrote:
>
> I cannot reproduce this issue on the latest version, can you give more 
> details? I verified everything went through on the web version as well.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/HabitRPG/habitrpg-android/issues/532#issuecomment-220161997>
>


-- 
Lauren Burianek Crowe
PhD Candidate, Haystead Lab
Cell Biology Department
Duke University

**Comment by christopherfowers** [comment]
I seem to have this issue on my Note 8. Current production version from Google Play Store. I'm getting my Dev environment set up now. Will try to reproduce and debug.
