### ISSUE TITLE
Add confirmation for leaving a party

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitica-android#537]
The leave button in the party view should never be visible (always in the dotted menu) and should prompt for confirmation.

**Comment by amohnacs15** [comment]
Hello.  My name is Adrian and I work as an Android dev during the day.  I was wondering if I could help tackle this issue as a way to get introduced to the project.  

What is the process?  Do I fork the repo and submit a pull request when the task is complete?

**Comment by vIiRuS** [comment]
Hi,

Yes! Help with this issue would be much appreciated.

Exactly. Simply fork it and then create a new PR from your repository once you are ready for it to be reviewed.
And if you have any questions, feel free to ask!

**Comment by amohnacs15** [comment]
In my app build.gradle file I am getting the thrown error "habatica.properties not found".  This is being throw by the Add Habitica Properties to buildConfigField block.  I cloned the rep and it is missing.  

Do you have this file hidden to keep keys and http's secret?  What is the recommended course of action here?

**Comment by jjbillings** [comment]
in your project directory there are two file: "habitia.properties.example" and "habitica.resources.example". Copy these files to "habitica.properties" and "habitica.resources" respectively. Also, in the Habitica folder inside your project directory, you will need to copy "google-services.json.example" to "google-services.json"

**Comment by amohnacs15** [comment]
What are you looking for in terms of styling and animation for this dialog(Fragment)?

**Comment by calvinchrst** [comment]
Hi @vIiRuS ,
I'm Calvin and I'm interested in attempting this issue to learn more about Habitica's Android project. 
May I know whether @amohnacs15 is still working on this issue? 

Thank you and hope to hear from both of you soon. Cheers.

**Comment by vIiRuS** [comment]
Hey, Sorry for the late response. It seems like this is no longer being worked on. In that case, go ahead with working on this!

**Comment by calvinchrst** [comment]
Okay great! Working on it :)

**Comment by dinesh3434** [comment]
Hi @vIiRuS ,
I'm Dinesh. This is my first attempt at solving an open source issue. I started working on this issue (apologies for asking before I started). I seem to have solved and tested the same on my device. I would be raising my first PR. Please do go through the same and let me know if I missed something.

**Comment by gunnaveen** [comment]
Hello,
I'm new to the open source community and wanted to attempt this as this is the only entry-level issue open for the android app. Is this still being worked on? If not, I'd like to give it a shot. Please let me know. Thank you.

**Comment by amohnacs15** [comment]
@gunnaveen looking above your comment it appears that code has already been merged in.  If you have enough Android skillz (which I assume you do since you're offering to help with open source) take a look at this guy https://github.com/HabitRPG/habitica-android/issues/748

**Comment by vIiRuS** [comment]
Sorry forgot to close this.
