### ISSUE TITLE
Some task lists not displayed for Marshmallow users

### ISSUE THREAD

**Issue by Deaconrayne** [HabitRPG/habitica-android#559]
No rewards found under tab  in Android App version 0.0.30.1 (86)

**Comment by vIiRuS** [comment]
Does this only affect your custom rewards or is purchasable gear also not displayed?

**Comment by Deaconrayne** [comment]
It affects all rewards that are purchasable: gear and custom awards alike

**Comment by vIiRuS** [comment]
@Deaconrayne Do you have Android 6.0 (Marshmallow) installed?

**Comment by Deaconrayne** [comment]
I do use 6.0.1

**Comment by vIiRuS** [comment]
Then as an addition/clarification for this issue: It can affect habits, dailies, todos and rewards (but not necessarily all at once) and only happens on android 6.0. I have reports from Samsung and sony devices, so it doesn't seem vendor specific, but I couldn't reproduce the issue in an android simulator or genymotion.

**Comment by Deaconrayne** [comment]
Is there a solution?

**Comment by vIiRuS** [comment]
No, not yet. I'm not sure yet why it is happening.
@Deaconrayne do you maybe use markdown in one/some of your rewards? If yes, could you send me the name and/ or notes (depending on where the markdown is) to mobile@habitica.com? It could be that one of those is causing this issue.
