### ISSUE TITLE
beard and mustache sets are bought separately (should be both in one set purchase)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#561]
On the website, you can buy all beard and mustache items together in one set for 5 gems.

On the Android app, there is one set for beards and one set for mustaches, each set costing 5 gems (so twice as expensive to buy on the app).

This might also be the case on the iOS app - could someone please test?

Maybe as a quick initial fix, the price for the beard set could be changed to 3 gems and the mustache set to 2 gems? Then later they could be combined into a single set, which I guess would take more time. @lemoness what do you think?

**Comment by saraolson** [comment]
This is sort of a hard problem because you can equip a beard and mustache in different slots, and since the app breaks up the screens by slots, having a combined view doesn't work with the current layout. Would def be good to discuss a solution for this.

**Comment by Alys** [comment]
If we don't like the idea of charging less for each subset, then you could make it so that when either the beard or moustache subset was bought for 5 gems, the other subset was also automatically bought, without additional gems being charged. That could be done without visible changes to the app.

Even if a better solution was done later to make it more obvious to the user what was happening, this initial quick fix would be helpful now to prevent app users being charged twice as much as website users for the facial hair options.

**Comment by Alys** [comment]
Just confirming that this is still happening. Here's a report from Simon Osborne (882416c9-0125-452d-8232-188116924bb0) in the Report a Bug guild, who's been charged the full five gems for only some of the facial hair styles (i.e., would have needed to pay twice as much as he should have to get all of them):

"There appears to be incorrect pricing on the facial hair package. The wiki states that 'To add hair to the chin area of your avatar requires purchasing the Facial Hair set of beards and mustaches. The cost is 5 gems for the whole set or 2 gems for an individual facial hair style.' This implies that the one set of three beards and two mustaches can be purchased for a total of 5 gems, but when I attempted to purchase the facial hair set I only received the beards. It may be that the wiki is out of date and they're now separate sets, but if that's the case why can I buy both set of mustaches for 4 gems (2+2) individually when the pair of them cost 5? It looks like they've mistakenly been split into two different sets."

**Comment by saraolson** [comment]
Ideally, i think i'd prefer charging less for each, and making them separate purchases to keep with the logic of all the rest of the sections of avatar customization. But agree that a quick fix of buy one get all would be better than nothing because right now its broken in a way that wastes people's money just because they purchased on the app
