### ISSUE TITLE
Stable subscreen for a pet type is not accessible if all such pets have been elevated to mounts

### ISSUE THREAD

**Issue by thebat137** [HabitRPG/habitica-android#563]
Example case:

Suppose I have never used any fox eggs at all. Then, on the stable screen, the fox pet and mount tiles both show a grey pawprint with a question mark.  Neither tile is clickable to view the different colored creatures, since I don't have any.  This makes sense.

Now suppose I use a base potion on a fox egg.  My fox pet tile now shows a base fox, while my mount tile is presumably still a pawprint.  (Not sure what it looks like if I have only hatched non-base fox pets so far, since I have no available examples like this currently, but presumably the first non-base version of the pet on my owned list would be shown instead.)  The pet tile is now clickable, so that I can see my base fox and grey pawprints for the other fox colors.

If I now hatch a red fox, it's pretty much the same, except that the fox pet subscreen now shows both the base and red foxes.  If I raise my red fox to a mount, the fox mount subscreen presumably gets activated with some appropriate image (can't check right now) and the red fox pet turns translucent on the fox pet subscreen, but that screen is still accessible, via a tile that looks like a base fox pet.  All good so far.

The problem comes if I now raise the base fox to a mount also --- because I no longer have any actual fox pets, instead of keeping the fox pet subscreen accessible (perhaps with a translucent fox icon) it reverts to an inert grey pawprint, as if I've never hatched a fox pet.  I have to go to the mount screen to review my fox hatching progress.

I think a more sensible solution would be to _always_ have each pet and mount type subscreen be accessible, with the tile in the main pet or mount list being a grey pawprint if no pets or mounts of that type have ever been hatched, a full-color image of the first pet/mount on the list that's actually owned, or, for the pet screen, a translucent image of the first raised-to-mount pet on the list if all such pets that have been hatched have been raised to mounts.

I don't think this is really a bug, but it seems sorta rough the way it currently is, so I hope this can be changed.

**Comment by saraolson** [comment]
This should be helped when we eventually get around to implementing the new stable designs.

**Comment by beffymaroo** [comment]
@saraolson Should this be assigned to a milestone?

**Comment by saraolson** [comment]
@beffymaroo eventually yes but we havent discussed the priority of stable redesign yet to place it
