### ISSUE TITLE
Use Proguard

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitica-android#567]
We are now slightly under the 64k method count. To keep it that way we will probably have to use proguard.

**Comment by meredrica** [comment]
If it's ok I could get my hands dirty with this.
Should not be too hard.

**Comment by vIiRuS** [comment]
Have a go at it! :)

**Comment by andrewlord1990** [comment]
Is there a reason you haven't just enabled MultiDex and then never worry about the 65K limit again? You should probably have Proguard to simplify things anyway so what you can have is:

release/debug = MultiDex and Proguard
development = MultiDex, minimum API 21, no Proguard

This development mode can be an extra Build Variant to select, which sets minimum API to 21 and disables Proguard, making builds really fast whilst developing, but still giving you benefits of Proguard for your full debug or release builds.

**Comment by Jawnnypoo** [comment]
You may have to MultiDex reguardless after some time, but I would say that ProGuard is the way to go initially due to the fact that it does optimize and remove bloat. I imagine a project with ProGuard will build faster than the same project with MultiDex enabled as well.
