### ISSUE TITLE
Add Language switcher in settings

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitica-android#574]
Add setting to switch the apps language. this should also switch the language of the account on the server and reload the content.

**Comment by DanielKaparunakis** [comment]
Okay vIiRus, I want to work on this feature. I've begun poking around the app & I noticed that there are localized strings in place already. If the user changes the language in the phone, the app will use the localized strings. So in developing this feature, is the intent to override the language of the phone?

**Comment by vIiRuS** [comment]
Yes, the app is already fully translatable (at least it should be. there still might be 1 or 2 strings that are not translatable yet). The goal of this PR is to have an option in the settings to change the habitica language (that is stored in the preferences.language property on the user object) and have that language selection also override the apps language that is set from the phone, so that users can have the app in the language of their choice. Since the last PR by @negue, the apps content already respects the language setting, but the app itself does not yet.

The available languages should be all languages the app is available in. Not sure if there is a way to get those languages, otherwise we would have to hard code that list in the app.

Also, the language should be set to the devices language during registration. There are two ways to do this

1. pass the `Accept-Language` HTTP header.
2. add `?lang=CODE` to the registration request.

In the latter case, the passed codes have to match the ones from [this folder](https://github.com/HabitRPG/habitrpg/tree/develop/common/locales). But since we don't want to hard code that in the app, it's probably easier to use the HTTP header. Either way, the app would have to check if the app itself is available in the phones language first. and only set the language during registration if that is the case.

If you have any further questions, let me know!

**Comment by DanielKaparunakis** [comment]
Hi @vIiRuS, I am now working daily on this so I should be able to deliver it soon. I wanted to know how you would like to handle languages that are present in the app but not the site. It seems like there are two: Korean (ko) & Lithuanian (lt). Should the app allow the user to change the language to these two? If so, how should the change be handled by the site?
