### ISSUE TITLE
Play sounds on special interactions

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitica-android#586]
Same as on the website. level up, habit scoring, daily/todo checking, death.

This should use the same audio theme as the website and use the same setting to enable/disable sounds entirely. Ideally the audio files are hosted somewhere and downloaded/cached when the user selected one. The setting for choosing a theme should then also be populated from data from the API, so that new themes can be deployed without an app update.

**Comment by Alys** [comment]
In case it's helpful to whichever developer works on this, [Guidance for Bards](http://habitica.wikia.com/wiki/Guidance_for_Bards) on the wiki describes how it's set up on the website.

**Comment by Repjarms** [comment]
Hi guys. I'm new to the Habitica project but I have experience as a dev and sound designer and I'd love to take a crack at this if it's still open. Let me know!

**Comment by TheHollidayInn** [comment]
@Repjarms This is still open!

**Comment by negue** [comment]
Ooops, I guess I haven't closed this issue, cause Sounds already got merged #646 

It uses the setting from Habitica itself, and will load / play the sound files.
