### ISSUE TITLE
Request: Notification of report when damage recieved

### ISSUE THREAD

**Issue by jonyeezs** [HabitRPG/habitica-android#588]
It would be nice to receive a notification of a report on the damage incurred.

For mvp:
1. Menu link to report/log of damage taken from failed tasks
2. A notification to view the report maybe once at the end of the day.

Then later able to set how often we would like to be notified of this report

**Comment by saraolson** [comment]
This could work well with a more general history view that shows a log of actions by and on you.

**Comment by veeeeeee** [comment]
We have thoughts on how we want to handle this interaction in the future but closing this for now. Moving forward, please submit requests through the feedback form: https://forms.gle/Fa6oztkDsbzLqSvE9. This will help us organize all the requests when we're thinking about next steps. Thanks!
