### ISSUE TITLE
Push notifications show up in sender's language instead of recipient's

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica-android#604]
The other day, I got a private message from a user in China. I received the push notification for it, but the system text ("New Private Message" / "You got a private message from <user>" -- not sure of the exact phrasing) showed up in Chinese despite my device using US English for everything else.

I'm guessing the push notification functionality needs to look up the recipient's language preference before generating the text to send. If that's even possible!

**Comment by vIiRuS** [comment]
This can not be fixed on the server side and is already being tracked in this issue: https://github.com/HabitRPG/habitica/issues/8718
