### ISSUE TITLE
Codebase should be commented more thouroughly

### ISSUE THREAD

**Issue by sambokai** [HabitRPG/habitica-android#606]
After having taken a look at the codebase i noticed that much of the code is uncommented. I don't know if it's just me (as a beginner/intermediate programmer) who has a rather hard time understanding some parts of the code. 

Would expanding the documentation, in form of code comments, be a viable contribution to the project? That would be a task that falls into my circle of competence, as a rather unexperienced dev. and even more unexperienced "open sourcer", and would allow me to dive into the project more thoroughly, while contributing in a more or less meaningful way.

Greetings

**Comment by vIiRuS** [comment]
We are currently planning a larger refactor of some parts of the app, so I am not sure if right now would be a good time to document the existing codebase. @TheHollidayInn @negue or what do you think?

We also have a few issues tagged as [entry level](https://github.com/HabitRPG/habitrpg-android/issues?q=is%3Aopen+is%3Aissue+label%3A%22Entry+Level%22), which are either easy to solve or don't require much knowledge of the codebase. Maybe those would also be a good place to start?
