### ISSUE TITLE
Responsive tablet UI

### ISSUE THREAD

**Issue by AlgoRyan** [HabitRPG/habitica-android#626]
As I personally use the app on a tablet I'd love to see an interface that was designed specifically for it. Ideally, this would also work with the new multi-window support that comes with Android N. 

A UI that compresses some of the many existing screens into the bigger screen real estate would make for a much more effective navigation pattern.

**Comment by saraolson** [comment]
While this would be nice, it would take a lot of work to create a better experience--on both the design side and code side of things. Considering out tablet user base, gonna mark this as low priority.

**Comment by saraolson** [comment]
with the size of our team, the difficulty of working on android tablet layouts, and the amount of users that have android tablet this isn't feasible for us implement or support.
