### ISSUE TITLE
Add Custom Day Start to Settings

### ISSUE THREAD

**Issue by KonomiKitten** [HabitRPG/habitica-android#641]
Currently "Custom Day Start" (located in https://habitica.com/#/options/settings/settings and in the iOS app I'm told) is missing from the Android version. It seems like this should be added to line up with the website and iOS app?

**Comment by Alys** [comment]
If this is implemented in the Android app, it's important that it has the same protective features that the website has, even though they aren't in the iOS app yet. When the CDS is changed on iOS without those protections, cron can run unexpectedly, causing damage to the player and their quest-mates. See https://github.com/HabitRPG/habitica-ios/issues/296 for a description of them.
