### ISSUE TITLE
Move codebase to kotlin 

### ISSUE THREAD

**Issue by caipivara** [HabitRPG/habitica-android#642]
It may help to have a small code base and make the code simpler.

**Comment by TheHollidayInn** [comment]
Is this supported by Google?

**Comment by danielgomezrico** [comment]
@TheHollidayInn what do you mean by supported by Google?

**Comment by TheHollidayInn** [comment]
@danielgomezrico I mean it very generically. But, what I am looking for is similar support that Swift has from Apple. Is Google thinking of making a big switch to Kotlin?

**Comment by joezorry** [comment]
@TheHollidayInn Most likely not. However it has excellent support by Jetbrains.

I love Kotlin, but moving an open source project like this to kotlin might alienate some developers to actually contribute since learning a new language is an obstacle.

**Comment by danielgomezrico** [comment]
it can make code base smaller, cleaner and also performant, I see the same kind of fear that I saw when swift arrived and now everyone is using it.

**Comment by danielgomezrico** [comment]
I heard that Google is using it, also because is full interoperable with Java

**Comment by vIiRuS** [comment]
Do you have references/examples for a codebase being significantly smaller and more performant when after switching to kotlin?

**Comment by TheHollidayInn** [comment]
I'm not against it, I'm just wondering about the future is all. I understand you have seen the same thing with Swift, but I have seen similar languages try to do this with other languages and fail as well. Java already has many replacement languages that compile to Java anyway.

Let's see what @vIiRuS thinks. I think we could try it on some sections for sure.

**Comment by joezorry** [comment]
It's probably in most cases as performant or less as Java, since it's all building to dalvik, it also adds a bit to compile time.
It will however make the codebase smaller.

**Comment by danielgomezrico** [comment]
@vIiRuS here are some cool posts about Kotlin:

- http://antonioleiva.com/kotlin-awesome-tricks-for-android/ (he made Kotlin for Android book)
- https://www.manning.com/books/kotlin-in-action (another great book)
- https://blog.jooq.org/2016/03/31/10-features-i-wish-java-would-steal-from-the-kotlin-language/
- https://www.youtube.com/watch?v=A2LukgT2mKc&t=1643s

Using Kotlin you can reduce a lot POJO classes, boilerplate with lambdas, ceremonies with extension functions (check Jake Wharton talk), one liner functions, and others...

There's also a button `Convert java to kotlin` to move all the code to Kotlin, but then you will have to fix some things manually :P

**Comment by danielgomezrico** [comment]
With this issue I just wanted to open the discussion, I think that may be a call for contributions for people learning Kotlin, but may be an issue for current contributors so not sure if its a good idea at the end...

Other cool videos about Kotlin in production:

https://www.youtube.com/results?search_query=kotlin+production&page=&utm_source=opensearch

**Comment by caipivara** [comment]
Theres another cool post about this https://medium.com/@amitshekhar/why-you-must-try-kotlin-for-android-development-e14d00c8084b#.5cohwiurd

**Comment by vIiRuS** [comment]
We have begun doing this in the develop branch! The current plan is to write new code in kotlin and convert existing code if it makes sense (p.e. significant changes are made to the class)

I'm working on updating the docs on how to contribute to the project and will include a note about this.
I'm going to close this issue now, so that we can get the issue list a bit smaller.
