### ISSUE TITLE
Can't launch the Android app after the last update

### ISSUE THREAD

**Issue by Veesha** [HabitRPG/habitica-android#651]
Hello. After the last update on my Android, my Habitica app stopped working on my phone, when I launch it the status bar becomes purple as usual but the screen goes white and after a while, the game crashes. My phone is a rooted Motorola Moto G with Cyanogenmod 13, if that can help. I believe that the problem is not the root or the Cyanogenmod because I've been using Habitica for more than a month just fine. I've tried uninstalling and reinstalling the game multiple times without success. For now, I'm sticking to the web app but I need the Android app as well. Hopefully you guys can get it fixed soon.

**Comment by vIiRuS** [comment]
can you tell me your habitica user ID, so that I can check the crashes? You can find that on the website by opening the API settings from the top right menu.

**Comment by Veesha** [comment]
Yes. It's 0423dea7-e777-4bb7-8356-3b084db7f708

**Comment by Veesha** [comment]
Any news @vIiRuS ?

**Comment by vIiRuS** [comment]
strangely there aren't any crashes in our system that match. If you delete the app data through the android settings, does it also crash during launch? Or are you able to log in?
What version do you have installed according to the play store? 0.0.34.4?

**Comment by Veesha** [comment]
I was able to get the app working again by reinstalling it once again and clearing both the data and the cache. I obviously had to log in again. Thanks a lot for the suggestions @vIiRuS ! And yes, the app version is 0.0.34.4.
