### ISSUE TITLE
Feature request: Tor support

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica-android#653]
With the growing prevalence of restrictions and surveillance on Internet traffic by various parties, it could be valuable for users to be able to route their Habitica connections through Tor.

[The Guardian Project](https://guardianproject.info/) provides a library, [NetCipher](https://github.com/guardianproject/NetCipher), for integration with their [Orbot](https://www.torproject.org/docs/android.html.en) Tor proxy. [DuckDuckGo search](https://play.google.com/store/apps/details?id=com.duckduckgo.mobile.android&hl=en) is an example of an app that already takes advantage of this integration, providing a one-touch setting to switch app traffic to use a running Orbot service.

**Comment by vIiRuS** [comment]
Note that NetCipher already offers OkHTTP, so adding this should be pretty straight forward! http://stackoverflow.com/a/40365117/1315039

For this there should also be an option in the apps settings to enable/disable it. Potentially with a short paragraph explaining the implications (more secure connection, but slower) and maybe a link to tor, for people that are not familiar.
