### ISSUE TITLE
Tag filter drawer empty on first launch

### ISSUE THREAD

**Issue by anitawoodruff** [HabitRPG/habitica-android#654]
Steps to reproduce:
- Fresh install, or clear app data in Android Settings
- Launch habitica and log in
- Open tag filter drawer in tasks view - drawer opens but is completely empty, just white.
- Hide and show drawer - it's still empty.

Drawer is only populated on sync or if the app is restarted. 

(I have a fix for this issue, will submit a PR tonight.)

**Comment by shippy** [comment]
This is still an issue on 0.0.37.1 (156). Has the PR above been deployed yet?

**Comment by anitawoodruff** [comment]
I don't know, but I am also curious to find out how to tell which commits
are in which releases as the process is opaque to me. Phillip?

On Sun, 12 Feb 2017, 13:02 Simon Podhajsky, <notifications@github.com>
wrote:

This is still an issue on 0.0.37.1 (156). Has the PR above been deployed
yet?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/HabitRPG/habitica-android/issues/654#issuecomment-279248590>,
or mute the thread

**Comment by vIiRuS** [comment]
We don't really have a good process for this. In general, the last thing that is changed for a release is the version code. So if that is changed (and the matching version is publicly released), all previous commits are live. But this isn't necessarily an easy way to tell. If people have suggestions for how they would like this to be handled, I'm open.

In this case, the PR is live for a while, so this issue might have resurfaced again. Will look into it.

**Comment by anitawoodruff** [comment]
I can't reproduce in 0.0.37.2 with a fresh install - do you get this with exactly the steps described above @shippy ?

**Comment by anitawoodruff** [comment]
Ah I wonder if this was fixed in https://github.com/HabitRPG/habitica-android/commit/18770e0083e1ce6db8d0a64bfee83c6a04dca198 @vIiRuS ?

**Comment by anitawoodruff** [comment]
Re: Suggestions for how we can tell which commits are in a given version - this would be very easy if there was always a [git tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) for every release. (Tags are simple to push, and can be converted to full-blown releases with binaries when you 'Draft a new release' on Github, or there's [an API](https://developer.github.com/v3/repos/releases/#create-a-release) for fully automating the process.) Actually I see there was a new release in the [habitica-android Releases page](https://github.com/HabitRPG/habitica-android/releases) recently for 0.0.37.1, but not for 0.0.37.2.. Would be great if this could be done consistently as part of the release process. 

One other suggestion while we're talking about processes - can we try to make sure commits only contain a single change? it seems quite often Habitica commits contain more than a single change / bug fix in them, which makes it hard to see when things happened from looking at the commit history. E.g. the last version bump was part of an unrelated change.. This could cause issues if that change needs to be reverted. Better to put the version bump in a separate commit. 

In my last job we'd always try to make sure the first commit after pushing a release tag was just a release bump to the next version, so e.g. you'd release & publish v1.2.3, then update the version name in the repo to 1.2.4, so it's clear we're now all working towards 1.2.4, which is then snapshotted & released the next time an apk needs to be published. So this is the process I'm used to, I don't know if it's the most suitable one for Habitica-android, but worth considering?

**Comment by vIiRuS** [comment]
Yes, this issue probably was also fixed with that commit.

I'll try to be more consistent with releasing the play store updates on github. Creating separate tags, shouldn't be necessary, since creating a github release also creates a tag. Automating that process might not make sense, since we'd only want the builds that end up in production be pushed there and not the beta builds that never get to production, because there are still bugs found.

I'll also try to do more atomic commits, so that changes are more clear.

I prefer to have the version bump be the last change made for a release. That way, you can look at the commit where the version was changed and have the state the app had for that version.
