### ISSUE TITLE
Egg does not disappear after hatching

### ISSUE THREAD

**Issue by AubreyKilian** [HabitRPG/habitica-android#659]
Hi guys,

When I hatch any egg, I get the "You hatched a blabla" dialog, and when I click the close button, the egg still stays there.  This is a display issue only, as the egg cannot be hatched again, it's merely a matter of the list not being sync'd with the server...
Switching to the "Tasks" screen and hitting the refresh button and then heading back to the Items page does end up doing a sync to the server.

Cheers
-Aubrey

**Comment by AubreyKilian** [comment]
I am going to try to fix this issue myself though...

**Comment by AlbRoehm** [comment]
Is still open? Probably the easiest way would be, to send a userUpdateEvent via the event bus?

**Comment by AubreyKilian** [comment]
Yeah still open from what I know, life and work happened for me and I've been unable to pay attention to this.

**Comment by AlbRoehm** [comment]
It seems that this receiver (ItemRecyclerFragemet) doesn't get a event:
`@Subscribe
    public void reloadedContent(ContentReloadedEvent event) {
        this.loadItems();
    }`
