### ISSUE TITLE
leader's name does not appear in guild and party screens

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#666]
The name of a guild or party leader does not appear on the group's first screen, although if the group has a leader message, you can see the leader's name in the "message from ... " text. 

I suggest that the leader's name be placed under the group's description and above the leader message if there is one, formatted something like this:

**Guild Leader:** TheNameGoesHere

I think there should be a line of whitespace above it to separate it from the guild's description, and also a line of space below it if a leader message exists.

For a party, it should say "Party Leader". 

It should not appear on the Tavern's screen.

**Comment by saraolson** [comment]
This should be fixed whenever we get around to party/guild updates. Guild is planned for 1.6, and that might be a good time to throw parties in too since they're very similar.

**Comment by emily-keller** [comment]
Has this issue been fixed?

**Comment by saraolson** [comment]
@emily-keller this issue hasn't been fixed yet as we never quite got around to implementing the new guilds design
