### ISSUE TITLE
Actions are performed twice

### ISSUE THREAD

**Issue by bentocin** [HabitRPG/habitica-android#669]
If I hit "+" or "-" on habits or if I add checklist items the actions are always performed twice. For the habits I can see it online when I open the statistics of the habit and for the checklist items I see it immediately in the app. If I add a checklist item to a daily it appears twice. If I mark a checklist item as done in my daily it immediately unchecks. It takes some attempts until it is stored as checked. The same applies vice versa if I try to uncheck a checklist item.
It also does not always show the gained xp and coins for when hitting "+" on habits.

This problem occured for Android-Version 6.0.1 with OxygenOS-Version 3.2.8.

**Comment by Alys** [comment]
@hurrycain3 Can you tell us your User ID please? You can find it on the app under Settings > Account Details. Tap on it to copy it to the clipboard. Do not tell us your API Token; it is like a password.

Admins / Devs:

This report was in the Report a Bug guild two days ago from Agrinja (25d0c729-af6b-46f8-8ea3-aad1efee508a). I am wondering if it's from the same cause.
**"Hello, I've been encountering an odd bug on the app wherein check boxes toggle themselves on checklist To-Dos/Dailies. I'll check something off, and I'll watch it toggle itself back off, or another one will toggle off, or come back, or do the same several times. Sometimes I have to check the same item up to about five times before it will stay checked off."**

I have seen other reports of ticked tasks becoming unticked but not often, and I've usually suggested that they're from sync errors (the completion can't be sent to the server so it's reversed when the client realises that). However duplicated actions might instead have been the cause.

Possibly related: https://github.com/HabitRPG/habitica-android/issues/599 "Rewards duplicated items", and the reports we see of people's tasks being duplicated.

**Comment by hurrycain3** [comment]
@Alys My user ID is: 8c75ec61-29d0-4e94-8dec-ea5ba294eea4

I didn't see the report posted on the guild but it is exactly the issue I encountered. In addition, I saw the above described issues with the habits. My first thought was that it is due to connection errors as you mentioned but it occurs over and over again. I could easily reproduce the bug when hitting "+" on habits and looked it up in stats of the browser version. I don't know if this is related to the issue, but I switched positions of my dailies and if I check off the daily with its subtasks it jumps back to its original position until I refresh/sync it again.

**Comment by frommberger** [comment]
Could all to be the same problem:
* habit ticks are counted multiple times (I had it up to 7 times!)
* to-dos are ticked and unticked
* newly created tasks appear twice or three times. sometimes the duplicates can be erased, sometimes not

As this makes the app *completely* useless - what can we do to provide necessary information needed to identify the problem?

**Comment by vIiRuS** [comment]
Yes, those are most likely all the same issue.

Information that would be of use:
- Device
- Android version
- If the issue also happens directly after the app was launched (with being killed from the multitasking menu)
- if the issue gets worse over time (so if it ticks things off more often when it's open longer or if your switch back and forth between habitica and other apps)

**Comment by maiatoday** [comment]
This happens on my device. Nexus Android 6.0 It happens where ever you load the app. Here's how I can reproduce it.
Make a daily with  a checklist. If you open the checklist and tick of items quickly then the tick and untick. If you tick items slowly (as if you wait for the messaging to happen in the background) you don't get the symptoms. It is also worse if you have a slow network connection.

It also happens on the latest update. I'll try it on an emulator from the latest develop and let you know if I see it there too.

**Comment by vIiRuS** [comment]
This actually sounds like it's a different issue. Should also only affect checklists and not other task types like the issue that is originally described here does.

**Comment by frommberger** [comment]
Device: OnePlus 3T, Android 7.0
Could *not* reproduce the behavior when trying directly after having it removed from memory, as suggested

**Comment by bricechilders** [comment]
I'm having the problem where tasks are created multiple times. 
LG G5
Android 6.0.1

Does not seem to happen after restarting app. Does seem to create more duplicates as the app is open longer.

**Comment by vIiRuS** [comment]
The app version that is on the play store beta channel should have a fix
for this issue. If you want to help test that it is gone, you can open the
habitica play store page and select the option to become a beta tester.

-- 
Phillip Thelen
Sent with Airmail

**Comment by frommberger** [comment]
I haven't noticed this issue for a longer time anyway, also in the non-beta.
