### ISSUE TITLE
[Feature Request] change task type after creation 

### ISSUE THREAD

**Issue by toddmedema** [HabitRPG/habitica-android#681]
Especially as a newbie learning the differences between habits and dailies, it was frustrating to make the wrong type, then have to delete and re-create it rather than being able to change the type and keep the name

**Comment by LordVladneutral** [comment]
keep the name and keep the tags...

**Comment by veeeeeee** [comment]
Closing this for now. Moving forward, please submit requests through the feedback form: https://forms.gle/Fa6oztkDsbzLqSvE9. This will help us organize all the requests when we're thinking about next steps. Thanks!
