### ISSUE TITLE
Two-handed equipment is not marked as such - confusion about items being unequipped automatically

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#688]
The two-handed weapon/shields don't have anything in their description that marks them as two-handed, so we've been receiving bug reports about shields becoming unequipped when a two-handed weapon is equipped, or vice versa. For example, from EternalLearner:

"I think this is a bug: does anyone know why, when I choose battle equipment, when I use Mustaine's Milestone Mashing Morning Star it knocks my shield off (which is the Taskwoods Lantern) and vice versa?"
"After much experimenting I determined the Taskwoods Lantern was the issue. I'm using the Android App. When I tried the mobile browser, I got the notification stating that it requires 2 hands. I have spent a while on this since nothing in its description indicates this limitation. Evidently not a bug, just a lack of info! Thank you for all you do!"

On the website, when you change equipment in a way that involves a two-handed piece, you get a notification like one of these:

- "Wielding Brass Staff takes two hands, so it was unequipped when you armed yourself with Golden Shield."
- "Wielding Brass Staff takes two hands, so Golden Shield has been unequipped."

Can that be added to the app?

_(EDIT: We did this in https://github.com/HabitRPG/habitica/pull/9839 ~FYI We might also want to adjust the two-handed items' descriptions to state upfront that they need two hands but that's something that would have to be done in the website's repository so I'll log it there if we decide to do that.)~_

**Comment by amohnacs15** [comment]
Are there test accounts available I can use to test and fix this so I don't have to make sizable changes to the code to reach the appropriate state?

**Comment by saraolson** [comment]
We'll add clarification for this when we implement the new equipment designs.

**Comment by beffymaroo** [comment]
@saraolson Should this be added to a milestone?

**Comment by saraolson** [comment]
so we now label gear as two-handed upfront, but we don't notify people of something being unequipped when a two-handed item is involved.

**Comment by saraolson** [comment]
We also still need to implement the main equipment screen redesign that marks items as two-handed in that view as well as in the view where you choose equipment. but that can be separate from implementing a toast.
