### ISSUE TITLE
Custom Day Start setting allows confusing selection of minutes

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#691]
Habitica's API enforces a Custom Day Start time that's a whole number of hours with no minutes (e.g., 4am but not 4:30am). On the Android app, the time selector does allow you to choose minutes, although they are never saved. This causes confusion, for example, in these two messages from Okeanos in the Report a Bug guild (the second message was after an explanation had been posted):

"Okay, so I have been trying to set my Custom Day Start Time to 4:30 A.M., but after I set it to that time, it keeps saying 4:00 A.M. instead of 4:30 A.M. I keep checking to see if I actually set the right time and I did set it to the right time, but the thing still keeps saying 4:00 A.M. anyway instead of 4:30 A.M. like I want it to be. HELP PLEASE???? I'M FRUSTRATED AND CONFUSED!!!"

"Thank you so much!! I had no idea if there was a glitch or if I was doing something wrong, or something else happened. I had no idea, but it was not obvious at all. I was on the Android app, I believe. It seemed like you could set the time to whatever you wanted, like whatever minute or hour you wanted to set it to, it seemed like you could.
Maybe if they changed it to just setting the hour, like just having the hour option and not including minutes option."

**Comment by jamesalvarez** [comment]
I could fix this by switching the TimePicker to a scroller and disabling the minutes scroller.  I don't think its possible to keep the default clock widget and disable the minutes there.
