### ISSUE TITLE
Notification icon is very hard to see in the notification bar on top of the screen.

### ISSUE THREAD

**Issue by khipkin** [HabitRPG/habitica-android#693]
The third notification from the left is for Habitica, the one that looks like a gap.

![image](https://cloud.githubusercontent.com/assets/5641207/21957798/356133c4-da54-11e6-839d-c12699239d6d.png)

**Comment by Alys** [comment]
A problem similar to to the favicon being near-invisible on the Windows 10 task bar: https://github.com/HabitRPG/habitica/issues/7720

See also suggestions for improvement to the favicon (e.g., white border around the purple Gryphon): https://github.com/HabitRPG/habitica/issues/8298

I'm pinging Sara Olsen, our designer, about this.
