### ISSUE TITLE
The developers crystal armour is not displayed correctly

### ISSUE THREAD

**Issue by AlbRoehm** [HabitRPG/habitica-android#698]
When the crystal armor(contributor rewards) is equipped, the character is displayed not wearing an armor at all.

**Comment by Atomk** [comment]
Did you find this bug by yourself or it was reported by someone? Because I reported this a few months ago via the in-app feedback feature but maybe it is better to just create an issue here on Github.

**Comment by AlbRoehm** [comment]
Just got the armor a few days ago and found it out by playing around with it.

**Comment by mandyzhou** [comment]
This is a duplicate of #485.
