### ISSUE TITLE
quests scrolls that can be bought for gold appear to cost gems

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#699]
Quest scrolls that are supposed to cost gold are displayed as being purchasable for gems in the confirmation screen.

If you buy them, they DO subtract gold, not gems, so this is just a display issue. However it's one that might turn people off buying some of the quests due to the apparent cost.... :)

![img_5833 jpg](https://cloud.githubusercontent.com/assets/1495809/22149966/42b2261a-df62-11e6-9905-066cc95072fe.png)

**Comment by AlbRoehm** [comment]
Are you sure this is the right platform? To me this screenshot looks quite IOSish, also i couldn't find the bug in my version of the app(neither "Release" nor "Dev").

**Comment by Alys** [comment]
Oh darn, yes. Sorry for the issue spam everyone. Thanks @AlbRoehm !
