### ISSUE TITLE
'Challenges' heading persists after leaving Challenges screen

### ISSUE THREAD

**Issue by mandyzhou** [HabitRPG/habitica-android#700]
If I navigate to the Challenges screen, then leave (by tapping the left arrow/back button), the 'Challenges' heading persists on all the other screens of the app. For example, my username, which usually appears when I'm viewing my task list, is replaced with 'Challenges'.

**Comment by Alys** [comment]
Also reported by alltootrue22 (af3c075a-a68c-48cc-b19a-14f73954b0f2) in the Report a Bug guild:

"Hi. I looked at Challenges on the Android app and now every heading says Challenges no matter if I'm in my inbox, the tavern, looking at my tasks or anything else."

**Comment by AlbRoehm** [comment]
It looks like most of the fragments are not overriding the BaseMainFragment method customTitle() expect the new ChallengesFragment, which behaving correctly. Just because it is the only one with a correct name the title is never re-set to something else.
