### ISSUE TITLE
sound effects stop playing if two are played at once (audio themes)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#701]
If you take some action that produces a sound effect and then before the sound effect has finished playing you take a second action that plays the **same** sound, then that particular sound effect stops playing for all future actions until the app is restarted.

Steps to reproduce both good behaviour and bad behaviour:

1. Wait until you've received all your drops for the day (not essential but makes it easier to hear sounds without interference from the drop notification sound).
1. Choose an audio theme that has long sounds (not essential but makes testing easier). E.g., LuneFox's Theme.
1. Click + on a Habit. Wait for the sound to start and finish completely.
1. Click + on a Habit again. The sound plays again - this is correct behaviour.
1. Click + on a Habit and wait for the sound to start then IMMEDIATELY (before the sound finishes):
1. Click + on a Habit again. The sound does not play (incorrect behaviour).
1. Click + on a Habit again. The sound still does not play (incorrect behaviour).
1. Click anything that causes a different sound (e.g., complete a Daily). That new sound does play (correct behaviour).
1. Close and reopen the app.
1. Click + on a Habit. The sound does play (correct behaviour).

_Reported by SakuraBlossoms64 (911b2b6e-60a9-4574-a99d-285511b243ee) in the Report a Bug guild; confirmed by me._

**Comment by Alys** [comment]
This is a minor bug because it's not good to click tasks too quickly because sync errors tend to happen more often.

**Comment by GuyKroizman** [comment]
@Alys , Could you confirm this was really fixed.
And also would like you to provide your opinion of #738

**Comment by Alys** [comment]
Confirmed fixed.
