### ISSUE TITLE
Pause / Reactivate your Dailies button doesn't give immediate feedback about resting in the inn

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#705]
Version 0.0.36 (149)

When you tap the "Pause Your Dailies" button, it takes effect immediately (confirmed by immediately syncing on the website), and the button's text changes correctly to "Reactivate your Dailies", however the avatar doesn't change in the app, so it looks like you are not resting in the inn. You have to go to Tasks and click the sync icon to see the avatar change. 

Similarly, if you click "Reactivate your Dailies", you do stop resting and the button's text changes correctly, but the avatar doesn't change until you sync.

If you click "Pause Your Dailies" and then **don't** do a manual sync, further clicks on the "Reactivate Your Dailies" button will always correctly start/stop resting in the inn, but the button's text stays stuck on "Reactivate Your Dailies".

The desired behaviour is that as soon as you click the button, the text on the button changes to indicate the button's new function, and the avatar changes to indicate the correct status, all without needing a manual sync.

This has also been reported in the Tavern by three people:

Katie Campbell (c7be9e1f-055f-403d-83f2-0156e014093b) 
"My dailies won't reactivate. My character keeps sleeping. Any advice would be appreciated!!"
 
jaxisjax (42892a0f-2362-4cae-8e59-ebd83317ce86) 
"I keep clicking "reactivate my dailies", but my avatar stays asleep. When I leave the tavern and come back, it offers me the reactivate button again. How can I wake up? Is my avatar hibernating?"
 
PhoenixCross (008124fe-a7eb-4738-95c5-70df91d02dd8) 
"Ok i'm trying to reactivate my dailes via the tavern but my guy is still asleep, and when i go back to the tavern it's asking for me to reactivate my dailies. How to fix? Please help"

Amplitude says they're all on Version 0.0.36 on Android 6.0.1

**Comment by saraolson** [comment]
Gonna add this to when we redo the tavern designs.

**Comment by saraolson** [comment]
This seems to be fixed for me
