### ISSUE TITLE
Dailies widget does not obey Custom Day Start time

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#706]
If you have a Custom Day Start time (CDS) other than midnight, the Android app obeys the CDS when choosing which Dailies to show but the widget does not. Steps to reproduce correct and incorrect behaviour depending on whether the current time is after or before the CDS:

1. Create a Daily with a start date of a couple of days ago and set it to be due on the current day of the week (e.g., Monday if today is Monday).
1. Create a second Daily with a start date of a couple of days ago and set it to be due on yesterday's day of the week (e.g., Sunday).
1. Set your CDS to be before the current time (e.g., if now is 8pm, set your CDS to be 7pm). This means that Habitica considers the current day to be Monday - the same as the real-world day.
1. Observe the correct behaviour: Both app and widget display the Monday Daily as due and the Sunday Daily as not due.
1. Set your CDS to be after the current time (e.g., if now is 8pm, set your CDS to be 9pm). This means that Habitica considers the current day to be Sunday, even though the real-world day is Monday, because your CDS time has not yet arrived.
1. Observe that the app displays the correct behaviour: The Sunday Daily is due and the Monday one is grey.
1. Observe that the widget is wrong: It displays the Monday Daily as due and does not show the Sunday Daily.

This was reported by osberend (bc630499-2941-4c1b-85ed-41fed2e8959e) in the Report a Bug guild:

osberend: _The Android fullscreen app respects custom day starts, but the Dailies widget (which only shows undone dailies that are due today) does not. Nothing that urgently needs fixing, just a note._

Alys: _...are you certain that the bug is as you described or could it just appear that way because the widget can be slow to update?_

osberend: _It's definitely not just a lag issue, because my custom day start of 4 AM means that the widget not respecting custom day starts results in it showing dailies that are due tomorrow but not today, i.e., it's anticipating, not lagging._
_To elaborate on that point a bit further: The widget isn't triggering cron at the wrong time, or displaying ticked-off dailies as undone. The problem is specifically that right now (just before 1 AM EST on Monday) it's showing dailies that (1) are not ticked off, and (2) are due on Monday, but (3) are not due on Sunday. Since the widget only shows dailies that are due, this is an error._

**Comment by vIiRuS** [comment]
Fixed in the next update.
