### ISSUE TITLE
Equipment check-in incentives prizes have wrong name

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#708]
As reported by Opal_owl (1c00ffd1-e6fe-4c45-860b-b34b5a11203e) in the Report a Bug guild, when you reach 60 check-ins and are given the Page Armor, the notification calls it "armor_special_pageArmor".

EDIT: The same thing occurs for head_special_pageHelm and weapon_special_bardInstrument and maybe others.

![page armor](https://pbs.twimg.com/media/C2xv6gNUcAI4WW4.jpg)

**Comment by AlbRoehm** [comment]
@Alys:  This looks to me that there is also a problem with the data of this item on the server. When i want to equip it, the text is not correctly translated (which is stored on the server) and the notifications is only displaying the name of the item which it got from the server. For me this is a litte hard to debug because i don't have a local server to mess around with the check-in counter. But from the first look i already saw some hardcoded strings which break the i18n.  I can change the strings for sure, but maybe someone else can help with the structure of notifications

![screenshot_20170124-110602](https://cloud.githubusercontent.com/assets/8029910/22242994/cc01e566-e225-11e6-949c-ff11b0c72655.png)

**Comment by Alys** [comment]
@AlbRoehm You're probably seeing the English name because the strings for the Page Armor haven't been translated yet (see below). I'm not saying there isn't a problem with the data of this item but the English text might not be related to that.

````
$ pwd; grep -r armorSpecialPageArmorText
..../habitrpg/website/common/locales
id/gear.json:    "armorSpecialPageArmorText": "Page Armor",
en_GB/gear.json:    "armorSpecialPageArmorText": "Page Armor",
sr/gear.json:    "armorSpecialPageArmorText": "Page Armor",
cs/gear.json:    "armorSpecialPageArmorText": "Page Armor",
he/gear.json:    "armorSpecialPageArmorText": "Page Armor",
bg/gear.json:    "armorSpecialPageArmorText": "Page Armor",
pt/gear.json:    "armorSpecialPageArmorText": "Page Armor",
zh/gear.json:    "armorSpecialPageArmorText": "Page Armor",
pl/gear.json:    "armorSpecialPageArmorText": "Page Armor",
de/gear.json:    "armorSpecialPageArmorText": "Page Armor",
pt_BR/gear.json:    "armorSpecialPageArmorText": "Page Armor",
nl/gear.json:    "armorSpecialPageArmorText": "Page Armor",
en/gear.json:  "armorSpecialPageArmorText": "Page Armor",
uk/gear.json:    "armorSpecialPageArmorText": "Page Armor",
fr/gear.json:    "armorSpecialPageArmorText": "Page Armor",
en@pirate/gear.json:    "armorSpecialPageArmorText": "Page Armor",
da/gear.json:    "armorSpecialPageArmorText": "Page Armor",
ro/gear.json:    "armorSpecialPageArmorText": "Page Armor",
es_419/gear.json:    "armorSpecialPageArmorText": "Page Armor",
ja/gear.json:    "armorSpecialPageArmorText": "Page Armor",
hu/gear.json:    "armorSpecialPageArmorText": "Page Armor",
it/gear.json:    "armorSpecialPageArmorText": "Page Armor",
es/gear.json:    "armorSpecialPageArmorText": "Page Armor",
ru/gear.json:    "armorSpecialPageArmorText": "Page Armor",
zh_TW/gear.json:    "armorSpecialPageArmorText": "Page Armor",
sk/gear.json:    "armorSpecialPageArmorText": "Page Armor",
sv/gear.json:    "armorSpecialPageArmorText": "Page Armor",
```

**Comment by AlbRoehm** [comment]
@Alys: Your right that should not be the problem, but my thought was, that there was no pretty name for the item and a wrong one was used. Too bad i didn't take a closer look on the other notifications, but they were probably correct?  
In PopupNotificationsManager.java 61: notification.data.reward.key is used to add the message together, but reward.key is probably not the thing we want to display. There is no way like "repair charaktervalues" to mess with the login-counter i guess?

**Comment by Alys** [comment]
The same thing occurs for head_special_pageHelm and weapon_special_bardInstrument. I haven't tested any others. I'm renaming this issue to "Equipment check-in incentives prizes have wrong name" and updating the top post.

**Comment by AlbRoehm** [comment]
I'm not sure that my PR fixed this completely, because i couldn't test it (like creating Notifications). There are probably still some issues with the names of the items itself.

**Comment by Alys** [comment]
This is happening again on version 0.0.37.4 (163)

![screenshot_20170318-131651](https://cloud.githubusercontent.com/assets/1495809/24068543/56efe8e0-0bdd-11e7-91fd-8e0294967344.png)

**Comment by DrStrangepork** [comment]
![image](https://cloud.githubusercontent.com/assets/7307373/26136564/df498fc6-3a8a-11e7-90f4-cbfe523809b6.png)

**Comment by DrStrangepork** [comment]
Is it possible that the app is just referencing the JSON for the items incorrectly?

**Comment by vIiRuS** [comment]
I think the issue is that the app might not have the full data set for the item. and the key is used as fallback.
