### ISSUE TITLE
Forgot password opens IP address in browser

### ISSUE THREAD

**Issue by kevinsearle** [HabitRPG/habitica-android#712]
Choosing "Forgot Password? Please use the mobile Website" from the native Android app causes a browser to spawn. The URL it tries to reach is 192.168.178.21:3000.

![screenshot_20170201-203448](https://cloud.githubusercontent.com/assets/54612/22535067/20427c6e-e8be-11e6-8984-9a9f1dbc1646.png)

**Comment by vIiRuS** [comment]
What app build are you using where this happens?

**Comment by kevinsearle** [comment]
I'm running 0.0.36 on a Samsung Galaxy S7 with Android 6.0.1
