### ISSUE TITLE
class bonus from INT equipment is missing

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#713]
EDIT: See the first comment on this issue for a more accurate description of what's probably happening.

EDIT: There's another issue about class bonuses which is not the same as this one but perhaps could be fixed at the same time if someone wants to work on both together: https://github.com/HabitRPG/habitica-android/issues/723

As reported by Ellyngal (5d3b72c4-d8d4-4b38-9213-5fb2093a03ee) in the Report a Bug guild:

"I reset my class/stats and switched to Mage. I have the class bonus to INT on the website, but not in the app. Here are the screenshots."

Website, showing correct equipment stats and correct class bonus:
![one](http://i1139.photobucket.com/albums/n546/Rynarda/Random-Public/HabiticaWeb.png)

Mobile app showing the right equipment but with the class bonus missing for INT:
![two](http://i1139.photobucket.com/albums/n546/Rynarda/Random-Public/HabiticaApp1.png)
![three](http://i1139.photobucket.com/albums/n546/Rynarda/Random-Public/HabiticaApp2.png)

I have replicated this on my own account as a Mage wearing the same equipment pictured above. I've also replicated it using other Mage gear. It happens even when not using a weapon, so it's not related to the Mage using a two-handed item.

I could not replicate it as a Warrior, although I tried only one gear set.

**Comment by 1810755jiawei** [comment]
小蜜蜂

**Comment by Alys** [comment]
This has also been reported by Birkwelch (310aea01-13f5-4fb6-929e-be39d63e665b), a Healer, who has noticed that the class bonus for INT gear does not appear on the app (it does appear on the website). See screenshots below.

It looks like this bug might be about the class bonus for equipment that gives Intelligence, rather than for Mages specifically. I'm changing the title of this issue from "class bonus from equipment is incorrect for Mage (maybe other classes?)" to "class bonus from INT equipment is missing".

Screenshots from the website:


![website](http://i.imgur.com/PQxPcrN.png)
![website](http://i.imgur.com/Im5TaEN.png)


Screenshots from the app:

![app](http://i.imgur.com/cEHLZjD.png)
![app](http://i.imgur.com/CcCjWYM.png)

**Comment by Alys** [comment]
There's another issue about class bonuses which is not the same as this one but perhaps could be fixed at the same time if someone wants to work on both together: https://github.com/HabitRPG/habitica-android/issues/723

(I'm about to copy that to the top post and delete this comment.)

**Comment by saraolson** [comment]
@Alys I tried checking this since we just updated stats and I seem to have my INT class bonus reported correctly in my mobile profile(2+1), and the 'equipment' total on the stats page reflects battle gear + class bonus accurately (3). Could you confirm?

However, where it lists the equipped gear in my profile, it still lists just the base +2 INT (not showing how many additional points my class bonus is giving me on that piece of gear). Is that something we want included? Or is this intended?

**Comment by Alys** [comment]
This has been fixed since it was reported. I replicated the case that Birkwelch described and that bug no longer occurs.

While it might be nice to include the class bonus in the equipment list (like `INT 2 + class bonus 1`) I don't think it's essential and is more of a feature request so I'm closing this.
