### ISSUE TITLE
Challenges will not load / refresh if member of Guilds with large challenge lists

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica-android#717]
Version: 0.0.37.1 (156)

If you are a member of guilds like the [📜 Library of Tasks and Challenges](https://habitica.com/#/options/groups/guilds/adcd6903-e3c6-4c27-a0e9-21f2e7515cd6) or [The Challenge Sandbox](https://habitica.com/#/options/groups/guilds/0cb00017-4074-435d-8b6d-717fabd7d492) your own challenge list and public challenge tabs does not populate. (Both these guilds have over 60 challenges). 

Or if your challenge tabs are already populated and then join guilds like the ones mention, the challenges tab will not refresh with any changes.

**Comment by saraolson** [comment]
Going to attach this to the challenges redo milestone which will hopefully help this.

**Comment by vIiRuS** [comment]
Is this still happening with the 1.3.3 version?

**Comment by beffymaroo** [comment]
@phillipthelen Is this still relevant?

**Comment by cTheDragons** [comment]
I have just tested it with version 1.4.3 and it is working. Thanks!

**Comment by Joseph67843** [comment]
If this is working, should this issue be closed?

**Comment by phillipthelen** [comment]
We still get a few reports from users where this is happening.
