### ISSUE TITLE
Custom build instructions

### ISSUE THREAD

**Issue by corrupt** [HabitRPG/habitica-android#721]
I just spent the better part of a day compiling the app for a self-hosted instance of Habitica and I can't really say I understand what everything means. Therefore I'm creating this issue to document what I've done, hoping you can point out things I should have done differently. Maybe eventually this can lead to better documentation of the custom build process. I'm not overly experienced with building Android apps, so maybe there's a simpler way that's obvious to an experienced developer but not me.

1. Clone repository.
2. Checkout tag 0.0.37.1.
3. Modify `$REPO/Habitica/res/values/strings.constants.xml`, change URIs to self-hosted instance.
4. Copy `habitica.properties` and `habitica.resources` as instructed.
5. Login to Firebase, create new project called `Habitica`, create two apps, `com.habitrpg.android.habitica` and `com.habitrpg.android.habitica.debug`.
6. Download `google-services.json`, copy to `$REPO/Habitica/`.
7. `./gradlew build` fails for missing Crashlytics key.
8. Create fabric.io account, visit `https://www.fabric.io/kits/android/crashlytics/install` (while logged in, important!) and copy `<meta-data />` section from _Add Your API Key_ to `$REPO/Habitica/AndroidManifest.xml`.
9. `./gradlew build` fails for _FindBugs_ plugin throwing errors.
10. Comment line  `apply plugin: 'com.chaitanyapramod.findbugs-android'` in `$REPO/Habitica/build.gradle` .
11. `./gradlew build` succeeds, copy apk to phone, sign using _ZipSigner_.

My question—apart from whether these steps are correct—is if there is a way to just disable the plugins that a custom build wouldn't use, like Crashlytics and Firebase (unless Habitica uses GMS). If these steps are correct, maybe you (or I) can modify `Readme.md` to provide better instructions.

**Comment by jcgruenhage** [comment]
This should indeed be simpler. I also just started hosting my own habitica instance, and all those libraries should not be necessary for those who build the app themselves and host their own instances.

This is also relevant for #194, since that also needs a way to build the app without all those closed source libraries.

**Comment by vIiRuS** [comment]
If a contributor wants to work on making some of the dependencies optional, I'd not be against merging that in, but the habitica team will probably not have the resources to work on this anytime soon.

**Comment by jcgruenhage** [comment]
I could maybe look into this in a few weeks.

**Comment by Alys** [comment]
If there's no objections, I'd like to have @corrupt's steps put on the wiki, along with our other documentation about coding for Habitica. That will make it easy for other Android contributors to add to them when needed. I'll arrange for that to be done in a couple of days unless anyone says otherwise.

**Comment by jcgruenhage** [comment]
I just tried building the app myself, and I needed a lot less steps:  
 - Open the project in Android Studio
 - Add the files gradle complains about (there is an example file you can just rename in each case)
 - Run the app.

To target a local habitica instance, you just have to edit habitica.properties and change the URL.

From what I have seen until now, this works just fine, I haven't tested it a lot yet though. That all of this works just fine, without any of these API tokens, gives me a lot of hope, that getting a FLOSS build shouldn't be too hard.

**Comment by corrupt** [comment]
I wasn't using Android Studio. I should probably have mentioned that.
Thing is, I don't think you should have to. If you just want to build a custom APK from the source and don't intend to work on it, you shouldn't have to run an IDE just for that.
The beauty of gradle-wrapper for me has always been that I can build most OSS projects for Android with a single shell command. And that is possible for Habitica as well, just the requirements are unclear.

**Comment by jcgruenhage** [comment]
Well, it should work about the same when using the gradle wrapper, can't test that though.
