### ISSUE TITLE
Class Bonus is incorrectly given for some Battle Gear

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#723]
As reported by Lydy (76220168-3529-4cbe-85a7-caf81e344360) in the Report a Bug guild, a class bonus can sometimes be displayed on the app when the user should not have a class bonus.

I don't know how reproducible this is or under what circumstances it occurs, but Lydy's example is below. With this equipment, there should be no class bonus. Lydy is a Warrior (possibly the [lunarWarriorArmor](http://habitica.wikia.com/wiki/Stop_the_Overshadowing_Stress) quest reward gear is being incorrectly identified as being Warrior class gear?)

```
"items.gear.equipped": {
	"shield": "shield_armoire_mysticLamp",
	"head": "head_armoire_greenFloppyHat",
	"armor": "armor_special_lunarWarriorArmor",
	"eyewear": "eyewear_special_blueTopFrame",
	"weapon": "weapon_special_pageBanner",
	"back": "back_mystery_201702"
}
```

app shows class bonus when there should not be one:
![image](https://cloud.githubusercontent.com/assets/1495809/23584866/de1d6cd0-01b9-11e7-8a79-391ba2b07386.png)

website correctly shows no class bonus:
![image](https://cloud.githubusercontent.com/assets/1495809/23584867/ea543c36-01b9-11e7-8caa-4b6691163e0e.png)

----

There's another issue about class bonuses which is not the same as this one but perhaps could be fixed at the same time if someone wants to work on both together: https://github.com/HabitRPG/habitica-android/issues/713

**Comment by TheHollidayInn** [comment]
So, the Lunar Warrior Armor is not Warrior Gear? On a side note, that seems sort of confusing :P

**Comment by TheHollidayInn** [comment]
It doesn't look like a gear issue. It seems that based on being a class you get some static bonus: https://github.com/HabitRPG/habitica-android/blob/develop/Habitica/src/main/java/com/habitrpg/android/habitica/ui/activities/FullProfileActivity.java#L442.

What is the correct formula for calculating class bonuses?
