### ISSUE TITLE
Enhancement: Party chat notifications

### ISSUE THREAD

**Issue by jaminroe** [HabitRPG/habitica-android#725]
I've been missing a lot of chats from my party since there's no notification support for it. Kind of a bummer.

I'm on OS 7.1.1 Nexus 6P

**Comment by saraolson** [comment]
Would like to add this feature in a notifications section accessible within the app (not push) similar to what web has.

**Comment by jaminroe** [comment]
Why not any push notifications for messages in my party?

**Comment by vIiRuS** [comment]
We will have to refactor some of our server infrastructure for push notifications to work correctly. We have this planned but can't tell yet when it will be implemented.

**Comment by saraolson** [comment]
i think we could try to do a small step towards this where we mark in the menu when theres activity in the party like iOS does

**Comment by phillipthelen** [comment]
Just added the indicator for party activity. Should we keep this issue open until we have push notifications or close it now?

**Comment by saraolson** [comment]
@phillipthelen i'd say keep it open and push to a later milestone until we can have true notifications of new chat activity in your party

**Comment by cvuorinen** [comment]
@phillipthelen @saraolson do you know if there are any plans to support push notifications for `@username` mentions in party & guild chats? Don't know if the push notifications discussed in this issue refer to that kind of notification or that you would get a push notification for all chat messages.

**Comment by phillipthelen** [comment]
We do have plans for that! I will most likely work on that once the upcoming iOS update is done.
