### ISSUE TITLE
User count should be fetched from the server, not a constant.

### ISSUE THREAD

**Issue by jcgruenhage** [HabitRPG/habitica-android#729]

**Comment by VarunBarad** [comment]
@jcgruenhage Which user count are you exactly talking about?

**Comment by jcgruenhage** [comment]
The one in the constant strings resource file :D 
This should be rather easy to do, although it of course has rather low priority.

It's just something I noticed while looking through the source code.

**Comment by Alys** [comment]
@jcgruenhage Please can you provide specific details? Which string (what's its exact name) in which file (what's its full path and file name)? I suspect that the user count you are talking about should not be fetched from the server, but we can't tell without being certain of which string you're referring to.

**Comment by jcgruenhage** [comment]
habitica_user_count in [this](https://github.com/HabitRPG/habitica-android/blob/develop/Habitica/res/values/strings.constants.xml) file.

**Comment by Alys** [comment]
Thanks for providing details!

It's actually deliberate that that's hard-coded. We want a round number to be displayed, as opposed to something like 2,137,712 which would look weirdly precise. We update the number when appropriate milestones are reached.

**Comment by jcgruenhage** [comment]
Technically, you could round the value before displaying it, or even before the transmission on the server, but I guess the growth of Habitica isn't that fast paced that this is really a problem ^^
