### ISSUE TITLE
Specify instance in Login/Register activity, not in build property file.

### ISSUE THREAD

**Issue by jcgruenhage** [HabitRPG/habitica-android#730]
It would be nice, if people who run their own instance of habitica for privacy reasons wouldn't have to compile the app themselves, but instead could just set the server they want to connect to on the login page.

**Comment by Alys** [comment]
Just as a note about this:

We had that feature on the original version of the app, a long time ago. Non-technical users were confused by it and would sometimes enter their own website addresses (e.g., a personal blog). I suspect that even if a description of the feature was provided on the login page, it would still cause confusion and misuse because people often don't read descriptions. The app needs to seem simple to use and not confusing for non-technical users otherwise they'll be less likely to use it.

**Comment by jcgruenhage** [comment]
Is there screenshot of that somewhere? Even though you're right about confusing non-technical users, I think hiding it away would be a lot better than having to compile the app, especially since this blocks auto-updates, and is not exactly trivial (harder than hosting your own instance with docker). Would there be a starting point, what needs to be changed?

**Comment by citrusella** [comment]
If we're talking the old HabitRPG app (the one that stopped working with API v2's being disabled), this is what it looks like, I believe.

![screenshot_2017-03-29-14-22-46 1](https://cloud.githubusercontent.com/assets/14182450/24470208/1e7989be-148c-11e7-9e43-ed627996b02b.png)

(Mine was filled in with "http://habitica.com" when I opened the app; I just blanked it out for the picture.

And here's the PR that introduced it (as far as my untrained eye can tell): HabitRPG/habitrpg-mobile#271

**Comment by jcgruenhage** [comment]
Ahh well.. If I do a PR on this, there would be at least 3 clicks, including a dialog that everything beyond this point is unsupported, to change this, not a simple text edit field below the password. This really is to confusing for non-tech users :D

Thanks for sending this :)

**Comment by Alys** [comment]
@jcgruenhage  Would you like to describe what the first step in accessing the field would be? For example, would there be a small link on the current login form?

@citrusella Nice work!!

**Comment by jcgruenhage** [comment]
First of all: WOW, I just went ahead to change up the layout to show how I think the UI Stuff for this should be done, and the new login/register activity is damn impressive.

Now, onto business: I'd use a small text view saying "Advanced Login", like this:

![screenshot_20170330-125812](https://cloud.githubusercontent.com/assets/6861958/24501230/e69092d2-1548-11e7-849d-136df899c6d9.png)

After a click on that, there is an AlertDialog, telling the user that using this is strictly not recommended and unsupported, that they can not play with friends and that this basically breaks most of the game.

After clicking on continue anyway, they will get another alert dialog with the three login fields as seen in the screenshot from the old app above.

**Comment by jcgruenhage** [comment]
The problem I have right now, is that I don't know where to store the API Endpoint entered, so that the app uses that instead of habitica.com

**Comment by jcgruenhage** [comment]
I also have to say, that I learn a lot looking through your code, that will definitely help me with other apps ^^

**Comment by vIiRuS** [comment]
I linked this to our designer (who also designed the new login screen) to see if she has some input on how we could handle this best.

From a technical perspective, storing the server url the SharedPreferences seems like the right place. During the app startup/injection, the HostConfig gets passed the SharedPreferences and could check if there is a custom hostname set. Although I think I'd prefer it, if that part was pulled out of the HostConfig constructor and instead we have daggere provide the hostname, port, username and api token to the HostConfig constructor.

**Comment by jcgruenhage** [comment]
The first alert dialog would look something like this:
![screenshot_20170330-145440](https://cloud.githubusercontent.com/assets/6861958/24505123/0d5cb886-1559-11e7-94e3-85bccd2058cf.png)


About the request made, I'd not save the API endpoint until the user has successfully logged in, using the advanced login path described above, and instantly delete it again, if the users logs out. This way, he can't really screw anything up. Using the normal login activity, he always lands on habitica.com.

Will that satisfy your request @vIiRuS ?

**Comment by jcgruenhage** [comment]
Since I still have other things to do, the second dialog took some time, but here it is:

![screenshot_20170330-184424](https://cloud.githubusercontent.com/assets/6861958/24515876/2804b7d6-1579-11e7-8740-804e6257cd3b.png)

Is that alright, from the UI side of things? I'll change some text for the register activity, so that it fits that better, and add the additional fields to the second dialog, but apart from that, does that look okay to you?

**Comment by citrusella** [comment]
> @citrusella Nice work!!

@Alys No problem! I'm glad my resistance to delete apps I won't get back (even useless ones) came in handy for once! :smile: \*skedaddles out of here since the conversation since then is different and I don't/can't have input on it XP*

**Comment by jcgruenhage** [comment]
I just need to take the HostConfig constructor and change the address assignment to check the preferences first, right? Is there a reason, why the HostConfig takes in a SharedPreferences object, and never uses that? It creates a new one instantly:

```java
    public HostConfig(SharedPreferences sharedPreferences, Context context) {
        SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(context);
        this.port = BuildConfig.PORT;
        this.address = BuildConfig.DEBUG ? BuildConfig.BASE_URL : context.getString(R.string.base_url);
        this.api = prefs.getString(context.getString(R.string.SP_APIToken), null);
        this.user = prefs.getString(context.getString(R.string.SP_userID), null);
    }
```

**Comment by jcgruenhage** [comment]
I tried that, but I get "Oh you must be new here" every time since that, with some justin introducing me to habitica in an endless loop :D

**Comment by jcgruenhage** [comment]
I have gotten it to the point, where clicking on login restarts the whole activity.. But when I force stop the app and launch it again, I have successfully logged in. I still have that infinite introduction loop though..

**Comment by negue** [comment]
Comment out this line https://github.com/HabitRPG/habitica-android/blob/develop/Habitica/src/main/java/com/habitrpg/android/habitica/HabiticaBaseApplication.java#L113 

It isn't an error on your side, @vIiRuS  just needed a never-ending-loop while working on it :)

**Comment by jcgruenhage** [comment]
Ahh well :D Thanks :)

**Comment by jcgruenhage** [comment]
Now I just need to find out, why the login activity restarts instead of logging me in ;D

**Comment by phorcys420** [comment]
Why was this closed ? The feature still isn't implemented (atleast that I know of).
if the concern is for the user experience, it could still be implemented like how Bitwarden does that if @jcgruenhage's UI choice isn't accepable for some reason.

https://user-images.githubusercontent.com/57866459/148111529-092a806f-de49-4d17-be75-f2be82b233c4.mp4

As far as how they store it code-wise, https://github.com/bitwarden/mobile exists I guess.


I am pretty impressed that no one re-opened this since 2017.

**Comment by citrusella** [comment]
Perhaps it's possible it was closed because the opener and requestor let it get stale and/or couldn't figure it out? (And then maybe wasn't re-opened because no one else expressed interest? \*shrug*

**Comment by OptimusGREEN** [comment]
Can this be reopened please?
