### ISSUE TITLE
Check-in prize when you have all available prizes gives wrong next check-in count

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#732]
As reported initially at https://github.com/HabitRPG/habitica/issues/8573, when you have obtained all the available check-in prizes, the message you get for the final prize is incorrect. It says "Your next prize unlocks at 0 Check-Ins" (screenshot below).

As described by Lemoness in her comment below, it should say: 
**"You have received all the Check-In prizes currently available! More will be added in the future."**

The code that defines the prizes is in https://github.com/HabitRPG/habitica/blob/develop/website/common/script/content/loginIncentives.js -- i.e., you can use that content data and the user's `user.loginIncentives` count to determine if the user has been given the final prize.

_Note that at some time in the future, we will stop adding new check-in prizes (ref: [Lemoness's comment](https://github.com/HabitRPG/habitica/issues/8573#issuecomment-288570486)) and at that time the message will be changed._

![image](https://cloud.githubusercontent.com/assets/1495809/24246448/195e7fde-1013-11e7-9ea5-3257c635d004.png)

The iOS version of this bug is at https://github.com/HabitRPG/habitica-ios/issues/447

**Comment by lemoness** [comment]
For wording, I'd suggest "You have received all the Check-In prizes
currently available! More will be added in the future."
