### ISSUE TITLE
Wintery Skins are mixed in with Basic Skins

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#733]
Under Avatar > Skin, the Wintery Skins are mixed in with the Basic Skins (instead of being separate as for the other skin types).

![image](https://cloud.githubusercontent.com/assets/1495809/24328292/c4d6e2f4-1228-11e7-9f10-37296d755226.png)

----

The website is correct:

![image](https://cloud.githubusercontent.com/assets/1495809/24328270/5087c8dc-1228-11e7-8c02-0d15e851dd67.png)

![image](https://cloud.githubusercontent.com/assets/1495809/24328273/5a4ae5b6-1228-11e7-9b3d-11a4fa490ab7.png)

----

The iOS app also has this bug: https://github.com/HabitRPG/habitica-ios/issues/452

**Comment by Alys** [comment]
Also when trying to equip a Wintery Skin, an error occurs:
"Must purchase {skin name} to set it on preferences.skin".
I found that on my account and I do own the skins.

**Comment by Alys** [comment]
Might be fixed by this PR when it goes live: https://github.com/HabitRPG/habitica/pull/8645

**Comment by SabreCat** [comment]
That PR was merged in a while ago. Is this issue still occurring?

**Comment by Alys** [comment]
That PR dnes seem to have fixed it.
