### ISSUE TITLE
players who have opted out of the class system can use Warrior skills and see Mana and see Stats Points options

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#739]
When a player has opted out of the class system, they are still able to cast the Warrior skills. They should not have access to any class skills.

A player who has opted out can be identified by `preferences.disableClasses` set to `true`

Note that they should still have access to the [transformation buff](http://habitica.wikia.com/wiki/Transformation_Items) skills (Snowball, Shiny Seed, Seafoam, Spooky Sparkles) so this issue should not be fixed by making the skills menu unavailable. For more information about that see https://github.com/HabitRPG/habitica-android/issues/740

**Comment by Alys** [comment]
In addition, as reported by ichwersonst (b36efa14-7457-4bc5-8849-5e3d3f29f6cc) in the Report a Bug guild:

Another minor bug is that I receive messages of losing mana when I check into the website, even though I am 'not supposed to' have mana

**Comment by Alys** [comment]
Additional information from Ehsanit (6e19bb02-7661-4ceb-b43c-fd8dfc31d010) in the Report a Bug guild:

"I am a level 11 default warrior, in that I have not enabled the class system. If I open the android app in the default tasks view, there is no mana bar and no Skills entry in the menu. (As expected) However, if I go to the Party view, this changes and the menu gains a Skills entry. Choosing it shows me as having access to Brutal smash and 52 mana. Similarly when I return to the tasks view from Party view, I show as a level 11 warrior with 52 Mana. (Refreshing returns it to normal)"

**Comment by vIiRuS** [comment]
This will be fixed in the next update. The last comment was the missing clue for why this was happening!

**Comment by Alys** [comment]
I'm reopening this because it's happening again. I have `preferences.disableClasses` set to true and I can see all the Warrior skills. I was able to successfully use one of them (I didn't test the others). I can see the mana bar in the header. When I complete a task, the notification at the bottom of the screen shows me that I get mana.

The expected behaviour is that there should be no class skills in the Skills tab (however transformation buffs should still appear there), and there should be no mana in the header and no mention of mana when tasks are ticked or unticked.

**Comment by Alys** [comment]
Also when you've opted out, on the Stats screen you see the "Auto Allocate Points" setting in the Stats screen and if you try to enable it, it toggles itself on and off repeatedly while you're on that screen. I believe the expected behaviour is that you shouldn't see the points allocation section at all.

**Comment by Alys** [comment]
Confirmation that you shouldn't see the points allocated section when you've opted out: https://github.com/HabitRPG/habitica/issues/9826
