### ISSUE TITLE
Wrong message when using a saddle or feeding a pet until it's a mount (says "hatched" not "tamed")

### ISSUE THREAD

**Issue by thatscoteng** [HabitRPG/habitica-android#742]
When using a saddle raise a pet into a mount, received a message that I had hatched said pet.

Not sure if this is just the android app or the website as well (don't have enough saddles to test further 😉)

**Comment by Alys** [comment]
Confirmed, and feeding a pet with food until it's a mount also produces the same wrong message:
"You hatched a desert peacock"

It doesn't happen on the website, which returns this message from the API: 
"You have tamed Shimmer Fox, let's go for a ride!"

**Comment by amohnacs15** [comment]
So is this an API issue or an issue with the hardcoded string resources?

**Comment by Alys** [comment]
@amohnacs15 I think not API, but you can test that by feeding a pet using the API until it's fully fed. See http://habitica.wikia.com/wiki/Application_Programming_Interface for information about using the API.

**Comment by thatscoteng** [comment]
Just checked the API and got the response message "You have tamed Fairy Wolf, let's go for a ride!" - so definitely not API but the Android App.

**Comment by LunarGem** [comment]
I could try to fix this, if someone hasn't taken it already.
