### ISSUE TITLE
PM notifications are not localized correctly -- the sender's language is used instead of the recipient's.

### ISSUE THREAD

**Issue by khipkin** [HabitRPG/habitica-android#750]
When a German Habitica user PMs me, the PM notification gets localized in German (instead of English, which is what my account uses). All other notifications I receive are correctly localized in English.

**Comment by vIiRuS** [comment]
This is an issue with the server and not the app directly. I created an issue in the habitica repository https://github.com/HabitRPG/habitica/issues/8718
