### ISSUE TITLE
speed improvement in emoji parser

### ISSUE THREAD

**Issue by ioanb7** [HabitRPG/habitica-android#751]
Hi,

I've spent a lot of time drilling down on why my habitica is so slow when scrolling through tasks and I've found the bottleneck and fixed it.

Habitica right now is using 'com.github.viirus:emoji-lib:0.0.3.4'. What's the different between this and "Data5tream/emoji-lib" ? Should I merge my changes in viirus's lib?

User ID: eeaa2757-fb24-49f9-afbf-1104e94bf70a

**Comment by vIiRuS** [comment]
The difference is that the version from data5tream has a dependency to
guava, which is a huge library thst was only used for one class. My version
does not have that dependency. A PR with a speed improvement should be made
on my clone.

-- 
Phillip Thelen
Sent with Airmail

**Comment by ioanb7** [comment]
I've created the PR at: https://github.com/vIiRuS/emoji-lib/pull/1
Speed improvement video comparison: https://www.youtube.com/watch?v=ODOsXUjYVk0

**Comment by vIiRuS** [comment]
Merged in the PR and updated the library in the app. Thanks!

I also noted this contribution in your habitica profile!
