### ISSUE TITLE
Handle the "Note to Self" intent

### ISSUE THREAD

**Issue by infomofo** [HabitRPG/habitica-android#752]
I just discovered this app and it's amazing- I've used it to replace a variety of other habit tracking, daily routine and calendaring, and todo list apps.

However one feature that I can't seem to find in habitica is the integration with the "Ok Google, [Note to Self](https://developer.android.com/training/wearables/apps/voice.html)" intent. 

If there is a different keyword or a workaround that lets you add Habitica Todos using a voice trigger from the Google Now or Android Wear interface that I just haven't been able to figure out, please let me know.

**Comment by veeeeeee** [comment]
We're closing this in favor of #482, which should also support this feature
