### ISSUE TITLE
message posted to Tavern containing banned words disappears (can't be edited)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#756]
On the website, when you try to post a message to the Tavern with one of the [banned words](https://github.com/HabitRPG/habitica/pull/8197) in it, you're notified that your message can't be posted and it remains in the message entry box for you to edit it.

On the Android app, you see the notification but your message is removed, meaning that you have to type it from scratch. The ideal behaviour is that the message remains for editing.

**Comment by lemoness** [comment]
I'm upping the priority on this because we've had to field several complaints from users about us "deleting their posts" because they didn't know that our swearword blocker was as stringent as it is.

**Comment by emily-keller** [comment]
I'd like to work on this issue.

**Comment by saraolson** [comment]
@emily-keller it's all yours! i'm taking off the help wanted label and adding the in progress label to give you claim

**Comment by saraolson** [comment]
@emily-keller hello! checking in to see how you're doing on this issue. are you still working on it? or do you have questions that we can help you with?

**Comment by emily-keller** [comment]
@saraolson hello! I'm making progress!
