### ISSUE TITLE
Only the beginning of long task notes can be read (in a practical way)

### ISSUE THREAD

**Issue by MegaDerf** [HabitRPG/habitica-android#758]
If a task's note is too long, only its first three lines are shown. This makes the task list tidier, but there's no practical way to read the rest of the text. The only way to read the whole note would be to go in the edit screen of the task, but reading it from there is a tedious and unpractical process. I think the best way to fix this problem would be to add a "read more" button at the end of the tasks that have long notes.

Here are some pictures:

The task seen on the website:
![taskwebsite](https://cloud.githubusercontent.com/assets/27898124/26025595/967b89f8-37eb-11e7-86f2-54112002398a.png)

The task seen on the app:
![taskapp](https://cloud.githubusercontent.com/assets/27898124/26025599/9b89eeda-37eb-11e7-9061-0f44c4dff1d2.png)

**Comment by LunarGem** [comment]
If this is a feature we are looking to add (I personally would love it) I'd like to try!
