### ISSUE TITLE
The Shops->Quests menu shows wrong unlock methods

### ISSUE THREAD

**Issue by StefanoTrv** [HabitRPG/habitica-android#765]
In the Shops->Quests menu, all the quests that can't be purchased with gold or gems have the same string next to them that explains how they can be unlocked: "Unlock by inviting friends". This is correct for only "The Basi-List" quest, while the others have different unlock methods.

These are the quests in the website:
![quests](https://cloud.githubusercontent.com/assets/27898124/26530419/be18145a-43d4-11e7-8632-2bb1c0ddac71.PNG)

And this is the shop in the app:
![screenshot_20170528-181955](https://cloud.githubusercontent.com/assets/27898124/26530435/d2d77afc-43d4-11e7-82c5-3bd802d1a68d.png)

![screenshot_20170528-182002](https://cloud.githubusercontent.com/assets/27898124/26530437/d71c7f72-43d4-11e7-8c3b-7357e92aa66a.png)

**Comment by LunarGem** [comment]
I noticed this, I could attempt to fix it if someone hasn't already started.

**Comment by SabreCat** [comment]
This will require some changes on the main Habitica repo. Basically, we need to define a new unlock method, and ensure that Android can handle it. (We originally did have separate unlock methods defined in the content files, but because Android didn't have cases for them, it crashed the app.)

**Comment by LunarGem** [comment]
Is there an issue for this in the main repo? I could still try to do it.

**Comment by SabreCat** [comment]
Looks like we didn't, but I've added one! See the reference above.

**Comment by LunarGem** [comment]
Can someone tell me where the code that `com.habitrpg.android.habitica.R` refers to is? I'd like to make sure that my returns are correct instead of just guessing and copying from the other one.

**Comment by vIiRuS** [comment]
The strings are in the res/values/strings.xml files.

**Comment by LunarGem** [comment]
I'm not finding the strings I'm looking for in that file. Should I add them or am I just overlooking them? @vIiRuS

**Comment by vIiRuS** [comment]
Which strings exactly are you not finding?

If I understood it correctly, the server will respond with the translated unlock text, right? In that case for the app the best solution would probably be to change the seitch statement to return the text from the field if it is not found in the switch statement. So instead of returning 0 it returns the unlock condition directly. Since in the future that would already be the translated text. That way we wouldn not have to coordinate an app update with the server change.
In the meantime additional cases can also be added to the switch statement to handle that if needed.

**Comment by LunarGem** [comment]
@vIiRuS I found the one that corresponds to "party_invite" but none for the login incentives or for creating an account. I can definitely change the return in the way you describe. Whether or not the strings/switch cases are added just depends on what you guys want the user to see, just "login incentive" or something like "log in to Habitica regularly".

**Comment by LunarGem** [comment]
@vIiRuS Okay I understand around 20x more about Android dev than I did last time I checked in. My dev computer is out of commission atm but I understand enough to be able to fix this rather quickly anyway (will just need someone to test it for me as I won't be able to).

**Comment by MFausB** [comment]
Hey, I will investigate this issue.
