### ISSUE TITLE
App Crashes when editing Task Checklist items

### ISSUE THREAD

**Issue by renodubois** [HabitRPG/habitica-android#766]
Haven't left an issue here before, so apologies if I use wrong terminology to refer to things.

On tasks that have multiple checklist items, my app crashes as soon as my keyboard loads in that checklist's text field.

My Habitica app is on version 1.0.3 (1899), and I'm running Android 7.1.2 on a Nexus 5X.

**Comment by vIiRuS** [comment]
Hey,

Can you tell us your habitica user ID? Then we can look into this better. You can find that in the apps settings under Account Details.

**Comment by renodubois** [comment]
Here ya go: e8d7206b-a058-4107-83f8-68d02d4c4e8d
