### ISSUE TITLE
Crash when creating a Challenge

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica-android#767]
Can't create Challenges in 1.0.3. Navigate to Challenges, hit ... menu, Create Challenge: "Unfortunately, Habitica has stopped."

**Comment by caipivara** [comment]
@SabreCat still an issue? Im trying with `1.2.2` and it let me open the new challenge view

**Comment by SabreCat** [comment]
Looks to have been fixed at some point!
