### ISSUE TITLE
Active Filters number is confusing

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica-android#770]
In task list views, there is a numeral in a colored bubble in one corner of the filter control, denoting how many filters are currently active. That UI convention, however, is more of an "unread messages" cue, causing some confusion and frustration in that it draws the user's attention to something that doesn't actually need to be attended to and cleared out. I know we want a "filters are active" cue to keep users from being confused about why some tasks have "disappeared", but might there be a better way? Maybe invert the filter button to purple-on-white when some tasks are filtered out, no need for a number?

**Comment by olson5504** [comment]
on the case
