### ISSUE TITLE
head_special_bardHat is not displaying text correctly.

### ISSUE THREAD

**Issue by TheHollidayInn** [HabitRPG/habitica-android#778]
Report from the bug guild: 'Hi, I unlocked a check in prize for three days check ins and in the Android app it says: 'you earned a head_special_bardHat as a reward...' Looks to me like it's supposed to display the name of the item differently. '

This could also be an issue with the API.

**Comment by Alys** [comment]
We have this reported at https://github.com/HabitRPG/habitica-android/issues/708 :)

**Comment by TheHollidayInn** [comment]
Ah, thanks!
