### ISSUE TITLE
Get reminder for daily which is not due today

### ISSUE THREAD

**Issue by Mupje** [HabitRPG/habitica-android#779]
I've reported this in the Report a bug guild, and this is what Alys advised:
"There's nothing wrong with the Daily's repeat settings, so can please report it to the app developers through the app's menu at About > Report a Bug? Tell them that the task's ID is ffa10543-c236-451d-bae7-b00956a682af"

**Comment by saraolson** [comment]
Writing more details within the github ticket on what happened would be helpful
