### ISSUE TITLE
remove flag menu item from system messages in chat

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#785]
As described in https://github.com/HabitRPG/habitica/issues/8824, the flag menu item should not be present for any messages where `uuid` is `system` (e.g., party quest progress messages).

After this is finished, we should make a note that it's been done in https://github.com/HabitRPG/habitica/issues/8824 since that issue is waiting on this one.

**Comment by HackerShark** [comment]
If no one else is working on this, I can take a crack at it.
