### ISSUE TITLE
First app open after cron does nothing until website is accessed

### ISSUE THREAD

**Issue by maiatoday** [HabitRPG/habitica-android#786]
The first time I open the android app after cron does not update the screen. (See screenshot). It does access the `GET https://habitica.com/api/v3/user/ http/1.1` and `GET https://habitica.com/api/v3/tasks/user http/1.1` and gets a 200 result on both `200 OK https://habitica.com/api/v3/tasks/user` and `200 OK https://habitica.com/api/v3/user/ `

You can open and close the app repeatedly it has the same behaviour.

If you leave the app open and then go into the website. The checking dialog shows, no need to go further. 

On subsequent api calls in the app the screen updates correctly.
![device-2017-06-22-085443](https://user-images.githubusercontent.com/440744/27421217-c7e58734-5729-11e7-82f2-199927006934.png)

**Comment by vIiRuS** [comment]
Is this with the most recent git status or the play store build?

**Comment by maiatoday** [comment]
It is a local debug build, I'll update to the latest develop and test again tonight.

**Comment by maiatoday** [comment]
I retested with latest develop commit at 34171b07 merged into my repo and the fault no longer occurs. False alarm sorry, we can close the ticket.
