### ISSUE TITLE
Habit Widgets broken after 1.1 update

### ISSUE THREAD

**Issue by salfej** [HabitRPG/habitica-android#788]
After updating to the latest version of Habitica on android (version 1.1), habit widgets are no longer working as expected. All personal habit widgets have been replaced with skeleton widgets that hold no content and are unresponsive to interaction. Deleting the widgets and recreating them does not fix the issue. 

- Android Version 6.0.1

![image](https://user-images.githubusercontent.com/10404888/27916904-109f9db4-6230-11e7-86a8-88bcbc750f5c.png)

**Comment by salfej** [comment]
So, I signed up for the beta through the Google play store, and upgrading to v1.1.1 (1907) has fixed the issue. You guys work fast! 
![screenshot_20170706-161345](https://user-images.githubusercontent.com/10404888/27933422-f1e8a334-6266-11e7-855f-37a4cf247cba.png)

**Comment by salfej** [comment]
Was testing the habits in the new update, and negative habits weren't returning messages until I turned my device sideways? They're showing up after doing something.... The widgets seem to be fully functional now.

**Comment by vIiRuS** [comment]
Is this with the regular habits in the app where it's not showing or the widgets?

**Comment by salfej** [comment]
Just the widgets. The in-app habits are all fine and functional.
