### ISSUE TITLE
Can't mark checklist items as "done"

### ISSUE THREAD

**Issue by Blaisorblade** [HabitRPG/habitica-android#789]
I think this used to work but broke recently. I've confirmed this issue with checklist items in dailies and TODOs, got no habits with checklists.

Currently, I just find no way to mark checklist items as done via the Android app. To reproduce, a reliable way is as follows:
- tick checklist item as done (EDIT: and confirm visually the item is ticked).
- refresh, or tick the parent daily/TODO itself;
- checklist item is not marked as done.

**Comment by Blaisorblade** [comment]
I can't find a page collecting info to attach to reports, but here's what I got (based on https://github.com/HabitRPG/habitica-android/issues/669#issuecomment-276624780):
- Nexus 5X with all updates, Android 7.1.2 fully updated (5 July 2017 patch, build N2G47Z).
- Habitica 1.1.3 (1916) according to its "about Info".
- Happens also right after a clean launch of the app.

**Comment by vIiRuS** [comment]
Can you confirm that if this is still happening int he most recent version?

**Comment by Blaisorblade** [comment]
Not any more, thanks for fixing this and sorry I didn't close it earlier—I honestly forgot the issue!

**Comment by vIiRuS** [comment]
No problem. Thanks for the quick update!
