### ISSUE TITLE
Crash when creating Daily with Reminder

### ISSUE THREAD

**Issue by davidgsharpe7** [HabitRPG/habitica-android#792]
1) Create a brand-new Daily
2) Before hitting save, set up a reminder
3) Hit save
4) You are returned to the main screen, the daily does not appear in the list, and a couple seconds later, the app crashes

Workaround: 
1) Create the Daily with everything except the Reminder
2) Save it
3) Edit it, set the reminder
4) Save it

**Comment by artem-p** [comment]
Cannot reproduce it. Works fine.
