### ISSUE TITLE
Global Notification Support

### ISSUE THREAD

**Issue by LunarGem** [HabitRPG/habitica-android#794]
Not sure if I'm using the right language for this, but I wanted to work on having the same notification support on the app as on the website. The inbox notifications do not currently appear to be working, and having guild and party notifications would be nice as well. I would do the code for this if it were something we were looking to implement.

**Comment by saraolson** [comment]
We'll be adding something like this after web finishes their notification rehaul and we finish a menu rehaul

**Comment by cvuorinen** [comment]
Has there been any progress/discussion/design on this issue? It's the main reason I keep switching between the mobile app & website, so would be nice to get the notifications in the mobile app.

cc @phillipthelen

**Comment by saraolson** [comment]
@cvuorinen there hasn't been any progress on this feature just yet, though I believe the notification rehaul was completed and we did the part of the menu update we had planned. 

Are you still interested? If so, I'll discuss the me shifting my priorities to making designs with the team so you'd have something to work off of.

**Comment by cvuorinen** [comment]
Yep, I'm still interested. Especially now since the website updated the menu and notifications is not usable on mobile through the website anymore (though I do hope it gets fixed soon).

**Comment by saraolson** [comment]
@cvuorinen great! alright, i'll work on adapting designs to mobile and give you links to the mockup by the end of the week hopefully with some notes from us on how it we're thinking it might behave. after that, we'll probably just ask for you to brief us on your plan of attack then let you go at it!

**Comment by saraolson** [comment]
Alright! Designs are finished and approved. We use Zeplin to handle our mockups. Can you give me an email address you'd like to use to access the Zeplin project board so I can invite you?

After gaining access, mockups can be found here: [Zeplin Designs](https://zpl.io/anpdePQ)

Our notes on which notifications to include in the mobile implementation and what tap areas should do can be found on this google sheet for reference: [Mobile Notification Breakdown](https://docs.google.com/spreadsheets/d/1I76AKl9chH_FHTpcjpqDNcsCat4mNdPp0gtPSGYN130/edit#gid=0)

Let us know if you have any questions now or throughout the process :)

**Comment by saraolson** [comment]
oops i forgot to tag you in my previous comment, @cvuorinen. designs are ready!

**Comment by cvuorinen** [comment]
@saraolson carl.vuorinen@gmail.com

**Comment by saraolson** [comment]
@cvuorinen thankya, sent you an invitation

**Comment by cvuorinen** [comment]
I think I need some help with some of this, since I haven't done that much Android development (web dev is my main expertise). 

For example what tool should I use to create the icon assets? Looks like they are in webp format in multiple different sizes, is there some tool that generates these automatically or should I export manually to each size? Should they be lossy or lossless? I don't have Photoshop but I do have Gimp, so I can probably figure out how to make them, but wanted to ask if there's some preferred way to do them or some helpful advice. Thanks.

**Comment by saraolson** [comment]
@cvuorinen 

i've update all of the icon files so they'd be exportable as png's from zeplin. you should be able to click on an icon from the mockup now and see the 'export as png' options. (see screenshot below). 

<img width="800" alt="exporting_icons_from_zep" src="https://user-images.githubusercontent.com/12453119/53758303-9d2f2680-3e8b-11e9-9699-68deb3d6ac7b.png">

After you get the .pngs from here you can use android studio to convert them to webp (or just submit the PR using the .pngs and Phillip will handle converting them). We use mdpi, hdpi, xhdpi, and xxhdpi. You can trash the xxxhdpi version of the icon as we don't use that size. 

Some icons, like the difficulty stars, are already included in the HabiticaIcons class. You should be able to pull them from there.

**Comment by cvuorinen** [comment]
@saraolson Thanks a lot, I'll look into it.

**Comment by phillipthelen** [comment]
The first version of this was merged in and will be included in the next beta build.
