### ISSUE TITLE
task attributes have old names (physical, mental, social, other)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#796]
When you edit a task in the app, the Attributes drop-down menu contains the old names for the attributes (e.g., Physical) instead of the names we use now on the website (Strength, etc).

Physical = Strength
Mental = Intelligence
Social = Constitution
Other = Perception

_(I had thought we already had this recorded so this might be a duplicate. I can't find the old one though. EDIT: cTheDragons has confirmed this happens in the iOS app too. Logged here: https://github.com/HabitRPG/habitica-ios/issues/476)_

**Comment by gunnaveen** [comment]
Hey,
I was thinking I might be able to tackle this but I'm unable to recreate the issue that you're taking about. I don't see a Attributes drop-down menu when editing tasks in my app. Where is the attributes drop down located?

**Comment by Alys** [comment]
It's just under the Difficulty drop-down. You might not see it if you're using an account that has never reached level 10 - I'm not sure about that but it's one thing that might explain why it's not there for you.

**Comment by MrTequila** [comment]
Hello,

I would like to start contributing to Habitica with this issue if it's possible. I have found occurrences of those Attributes in values.xml and static variable in R.java. Should I change all of those? 
And also values.xml files for translations should be changed ? Or this is managed separately like in Habitica website translations ?
Thanks for your help.

**Comment by vIiRuS** [comment]
The values in the R.java file are generated and should not be changed.
The strings in the values/strings.xml are the ones that would need to be
changed. Translations are then later handled through transifex


-- 
Phillip Thelen
Sent with Airmail

**Comment by MrTequila** [comment]
Thank you for clarification. Then I'll make changes in values/strings.xml as you pointed.
