### ISSUE TITLE
Custom Rewards have different titles on app, from computer version.

### ISSUE THREAD

**Issue by jamesjpk123** [HabitRPG/habitica-android#797]
In this photo, is my rewards list of custom rewards created from challenges on computer habitica:
![capture](https://user-images.githubusercontent.com/18013689/29220946-0f3ff958-7e7a-11e7-81fa-827719f9838f.PNG)
In this photo, is my rewards list of custom rewards created from challenges on mobile habitica:
![img_0146](https://user-images.githubusercontent.com/18013689/29220982-35707300-7e7a-11e7-9314-e74ba91e383b.PNG)
See the difference? The second picture includes the part of the title that gives the challenge a photo. I propose on mobile, that this part is not shown to the user.
Ex: ![*image alt*](*image url*)*Image Title* should only show *Image Title*.
So, "![balist] (https://s2.postimg.org/m7d7jndu1/ballisa.png)Fire the Ballista!" should only show in the title of the reward "Fire the Ballista!"

**Comment by Alys** [comment]
Thanks for your report! In the case of your two Rewards where the images are there to add flavour, it wouldn't matter so much if they weren't shown, as you suggest, however other players might have tasks with images that are important to the meaning and so it would be helpful for them for the images to be shown in the mobile apps.

**Comment by jamesjpk123** [comment]
Oh, sorry if my text wasn't clear @Alys. I meant that the images would still be shown, but the messy text in the title wouldn't.

**Comment by LunarGem** [comment]
I could try to show the images, found some code on StackOverflow that I should be learning, great way to figure out if I know what I'm doing.

**Comment by jamesjpk123** [comment]
@LunarGem, that would be amazing!

**Comment by vIiRuS** [comment]
Which code would this be? Is it compatible with the markdown library we are using?

**Comment by LunarGem** [comment]
The second answer [here](https://stackoverflow.com/questions/5776851/load-image-from-url) or perhaps something else. I believe it's just an ImageView and internet permissions, but not sure what would mess with the markdown library.

**Comment by LunarGem** [comment]
I could also try to use Glide or Picasso.

**Comment by vIiRuS** [comment]
I don't think that actually helps in this case. Since the problem is about images embedded in the markdown. Which means there is not imageview that can be used to display any images, since they have to be embedded in the text.

**Comment by LunarGem** [comment]
Which markdown library do we use? Perhaps I could troubleshoot or find a workaround. An interesting idea would be allowing the user to set the custom reward image like the official rewards have. Then we could potentially not need this... Any thoughts? I'm just brainstorming.

**Comment by Alys** [comment]
@LunarGem The user might want to use two or more images in a Reward (or in any of their tasks), so allowing them to do that with markdown is the most flexible solution. The website uses this markdown library: https://github.com/HabitRPG/habitica-markdown
I have no knowledge of how the app does markdown. :)

**Comment by LunarGem** [comment]
@Alys Did we have any plans of letting users set custom rewards images, though? It's something I've really wished were possible. I'll see what I can do looking at the library.

**Comment by vIiRuS** [comment]
setting custom images through markdown is possible (as alys mentioned), but we don't have plans to allow users to set a custom image that appears on the left side of the reward.

The Android app uses [CWAC Anddown](https://github.com/commonsguy/cwac-anddown) for markdown.

**Comment by LunarGem** [comment]
Okay so I've been thinking about this, and it looks like the images are recognized for what they are but aren't loaded. Any clue why that might be?

**Comment by vIiRuS** [comment]
I haven't looked further into how the images are currently handled yet. The original PR where markdown support was added can be found here: https://github.com/HabitRPG/habitica-android/pull/348 maybe there is some more info there.

**Comment by vIiRuS** [comment]
created an issue that better describes what is needed https://github.com/HabitRPG/habitica-android/issues/904
