### ISSUE TITLE
Record Yesterday's Activity (RYA) screen appears too early

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#798]
The RYA screen can appear earlier than it should. This happened to me around 1am my time this morning.

Background information:
- My Custom Day Start time is 6am. That hasn't changed for a few weeks.
- My time zone is UTC+10 on all my devices. I've confirmed that on my phone by using habitica.com's Settings > Site page in my mobile browser. My time zone hasn't changed for two months.
- My cron yesterday ran correctly at 2017-08-11 00:06 UTC (2017-08-11 10:06 in my time zone). I was using the website then.

The bug:
At about 2017-08-11 15:13 UTC (2017-08-12 01:13 in my time zone), I opened the Android app and the Record Yesterday's Activity screen appeared. It shouldn't have appeared until after 6am in my time zone (i.e., not for another five hours).

This seems to be just a problem with the RYA screen appearing too early on the Android app, not a problem with cron running too early, because after I clicked the "start my new day" button on the RYA screen, as best as I can tell cron halted correctly at this point in its code:
https://github.com/HabitRPG/habitica/blob/4ba97755a5825bd92f926edc2ae51ac478fac248/website/server/middlewares/cron.js#L55
I.e., it set the value for `lastCron` to the current time but did not reset my Dailies or perform any other actions. 
Later that day after 6am, I used the website and RYA and cron both ran correctly there.

**Comment by vIiRuS** [comment]
It’s likely that this is a server side issue. Since the android app only
displays the dialog if the server returns the needsCron flag with true.

-- 
Phillip Thelen
Sent with Airmail
