### ISSUE TITLE
"Invited a Friend" achievement is blank

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#801]
When a player has the "Invited a Friend" achievement, it doesn't appear in their profile in the Android app. Instead, there's a blank white space.

![image](https://user-images.githubusercontent.com/1495809/29738924-ff0b7c28-8a73-11e7-9954-0cafb5edc57d.png)

I've confirmed that that account does have the achievement.

**Comment by artem-p** [comment]
The app doesn't have access to this image on the server. It tries to load it from this url: [https://habitica-assets.s3.amazonaws.com/mobileApp/images/achievement-friends2x.png](https://habitica-assets.s3.amazonaws.com/mobileApp/images/achievement-friends2x.png), but respond is access denied.

**Comment by jamesjpk123** [comment]
It looks like this: ![Invited a Friend](https://vignette.wikia.nocookie.net/habitrpg/images/f/fc/Achievement-friends2x.png/revision/latest?cb=20170804014008) is the image it is trying to load.

**Comment by Alys** [comment]
Nexian (a949047e-1393-49ad-afd0-96a8c1475f70) reports that this is still happening:

"Hi again guys, I found something else. The badge for "invite a friend" does not appear for me. If someone has that badge, I cannot see it. All I see is an empty space where the badge should be, but I can still click on it and see their achievement. I'm on android."

Pinging @SabreCat since @jamesjpk123 mentioned above that it seems like an assets error.

**Comment by Alys** [comment]
That's fixed it. Thanks SabreCat.
