### ISSUE TITLE
add confirmation step to "begin" button for quests

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#804]
Quest owners sometimes click the "Begin" button on a quest before party members have had a chance to accept/reject the invitation because they don't understand what the button is for.

We want to add a confirmation screen that displays this text:
**"Are you sure? Only X of your Y party members have joined this quest! Quests start automatically when all players have joined or rejected the invitation."**
where X and Y are replaced by appropriate numbers.

The buttons on the confirmation screen should be **"Not yet"** and **"Start Now"**

_The website and iOS versions of this issue are https://github.com/HabitRPG/habitica/issues/9083 and https://github.com/HabitRPG/habitica-ios/issues/487_

**Comment by LulaV14** [comment]
Hi! Can I take this?

**Comment by vIiRuS** [comment]
Sure!

If you need any pointers as to where to start or are stuck anywhere, feel
free to comment here and let me know :)

-- 
Phillip Thelen
Sent with Airmail
