### ISSUE TITLE
Using markdown inside a task title renders incorrectly

### ISSUE THREAD

**Issue by JacobFrericks** [HabitRPG/habitica-android#805]
I recently saw a Reddit post that suggested using markdown to display an image inside a task title. That way it would feel like you're killing whatever is displayed by checking it off. For example, by pasting
 ```![Write 2000+ Words in a Day](http://hydra-media.cursecdn.com/terraria.gamepedia.com/1/1b/Harpy.png) 2000+ Word```
Into a task title, you would get the following on the website:
![screenshot_20170928-150528](https://user-images.githubusercontent.com/5521414/30988225-47521c44-a45f-11e7-9685-8776e37b5e7b.png)
And the following on the app:
![screenshot_20170928-150608](https://user-images.githubusercontent.com/5521414/30988249-5802a4be-a45f-11e7-9d32-3898e169c7d1.png)

**Comment by LunarGem** [comment]
They know about this, I'm working on the issue in another thread, I believe.

**Comment by JacobFrericks** [comment]
Perfect! If you want to link to that thread and close this one, I'm ok with that.

**Comment by vIiRuS** [comment]
See #904
