### ISSUE TITLE
"Visit Habitica Website" directs to habitrpg-staging.herokuapp.com

### ISSUE THREAD

**Issue by mchlltt** [HabitRPG/habitica-android#807]
![screenshot_20170929-222957](https://user-images.githubusercontent.com/15218445/31042107-37ba09f6-a566-11e7-8b54-a25e92feb86a.png)

Steps to reproduce:
1. Tap "Gems & Subscriptions" in the menu
2. Tap "Subscriptions"
3. Scroll down and tap the purple "Visit Habitica Website" button

UserID: 804ca182-f16c-4ff5-b115-d73cdba94935
OS: Android 8.0.0
App version: 1.2

**Comment by mchlltt** [comment]
The new app looks great! This is definitely a bug, tho, and one that's likely to really throw less tech-savvy users.

**Comment by caipivara** [comment]
@mchlltt it is still an issue? I cant find the link "Visit Habitica Website"  in the app, where is it?

**Comment by mchlltt** [comment]
It's not happening for me anymore -- that is, that button actually opens Habitica. I'll reopen if it comes back.
