### ISSUE TITLE
App hangs when you try to change class without enough gems.

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#826]
Steps:

tap 'change class' > tap class to change to > confirm change > get the 'you're now a X!' dialogue but then the ‘not enough gems’ dialogue on top of it immediately > tap okay > sent back to last 'you're now an X!' dialogue > press 'got it' (only option) > hang

Fixes when you minimize and reopen app, but still a pretty confusing flow that could use some work (potentially design work).

**Comment by dumbinacan** [comment]
Hey I am new to working on open source projects, but I have academic experience with Java, and played a little with android studio on my own. This seems like something small enough for me to handle.  Could I give it a go please?

**Comment by phillipthelen** [comment]
Sure! If you need any assistance, please let us know.
