### ISSUE TITLE
Error:Could not find javassist.jar 

### ISSUE THREAD

**Issue by altaf933** [HabitRPG/habitica-android#831]
I just cloned the project and gradle synching started but they failed to resolve dependency of javaassist.jar. Here it 's the error message : 

> Error:Could not find javassist.jar (org.javassist:javassist:3.20.0-GA).
> Searched in the following locations:
> https://jcenter.bintray.com/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar

**Comment by vIiRuS** [comment]
Are you using Android Studio 3.0? The develop branch requires that.

**Comment by altaf933** [comment]
Yes I am working Android studio 3.0 and checked out develop branch.

**Comment by altaf933** [comment]
I set up the target sdk version and  all dependency started downloading  which are missing. Please @vIiRuS close this issue I don't think it should be here anymore.
