### ISSUE TITLE
Market: Make class icons in the drop down line up better (see last comment)

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#857]
To add extra visual weight and clarification to the class that's currently selected.

Market view:
https://zpl.io/amLA3eV

Dropdown:
https://zpl.io/VQ0p7yP

**Comment by saraolson** [comment]
The visuals for what class is currently selected is slightly off: 
1. The type size should be 16sp, same size as the section title
2. Can we move the class name closer to the arrow to make them look more like one control and  save some space?

**Comment by vIiRuS** [comment]
I updated the type, but I can't get the selected class to be right aligned and close to the arrow. android always shows it left aligned for some reason.
