### ISSUE TITLE
Time Travelers: Gear sets are shown as individual parts, rather than the full set like on web

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#862]
The way this displays is rather confusing, because it shows each individual item as costing 1 hourglass, when really you get the whole set for 1 hourglass. I do remember that it does work properly, buying one charges you the right amount and awards the whole set, but its very misleading.

All the art for the sets should be on the server. I'm assigning this to 1.3 but if it needs server/API work, I'm okay with pushing it back to 1.4. However, I do think we need to make this a priority by then.

**Comment by saraolson** [comment]
@vIiRuS when you have time, could you comment what needs to happen for this to display properly? thankya sir.

**Comment by kent12t** [comment]
To follow up on this issue, if I pin the set (eg. the Flame Wielder set) from the Shops > Time Travelers on the website, it will be displayed properly in my Rewards section on mobile! So I can purchase a set for 1 Hourglass from my Rewards section, but 2 Hourglass from the Shops -- all done in-app (not website, except the pinning part). 

https://imgur.com/a/7je2K

**Comment by saraolson** [comment]
@kent12t purchasing a set from the TT shop actually still works as intended, if you buy one piece for 1 hourglass it gives you the other, so the way its displayed currently is just misleading. it doesnt actually cost more from the shop.
