### ISSUE TITLE
Quest Shop: Fix reasons why quests are locked

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#871]
Right now it says 'Unlock by inviting' on quests that aren't unlocked by inviting. 

1. Just show the price of those quests for now, only the basilist quest should show the string 'Invite to Party'

2. Make sure the type is 12sp medium, centered (it may be 14sp now?)

**Comment by saraolson** [comment]
The text is right but it's still appearing on the wrong scrolls. Only the basilist scroll is unlocked by inviting, but its not showing on it. Instead it's showing on the lunar battle scrolls that are unlocked through check-in rewards.

**Comment by LunarGem** [comment]
I recall doing part of a fix for, this I believe we figured out it was contingent on the reversion of a hack commit from the main repo (and that a complete revamp of the unlock method code was probably in order).

**Comment by vIiRuS** [comment]
This is because of an error in the content API. The unlockCondition for those quests is set to `party invite`.
