### ISSUE TITLE
Can't buy gem-purchasable items from Market unless your balance >= gem cost

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#886]
If you have just enough gems to buy a hatching potion or egg, when you try to buy the item, the purchase fails and you're told that you don't have enough gems. However if the number of gems you own is 4 times the cost of the item, the purchase succeeds (the correct number of gems is subtracted from your account).

For example, if you want to buy a hatching potion that costs **2** gems:
- it fails if you own 2 gems (i.e., if your `balance` is 0.5)
- it fails if you own  7 gems (your `balance` is 1.75)
- it succeeds if you own 8 gems (`balance` is **2**)

If you want to buy an egg that costs **3** gems:
- it fails if you own 3 gems
- it fails if you own 11 gems (your `balance` is 2.75)
- it succeeds if you own 12 gems (`balance` is **3**)

I.e., it looks like when you try to purchase something with gems, the app is comparing your `balance` with the gem cost, instead of comparing your number of gems with the gem cost.
(`balance` = number of gems * 4)

**Comment by saraolson** [comment]
adding to current release milestone
