### ISSUE TITLE
Chat: Update visuals, add avatars and auto-refresh

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#891]
Basically do a lot of UI/UX work on chat til it feels better

**Comment by saraolson** [comment]
Adding the needs design labels because web is working on some chat changes now to make moderators, leaders, and tiers more obvious

**Comment by phillipthelen** [comment]
Still needs: moderator/staff display, Improved handling for when there are new messages, improve link handling, automatic refreshing
