### ISSUE TITLE
Stats: When choosing task based allocation, the options on the tasks don't show

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#893]
Also, the labels may be wrong? From tavern: "Every single task, habit and daily had a default setting of “physical” when I opened them all this morning". I can't see this when I set my allocation method to task based (I just see nothing).

**Comment by trepto** [comment]
You can change the task's attribute through the Task Adjustor, but any time you edit the task it reverts to Physical. Just opening the edit screen and immediately backing out does *not* revert the attribute to Physical, but changing even a single text character, tag, or date option does.
