### ISSUE TITLE
Tasks: No way to make individual dailies not appear in RYA

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#901]
There should be a checkbox when creating/editing a daily that lets you make it not appear (will wait for confirmation from web on string and whether it should be an auto-on switch you turn off, or an auto-off switch you turn on)

**Comment by saraolson** [comment]
Assigning to 1.5 when we're redoing the task forms

**Comment by Alys** [comment]
When creating a Daily, it is an auto-on switch that the user can chose to turn off (that's how it's coded in the task model).

Website version of this bug: https://github.com/HabitRPG/habitica/issues/9622
