### ISSUE TITLE
FAQ uses web answers

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#903]
In the FAQ, `faqQuestion11` ("How do I report a bug or request a feature?") uses the answer for the website (`webFaqAnswer11`). It should use the answer for Android (`androidFaqAnswer11`).

https://github.com/HabitRPG/habitica/blob/f3c2c0f9013f3a4d498d241f77e2bda376d81c6b/website/common/locales/en/faq.json#L59-L62

The same might be true of other answers; 11 was the only one I checked.

**Comment by wskinner74** [comment]
Looks like this one's been sitting here for a little bit, I wouldn't mind taking a crack at it.

**Comment by phillipthelen** [comment]
See the linked PR for the fix for this.
