### ISSUE TITLE
Image support for markdown

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica-android#904]
Currently we don't display images that are embedded with markdown. They should be shown in tasks and in chat messages. (and potentially tags)

**Comment by cvuorinen** [comment]
@phillipthelen can we reopen this? It's not fixed yet.

**Comment by Alys** [comment]
In case a screenshot helps to illustrate @cvuorinen's post, the one below shows two examples of markdown images not appearing in the Android app. In each of the two posts there, where you see the "img" text, on the website you see an image inserted with markdown.

It's reproducable with every post that contains a markdown image, and it happens for everyone - as you can see from the links under each image, the guild members know that they have to add a separate link to the image for Android users to click on. 

The guild from the screenshot is https://habitica.com/groups/guild/3884eeaa-2d6a-45e8-a279-ada6de9709e1 ("Costume Carnival") but it happens in every guild.

![image](https://user-images.githubusercontent.com/1495809/87871006-437fbb80-c9f0-11ea-8691-77522280f180.png)

**Comment by saraolson** [comment]
@cvuorinen @Alys sorry for missing these comments! i've reopened the issue since it doesn't seem to be working

**Comment by cvuorinen** [comment]
I finally got around to look into this and made a PR to fix it :tada:

**Comment by saraolson** [comment]
@cvuorinen thank you! will add the pr to 3.3 for review. there may be a bit of a delay for us to get around to that, as we're workin on an spring event support update on both platforms right now.
