### ISSUE TITLE
Rage bar for quests does not appear

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#905]
In the Report a Bug guild, geolojess ( da27bf23-48f7-469d-9a32-58521f9c84a9 ) says:

"(Android) I can't see the rage bar for the boss of Mystery of the Masterclassers part 3."

I'm guessing this also applies to other quests that have rage bars but haven't tested that.

**Comment by saraolson** [comment]
Yeah this feature isn't in yet, we should add it for world boss updates tho
