### ISSUE TITLE
confirmation step for leaving a guild / party

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#908]
When clicking the "leave" button for a guild or party, it would be good if there was a confirmation step (e..g., "Are you sure you want to leave this guild / party?")

Dewines reported in moderator slack, "I managed to throw myself out of [a] guild today using the app... The three dot button which appears at the top right of the screen on the Android app leads to the Refresh option when you're on the task page, but if you're reading a guild, it's the Leave button. I must have thought I was refreshing the guild chat, but actually left the guild instead! (Yes, I know I should have read what the option said, but I just assumed.) ... Leaving a guild unintentionally could be quite serious if it was a private guild and/or you are the guild leader!"

It would also be serious if you accidentally left a guild with a Group Plan since you would lose the group tasks and it would affect task approvals or tracking of your progress by the leader.

_A similar confirmation step for the iOS app would be desirable if it doesn't already exist._

**Comment by saraolson** [comment]
While i think accidentally leaving will be helped once we actually get the guilds redesign in and the option is only available from the bottom of the details page, i wouldn't really mind an extra onfirmation step since leaving isn't a common action.
