### ISSUE TITLE
profile "Pets & Mounts" is empty - just contains "Pets Found" and "Mounts Tamed" labels

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#910]
The "Pets & Mounts" section in a user's profile contains only the labels "Pets Found" and "Mounts Tamed" but no counts for them, and it doesn't display the player's currently equipped pet and mount.

This occurs on your own profile and those of your party members.

**Comment by Alys** [comment]
This occurs on your own profile and those of your party members.

**Comment by saraolson** [comment]
going to reopen this because while it shows more now, it still only displays '0' for both counts

**Comment by ashleyng** [comment]
Is this still an issue? I've tried going to other profiles and can't seem to reproduce the '0' count. If it's still an issue, is there any more information that can be given about the repro steps?

**Comment by saraolson** [comment]
I can't reproduce this anymore so going to close unless someone finds it happening again.
