### ISSUE TITLE
challenge creator can't add tasks to challenge

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#912]
As reported in the Report a Bug guild by Mari Lee ( c3ebea56-362c-4ba1-9b41-2277f4b90b13 ) :

"Hi! I use Habitica on the Android app, and I'm having difficulty creating a challenge. When I add a task - habit, daily or to-do, I've tried them all - and click on "save", it seems like nothing's happened. When I try to save the challenge, I get a message saying that I need to add at least one task, and therefore I'm unable to save the challenge. When I leave the 'Challenge' page and go back to my Tasks, the tasks I created within the challenge are there. They are being created in my personal Tasks, and not within the challenge! Help?"

I've confirmed this on Version 1.3.3 (1963)

**Comment by shanaqui** [comment]
This is an issue with editing existing challenges as well, not just creating them. 

In addition, it's worth noting that challenges without tasks do have a valid use case and should be allowed on Android to be consistent with the web version. (E.g. my New Year's Resolution freebie challenges.)
