### ISSUE TITLE
rounding for player's Health (HP) needs to match the website in header, widget, profile screens

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#914]
Rounding for player Health values needs to be adjusted again to match what's done on the new website. This should be done identically for:
- the player's stats at the top of the app
- the player's stats in the widget
- any player's stats when shown in a profile screen (e.g., party members)

The rounding and the decimal places shown needs to be different depending on whether your health is below 1 or not:
- For health of 1 and above:
   - display zero decimal places
   -  round **down** so that you don't think you have more health than you really have
   - e.g., health of 49.9 should be displayed as 49
- For health between 0 and 1:
   - display one decimal place
   - round **up** (rounding down is bad because if we display 0 health when you actually have slightly more than 0, we get bug reports: "I have zero health but I haven't died")
   - e.g., health of 0.11 should be displayed as 0.2
- For health less than zero:
   - display zero decimal places always
   - round **down** always
   - show the negative sign
   - e.g., -0.1 should be displayed as -1
   - i.e, the code for negative values of health can be identical to the code for health of +1 and above - you don't need a special case for negatives

The website's code for rounding and decimal places is here:
https://github.com/HabitRPG/habitica/blob/3b4b459e6861fd5e1c1abc5471fff95007559ff1/website/client/components/memberDetails.vue#L237-L243

Other examples of desired behaviour: 
  - 49.9 -> 49
  - 9.9 -> 9
  - 1.9 > 1
  - 0.99 -> 1
  - 0.9 -> 0.9
  - 0.11 -> 0.2
  - 0.09 -> 0.1
  - 0.0001 -> 0.1 
  - 0 -> 0
  - -0.1 -> -1

_The same will be needed for the iOS app if not already done there (I can't test there). EDIT: https://github.com/HabitRPG/habitica-ios/issues/556_

**Comment by Alys** [comment]
I'll log a copy of this issue in the iOS repo in a few days if I don't hear anything about whether iOS already does this.

**Comment by ptreitler** [comment]
Apparently this has been fixed on iOS here: https://github.com/HabitRPG/habitica-ios/commit/159652adac3d9cbd99c7fb2fc3c78315e1c2b656

I'd like to tackle this if it's still open and nobody is on it yet.

**Comment by HiroinaProtagonist** [comment]
Apparently, this issue has been fixed with pr #1081. Should this be closed?

**Comment by saraolson** [comment]
yup! just tested this and seems to be working correctly now. closing this.
