### ISSUE TITLE
boss health in a running quest should be rounded up

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#915]
As reported in [rounding inconsistencies - Issue #8368 · HabitRPG/habitica](https://github.com/HabitRPG/habitica/issues/8368), on the Android app a boss's health is rounded down. For consistency with the website, it should be rounded up. Rounding up gives the users a more accurate view of the quest progress (they won't be misled into thinking they need to do less damage than is actually needed to kill the boss).

The website displays the bosses health to two decimal places (e.g., 300.141 will be displayed as 300.15). I don't have a strong opinion about whether decimal places should be used on the app or not - it would be nice for consistency but it's the rounding up that's most important. E.g., 300.141 could be displayed as 300.15 or 300.2 or 300.

_As a note for the future, if the player's pending damage to the boss is ever displayed on the app, it should be rounded **down** so that if you're aiming to kill the boss, you don't overestimate the damage you have already done._

**Comment by Alys** [comment]
I've renamed this issue from "boss health in a running quest should be rounded down" to "boss health in a running quest should be rounded up". Kinda important. :-/

**Comment by saraolson** [comment]
adding to 1.4 with world boss stuff
