### ISSUE TITLE
Facebook / Google sign-in authentication methods should be shown in Settings

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#916]
If the player does not have a login name and password set up, the Settings > Authentication screen should show a message such as something like "log in using the Google sign-in button" or "log in using the Facebook sign-in button". 

It would be useful to display this information because users often forget which sign-in method they have used. We often get emails from players who need help working out how to log in to the website when they're already logged in to the app.

It's possible to have two or all three authentication methods on a single account and all of them should be shown.

This would also be useful on the iOS app if it's not there already. I'll log it in that repo in a few days if I don't hear otherwise.

**Comment by beffymaroo** [comment]
@saraolson Is this a "needs design" kinda thing?

**Comment by saraolson** [comment]
@beffymaroo it sounds simple enough for phillip to handle with his design skills heh
