### ISSUE TITLE
Can't dismiss tutorial text

### ISSUE THREAD

**Issue by pafcu** [HabitRPG/habitica-android#918]
I signed up using the app, got Justin to tell me how the app works, but on the (final?) message ("Give it a shot!..."), pressing "GOT IT!" doesn't actually do anything and there also does not seem to be any other way to dismiss the dialog. Closing the application and restarting seems to be the only way to continue.

**Comment by saraolson** [comment]
i tested this a few times and couldn't get the issue to repeat

**Comment by jaller94** [comment]
To reproduce quickly tab on two buttons that will start a tutorial text (e.g. "Dailies", "To-Dos" or "Rewards").
The tutorial text starts with a small delay, letting you tab on the second navigation item. You will then get two tutorial above each other. Each tutorial ends with "Got it!", however, it won't let you finish the one underneath. "Got it!" won't quit the tutorial.

**Comment by saraolson** [comment]
@jaller94 thanks! could reproduce now
