### ISSUE TITLE
Text under My Challenges not all viewable

### ISSUE THREAD

**Issue by anitawoodruff** [HabitRPG/habitica-android#922]
Habitica version
1.3.3

Device details
Evercoss A65
Android 6.0.1

Steps to reproduce

1. Tap on Challenges in the side bar

2. Try to read all the text under MY CHALLENGES

Expected 
All text is viewable

Actual
The end of the text goes off the bottom of the screen and is not scrollable. 

I don't have any challenges right now, and the text stops abruptly at "tap the public tab to view all challenges that are”

I'm assuming there is more text that should be scrollable through, rather than the string just stopping there.

**Comment by saraolson** [comment]
challenges will be getting a redo in 1.5 so this will be addressed with that most likely.
