### ISSUE TITLE
Daily Reminder only works sometimes

### ISSUE THREAD

**Issue by KonomiKitten** [HabitRPG/habitica-android#923]
Sometimes I'll get my Daily Reminder other times it doesn't show when it should. I suspect this might be because Habitica has no always running service, but it's just a guess.

**Habitica:** 1.3.3 (1963)
**Android:** 7.1.2

**Comment by JacobFrericks** [comment]
I am also having this issue, although mine hasn't given me a daily reminder in a long time.

Android 8.1.0
Habitica 1.4.1 (1970)

**Comment by KonomiKitten** [comment]
@JacobFrericks this bug report is for daily reminder working sometimes and not others, not when it doesn't work at all.

**Comment by KonomiKitten** [comment]
I'm not sure why this issue was closed, problem still persists for me.

**Habitica:** 1.4.5 (1989)
**Android:** 7.1.2

**Comment by phillipthelen** [comment]
This should be fixed in the 1.5 update.

--  
Phillip Thelen
Sent with Airmail

**Comment by KonomiKitten** [comment]
@phillipthelen thanks this does seem to be fixed, thanks for the hard work :smiley:
