### ISSUE TITLE
"Wear Costume" ("Use Costume") switch is always off

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#930]
The "Wear Costume" switch in the Equipment screen is always in the off position, even when `preferences.costume` is set to true.

If `preferences.costume` is false, using the switch will cause it to be set to true (which is the correct behaviour) but when you leave the Equipment screen and then go back into it, the switch is set to off again (even though your `preferences.costume` value is still true).

Is it possible for this to be fixed in the next release? We see a lot of confusion about costumes in the Tavern, Help guild, and Bug guild, and this will be causing part of it.

Also can we consider changing the label for the switch to "Use Costume" for consistency with the website? It helps the users if the same labels are used on website and apps because then advice they get from other players will be accurate regardless of platform.

**Comment by saraolson** [comment]
optimistically added to 1.4, but since 1.4 is worldboss update and that has a hard release date we may have to push this out.
