### ISSUE TITLE
Equipping a weapon does not immediately update Equipment screen

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica-android#932]
When you go to Equipment, tap your currently equipped weapon, and tap a new weapon you'd like to equip, the new weapon shows as "equipped" in the gear list. When you head back to the Equipment screen, however, your old weapon still appears. You have to go to Tasks or some other screen that allows pull-refresh, sync, and head back to Equipment to see the updated gear.

**Comment by ajsviado** [comment]
@SabreCat can you check if this is still happening?

**Comment by saraolson** [comment]
i just tested this and it seems to have been fixed! going to close this issue.
