### ISSUE TITLE
wheelchair misaligned / missing in avatar

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#933]
When I put a wheelchair on my avatar, it's not aligned correctly. Screenshots below.

There's also two reports in the Report a Bug guild of wheelchairs not being visible. I'll be asking for more details about the problem.

My avatar on the app:
![screenshot_2018-02-08_20-22-41](https://user-images.githubusercontent.com/1495809/35967819-ca271180-0d0d-11e8-93f8-c837e9b6ace0.png)

Correct alignment from the website:
![screenshot_2018-02-08_20-23-21](https://user-images.githubusercontent.com/1495809/35967858-e87b9fd4-0d0d-11e8-90b1-e6a85352eeea.png)

**Comment by Alys** [comment]
My avatar on the app:
![screenshot_2018-02-08_20-22-41](https://user-images.githubusercontent.com/1495809/35967819-ca271180-0d0d-11e8-93f8-c837e9b6ace0.png)

Correct alignment from the website:
![screenshot_2018-02-08_20-23-21](https://user-images.githubusercontent.com/1495809/35967858-e87b9fd4-0d0d-11e8-90b1-e6a85352eeea.png)

**Comment by citrusella** [comment]
My avatar doesn't have the alignment issue, as far as I can tell. (The upper part is properly centered on the head.)

![my header, the wheelchair visible and in correct alignment](https://user-images.githubusercontent.com/14182450/35973004-d74753fa-0ca1-11e8-9897-d4883d66eb11.jpg)

But the place where the wheelchair doesn't appear is the chat profile.

![my user profile, the wheelchair not visible](https://user-images.githubusercontent.com/14182450/35972691-e3a99cd0-0ca0-11e8-95d5-dcaff4047085.png)

**Comment by saraolson** [comment]
I also have an alignment issues with my crystal blade coming out of my character's chest thats android specific so this may be more than just wheelchairs.

**Comment by Alys** [comment]
The missing wheelchair on avatars occurs in the Party > Members screen. Your own avatar and that of your party members will not show a wheelchair.
