### ISSUE TITLE
Guild and Party descriptions should support Markdown, Emoji, `&nbsp;`

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#935]
_This isn't a new bug but we don't have an issue for it as far as I can find._

Guild and Party descriptions should have support for markdown, emoji, and simple HTML like `&nbsp;` (which is used to insert blank lines between paragraphs).

For example, this is what the app is like:
![screenshot_2018-02-10_14-31-41](https://user-images.githubusercontent.com/1495809/36058555-228fd5a2-0e6f-11e8-8c45-e682c9083faf.png)

And this is the website version:
![screenshot_2018-02-10_14-33-16](https://user-images.githubusercontent.com/1495809/36058559-4f747168-0e6f-11e8-93b5-216acb9d400d.png)

**Comment by Alys** [comment]
Faelwyn the Rising Phoenix (87c82b20-a762-4d27-81a5-f59bf37170bd) reports that for the Party description, the markdown is converted but don't work: "They show up as a link, but don't let you open them. Here's a picture: [Imgur](https://i.imgur.com/P4ch6LY.png)"

**Comment by saraolson** [comment]
we'll address this when we do the guild redo in 1.6
