### ISSUE TITLE
Saddles are easy to waste by accidental use

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#937]
Below is some feedback about how Saddles are too easy to use accidentally. Since they're rare and cost 5 Gems if purchased, I think it's worth adding a confirmation step or separating them from the cheaper foods. This might also be worth considering for the iOS app.

"I was just feeding some magic potion pets when I discovered that while Saddles are usually at the bottom of the list, and I can avoid accidentally using them while feeding, Cake versions of normal foods appear below Saddles. As it doesn't really matter what kind of food you give Magic Potion pets, I usually just tap on whatever the top food is until the list starts getting shorter, providing some warning that I am getting close to the bottom and thus the Saddles. 

"It would be preferable if all food of equivalent value (normal, cake, candy, etc.) appeared above Saddles, which are much more valuable, so that the appearance of seasonal food doesn't require a change in user feeding behavior. This is especially true because it is people who are particularly enthusiastic about raising pets who are likely to reach the stage where they are feeding a large number of Magic Potion pets.

"Not asking for the saddle back (it did save me some feeding, after all), but I do wish I hadn't accidentally used it, so I decided to mention it."

**Comment by saraolson** [comment]
we'll probably address this when stable gets it's redo

**Comment by saraolson** [comment]
I think my proposed solution for this would be to have separate options on the pet when you tap it. ie: Equip, Feed, Give Saddle. Then Saddle will not show in the food modal.

If there are still issues with mistapping after that, we can add another dialogue before.

**Comment by JasonBaby87** [comment]
I just accidentally used one because I didn't know it'd get used without telling me what it does 😭

**Comment by saraolson** [comment]
@JasonBaby87 if you reach out to admin@habitica.com with your username and let them know what happened, they can restore that for you if you haven't already! totally fair to expect more explanation there.
