### ISSUE TITLE
Make offline notices non-intrusive

### ISSUE THREAD

**Issue by jaller94** [HabitRPG/habitica-android#938]
App version: 1.3.3 from the Google Play Store
Device: marmite

If you have an unstable connection (e.g. public transport) or you disable the network on purpose, the app becomes a pain to use. Almost every new screen will trigger a notification that has to be dismissed. When switching between apps and coming back to Habitica there are sometimes five or more of those notifications stacked above each other.

I find the offline notices to be very annoying. A short toast message might be less of an interruption while giving the same information to the user. Speaking of, it would be more helpful to state if offline usage gets saved and send later or is simply lost. None of the offline messages inform me about this.

Also, I prefer the text "Connectivity to the server has been lost". "There seems to be a problem with the server. Try again later." is misinterpretation of disabled wifi/data.

**Comment by saraolson** [comment]
here's a mockup of the banner placement on screens with the big header and all other screens. shortened the text to give the most room for translations to fit on one line.

specs: 24dp high, bg is #4E4A57 (gray 50) with white text. 12sp medium (caption 2)

<img width="500" alt="Screen Shot 2019-05-10 at 5 26 20 PM" src="https://user-images.githubusercontent.com/12453119/57557599-c61ade80-7348-11e9-9e94-e7292029ea5d.png">
