### ISSUE TITLE
tag filtering doesn't filter - it ADDS tags to all your tasks

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#939]
When you select one or more tags in the tag filter, your list of tasks is *not* filtered to show only those tasks associated with that tag. It still shows all your tasks.

If you go into the edit screen for any task, you can see that the tag you selected in the filter has actually been set into that task's own list of tags (presumablly that's why all tasks are still visible when the filter is on). If you click the save button, the tag is permanently saved to the task's own list of tags - i.e., you can then sync on the website and see that the task's tags have been modified.

Steps to reproduce:
1. Create a task. Do NOT give it any tags.
2. Use the filter menu to select any tag.
3. Click the new task to open it for editing.
4. Observe that the tag you selected in step 2 is now ticked in the task's edit screen.
5. Click "save".
6. Sync website.
7. Observe that the tag is now saved into the task on the website too.

This has the potential to cause many of a user's tasks to be mistagged if a user doesn't realise what's happening, which is damaging to the user's organisational system, so is it possible for this to be added to the next milestone?

I observed this in alpha Version 1.4 (1965) and we also have this report from a user in the Report a Bug guild so it will be happening in previous versions too (Amplitude says 1.3.3):

trishinboots (ab031c0f-b54d-4a84-91ea-5b3807024ca6)
"I am having an issue with filtering based on tags I set on my tasks within the Android app. If I try to filter based on 1 or 2 tags nothing happens - I can still see my entire list of tasks. I set up my tags and added them via browser on a PC, but I can see the tags on my mobile app and can see that they are checked on the relevant tasks so I am not sure if that is part of the cause or not. I tried refreshing the app or the page and it still doesn't filter."

**Comment by phillipthelen** [comment]
That the tag is added is intentional and not a bug. This is done so that
new tags that are created while filtering are created having that tag set.
The bug here is that the filter isn’r affecting todos for some reason. (I
think there is already an issue for this).
Note that just filtering causes nonchanges to the tasks. This is only when
you then edit them.

-- 
Phillip Thelen
Sent with Airmail
