### ISSUE TITLE
 Equipment descriptions missing for all weapons and for Rogue off-hand gear (shields)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#940]
As reported by Kent the Apprentice (b82b7aa8-161f-4b02-aef9-4a319e47f7b2) in the Report a Bug guild:

"The equipment description is missing for all rogue offhand item (class specific items, non seasonal) and for all mainhand items in my android phone! (tried reloading content) Thanks :)"

Confirmed in alpha version 1.4 (1965).

If this turns out to be an API problem, tell me and I'll log this in the main repo instead (we can reuse https://github.com/HabitRPG/habitica/issues/9987 with an extra note added).

Rogue off-hand items:

![screenshot_20180212-081345](https://user-images.githubusercontent.com/1495809/36079287-1f6d48a0-0fcd-11e8-9087-ad650c1d8e18.png)

----

Weapons:
![screenshot_20180212-081415](https://user-images.githubusercontent.com/1495809/36079289-24241dd8-0fcd-11e8-90f6-7c183e863409.png):

**Comment by phillipthelen** [comment]
This is not a client issue. Looking at the content API, all of the default class weapons and shields are missing their descriptions (possibly also other gear, but that's the one where I noticed it)
