### ISSUE TITLE
Tavern: Check into inn is above worldboss section

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#943]
Should be below

**Comment by Alys** [comment]
Just as a note, in a previous world boss battle when the world boss on the website pushed down the rest in the inn button, we had distressed questions and bug reports from users who thought that they could not rest in the inn while the world boss battle was in progress. They didn't see that the rest in the inn button was just in a different place.
You don't need to reply, or to consider this if you don't want to. I just wanted to make you aware that that user confusion can happen.

**Comment by phillipthelen** [comment]
I don't think the confusion would happen here, since 1. the way the world boss section looks like on mobile it's clear you can scroll on this page 2. it's not like it's just the "check into inn" button is lower. it's the whole section that informs about the inn.
