### ISSUE TITLE
Quest Shop says every Boss Quest has a Rage Meter

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#963]
In the Quest Shop, when you tap on any Boss Quest scroll, you see "Rage Meter" to the right of the "Difficulty" rating.

The Rage Meter text should (I assume) appear only on those quests where the boss does have Rage - i.e., when the Quest's data has a non-empty object for `boss.rage`, such as this example:

https://github.com/HabitRPG/habitica/blob/d5e4be85e991740e6ec622c41f7c38a307b802ea/website/common/script/content/quests.js#L1177-L1187

```
  trex_undead: { // eslint-disable-line camelcase
    text: t('questTRexUndeadText'),
    notes: t('questTRexUndeadNotes'),
    completion: t('questTRexUndeadCompletion'),
    value: 4,
    category: 'pet',
    boss: {
      name: t('questTRexUndeadBoss'),
      hp: 500,
      str: 2,
      rage: {
        title: t('questTRexUndeadRageTitle'),
        description: t('questTRexUndeadRageDescription'),
        value: 50,
        healing: 0.3,
        effect: t('questTRexUndeadRageEffect'),
      },
    },
```

**Comment by DoguD** [comment]
I can work on this issue.

**Comment by TheHollidayInn** [comment]
Thanks!

**Comment by DoguD** [comment]
I am getting this error while building:
Unresolved dependencies:
seeds-sdk/build.gradle
    Failed to resolve: multidex
Habitica/build.gradle
    Failed to resolve: multidex
    Failed to resolve: runtime
    Failed to resolve: common

Do you know what can I do?

**Comment by DoguD** [comment]
I solved those issues by adding
`allprojects {
    repositories {
        maven {
            url 'https://maven.google.com'
        }
    }
}`
to build.sdk but now I am getting this error:
> Could not find runtime.aar (android.arch.lifecycle:runtime:1.0.3).
Searched in the following locations:
    https://jcenter.bintray.com/android/arch/lifecycle/runtime/1.0.3/runtime-1.0.3.aar

Sorry this is my first contribution.
