### ISSUE TITLE
Time Travelers: no images shown for purchasable Pets and Mounts 

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#968]
In the Time Travelers shop, the images for the rare Pets and Mounts that you can buy do not appear in either the shop's main screen or the popup confirmation screen.

Version 1.4.2 (1972).

![screenshot_20180308-193055](https://user-images.githubusercontent.com/1495809/37143736-be3183fa-2307-11e8-957f-c2a8e693ef7b.png)

![screenshot_20180308-193101](https://user-images.githubusercontent.com/1495809/37143734-bdec52b2-2307-11e8-90dd-cf7b1c51b870.png)

**Comment by saraolson** [comment]
i just checked this and images seem to show now. going to close this issue, feel free to reopen if it pops up again
