### ISSUE TITLE
Stats Points can be allocated before you've enabled the class system (e.g., below level 10)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#969]
If you have not yet enabled the class system (e.g., you are below level 10), the menu shows you a count of your unallocated Stats Points on the "Stats" menu entry. If you go into the Stats screen, it says correctly "No Points to Allocate" but if you tap on that text you gain access to the bulk allocation screen and you are allowed to allocate your points.

The expected behaviour is that before you have enabled the class system (i.e., when `flags.classSelected` is false) then you shouldn't see that you have any points to allocate (even if those points are in your account) and you shouldn't be able to use the bulk allocation screen to allocate them.

This behaviour is already correct for anyone who has opted out of the class system (`preferences.disableClasses` is true) so perhaps similar code could be used for when `flags.classSelected` is false

**Comment by saraolson** [comment]
Adding to this: if you go to stats pre-10, you still get the justin tutorial pop-up teaching you how to allocate points. this should only appear post-10 when you're able to allocate points.

**Comment by amohnacs15** [comment]
I'll take a look at this.  I'm new to this project so I'll fork the repo.  Are there any special files I need for the debug build?

**Comment by amohnacs15** [comment]
I just configured my fork of this project and I would like to look into this.  As a new contributor is there anything I should know before I roll up my sleeves?

**Comment by amohnacs15** [comment]
https://github.com/HabitRPG/habitica-android/pull/991
