### ISSUE TITLE
Show Guild and Party Challenges

### ISSUE THREAD

**Issue by LunarGem** [HabitRPG/habitica-android#972]
I think this is one of the last obstacles in the way of the app being the sole method of using Habitica on mobile. This and the notifications are the only things I think I'd need the website for at this point. Just wanted to create the issue so it can go in the design queue (if I'm wrong in doing this feel free to close or tell me to close).

Problem: There is no tab to show a guild or party's challenges, a user would need to filter in the challenge tab, which is rather buggy at the moment.

Proposed Solution: A tab similar to the description and chat tabs that would list the challenges for the guild/party in the same way the main challenge tab does.

**Comment by saraolson** [comment]
hello! we already have designs for this, they just need to be implemented when we have time. (we have a challenges redo milestone and guilds redo milestone in the works) so no worries, we're on it :) going to close this issue.
