### ISSUE TITLE
Gems purchasing cost is imbalanced

### ISSUE THREAD

**Issue by ritiek** [HabitRPG/habitica-android#977]
Hi, I don't know if this qualifies as an issue but nevertheless.

<img src="https://user-images.githubusercontent.com/20314742/38883597-0fd3c8ba-428b-11e8-8cad-04be2bcc97fb.png" width=250>

It says that 21 gems cost ₹320 and 42 gems cost ₹650. Wouldn't one be better off buying 2 sets of 21 gems rather than a single set of 42 gems? Is there a reason for having it like that?

**Comment by josephnw** [comment]
I haven't checked this issue but I don't think this is relevant to Android application's code.

**Comment by beffymaroo** [comment]
@ritiek This is indeed not an issue for discussion on Github. Feedback can be sent to the developers via Menu>About. Thank you for your understanding.
