### ISSUE TITLE
Connection Error There seems to be a problem with the server.Try again later

### ISSUE THREAD

**Issue by tchangeme** [HabitRPG/habitica-android#978]
1、Login habitica android app；
2、login with my email and password
3、on the home page，show the error：
“Connection Error 
There seems to be a problem with the server.Try again latter;”

**Comment by saraolson** [comment]
I get these error messaged a lot at random points throughout the app but it doesn't seem to actually affect loading/performance, it just makes me tap to get it out of the way.

**Comment by MoisesMsa** [comment]
This occurs with me when I am on 4g and try to update some task.

**Comment by flexbusterman** [comment]
Getting this error as well.
Apparently not the servers since the website works fine.
