### ISSUE TITLE
can't like / plus-one more than one message at a time

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#981]
When you enter the Tavern or a guild or your party, you can click plus-one on a message and the plus-one is recorded in Habitica's database. If you then try to plus-one a second message, it doesn't work (no plus-one is recorded in the database).

If you go to another screen then back to the guild/party/tavern, you're then able to plus-one another message.

**Comment by 199sm** [comment]
This issue has been fixed 5040574
