### ISSUE TITLE
like / plus-one doesn't display correctly at first (goes green then grey)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#982]
In the Tavern/party/guilds, when you click plus-one on a message, the plus-one symbol goes green (as expected) then after a second goes back to grey. When you pull to refresh the chat, the symbol goes green again and then stays green.

The expected behaviour is that as soon as you've plus-oned a message, the symbol should turn green and stay green.

**Comment by 199sm** [comment]
This issue has been fixed 5040574
