### ISSUE TITLE
Enable Class System should not say that it will cost 3 Gems

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#983]
When you are opted out of the class system, if you go to settings and click "Enable Class System", you see a message saying it will cost you 3 Gems. The expected behaviour is that you get directly into the "Select Class" screen with no message about a Gem cost.

The Gem cost message should appear only when you have previously selected a class and are not opted out of the class system.

**Comment by matheusvictor** [comment]
@Alys: I recently used Orb to be reborn and by reaching level 10/11 the class options were skilful as usual. Does this happen if the user chooses to select the class later?

_Translated by Google Translate_

**Comment by Alys** [comment]
@matheusvictor It happens after you've opted out of the class system. When an opted-out player goes to Settings and clicks on "Change your class", they see a popup screen saying "Are you sure you want to change your class? This will cost 3 gems." with buttons saying "GO BACK" and "CHANGE YOUR CLASS".  The message about costing 3 Gems should not appear because it's free to select a class after you've opted out.
