### ISSUE TITLE
To-Do reminders are still sent after the To-Do is completed

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#986]
_From Fentie (8f4a567a-038c-4c48-9941-fea2dc1d2845) in the Report a Bug guild:_

So this may be a feature request, may be a bug depending on how it was intended. I've noticed that if I set a reminder on a Todo, and then complete the Todo before the reminder is scheduled to fire, I still get a reminder on Android even though the Todo has been finished. Is that as designed? I'd expect that completed tasks would have their reminders disabled. Thanks!

**Comment by asharma0703** [comment]
I'd like to take a look at this in a bit as well if no one's working on it. After poking around, it looks like you'd want to handle the reminders here based on task direction:

https://github.com/HabitRPG/habitica-android/blob/29227f777259a6036e7d6ef483edc61ea1bdfca7/Habitica/src/main/java/com/habitrpg/android/habitica/data/implementation/TaskRepositoryImpl.kt#L67-L67

`TaskAlarmManager` has some methods for scheduling/removing the alarms for a task, but only the scheduling one is public and the spot I linked above doesn't have access to a `TaskAlarmManager` afaik (the only usages I found were in `MainActivity.kt`, `TaskFormActivity.kt`, and `TaskReceiver.kt`.

Once that's figured out, I think you'd just be able to cancel the alarms for the task on `direction` down and reset them on `direction` up.

**Comment by phillipthelen** [comment]
I'd prefer to have this handled, so that when the notification is being built by the receiver, there is a check to see if the task is already completed. With your approach, the task would still send a notification if it was completed on the website (This can always happen, since the app might not have synced since then, but there's nothing we can do about that right now). Checking right before the notification is displayed should make the notification show/not show correctly in most cases.

**Comment by LulaV14** [comment]
@asharma0703 Are you still working on this? If not I'd like to give it a try.

**Comment by asharma0703** [comment]
Ah, sorry about that - go ahead, it's all yours.

**Comment by camerz** [comment]
@LulaV14 Hello, I'm new to this project and would love to give this issue a try if you aren't working on it now. Please let me know!

**Comment by saraolson** [comment]
@camerz hey there! since there hasn't been any activity on this since october, I'm giving you the claim on this issue. I'll take off the help wanted tag while you work on it.

**Comment by saraolson** [comment]
@camerz hello! just wanted to check in to see how this is going. are you still working on it? or do you have questions you need help with?

**Comment by camerz** [comment]
Hi @saraolson, still working on it! I'll let you know if we have any questions. Thanks!

**Comment by phillipthelen** [comment]
Hey, so I completely goofed. I saw the title of the issue in the list for the 1.9 milestone and then fixed it without checking the comments. Super sorry about that 😐

**Comment by camerz** [comment]
No worries! If possible, could you assign me to this issue instead? https://github.com/HabitRPG/habitica-android/issues/1122
