### ISSUE TITLE
party leader should be able to begin, cancel, abort quests

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#988]
When a quest scroll is used in a party, the party leader should have the same control over the quest as the quest owner does. I.e., both the quest owner and the party leader should see buttons for "Begin Quest" and "Cancel Invitation" before the quest has started, and a button for "Abort Quest" (not sure of the exact wording) after the quest has started.

Currently, only the quest owner sees the "begin" and "cancel" buttons (not sure about "abort"; our quest isn't at the right stage for testing that).

**Comment by DoguD** [comment]
I can work on this issue.
