### ISSUE TITLE
could you add the lastest release on github 

### ISSUE THREAD

**Issue by Lavinci** [HabitRPG/habitica-android#990]
why the release vision is 1.3 on github but 1.4.3 on google play?
could you add the lastest release on github that we can down it from here,beacuse we can not visit google play at our‘s（China） region.

**Comment by beffymaroo** [comment]
Hi there, thank you for your feedback but a Github issue is not the best way to reach us about something like this. Please use the in-app feedback feature in Menu>About if you'd like to communicate further about it.
