### ISSUE TITLE
On Samsung Tablet, app doesnt reorient with the screen

### ISSUE THREAD

**Issue by MrsWhatsit** [HabitRPG/habitica-android#999]
Not sure if this has already been reported, but on my samsung Tab the app will only display vertically, not horizontally--which means if I want to use the app with my keyboard I have to look at it sideways.

**Comment by Gunnie42** [comment]
Same here. Workaround: open mutli-view, and put some random app on the other side.

**Comment by saraolson** [comment]
i'm going to close this because this isnt actually a bug, its intentional. screen rotation was disabled because it caused too many bugs, with the intention to re-enable it when those bugs can be addressed. you can read more on it in this issue: #193
